insert into public.template_decks (slug, name, description, level)
values (
  'hsk1-co-ban',
  'HSK1 cơ bản',
  'Bộ 150 từ vựng HSK1 cơ bản cho người mới bắt đầu.',
  'HSK1'
)
on conflict (slug) do update
set
  name = excluded.name,
  description = excluded.description,
  level = excluded.level;

with target_deck as (
  select id from public.template_decks where slug = 'hsk1-co-ban'
)
insert into public.template_cards (
  template_deck_id,
  chinese,
  pinyin,
  meaning_vi,
  position
)
select
  target_deck.id,
  word.chinese,
  word.pinyin,
  word.meaning_vi,
  word.position
from target_deck
cross join (
  values
    ('爱', 'ài', 'yêu, thích', 1),
    ('八', 'bā', 'số tám', 2),
    ('爸爸', 'bàba', 'bố', 3),
    ('杯子', 'bēizi', 'cái cốc', 4),
    ('北京', 'Běijīng', 'Bắc Kinh', 5),
    ('本', 'běn', 'quyển, lượng từ cho sách', 6),
    ('不客气', 'bú kèqi', 'không có gì', 7),
    ('不', 'bù', 'không', 8),
    ('菜', 'cài', 'món ăn, rau', 9),
    ('茶', 'chá', 'trà', 10),
    ('吃', 'chī', 'ăn', 11),
    ('出租车', 'chūzūchē', 'taxi', 12),
    ('打电话', 'dǎ diànhuà', 'gọi điện thoại', 13),
    ('大', 'dà', 'to, lớn', 14),
    ('的', 'de', 'trợ từ sở hữu', 15),
    ('点', 'diǎn', 'giờ, điểm', 16),
    ('电脑', 'diànnǎo', 'máy tính', 17),
    ('电视', 'diànshì', 'tivi', 18),
    ('电影', 'diànyǐng', 'phim', 19),
    ('东西', 'dōngxi', 'đồ vật', 20),
    ('都', 'dōu', 'đều', 21),
    ('读', 'dú', 'đọc', 22),
    ('对不起', 'duìbuqǐ', 'xin lỗi', 23),
    ('多', 'duō', 'nhiều', 24),
    ('多少', 'duōshao', 'bao nhiêu', 25),
    ('儿子', 'érzi', 'con trai', 26),
    ('二', 'èr', 'số hai', 27),
    ('饭馆', 'fànguǎn', 'nhà hàng', 28),
    ('飞机', 'fēijī', 'máy bay', 29),
    ('分钟', 'fēnzhōng', 'phút', 30),
    ('高兴', 'gāoxìng', 'vui, vui vẻ', 31),
    ('个', 'gè', 'lượng từ chung', 32),
    ('工作', 'gōngzuò', 'công việc, làm việc', 33),
    ('狗', 'gǒu', 'con chó', 34),
    ('汉语', 'Hànyǔ', 'tiếng Hán', 35),
    ('好', 'hǎo', 'tốt, khỏe', 36),
    ('号', 'hào', 'ngày, số hiệu', 37),
    ('喝', 'hē', 'uống', 38),
    ('和', 'hé', 'và', 39),
    ('很', 'hěn', 'rất', 40),
    ('后面', 'hòumiàn', 'phía sau', 41),
    ('回', 'huí', 'trở về, lần', 42),
    ('会', 'huì', 'biết, sẽ', 43),
    ('几', 'jǐ', 'mấy, bao nhiêu', 44),
    ('家', 'jiā', 'nhà, gia đình', 45),
    ('叫', 'jiào', 'gọi là', 46),
    ('今天', 'jīntiān', 'hôm nay', 47),
    ('九', 'jiǔ', 'số chín', 48),
    ('开', 'kāi', 'mở, lái', 49),
    ('看', 'kàn', 'xem, nhìn', 50),
    ('看见', 'kànjiàn', 'nhìn thấy', 51),
    ('块', 'kuài', 'đồng, miếng', 52),
    ('来', 'lái', 'đến', 53),
    ('老师', 'lǎoshī', 'giáo viên', 54),
    ('了', 'le', 'trợ từ hoàn thành', 55),
    ('冷', 'lěng', 'lạnh', 56),
    ('里', 'lǐ', 'bên trong', 57),
    ('六', 'liù', 'số sáu', 58),
    ('妈妈', 'māma', 'mẹ', 59),
    ('吗', 'ma', 'trợ từ nghi vấn', 60),
    ('买', 'mǎi', 'mua', 61),
    ('猫', 'māo', 'con mèo', 62),
    ('没关系', 'méi guānxi', 'không sao', 63),
    ('没有', 'méiyǒu', 'không có', 64),
    ('米饭', 'mǐfàn', 'cơm', 65),
    ('明天', 'míngtiān', 'ngày mai', 66),
    ('名字', 'míngzi', 'tên', 67),
    ('哪', 'nǎ', 'nào', 68),
    ('哪儿', 'nǎr', 'ở đâu', 69),
    ('那', 'nà', 'kia, đó', 70),
    ('呢', 'ne', 'trợ từ hỏi', 71),
    ('能', 'néng', 'có thể', 72),
    ('你', 'nǐ', 'bạn', 73),
    ('年', 'nián', 'năm', 74),
    ('女儿', 'nǚér', 'con gái', 75),
    ('朋友', 'péngyou', 'bạn bè', 76),
    ('漂亮', 'piàoliang', 'đẹp', 77),
    ('苹果', 'píngguǒ', 'quả táo', 78),
    ('七', 'qī', 'số bảy', 79),
    ('钱', 'qián', 'tiền', 80),
    ('前面', 'qiánmiàn', 'phía trước', 81),
    ('请', 'qǐng', 'mời, xin hãy', 82),
    ('去', 'qù', 'đi', 83),
    ('热', 'rè', 'nóng', 84),
    ('人', 'rén', 'người', 85),
    ('认识', 'rènshi', 'quen biết', 86),
    ('三', 'sān', 'số ba', 87),
    ('商店', 'shāngdiàn', 'cửa hàng', 88),
    ('上', 'shàng', 'trên, lên', 89),
    ('上午', 'shàngwǔ', 'buổi sáng', 90),
    ('少', 'shǎo', 'ít', 91),
    ('谁', 'shéi', 'ai', 92),
    ('什么', 'shénme', 'cái gì', 93),
    ('十', 'shí', 'số mười', 94),
    ('时候', 'shíhou', 'thời điểm', 95),
    ('是', 'shì', 'là', 96),
    ('书', 'shū', 'sách', 97),
    ('水', 'shuǐ', 'nước', 98),
    ('水果', 'shuǐguǒ', 'trái cây', 99),
    ('睡觉', 'shuìjiào', 'ngủ', 100),
    ('说话', 'shuōhuà', 'nói chuyện', 101),
    ('四', 'sì', 'số bốn', 102),
    ('岁', 'suì', 'tuổi', 103),
    ('他', 'tā', 'anh ấy', 104),
    ('她', 'tā', 'cô ấy', 105),
    ('太', 'tài', 'quá, rất', 106),
    ('天气', 'tiānqì', 'thời tiết', 107),
    ('听', 'tīng', 'nghe', 108),
    ('同学', 'tóngxué', 'bạn học', 109),
    ('喂', 'wèi', 'alo', 110),
    ('我', 'wǒ', 'tôi', 111),
    ('我们', 'wǒmen', 'chúng tôi, chúng ta', 112),
    ('五', 'wǔ', 'số năm', 113),
    ('喜欢', 'xǐhuan', 'thích', 114),
    ('下', 'xià', 'dưới, xuống', 115),
    ('下午', 'xiàwǔ', 'buổi chiều', 116),
    ('下雨', 'xià yǔ', 'mưa', 117),
    ('先生', 'xiānsheng', 'ông, ngài', 118),
    ('现在', 'xiànzài', 'bây giờ', 119),
    ('想', 'xiǎng', 'muốn, nghĩ', 120),
    ('小', 'xiǎo', 'nhỏ', 121),
    ('小姐', 'xiǎojiě', 'cô, tiểu thư', 122),
    ('些', 'xiē', 'một vài', 123),
    ('写', 'xiě', 'viết', 124),
    ('谢谢', 'xièxie', 'cảm ơn', 125),
    ('星期', 'xīngqī', 'tuần, thứ', 126),
    ('学生', 'xuésheng', 'học sinh, sinh viên', 127),
    ('学习', 'xuéxí', 'học tập', 128),
    ('学校', 'xuéxiào', 'trường học', 129),
    ('一', 'yī', 'số một', 130),
    ('一点儿', 'yìdiǎnr', 'một chút', 131),
    ('衣服', 'yīfu', 'quần áo', 132),
    ('医生', 'yīshēng', 'bác sĩ', 133),
    ('医院', 'yīyuàn', 'bệnh viện', 134),
    ('椅子', 'yǐzi', 'cái ghế', 135),
    ('有', 'yǒu', 'có', 136),
    ('月', 'yuè', 'tháng', 137),
    ('在', 'zài', 'ở, đang', 138),
    ('再见', 'zàijiàn', 'tạm biệt', 139),
    ('怎么', 'zěnme', 'thế nào', 140),
    ('怎么样', 'zěnmeyàng', 'như thế nào', 141),
    ('这', 'zhè', 'này, đây', 142),
    ('中国', 'Zhōngguó', 'Trung Quốc', 143),
    ('中午', 'zhōngwǔ', 'buổi trưa', 144),
    ('住', 'zhù', 'ở, sống', 145),
    ('桌子', 'zhuōzi', 'cái bàn', 146),
    ('字', 'zì', 'chữ', 147),
    ('昨天', 'zuótiān', 'hôm qua', 148),
    ('坐', 'zuò', 'ngồi', 149),
    ('做', 'zuò', 'làm', 150)
) as word(chinese, pinyin, meaning_vi, position)
on conflict (template_deck_id, chinese) do update
set
  pinyin = excluded.pinyin,
  meaning_vi = excluded.meaning_vi,
  position = excluded.position;
