insert into public.template_decks (slug, name, description, level)
values (
  'hsk2-co-ban',
  'HSK2 cơ bản',
  'Bộ 150 từ vựng HSK2 cơ bản, nối tiếp sau HSK1.',
  'HSK2'
)
on conflict (slug) do update
set
  name = excluded.name,
  description = excluded.description,
  level = excluded.level;

with target_deck as (
  select id from public.template_decks where slug = 'hsk2-co-ban'
)
insert into public.template_cards (
  template_deck_id,
  chinese,
  pinyin,
  meaning_vi,
  position
)
select
  target_deck.id,
  word.chinese,
  word.pinyin,
  word.meaning_vi,
  word.position
from target_deck
cross join (
  values
    ('吧', 'ba', 'trợ từ gợi ý, nhé', 1),
    ('白', 'bái', 'màu trắng', 2),
    ('百', 'bǎi', 'một trăm', 3),
    ('帮助', 'bāngzhù', 'giúp đỡ', 4),
    ('报纸', 'bàozhǐ', 'báo giấy', 5),
    ('比', 'bǐ', 'so với', 6),
    ('别', 'bié', 'đừng, khác', 7),
    ('宾馆', 'bīnguǎn', 'khách sạn', 8),
    ('长', 'cháng', 'dài', 9),
    ('唱歌', 'chàng gē', 'hát', 10),
    ('出', 'chū', 'ra, xuất hiện', 11),
    ('穿', 'chuān', 'mặc, đi xuyên qua', 12),
    ('船', 'chuán', 'thuyền', 13),
    ('次', 'cì', 'lần', 14),
    ('从', 'cóng', 'từ', 15),
    ('错', 'cuò', 'sai, lỗi', 16),
    ('打篮球', 'dǎ lánqiú', 'chơi bóng rổ', 17),
    ('大家', 'dàjiā', 'mọi người', 18),
    ('到', 'dào', 'đến', 19),
    ('得', 'de', 'trợ từ bổ ngữ', 20),
    ('等', 'děng', 'đợi, chờ', 21),
    ('弟弟', 'dìdi', 'em trai', 22),
    ('第一', 'dì yī', 'thứ nhất', 23),
    ('懂', 'dǒng', 'hiểu', 24),
    ('对', 'duì', 'đúng, đối với', 25),
    ('房间', 'fángjiān', 'phòng', 26),
    ('非常', 'fēicháng', 'rất, vô cùng', 27),
    ('服务员', 'fúwùyuán', 'nhân viên phục vụ', 28),
    ('高', 'gāo', 'cao', 29),
    ('告诉', 'gàosu', 'nói cho biết', 30),
    ('哥哥', 'gēge', 'anh trai', 31),
    ('给', 'gěi', 'cho, đưa cho', 32),
    ('公共汽车', 'gōnggòng qìchē', 'xe buýt', 33),
    ('公司', 'gōngsī', 'công ty', 34),
    ('贵', 'guì', 'đắt, quý', 35),
    ('过', 'guò', 'qua, từng', 36),
    ('还', 'hái', 'còn, vẫn', 37),
    ('孩子', 'háizi', 'trẻ con', 38),
    ('好吃', 'hǎochī', 'ngon', 39),
    ('黑', 'hēi', 'màu đen', 40),
    ('红', 'hóng', 'màu đỏ', 41),
    ('火车站', 'huǒchēzhàn', 'ga tàu hỏa', 42),
    ('机场', 'jīchǎng', 'sân bay', 43),
    ('鸡蛋', 'jīdàn', 'trứng gà', 44),
    ('件', 'jiàn', 'lượng từ cho quần áo, sự việc', 45),
    ('教室', 'jiàoshì', 'phòng học', 46),
    ('姐姐', 'jiějie', 'chị gái', 47),
    ('介绍', 'jièshào', 'giới thiệu', 48),
    ('进', 'jìn', 'vào', 49),
    ('近', 'jìn', 'gần', 50),
    ('就', 'jiù', 'thì, ngay', 51),
    ('觉得', 'juéde', 'cảm thấy, cho rằng', 52),
    ('咖啡', 'kāfēi', 'cà phê', 53),
    ('开始', 'kāishǐ', 'bắt đầu', 54),
    ('考试', 'kǎoshì', 'thi, kỳ thi', 55),
    ('可能', 'kěnéng', 'có thể', 56),
    ('可以', 'kěyǐ', 'có thể, được phép', 57),
    ('课', 'kè', 'bài học, tiết học', 58),
    ('快', 'kuài', 'nhanh, sắp', 59),
    ('快乐', 'kuàilè', 'vui vẻ', 60),
    ('累', 'lèi', 'mệt', 61),
    ('离', 'lí', 'cách, rời khỏi', 62),
    ('两', 'liǎng', 'hai', 63),
    ('零', 'líng', 'số không', 64),
    ('路', 'lù', 'đường', 65),
    ('旅游', 'lǚyóu', 'du lịch', 66),
    ('卖', 'mài', 'bán', 67),
    ('慢', 'màn', 'chậm', 68),
    ('忙', 'máng', 'bận', 69),
    ('每', 'měi', 'mỗi', 70),
    ('妹妹', 'mèimei', 'em gái', 71),
    ('门', 'mén', 'cửa', 72),
    ('面条', 'miàntiáo', 'mì sợi', 73),
    ('男', 'nán', 'nam', 74),
    ('您', 'nín', 'ngài, bạn dạng lịch sự', 75),
    ('牛奶', 'niúnǎi', 'sữa bò', 76),
    ('女', 'nǚ', 'nữ', 77),
    ('旁边', 'pángbiān', 'bên cạnh', 78),
    ('跑步', 'pǎobù', 'chạy bộ', 79),
    ('便宜', 'piányi', 'rẻ', 80),
    ('票', 'piào', 'vé', 81),
    ('妻子', 'qīzi', 'vợ', 82),
    ('起床', 'qǐchuáng', 'thức dậy', 83),
    ('千', 'qiān', 'một nghìn', 84),
    ('晴', 'qíng', 'trời nắng', 85),
    ('去年', 'qùnián', 'năm ngoái', 86),
    ('让', 'ràng', 'để, bảo, nhường', 87),
    ('日', 'rì', 'ngày', 88),
    ('上班', 'shàng bān', 'đi làm', 89),
    ('身体', 'shēntǐ', 'cơ thể, sức khỏe', 90),
    ('生病', 'shēng bìng', 'bị bệnh', 91),
    ('生日', 'shēngrì', 'sinh nhật', 92),
    ('时间', 'shíjiān', 'thời gian', 93),
    ('事情', 'shìqing', 'sự việc, công việc', 94),
    ('手表', 'shǒubiǎo', 'đồng hồ đeo tay', 95),
    ('手机', 'shǒujī', 'điện thoại di động', 96),
    ('说话', 'shuōhuà', 'nói chuyện', 97),
    ('送', 'sòng', 'tặng, đưa tiễn', 98),
    ('虽然', 'suīrán', 'tuy rằng', 99),
    ('但是', 'dànshì', 'nhưng', 100),
    ('它', 'tā', 'nó', 101),
    ('踢足球', 'tī zúqiú', 'đá bóng', 102),
    ('题', 'tí', 'đề bài, câu hỏi', 103),
    ('跳舞', 'tiào wǔ', 'nhảy múa', 104),
    ('外', 'wài', 'ngoài', 105),
    ('完', 'wán', 'xong, hoàn thành', 106),
    ('玩', 'wán', 'chơi', 107),
    ('晚上', 'wǎnshang', 'buổi tối', 108),
    ('为什么', 'wèishénme', 'tại sao', 109),
    ('问', 'wèn', 'hỏi', 110),
    ('问题', 'wèntí', 'vấn đề, câu hỏi', 111),
    ('西瓜', 'xīguā', 'dưa hấu', 112),
    ('希望', 'xīwàng', 'hy vọng', 113),
    ('洗', 'xǐ', 'rửa, giặt', 114),
    ('小时', 'xiǎoshí', 'giờ, tiếng đồng hồ', 115),
    ('笑', 'xiào', 'cười', 116),
    ('新', 'xīn', 'mới', 117),
    ('姓', 'xìng', 'họ', 118),
    ('休息', 'xiūxi', 'nghỉ ngơi', 119),
    ('雪', 'xuě', 'tuyết', 120),
    ('颜色', 'yánsè', 'màu sắc', 121),
    ('眼睛', 'yǎnjing', 'mắt', 122),
    ('羊肉', 'yángròu', 'thịt cừu', 123),
    ('药', 'yào', 'thuốc', 124),
    ('要', 'yào', 'muốn, cần, sẽ', 125),
    ('也', 'yě', 'cũng', 126),
    ('已经', 'yǐjīng', 'đã', 127),
    ('一起', 'yìqǐ', 'cùng nhau', 128),
    ('一下', 'yíxià', 'một chút', 129),
    ('意思', 'yìsi', 'ý nghĩa', 130),
    ('因为', 'yīnwèi', 'bởi vì', 131),
    ('所以', 'suǒyǐ', 'cho nên', 132),
    ('阴', 'yīn', 'âm u, râm', 133),
    ('游泳', 'yóuyǒng', 'bơi', 134),
    ('右边', 'yòubiān', 'bên phải', 135),
    ('鱼', 'yú', 'cá', 136),
    ('远', 'yuǎn', 'xa', 137),
    ('运动', 'yùndòng', 'vận động, thể thao', 138),
    ('再', 'zài', 'lại, lần nữa', 139),
    ('早上', 'zǎoshang', 'buổi sáng', 140),
    ('丈夫', 'zhàngfu', 'chồng', 141),
    ('找', 'zhǎo', 'tìm', 142),
    ('着', 'zhe', 'trợ từ trạng thái tiếp diễn', 143),
    ('真', 'zhēn', 'thật, thật sự', 144),
    ('正在', 'zhèngzài', 'đang', 145),
    ('知道', 'zhīdào', 'biết', 146),
    ('准备', 'zhǔnbèi', 'chuẩn bị', 147),
    ('走', 'zǒu', 'đi, rời đi', 148),
    ('最', 'zuì', 'nhất', 149),
    ('左边', 'zuǒbiān', 'bên trái', 150)
) as word(chinese, pinyin, meaning_vi, position)
on conflict (template_deck_id, chinese) do update
set
  pinyin = excluded.pinyin,
  meaning_vi = excluded.meaning_vi,
  position = excluded.position;
