insert into public.template_decks (slug, name, description, level)
values (
  'hsk3-co-ban',
  'HSK3 cơ bản',
  'Bộ 300 từ vựng HSK3 cơ bản, nối tiếp sau HSK1 và HSK2.',
  'HSK3'
)
on conflict (slug) do update
set
  name = excluded.name,
  description = excluded.description,
  level = excluded.level;

with target_deck as (
  select id from public.template_decks where slug = 'hsk3-co-ban'
)
insert into public.template_cards (
  template_deck_id,
  chinese,
  pinyin,
  meaning_vi,
  position
)
select
  target_deck.id,
  word.chinese,
  word.pinyin,
  word.meaning_vi,
  word.position
from target_deck
cross join (
  values
    ('阿姨', 'āyí', 'dì, cô, người giúp việc', 1),
    ('啊', 'a', 'à, ồ, trợ từ cảm thán', 2),
    ('矮', 'ǎi', 'thấp, lùn', 3),
    ('爱好', 'àihào', 'sở thích', 4),
    ('安静', 'ānjìng', 'yên tĩnh', 5),
    ('把', 'bǎ', 'cầm, đem, trợ từ xử lý tân ngữ', 6),
    ('搬', 'bān', 'chuyển, dọn', 7),
    ('班', 'bān', 'lớp, ca làm', 8),
    ('半', 'bàn', 'một nửa, rưỡi', 9),
    ('办法', 'bànfǎ', 'cách, biện pháp', 10),
    ('办公室', 'bàngōngshì', 'văn phòng', 11),
    ('帮忙', 'bāngmáng', 'giúp đỡ', 12),
    ('包', 'bāo', 'túi, bao, gói', 13),
    ('饱', 'bǎo', 'no', 14),
    ('北方', 'běifāng', 'phía bắc', 15),
    ('被', 'bèi', 'bị, được bởi', 16),
    ('鼻子', 'bízi', 'mũi', 17),
    ('比较', 'bǐjiào', 'khá, tương đối, so sánh', 18),
    ('比赛', 'bǐsài', 'cuộc thi, trận đấu', 19),
    ('必须', 'bìxū', 'phải, bắt buộc', 20),
    ('变化', 'biànhuà', 'sự thay đổi', 21),
    ('表示', 'biǎoshì', 'biểu thị, bày tỏ', 22),
    ('表演', 'biǎoyǎn', 'biểu diễn', 23),
    ('别人', 'biérén', 'người khác', 24),
    ('宾馆', 'bīnguǎn', 'khách sạn', 25),
    ('冰箱', 'bīngxiāng', 'tủ lạnh', 26),
    ('才', 'cái', 'mới, vừa mới, tài năng', 27),
    ('菜单', 'càidān', 'thực đơn', 28),
    ('参加', 'cānjiā', 'tham gia', 29),
    ('草', 'cǎo', 'cỏ', 30),
    ('层', 'céng', 'tầng, lớp', 31),
    ('差', 'chà', 'kém, thiếu, sai lệch', 32),
    ('超市', 'chāoshì', 'siêu thị', 33),
    ('衬衫', 'chènshān', 'áo sơ mi', 34),
    ('成绩', 'chéngjì', 'thành tích, điểm số', 35),
    ('城市', 'chéngshì', 'thành phố', 36),
    ('迟到', 'chídào', 'đến muộn', 37),
    ('除了', 'chúle', 'ngoài ra, trừ ra', 38),
    ('船', 'chuán', 'thuyền', 39),
    ('春', 'chūn', 'mùa xuân', 40),
    ('词语', 'cíyǔ', 'từ ngữ', 41),
    ('聪明', 'cōngming', 'thông minh', 42),
    ('打扫', 'dǎsǎo', 'quét dọn', 43),
    ('打算', 'dǎsuan', 'dự định, tính toán', 44),
    ('带', 'dài', 'mang theo, dẫn theo', 45),
    ('担心', 'dānxīn', 'lo lắng', 46),
    ('蛋糕', 'dàngāo', 'bánh kem', 47),
    ('当然', 'dāngrán', 'đương nhiên', 48),
    ('地', 'de', 'trợ từ trạng ngữ', 49),
    ('灯', 'dēng', 'đèn', 50),
    ('低', 'dī', 'thấp', 51),
    ('地方', 'dìfang', 'nơi, địa phương', 52),
    ('地铁', 'dìtiě', 'tàu điện ngầm', 53),
    ('地图', 'dìtú', 'bản đồ', 54),
    ('电梯', 'diàntī', 'thang máy', 55),
    ('电子邮件', 'diànzǐ yóujiàn', 'email, thư điện tử', 56),
    ('东', 'dōng', 'phía đông', 57),
    ('冬', 'dōng', 'mùa đông', 58),
    ('动物', 'dòngwù', 'động vật', 59),
    ('短', 'duǎn', 'ngắn', 60),
    ('段', 'duàn', 'đoạn, khoảng', 61),
    ('锻炼', 'duànliàn', 'rèn luyện, tập thể dục', 62),
    ('多么', 'duōme', 'biết bao, thật là', 63),
    ('饿', 'è', 'đói', 64),
    ('耳朵', 'ěrduo', 'tai', 65),
    ('发', 'fā', 'gửi, phát ra', 66),
    ('发现', 'fāxiàn', 'phát hiện', 67),
    ('方便', 'fāngbiàn', 'tiện lợi', 68),
    ('放', 'fàng', 'đặt, để, thả', 69),
    ('放心', 'fàngxīn', 'yên tâm', 70),
    ('分', 'fēn', 'phút, điểm, chia', 71),
    ('附近', 'fùjìn', 'gần đây, lân cận', 72),
    ('复习', 'fùxí', 'ôn tập', 73),
    ('干净', 'gānjìng', 'sạch sẽ', 74),
    ('感冒', 'gǎnmào', 'cảm cúm', 75),
    ('感兴趣', 'gǎn xìngqù', 'có hứng thú', 76),
    ('刚才', 'gāngcái', 'vừa nãy', 77),
    ('个子', 'gèzi', 'vóc dáng, chiều cao', 78),
    ('根据', 'gēnjù', 'dựa theo, căn cứ', 79),
    ('跟', 'gēn', 'với, theo', 80),
    ('更', 'gèng', 'hơn, càng', 81),
    ('公园', 'gōngyuán', 'công viên', 82),
    ('故事', 'gùshi', 'câu chuyện', 83),
    ('刮风', 'guā fēng', 'có gió, gió thổi', 84),
    ('关', 'guān', 'đóng, tắt', 85),
    ('关系', 'guānxi', 'quan hệ, mối quan hệ', 86),
    ('关心', 'guānxīn', 'quan tâm', 87),
    ('关于', 'guānyú', 'về, liên quan đến', 88),
    ('国家', 'guójiā', 'quốc gia', 89),
    ('果汁', 'guǒzhī', 'nước ép trái cây', 90),
    ('过去', 'guòqù', 'quá khứ, đi qua', 91),
    ('还是', 'háishi', 'hay là, vẫn là', 92),
    ('害怕', 'hàipà', 'sợ hãi', 93),
    ('河', 'hé', 'sông', 94),
    ('黑板', 'hēibǎn', 'bảng đen', 95),
    ('护照', 'hùzhào', 'hộ chiếu', 96),
    ('花', 'huā', 'hoa, tiêu tiền', 97),
    ('花园', 'huāyuán', 'vườn hoa', 98),
    ('画', 'huà', 'vẽ, tranh', 99),
    ('坏', 'huài', 'xấu, hỏng', 100),
    ('欢迎', 'huānyíng', 'hoan nghênh, chào đón', 101),
    ('环境', 'huánjìng', 'môi trường', 102),
    ('换', 'huàn', 'đổi, thay', 103),
    ('黄', 'huáng', 'màu vàng', 104),
    ('会议', 'huìyì', 'cuộc họp, hội nghị', 105),
    ('或者', 'huòzhě', 'hoặc, hoặc là', 106),
    ('机会', 'jīhuì', 'cơ hội', 107),
    ('极', 'jí', 'cực kỳ, rất', 108),
    ('记得', 'jìde', 'nhớ, nhớ rằng', 109),
    ('季节', 'jìjié', 'mùa', 110),
    ('检查', 'jiǎnchá', 'kiểm tra', 111),
    ('简单', 'jiǎndān', 'đơn giản', 112),
    ('见面', 'jiànmiàn', 'gặp mặt', 113),
    ('健康', 'jiànkāng', 'khỏe mạnh, sức khỏe', 114),
    ('讲', 'jiǎng', 'giảng, nói', 115),
    ('脚', 'jiǎo', 'bàn chân', 116),
    ('角', 'jiǎo', 'góc, hào', 117),
    ('接', 'jiē', 'đón, nhận, nối', 118),
    ('街道', 'jiēdào', 'đường phố', 119),
    ('结婚', 'jiéhūn', 'kết hôn', 120),
    ('结束', 'jiéshù', 'kết thúc', 121),
    ('节目', 'jiémù', 'chương trình', 122),
    ('节日', 'jiérì', 'ngày lễ', 123),
    ('解决', 'jiějué', 'giải quyết', 124),
    ('借', 'jiè', 'mượn, cho mượn', 125),
    ('经常', 'jīngcháng', 'thường xuyên', 126),
    ('经过', 'jīngguò', 'đi qua, trải qua', 127),
    ('经理', 'jīnglǐ', 'giám đốc, quản lý', 128),
    ('久', 'jiǔ', 'lâu', 129),
    ('旧', 'jiù', 'cũ', 130),
    ('句子', 'jùzi', 'câu văn', 131),
    ('决定', 'juédìng', 'quyết định', 132),
    ('可爱', 'kěài', 'đáng yêu', 133),
    ('渴', 'kě', 'khát', 134),
    ('刻', 'kè', 'mười lăm phút, khắc', 135),
    ('客人', 'kèrén', 'khách', 136),
    ('空调', 'kōngtiáo', 'máy điều hòa', 137),
    ('口', 'kǒu', 'miệng, khẩu', 138),
    ('哭', 'kū', 'khóc', 139),
    ('裤子', 'kùzi', 'quần', 140),
    ('筷子', 'kuàizi', 'đũa', 141),
    ('蓝', 'lán', 'màu xanh lam', 142),
    ('老', 'lǎo', 'già, cũ', 143),
    ('离开', 'líkāi', 'rời khỏi', 144),
    ('礼物', 'lǐwù', 'quà tặng', 145),
    ('历史', 'lìshǐ', 'lịch sử', 146),
    ('脸', 'liǎn', 'mặt', 147),
    ('练习', 'liànxí', 'luyện tập', 148),
    ('辆', 'liàng', 'lượng từ cho xe', 149),
    ('了解', 'liǎojiě', 'hiểu, tìm hiểu', 150),
    ('邻居', 'línjū', 'hàng xóm', 151),
    ('楼', 'lóu', 'tòa nhà, lầu', 152),
    ('绿', 'lǜ', 'màu xanh lá', 153),
    ('马', 'mǎ', 'con ngựa', 154),
    ('马上', 'mǎshàng', 'ngay lập tức', 155),
    ('满意', 'mǎnyì', 'hài lòng', 156),
    ('帽子', 'màozi', 'mũ', 157),
    ('米', 'mǐ', 'gạo, mét', 158),
    ('面包', 'miànbāo', 'bánh mì', 159),
    ('明白', 'míngbai', 'hiểu, rõ', 160),
    ('拿', 'ná', 'cầm, lấy', 161),
    ('奶奶', 'nǎinai', 'bà nội', 162),
    ('南', 'nán', 'phía nam', 163),
    ('难', 'nán', 'khó', 164),
    ('难过', 'nánguò', 'buồn, khó chịu', 165),
    ('年级', 'niánjí', 'khối lớp, niên cấp', 166),
    ('年轻', 'niánqīng', 'trẻ', 167),
    ('鸟', 'niǎo', 'chim', 168),
    ('努力', 'nǔlì', 'cố gắng', 169),
    ('爬山', 'pá shān', 'leo núi', 170),
    ('盘子', 'pánzi', 'cái đĩa', 171),
    ('胖', 'pàng', 'béo, mập', 172),
    ('啤酒', 'píjiǔ', 'bia', 173),
    ('皮鞋', 'píxié', 'giày da', 174),
    ('瓶子', 'píngzi', 'cái chai', 175),
    ('其实', 'qíshí', 'thật ra', 176),
    ('其他', 'qítā', 'khác, những cái khác', 177),
    ('奇怪', 'qíguài', 'kỳ lạ', 178),
    ('骑', 'qí', 'cưỡi, đi xe', 179),
    ('起飞', 'qǐfēi', 'cất cánh', 180),
    ('清楚', 'qīngchu', 'rõ ràng', 181),
    ('秋', 'qiū', 'mùa thu', 182),
    ('裙子', 'qúnzi', 'váy', 183),
    ('然后', 'ránhòu', 'sau đó', 184),
    ('认为', 'rènwéi', 'cho rằng, nghĩ rằng', 185),
    ('认真', 'rènzhēn', 'nghiêm túc', 186),
    ('容易', 'róngyì', 'dễ dàng', 187),
    ('如果', 'rúguǒ', 'nếu', 188),
    ('伞', 'sǎn', 'ô, dù', 189),
    ('上网', 'shàng wǎng', 'lên mạng', 190),
    ('生气', 'shēngqì', 'tức giận', 191),
    ('声音', 'shēngyīn', 'âm thanh, giọng nói', 192),
    ('使', 'shǐ', 'khiến, làm cho', 193),
    ('世界', 'shìjiè', 'thế giới', 194),
    ('试', 'shì', 'thử', 195),
    ('瘦', 'shòu', 'gầy', 196),
    ('舒服', 'shūfu', 'thoải mái', 197),
    ('树', 'shù', 'cây', 198),
    ('数学', 'shùxué', 'toán học', 199),
    ('刷牙', 'shuā yá', 'đánh răng', 200),
    ('双', 'shuāng', 'đôi, cặp', 201),
    ('水平', 'shuǐpíng', 'trình độ, mức độ', 202),
    ('司机', 'sījī', 'tài xế', 203),
    ('太阳', 'tàiyáng', 'mặt trời', 204),
    ('特别', 'tèbié', 'đặc biệt', 205),
    ('疼', 'téng', 'đau', 206),
    ('提高', 'tígāo', 'nâng cao', 207),
    ('体育', 'tǐyù', 'thể dục, thể thao', 208),
    ('甜', 'tián', 'ngọt', 209),
    ('条', 'tiáo', 'lượng từ cho vật dài', 210),
    ('同事', 'tóngshì', 'đồng nghiệp', 211),
    ('同意', 'tóngyì', 'đồng ý', 212),
    ('头发', 'tóufa', 'tóc', 213),
    ('突然', 'tūrán', 'đột nhiên', 214),
    ('图书馆', 'túshūguǎn', 'thư viện', 215),
    ('腿', 'tuǐ', 'chân', 216),
    ('完成', 'wánchéng', 'hoàn thành', 217),
    ('碗', 'wǎn', 'cái bát', 218),
    ('万', 'wàn', 'mười nghìn', 219),
    ('忘记', 'wàngjì', 'quên', 220),
    ('为', 'wèi', 'vì, cho', 221),
    ('为了', 'wèile', 'để, vì mục đích', 222),
    ('位', 'wèi', 'vị, lượng từ lịch sự cho người', 223),
    ('文化', 'wénhuà', 'văn hóa', 224),
    ('西', 'xī', 'phía tây', 225),
    ('习惯', 'xíguàn', 'thói quen, quen với', 226),
    ('洗手间', 'xǐshǒujiān', 'nhà vệ sinh', 227),
    ('洗澡', 'xǐ zǎo', 'tắm', 228),
    ('夏', 'xià', 'mùa hè', 229),
    ('先', 'xiān', 'trước, trước tiên', 230),
    ('香蕉', 'xiāngjiāo', 'chuối', 231),
    ('相同', 'xiāngtóng', 'giống nhau', 232),
    ('相信', 'xiāngxìn', 'tin tưởng', 233),
    ('像', 'xiàng', 'giống như, hình ảnh', 234),
    ('小心', 'xiǎoxīn', 'cẩn thận', 235),
    ('校长', 'xiàozhǎng', 'hiệu trưởng', 236),
    ('新闻', 'xīnwén', 'tin tức', 237),
    ('新鲜', 'xīnxiān', 'tươi mới', 238),
    ('信', 'xìn', 'thư, tin', 239),
    ('行李箱', 'xínglixiāng', 'vali', 240),
    ('兴趣', 'xìngqù', 'hứng thú, sở thích', 241),
    ('熊猫', 'xióngmāo', 'gấu trúc', 242),
    ('需要', 'xūyào', 'cần, cần thiết', 243),
    ('选择', 'xuǎnzé', 'lựa chọn', 244),
    ('要求', 'yāoqiú', 'yêu cầu', 245),
    ('爷爷', 'yéye', 'ông nội', 246),
    ('一般', 'yìbān', 'bình thường, thông thường', 247),
    ('一边', 'yìbiān', 'một bên, vừa... vừa...', 248),
    ('一定', 'yídìng', 'nhất định', 249),
    ('一共', 'yígòng', 'tổng cộng', 250),
    ('一会儿', 'yíhuìr', 'một lát', 251),
    ('一样', 'yíyàng', 'giống nhau', 252),
    ('以后', 'yǐhòu', 'sau này, về sau', 253),
    ('以前', 'yǐqián', 'trước đây', 254),
    ('以为', 'yǐwéi', 'tưởng rằng', 255),
    ('银行', 'yínháng', 'ngân hàng', 256),
    ('音乐', 'yīnyuè', 'âm nhạc', 257),
    ('应该', 'yīnggāi', 'nên, phải', 258),
    ('影响', 'yǐngxiǎng', 'ảnh hưởng', 259),
    ('用', 'yòng', 'dùng, sử dụng', 260),
    ('游戏', 'yóuxì', 'trò chơi', 261),
    ('有名', 'yǒumíng', 'nổi tiếng', 262),
    ('又', 'yòu', 'lại, vừa... vừa...', 263),
    ('遇到', 'yùdào', 'gặp phải, gặp được', 264),
    ('元', 'yuán', 'đồng, nhân dân tệ', 265),
    ('愿意', 'yuànyì', 'sẵn lòng, bằng lòng', 266),
    ('越', 'yuè', 'càng', 267),
    ('月亮', 'yuèliang', 'mặt trăng', 268),
    ('云', 'yún', 'mây', 269),
    ('站', 'zhàn', 'trạm, đứng', 270),
    ('长', 'zhǎng', 'lớn lên, trưởng thành', 271),
    ('着急', 'zháojí', 'lo lắng, sốt ruột', 272),
    ('照顾', 'zhàogu', 'chăm sóc', 273),
    ('照片', 'zhàopiàn', 'bức ảnh', 274),
    ('照相机', 'zhàoxiàngjī', 'máy ảnh', 275),
    ('只', 'zhǐ', 'chỉ, chỉ có', 276),
    ('只好', 'zhǐhǎo', 'đành phải', 277),
    ('只有', 'zhǐyǒu', 'chỉ có', 278),
    ('种', 'zhǒng', 'loại, chủng loại', 279),
    ('重要', 'zhòngyào', 'quan trọng', 280),
    ('周末', 'zhōumò', 'cuối tuần', 281),
    ('主要', 'zhǔyào', 'chủ yếu', 282),
    ('注意', 'zhùyì', 'chú ý', 283),
    ('自己', 'zìjǐ', 'bản thân, tự mình', 284),
    ('自行车', 'zìxíngchē', 'xe đạp', 285),
    ('总是', 'zǒngshì', 'luôn luôn', 286),
    ('嘴', 'zuǐ', 'miệng', 287),
    ('最后', 'zuìhòu', 'cuối cùng', 288),
    ('最近', 'zuìjìn', 'gần đây', 289),
    ('作业', 'zuòyè', 'bài tập', 290),
    ('作用', 'zuòyòng', 'tác dụng, vai trò', 291),
    ('笔记本', 'bǐjìběn', 'sổ tay, vở ghi chép', 292),
    ('不但', 'búdàn', 'không những', 293),
    ('而且', 'érqiě', 'hơn nữa, mà còn', 294),
    ('词典', 'cídiǎn', 'từ điển', 295),
    ('发烧', 'fāshāo', 'bị sốt', 296),
    ('公斤', 'gōngjīn', 'ki-lô-gam', 297),
    ('后来', 'hòulái', 'sau đó, về sau', 298),
    ('回答', 'huídá', 'trả lời', 299),
    ('几乎', 'jīhū', 'gần như, hầu như', 300)
) as word(chinese, pinyin, meaning_vi, position)
on conflict (template_deck_id, chinese) do update
set
  pinyin = excluded.pinyin,
  meaning_vi = excluded.meaning_vi,
  position = excluded.position;
