insert into public.template_decks (slug, name, description, level)
values (
  'cau-thuong-ngay-100',
  '100 câu thường ngày',
  'Bộ 100 câu tiếng Trung sử dụng hằng ngày để luyện nghe, luyện đọc và phản xạ.',
  'Luyện câu'
)
on conflict (slug) do update
set
  name = excluded.name,
  description = excluded.description,
  level = excluded.level;

with target_deck as (
  select id from public.template_decks where slug = 'cau-thuong-ngay-100'
)
insert into public.template_sentence_cards (
  template_deck_id,
  sentence_cn,
  sentence_pinyin,
  sentence_vi,
  vocab_json,
  position
)
select
  target_deck.id,
  card.sentence_cn,
  card.sentence_pinyin,
  card.sentence_vi,
  card.vocab_json::jsonb,
  card.position
from target_deck
cross join (
  values
    ('你好！', 'Nǐ hǎo!', 'Xin chào.', '[]', 1),
    ('早上好！', 'Zǎoshang hǎo!', 'Chào buổi sáng.', '[]', 2),
    ('晚上好！', 'Wǎnshang hǎo!', 'Chào buổi tối.', '[]', 3),
    ('好久不见。', 'Hǎojiǔ bú jiàn.', 'Lâu rồi không gặp.', '[]', 4),
    ('你最近怎么样？', 'Nǐ zuìjìn zěnmeyàng?', 'Dạo gần đây bạn thế nào?', '[]', 5),
    ('我很好，谢谢。', 'Wǒ hěn hǎo, xièxie.', 'Tôi rất khỏe, cảm ơn.', '[]', 6),
    ('你叫什么名字？', 'Nǐ jiào shénme míngzi?', 'Bạn tên là gì?', '[]', 7),
    ('我叫小明。', 'Wǒ jiào Xiǎomíng.', 'Tôi tên là Tiểu Minh.', '[]', 8),
    ('很高兴认识你。', 'Hěn gāoxìng rènshi nǐ.', 'Rất vui được quen bạn.', '[]', 9),
    ('你是哪国人？', 'Nǐ shì nǎ guó rén?', 'Bạn là người nước nào?', '[]', 10),
    ('我是越南人。', 'Wǒ shì Yuènán rén.', 'Tôi là người Việt Nam.', '[]', 11),
    ('我会说一点儿中文。', 'Wǒ huì shuō yìdiǎnr Zhōngwén.', 'Tôi biết nói một chút tiếng Trung.', '[]', 12),
    ('请说慢一点。', 'Qǐng shuō màn yìdiǎn.', 'Làm ơn nói chậm một chút.', '[]', 13),
    ('请再说一遍。', 'Qǐng zài shuō yí biàn.', 'Làm ơn nói lại một lần nữa.', '[]', 14),
    ('我听不懂。', 'Wǒ tīng bù dǒng.', 'Tôi nghe không hiểu.', '[]', 15),
    ('我不知道。', 'Wǒ bù zhīdào.', 'Tôi không biết.', '[]', 16),
    ('没关系。', 'Méi guānxi.', 'Không sao.', '[]', 17),
    ('没问题。', 'Méi wèntí.', 'Không vấn đề gì.', '[]', 18),
    ('谢谢你的帮助。', 'Xièxie nǐ de bāngzhù.', 'Cảm ơn sự giúp đỡ của bạn.', '[]', 19),
    ('不客气。', 'Bú kèqi.', 'Không có gì.', '[]', 20),
    ('对不起。', 'Duìbuqǐ.', 'Xin lỗi.', '[]', 21),
    ('请问，洗手间在哪儿？', 'Qǐngwèn, xǐshǒujiān zài nǎr?', 'Xin hỏi, nhà vệ sinh ở đâu?', '[]', 22),
    ('我想喝水。', 'Wǒ xiǎng hē shuǐ.', 'Tôi muốn uống nước.', '[]', 23),
    ('我有点儿饿。', 'Wǒ yǒu diǎnr è.', 'Tôi hơi đói.', '[]', 24),
    ('我们去吃饭吧。', 'Wǒmen qù chīfàn ba.', 'Chúng ta đi ăn cơm nhé.', '[]', 25),
    ('你想吃什么？', 'Nǐ xiǎng chī shénme?', 'Bạn muốn ăn gì?', '[]', 26),
    ('这个菜很好吃。', 'Zhège cài hěn hǎochī.', 'Món này rất ngon.', '[]', 27),
    ('请给我菜单。', 'Qǐng gěi wǒ càidān.', 'Làm ơn cho tôi thực đơn.', '[]', 28),
    ('我不要辣。', 'Wǒ bú yào là.', 'Tôi không muốn cay.', '[]', 29),
    ('请给我一杯茶。', 'Qǐng gěi wǒ yì bēi chá.', 'Làm ơn cho tôi một ly trà.', '[]', 30),
    ('这个多少钱？', 'Zhège duōshao qián?', 'Cái này bao nhiêu tiền?', '[]', 31),
    ('太贵了。', 'Tài guì le.', 'Đắt quá.', '[]', 32),
    ('可以便宜一点吗？', 'Kěyǐ piányi yìdiǎn ma?', 'Có thể rẻ hơn một chút không?', '[]', 33),
    ('我要买这个。', 'Wǒ yào mǎi zhège.', 'Tôi muốn mua cái này.', '[]', 34),
    ('我只是看看。', 'Wǒ zhǐ shì kànkan.', 'Tôi chỉ xem thôi.', '[]', 35),
    ('可以用手机支付吗？', 'Kěyǐ yòng shǒujī zhīfù ma?', 'Có thể thanh toán bằng điện thoại không?', '[]', 36),
    ('请给我发票。', 'Qǐng gěi wǒ fāpiào.', 'Làm ơn cho tôi hóa đơn.', '[]', 37),
    ('我想去这个地方。', 'Wǒ xiǎng qù zhège dìfang.', 'Tôi muốn đến nơi này.', '[]', 38),
    ('这里离地铁站远吗？', 'Zhèlǐ lí dìtiězhàn yuǎn ma?', 'Ở đây cách ga tàu điện ngầm có xa không?', '[]', 39),
    ('我想打车。', 'Wǒ xiǎng dǎchē.', 'Tôi muốn gọi xe.', '[]', 40),
    ('请在这里停车。', 'Qǐng zài zhèlǐ tíngchē.', 'Làm ơn dừng xe ở đây.', '[]', 41),
    ('我要去机场。', 'Wǒ yào qù jīchǎng.', 'Tôi muốn đi sân bay.', '[]', 42),
    ('这辆车到火车站吗？', 'Zhè liàng chē dào huǒchēzhàn ma?', 'Xe này có đến ga tàu không?', '[]', 43),
    ('我迷路了。', 'Wǒ mílù le.', 'Tôi bị lạc đường.', '[]', 44),
    ('请帮我看一下地图。', 'Qǐng bāng wǒ kàn yíxià dìtú.', 'Làm ơn giúp tôi xem bản đồ một chút.', '[]', 45),
    ('今天星期几？', 'Jīntiān xīngqī jǐ?', 'Hôm nay là thứ mấy?', '[]', 46),
    ('现在几点？', 'Xiànzài jǐ diǎn?', 'Bây giờ mấy giờ?', '[]', 47),
    ('我八点上班。', 'Wǒ bā diǎn shàngbān.', 'Tôi đi làm lúc tám giờ.', '[]', 48),
    ('我今天很忙。', 'Wǒ jīntiān hěn máng.', 'Hôm nay tôi rất bận.', '[]', 49),
    ('我明天有时间。', 'Wǒ míngtiān yǒu shíjiān.', 'Ngày mai tôi có thời gian.', '[]', 50),
    ('我们几点见面？', 'Wǒmen jǐ diǎn jiànmiàn?', 'Mấy giờ chúng ta gặp nhau?', '[]', 51),
    ('我可能会迟到。', 'Wǒ kěnéng huì chídào.', 'Có thể tôi sẽ đến muộn.', '[]', 52),
    ('请等我一下。', 'Qǐng děng wǒ yíxià.', 'Làm ơn đợi tôi một chút.', '[]', 53),
    ('我马上到。', 'Wǒ mǎshàng dào.', 'Tôi đến ngay.', '[]', 54),
    ('我们一起去吧。', 'Wǒmen yìqǐ qù ba.', 'Chúng ta cùng đi nhé.', '[]', 55),
    ('我在学习中文。', 'Wǒ zài xuéxí Zhōngwén.', 'Tôi đang học tiếng Trung.', '[]', 56),
    ('这个字怎么读？', 'Zhège zì zěnme dú?', 'Chữ này đọc thế nào?', '[]', 57),
    ('这个词是什么意思？', 'Zhège cí shì shénme yìsi?', 'Từ này có nghĩa là gì?', '[]', 58),
    ('请写下来。', 'Qǐng xiě xiàlai.', 'Làm ơn viết xuống.', '[]', 59),
    ('我需要复习。', 'Wǒ xūyào fùxí.', 'Tôi cần ôn tập.', '[]', 60),
    ('我今天学了十个新词。', 'Wǒ jīntiān xué le shí ge xīn cí.', 'Hôm nay tôi đã học mười từ mới.', '[]', 61),
    ('这个句子很有用。', 'Zhège jùzi hěn yǒuyòng.', 'Câu này rất hữu ích.', '[]', 62),
    ('我想练习发音。', 'Wǒ xiǎng liànxí fāyīn.', 'Tôi muốn luyện phát âm.', '[]', 63),
    ('请纠正我的错误。', 'Qǐng jiūzhèng wǒ de cuòwù.', 'Làm ơn sửa lỗi cho tôi.', '[]', 64),
    ('我每天学习一点。', 'Wǒ měitiān xuéxí yìdiǎn.', 'Mỗi ngày tôi học một chút.', '[]', 65),
    ('我今天有点儿累。', 'Wǒ jīntiān yǒu diǎnr lèi.', 'Hôm nay tôi hơi mệt.', '[]', 66),
    ('我想休息一下。', 'Wǒ xiǎng xiūxi yíxià.', 'Tôi muốn nghỉ một chút.', '[]', 67),
    ('你身体怎么样？', 'Nǐ shēntǐ zěnmeyàng?', 'Sức khỏe của bạn thế nào?', '[]', 68),
    ('我感冒了。', 'Wǒ gǎnmào le.', 'Tôi bị cảm rồi.', '[]', 69),
    ('我头有点儿疼。', 'Wǒ tóu yǒu diǎnr téng.', 'Đầu tôi hơi đau.', '[]', 70),
    ('我要去医院。', 'Wǒ yào qù yīyuàn.', 'Tôi muốn đi bệnh viện.', '[]', 71),
    ('请帮我买药。', 'Qǐng bāng wǒ mǎi yào.', 'Làm ơn giúp tôi mua thuốc.', '[]', 72),
    ('今天天气很好。', 'Jīntiān tiānqì hěn hǎo.', 'Thời tiết hôm nay rất đẹp.', '[]', 73),
    ('今天很热。', 'Jīntiān hěn rè.', 'Hôm nay rất nóng.', '[]', 74),
    ('今天有点儿冷。', 'Jīntiān yǒu diǎnr lěng.', 'Hôm nay hơi lạnh.', '[]', 75),
    ('外面在下雨。', 'Wàimiàn zài xià yǔ.', 'Bên ngoài đang mưa.', '[]', 76),
    ('明天可能下雪。', 'Míngtiān kěnéng xià xuě.', 'Ngày mai có thể có tuyết.', '[]', 77),
    ('我喜欢这个城市。', 'Wǒ xǐhuan zhège chéngshì.', 'Tôi thích thành phố này.', '[]', 78),
    ('这里很安静。', 'Zhèlǐ hěn ānjìng.', 'Ở đây rất yên tĩnh.', '[]', 79),
    ('这里人很多。', 'Zhèlǐ rén hěn duō.', 'Ở đây rất đông người.', '[]', 80),
    ('你的家离这里远吗？', 'Nǐ de jiā lí zhèlǐ yuǎn ma?', 'Nhà bạn cách đây có xa không?', '[]', 81),
    ('我住在附近。', 'Wǒ zhù zài fùjìn.', 'Tôi sống gần đây.', '[]', 82),
    ('我想换一个房间。', 'Wǒ xiǎng huàn yí ge fángjiān.', 'Tôi muốn đổi một phòng khác.', '[]', 83),
    ('房间里有空调吗？', 'Fángjiān lǐ yǒu kōngtiáo ma?', 'Trong phòng có máy điều hòa không?', '[]', 84),
    ('请把灯打开。', 'Qǐng bǎ dēng dǎkāi.', 'Làm ơn bật đèn lên.', '[]', 85),
    ('请把门关上。', 'Qǐng bǎ mén guānshàng.', 'Làm ơn đóng cửa lại.', '[]', 86),
    ('我正在开会。', 'Wǒ zhèngzài kāihuì.', 'Tôi đang họp.', '[]', 87),
    ('我下班以后给你打电话。', 'Wǒ xiàbān yǐhòu gěi nǐ dǎ diànhuà.', 'Sau khi tan làm tôi sẽ gọi điện cho bạn.', '[]', 88),
    ('请给我发邮件。', 'Qǐng gěi wǒ fā yóujiàn.', 'Làm ơn gửi email cho tôi.', '[]', 89),
    ('我已经完成了。', 'Wǒ yǐjīng wánchéng le.', 'Tôi đã hoàn thành rồi.', '[]', 90),
    ('我们明天再谈。', 'Wǒmen míngtiān zài tán.', 'Ngày mai chúng ta nói tiếp.', '[]', 91),
    ('这个办法很好。', 'Zhège bànfǎ hěn hǎo.', 'Cách này rất tốt.', '[]', 92),
    ('我同意你的想法。', 'Wǒ tóngyì nǐ de xiǎngfǎ.', 'Tôi đồng ý với ý kiến của bạn.', '[]', 93),
    ('我不同意。', 'Wǒ bù tóngyì.', 'Tôi không đồng ý.', '[]', 94),
    ('这件事很重要。', 'Zhè jiàn shì hěn zhòngyào.', 'Việc này rất quan trọng.', '[]', 95),
    ('请注意安全。', 'Qǐng zhùyì ānquán.', 'Làm ơn chú ý an toàn.', '[]', 96),
    ('我需要你的建议。', 'Wǒ xūyào nǐ de jiànyì.', 'Tôi cần lời khuyên của bạn.', '[]', 97),
    ('祝你生日快乐！', 'Zhù nǐ shēngrì kuàilè!', 'Chúc bạn sinh nhật vui vẻ.', '[]', 98),
    ('祝你一路平安！', 'Zhù nǐ yílù píngān!', 'Chúc bạn thượng lộ bình an.', '[]', 99),
    ('明天见！', 'Míngtiān jiàn!', 'Hẹn gặp ngày mai.', '[]', 100)
) as card(sentence_cn, sentence_pinyin, sentence_vi, vocab_json, position)
on conflict (template_deck_id, sentence_cn) do update
set
  sentence_pinyin = excluded.sentence_pinyin,
  sentence_vi = excluded.sentence_vi,
  vocab_json = excluded.vocab_json,
  position = excluded.position;
