-- HSK 2.0 Level 4: 600 level-specific words (1,200 cumulative through HSK4).
-- Vietnamese gloss source: https://mychinese.vn/tu-vung-hsk-4.html
insert into public.template_decks (slug, name, description, level)
values (
  'hsk4-co-ban',
  'HSK4 cơ bản',
  'Bộ 600 từ vựng HSK4 cơ bản, nối tiếp sau HSK1, HSK2 và HSK3.',
  'HSK4'
)
on conflict (slug) do update
set
  name = excluded.name,
  description = excluded.description,
  level = excluded.level;

with target_deck as (
  select id from public.template_decks where slug = 'hsk4-co-ban'
)
insert into public.template_cards (
  template_deck_id,
  chinese,
  pinyin,
  meaning_vi,
  position
)
select
  target_deck.id,
  word.chinese,
  word.pinyin,
  word.meaning_vi,
  word.position
from target_deck
cross join (
  values
    ('爱情', 'ài qíng', 'tình yêu', 1),
    ('按照', 'àn zhào', 'dựa vào, theo', 2),
    ('按时', 'àn shí', 'đúng hạn', 3),
    ('安排', 'ān pái', 'sắp xếp', 4),
    ('安全', 'ān quán', 'an toàn', 5),
    ('百分之', 'bǎi fēn zhī', 'phần trăm (%)', 6),
    ('饼干', 'bǐng gān', 'bánh', 7),
    ('部分', 'bù fèn', 'bộ phận, phần', 8),
    ('遍', 'biàn', 'lần, lượt', 9),
    ('表示', 'biǎo shì', 'biểu thị, cho thấy', 10),
    ('表演', 'biǎo yǎn', 'biểu diễn', 11),
    ('表格', 'biǎo gé', 'bảng biểu', 12),
    ('表扬', 'biǎo yáng', 'tuyên dương', 13),
    ('笨', 'bèn', 'ngốc nghếch', 14),
    ('毕业', 'bì yè', 'tốt nghiệp', 15),
    ('比如', 'bǐ rú', 'ví dụ như', 16),
    ('棒', 'bàng', 'cây gậy', 17),
    ('标准', 'biāo zhǔn', 'tiêu chuẩn', 18),
    ('本来', 'běn lái', 'vốn có', 19),
    ('抱歉', 'bào qiàn', 'xin lỗi', 20),
    ('抱', 'bào', 'ôm', 21),
    ('报名', 'bào míng', 'đăng kí', 22),
    ('并且', 'bìng qiě', 'đồng thời', 23),
    ('博士', 'bó shì', 'tiến sĩ', 24),
    ('包子', 'bāo zi', 'bánh bao', 25),
    ('倍', 'bèi', 'lần', 26),
    ('保证', 'bǎo zhèng', 'đảm bảo, cam đoan', 27),
    ('保护', 'bǎo hù', 'che chở, bảo vệ', 28),
    ('不过', 'bù guò', 'nhưng', 29),
    ('不管', 'bù guǎn', 'bất kể', 30),
    ('不得不', 'bù dé bù', 'đành', 31),
    ('不仅', 'bù jǐn', 'không những', 32),
    ('擦', 'cā', 'lau', 33),
    ('餐厅', 'cān tīng', 'căng tin, nhà ăn', 34),
    ('长江', 'cháng jiāng', 'Trường Giang', 35),
    ('长城', 'cháng chéng', 'Trường Thành', 36),
    ('错误', 'cuò wù', 'sai lầm', 37),
    ('重新', 'chóng xīn', 'làm lại', 38),
    ('超过', 'chāo guò', 'vượt trên', 39),
    ('诚实', 'chéng shí', 'trung thực', 40),
    ('词语', 'cí yǔ', 'từ ngữ', 41),
    ('粗心', 'cū xīn', 'thô lỗ, cẩu thả', 42),
    ('窗户', 'chuāng hù', 'cửa sổ', 43),
    ('猜', 'cāi', 'đoán', 44),
    ('材料', 'cái liào', 'tài liệu', 45),
    ('抽烟', 'chōu yān', 'hút thuốc', 46),
    ('成功', 'chéng gōng', 'thành công', 47),
    ('成为', 'chéng wéi', 'trở thành', 48),
    ('差不多', 'chà bù duō', 'gần như', 49),
    ('尝', 'cháng', 'nếm thử', 50),
    ('存', 'cún', 'giữ, tiết kiệm, tồn', 51),
    ('场', 'chǎng', 'trận, suất', 52),
    ('吃惊', 'chī jīng', 'ngạc nhiên', 53),
    ('参观', 'cān guān', 'tham quan', 54),
    ('厨房', 'chú fáng', 'phòng bếp', 55),
    ('厕所', 'cè suǒ', 'phòng vệ sinh', 56),
    ('出生', 'chū shēng', 'ra đời', 57),
    ('出现', 'chū xiàn', 'xuất hiện', 58),
    ('出差', 'chū chāi', 'đi công tác', 59),
    ('出发', 'chū fā', 'xuất phát', 60),
    ('传真', 'chuán zhēn', 'fax, bản fax', 61),
    ('从来', 'cóng lái', 'từ trước đến nay', 62),
    ('乘坐', 'chéng zuò', 'ngồi xe', 63),
    ('答案', 'dá àn', 'đáp án', 64),
    ('道歉', 'dào qiàn', 'xin lỗi', 65),
    ('调查', 'diào chá', 'điều tra', 66),
    ('肚子', 'dù zi', 'bụng', 67),
    ('等（助词）', 'děng （ zhù cí ）', 'vân vân', 68),
    ('短信', 'duǎn xìn', 'tin nhắn', 69),
    ('登机牌', 'dēng jī pái', 'thẻ lên tàu', 70),
    ('掉', 'diào', 'rơi', 71),
    ('打针', 'dǎ zhēn', 'tiêm', 72),
    ('打招呼', 'dǎ zhāo hū', 'chào hỏi', 73),
    ('打折', 'dǎ zhé', 'giảm giá', 74),
    ('打扰', 'dǎ rǎo', 'làm phiền', 75),
    ('打扮', 'dǎ bàn', 'trau chuốt, trang điểm', 76),
    ('打印', 'dǎ yìn', 'in ấn', 77),
    ('戴', 'dài', 'đeo', 78),
    ('得意', 'dé yì', 'đắc ý', 79),
    ('得（助动词）', 'de（ zhù dòng cí)', 'trợ từ', 80),
    ('当时', 'dāng shí', 'lúc đó', 81),
    ('当', 'dāng', 'làm', 82),
    ('底', 'dǐ', 'đáy', 83),
    ('导游', 'dǎo yóu', 'hướng dẫn viên du lịch', 84),
    ('对面', 'duì miàn', 'đối diện', 85),
    ('对话', 'duì huà', 'hội thoại, đối thoại', 86),
    ('对于', 'duì yú', 'về (vấn đề gì đó)', 87),
    ('大约', 'dà yuē', 'khoảng', 88),
    ('大概', 'dà gài', 'khoảng', 89),
    ('大夫', 'dài fū', 'bác sĩ, đại phu', 90),
    ('大使馆', 'dà shǐ guǎn', 'đại sứ quán', 91),
    ('堵车', 'dǔ chē', 'tắc đường', 92),
    ('地球', 'dì qiú', 'địa cầu', 93),
    ('地点', 'dì diǎn', 'địa điểm', 94),
    ('地址', 'dì zhǐ', 'địa chỉ', 95),
    ('动作', 'dòng zuò', 'động tác', 96),
    ('到底', 'dào dǐ', 'cuối cùng', 97),
    ('到处', 'dào chù', 'khắp nơi', 98),
    ('刀', 'dāo', 'cái dao', 99),
    ('倒', 'dǎo', 'đổ, ngã', 100),
    ('低', 'dī', 'thấp', 101),
    ('丢', 'diū', 'mất', 102),
    ('儿童', 'ér tóng', 'trẻ con', 103),
    ('而', 'ér', 'còn', 104),
    ('发生', 'fā shēng', 'xảy ra', 105),
    ('负责', 'fù zé', 'phụ trách', 106),
    ('翻译', 'fān yì', 'phiên dịch', 107),
    ('符合', 'fú hé', 'phù hợp', 108),
    ('父亲', 'fù qīn', 'bố', 109),
    ('烦恼', 'fán nǎo', 'phiền não', 110),
    ('法律', 'fǎ lǜ', 'pháp luật', 111),
    ('方面', 'fāng miàn', 'phương diện', 112),
    ('方法', 'fāng fǎ', 'phương pháp', 113),
    ('方向', 'fāng xiàng', 'phương hướng', 114),
    ('放松', 'fàng sōng', 'thư giãn', 115),
    ('放暑假', 'fàng shǔ jià', 'nghỉ hè', 116),
    ('放弃', 'fàng qì', 'vứt bỏ, từ bỏ', 117),
    ('房东', 'fáng dōng', 'chủ nhà', 118),
    ('富', 'fù', 'giàu', 119),
    ('复杂', 'fù zá', 'phức tạp', 120),
    ('复印', 'fù yìn', 'phô tô', 121),
    ('否则', 'fǒu zé', 'nếu không thì', 122),
    ('发展', 'fā zhǎn', 'phát triển', 123),
    ('反对', 'fǎn duì', 'phản đối', 124),
    ('份', 'fèn', 'phần', 125),
    ('付款', 'fù kuǎn', 'thanh toán', 126),
    ('丰富', 'fēng fù', 'phong phú', 127),
    ('改变', 'gǎi biàn', 'thay đổi', 128),
    ('鼓励', 'gǔ lì', 'cổ vũ', 129),
    ('高速公路', 'gāo sù gōng lù', 'đường cao tốc', 130),
    ('顾客', 'gù kè', 'khách hàng', 131),
    ('逛', 'guàng', 'đi dạo', 132),
    ('过程', 'guò chéng', 'quá trình', 133),
    ('赶', 'gǎn', 'đuổi theo', 134),
    ('购物', 'gòu wù', 'mua sắm', 135),
    ('规定', 'guī dìng', 'qui định', 136),
    ('观众', 'guān zhòng', 'khán giả', 137),
    ('胳膊', 'gē bo', 'cánh tay', 138),
    ('管理', 'guǎn lǐ', 'quản lý', 139),
    ('果汁', 'guǒ zhī', 'nước hoa quả', 140),
    ('敢', 'gǎn', 'dám', 141),
    ('故意', 'gù yì', 'cố ý', 142),
    ('挂', 'guà', 'treo', 143),
    ('感谢', 'gǎn xiè', 'cảm ơn', 144),
    ('感觉', 'gǎn jué', 'cảm giác', 145),
    ('感情', 'gǎn qíng', 'tình cảm', 146),
    ('感动', 'gǎn dòng', 'cảm động', 147),
    ('广播', 'guǎng bō', 'phát thanh', 148),
    ('广告', 'guǎng gào', 'quảng cáo', 149),
    ('干杯', 'gān bēi', 'cạn ly', 150),
    ('干', 'gān', 'khô', 151),
    ('工资', 'gōng zī', 'lương', 152),
    ('够', 'gòu', 'đủ', 153),
    ('国际', 'guó jì', 'quốc tế', 154),
    ('国籍', 'guó jí', 'quốc tịch', 155),
    ('各', 'gè', 'các', 156),
    ('功夫', 'gōng fū', 'công phu', 157),
    ('刚', 'gāng', 'vừa mới', 158),
    ('关键', 'guān jiàn', 'quan trọng', 159),
    ('共同', 'gòng tóng', 'giống nhau', 160),
    ('公里', 'gōng lǐ', 'km', 161),
    ('光', 'guāng', 'chỉ, hết', 162),
    ('估计', 'gū jì', 'ước lượng', 163),
    ('海洋', 'hǎi yáng', 'đại dương', 164),
    ('获得', 'huò dé', 'giành được', 165),
    ('航班', 'háng bān', 'chuyến bay', 166),
    ('盒子', 'hé zi', 'cái hộp', 167),
    ('火', 'huǒ', 'lửa', 168),
    ('活泼', 'huó pō', 'hoạt bát', 169),
    ('活动', 'huó dòng', 'hoạt động', 170),
    ('汗', 'hàn', 'mồ hôi', 171),
    ('护士', 'hù shì', 'y tá', 172),
    ('怀疑', 'huái yí', 'nghi ngờ', 173),
    ('寒假', 'hán jià', 'kì nghỉ đông', 174),
    ('害羞', 'hài xiū', 'xấu hổ', 175),
    ('好处', 'hǎo chù', 'cái tốt', 176),
    ('好像', 'hǎo xiàng', 'dường như', 177),
    ('回忆', 'huí yì', 'hồi ức, nhớ lại', 178),
    ('后悔', 'hòu huǐ', 'hối hận', 179),
    ('合适', 'hé shì', 'thích hợp', 180),
    ('合格', 'hé gé', 'đạt yêu cầu', 181),
    ('号码', 'hào mǎ', 'số', 182),
    ('厚', 'hòu', 'dày', 183),
    ('互联网', 'hù lián wǎng', 'mạng internet', 184),
    ('互相', 'hù xiāng', 'lẫn nhau', 185),
    ('积极', 'jī jí', 'tích cực', 186),
    ('骄傲', 'jiāo ào', 'tự hào, kiêu ngạo', 187),
    ('饺子', 'jiǎo zi', 'sủi cảo', 188),
    ('降落', 'jiàng luò', 'hạ cánh', 189),
    ('降低', 'jiàng dī', 'hạ thấp', 190),
    ('镜子', 'jìng zi', 'kính', 191),
    ('郊区', 'jiāo qū', 'ngoại ô', 192),
    ('进行', 'jìn xíng', 'tiến hành', 193),
    ('距离', 'jù lí', 'khoảng cách', 194),
    ('记者', 'jì zhě', 'phóng viên', 195),
    ('计划', 'jì huà', 'kế hoạch', 196),
    ('警察', 'jǐng chá', 'cảnh sát', 197),
    ('解释', 'jiě shì', 'giải thích', 198),
    ('节约', 'jié yuē', 'tiết kiệm', 199),
    ('节', 'jié', 'tiết', 200),
    ('聚会', 'jù huì', 'tụ tập', 201),
    ('继续', 'jì xù', 'tiếp tục', 202),
    ('结果', 'jié guǒ', 'kết quả', 203),
    ('经验', 'jīng yàn', 'kinh nghiệm', 204),
    ('经济', 'jīng jì', 'kinh tế', 205),
    ('经历', 'jīng lì', 'trải qua, kinh qua', 206),
    ('紧张', 'jǐn zhāng', 'căng thẳng', 207),
    ('精彩', 'jīng cǎi', 'hấp dẫn', 208),
    ('竟然', 'jìng rán', 'mà lại', 209),
    ('竞争', 'jìng zhēng', 'cạnh tranh', 210),
    ('究竟', 'jiū jìng', 'rốt cuộc', 211),
    ('积累', 'jī lěi', 'tích lũy', 212),
    ('禁止', 'jìn zhǐ', 'cấm', 213),
    ('激动', 'jī dòng', 'xúc động', 214),
    ('景色', 'jǐng sè', 'cảnh sắc', 215),
    ('既然', 'jì rán', 'đã….', 216),
    ('教育', 'jiào yù', 'giáo dục', 217),
    ('教授', 'jiào shòu', 'giáo sư', 218),
    ('接着', 'jiē zhe', 'tiếp theo', 219),
    ('接受', 'jiē shòu', 'tiếp nhận', 220),
    ('拒绝', 'jù jué', 'từ chối', 221),
    ('技术', 'jì shù', 'kỹ thuật', 222),
    ('建议', 'jiàn yì', 'kiến nghị', 223),
    ('尽管', 'jǐn guǎn', 'tuy rằng', 224),
    ('将来', 'jiāng lái', 'tương lai', 225),
    ('寄', 'jì', 'gửi', 226),
    ('家具', 'jiā jù', 'đồ gia dụng', 227),
    ('奖金', 'jiǎng jīn', 'học bổng', 228),
    ('基础', 'jī chǔ', 'cơ sở, căn bản', 229),
    ('坚持', 'jiān chí', 'kiên trì', 230),
    ('及时', 'jí shí', 'kịp thời', 231),
    ('即使', 'jí shǐ', 'cho dù', 232),
    ('加班', 'jiā bān', 'tăng ca', 233),
    ('加油站', 'jiā yóu zhàn', 'cây xăng', 234),
    ('减肥', 'jiǎn féi', 'giảm béo', 235),
    ('减少', 'jiǎn shǎo', 'cắt giảm', 236),
    ('假', 'jiǎ', 'giả', 237),
    ('价格', 'jià gé', 'giá cả', 238),
    ('京剧', 'jīng jù', 'kinh kịch', 239),
    ('交通', 'jiāo tōng', 'giao thông', 240),
    ('交流', 'jiāo liú', 'giao lưu', 241),
    ('交', 'jiāo', 'giao', 242),
    ('举行', 'jǔ xíng', 'tổ chức', 243),
    ('举办', 'jǔ bàn', 'tổ chức', 244),
    ('举', 'jǔ', 'giơ, nâng', 245),
    ('开玩笑', 'kāi wán xiào', 'đùa', 246),
    ('苦', 'kǔ', 'khổ, đắng', 247),
    ('肯定', 'kěn dìng', 'khẳng định', 248),
    ('考虑', 'kǎo lǜ', 'suy nghĩ', 249),
    ('空气', 'kōng qì', 'không khí', 250),
    ('空', 'kōng', 'trống rỗng', 251),
    ('科学', 'kē xué', 'khoa học', 252),
    ('矿泉水', 'kuàng quán shuǐ', 'nước khoáng', 253),
    ('看法', 'kàn fǎ', 'quan điểm', 254),
    ('烤鸭', 'kǎo yā', 'vịt quay', 255),
    ('棵', 'kē', 'lượng từ cho cây', 256),
    ('恐怕', 'kǒng pà', 'e rằng', 257),
    ('开心', 'kāi xīn', 'vui vẻ', 258),
    ('客厅', 'kè tīng', 'phòng khách', 259),
    ('困难', 'kùn nán', 'khó khăn', 260),
    ('困', 'kùn', 'buồn ngủ', 261),
    ('咳嗽', 'ké sou', 'ho', 262),
    ('可是', 'kě shì', 'nhưng', 263),
    ('可惜', 'kě xī', 'đáng tiếc', 264),
    ('可怜', 'kě lián', 'đáng thương', 265),
    ('垃圾桶', 'lā jī tǒng', 'thùng rác', 266),
    ('零钱', 'líng qián', 'tiền lẻ', 267),
    ('连', 'lián', 'liên kết, nối', 268),
    ('辣', 'là', 'cay', 269),
    ('联系', 'lián xì', 'liên hệ', 270),
    ('老虎', 'lǎo hǔ', 'hổ', 271),
    ('礼貌', 'lǐ mào', 'lễ phép, lịch sự', 272),
    ('礼拜天', 'lǐ bài tiān', 'chủ nhật', 273),
    ('留', 'liú', 'lưu lại, ở lại', 274),
    ('理解', 'lǐ jiě', 'lý giải, hiểu', 275),
    ('理想', 'lǐ xiǎng', 'lý tưởng', 276),
    ('理发', 'lǐ fà', 'cắt tóc', 277),
    ('浪费', 'làng fèi', 'lãng phí', 278),
    ('浪漫', 'làng màn', 'lãng mạn', 279),
    ('流行', 'liú xíng', 'thịnh hành', 280),
    ('流利', 'liú lì', 'lưu loát', 281),
    ('来自', 'lái zì', 'đến từ', 282),
    ('来得及', 'lái de jí', 'kịp', 283),
    ('来不及', 'lái bù jí', 'không kịp', 284),
    ('旅行', 'lǚ xíng', 'du lịch', 285),
    ('拉', 'lā', 'kéo', 286),
    ('懒', 'lǎn', 'lười biếng', 287),
    ('律师', 'lǜ shī', 'luật sư', 288),
    ('另外', 'lìng wài', 'ngoài ra, còn lại', 289),
    ('厉害', 'lì hài', 'lợi hại', 290),
    ('力气', 'lì qì', 'sức lực', 291),
    ('凉快', 'liáng kuài', 'mát mẻ', 292),
    ('冷静', 'lěng jìng', 'bình tĩnh', 293),
    ('俩', 'liǎ', 'hai người', 294),
    ('例如', 'lì rú', 'ví dụ', 295),
    ('乱', 'luàn', 'loạn', 296),
    ('麻烦', 'má fan', 'phiền phức, làm phiền', 297),
    ('马虎', 'mǎ hu', 'qua loa', 298),
    ('迷路', 'mí lù', 'lạc đường', 299),
    ('美丽', 'měi lì', 'đẹp', 300),
    ('秒', 'miǎo', 'giây', 301),
    ('目的', 'mù dì', 'mục đích', 302),
    ('满', 'mǎn', 'đầy', 303),
    ('民族', 'mín zú', 'dân tộc', 304),
    ('毛巾', 'máo jīn', 'khăn bông', 305),
    ('毛', 'máo', 'lông', 306),
    ('母亲', 'mǔ qin', 'mẹ', 307),
    ('梦', 'mèng', 'giấc mơ, mơ', 308),
    ('密码', 'mì mǎ', 'mật khẩu', 309),
    ('免费', 'miǎn fèi', 'miễn phí', 310),
    ('耐心', 'nài xīn', 'nhẫn nại', 311),
    ('难道', 'nán dào', 'lẽ nào', 312),
    ('难受', 'nán shòu', 'buồn', 313),
    ('能力', 'néng lì', 'năng lực', 314),
    ('暖和', 'nuǎn huo', 'ấm áp', 315),
    ('弄', 'nòng', 'làm', 316),
    ('年龄', 'nián líng', 'tuổi tác', 317),
    ('内容', 'nèi róng', 'nội dung', 318),
    ('内', 'nèi', 'bên trong', 319),
    ('偶尔', 'ǒu ěr', 'đôi khi', 320),
    ('排队', 'pái duì', 'xếp hàng', 321),
    ('骗', 'piàn', 'lừa', 322),
    ('陪', 'péi', 'cùng', 323),
    ('葡萄', 'pú táo', 'nho', 324),
    ('脾气', 'pí qì', 'tính khí', 325),
    ('篇', 'piān', 'lượng từ cho bài viết', 326),
    ('破', 'pò', 'rách, nổ', 327),
    ('皮肤', 'pí fū', 'da', 328),
    ('普遍', 'pǔ biàn', 'phổ biến', 329),
    ('普通话', 'pǔ tōng huà', 'tiếng phổ thông', 330),
    ('排列', 'pái liè', 'liệt kê', 331),
    ('批评', 'pī píng', 'phê bình', 332),
    ('平时', 'píng shí', 'bình thường', 333),
    ('判断', 'pàn duàn', 'phán đoán', 334),
    ('乒乓球', 'pīng pāng qiú', 'bóng bàn', 335),
    ('其次', 'qí cì', 'tiếp theo', 336),
    ('轻松', 'qīng sōng', 'thoải mái', 337),
    ('轻', 'qīng', 'nhẹ', 338),
    ('缺点', 'quē diǎn', 'khuyết điểm', 339),
    ('缺少', 'quē shǎo', 'thiếu', 340),
    ('签证', 'qiān zhèng', 'visa', 341),
    ('穷', 'qióng', 'nghèo', 342),
    ('确实', 'què shí', 'thật sự', 343),
    ('气候', 'qì hòu', 'khí hậu', 344),
    ('桥', 'qiáo', 'cầu', 345),
    ('敲', 'qiāo', 'gõ', 346),
    ('情况', 'qíng kuàng', 'tình hình', 347),
    ('巧克力', 'qiǎo kè lì', 'sô cô la', 348),
    ('取', 'qǔ', 'lấy', 349),
    ('却', 'què', 'lại', 350),
    ('千万', 'qiān wàn', 'nhất thiết', 351),
    ('区别', 'qū bié', 'khác biệt', 352),
    ('其中', 'qí zhōng', 'trong đó', 353),
    ('全部', 'quán bù', 'toàn bộ', 354),
    ('亲戚', 'qīn qi', 'họ hàng', 355),
    ('然而', 'rán ér', 'vậy mà', 356),
    ('热闹', 'rè nào', 'náo nhiệt', 357),
    ('日记', 'rì jì', 'nhật kí', 358),
    ('扔', 'rēng', 'ném', 359),
    ('入口', 'rù kǒu', 'cửa vào', 360),
    ('任务', 'rèn wù', 'nhiệm vụ', 361),
    ('任何', 'rèn hé', 'bất kì', 362),
    ('仍然', 'réng rán', 'vẫn', 363),
    ('散步', 'sàn bù', 'tản bộ', 364),
    ('首都', 'shǒu dū', 'thủ đô', 365),
    ('首先', 'shǒu xiān', 'đầu tiên', 366),
    ('顺序', 'shùn xù', 'thứ tự', 367),
    ('顺利', 'shùn lì', 'thuận lợi', 368),
    ('顺便', 'shùn biàn', 'nhân tiện', 369),
    ('随着', 'suí zhe', 'cùng với', 370),
    ('随便', 'suí biàn', 'tùy tiện, tự nhiên', 371),
    ('酸', 'suān', 'chua', 372),
    ('速度', 'sù dù', 'tốc độ', 373),
    ('适应', 'shì yìng', 'thích nghi', 374),
    ('适合', 'shì hé', 'thích hợp', 375),
    ('输', 'shū', 'thua', 376),
    ('说明', 'shuō míng', 'nói rõ', 377),
    ('稍微', 'shāo wēi', 'một chút', 378),
    ('社会', 'shè huì', 'xã hội', 379),
    ('硕士', 'shuò shì', 'thạc sĩ', 380),
    ('省', 'shěng', 'tỉnh thành', 381),
    ('申请', 'shēn qǐng', 'xin', 382),
    ('生活', 'shēng huó', 'cuộc sống', 383),
    ('生意', 'shēng yì', 'kinh doanh', 384),
    ('生命', 'shēng mìng', 'tính mạng', 385),
    ('甚至', 'shèn zhì', 'thậm chí', 386),
    ('熟悉', 'shú xī', 'quen thuộc', 387),
    ('深', 'shēn', 'sâu', 388),
    ('沙发', 'shā fā', 'ghế sô pha', 389),
    ('死', 'sǐ', 'chết', 390),
    ('森林', 'sēn lín', 'rừng sâu', 391),
    ('是否', 'shì fǒu', 'liệu có phải', 392),
    ('数量', 'shù liàng', 'số lượng', 393),
    ('数字', 'shù zi', 'con cố', 394),
    ('收拾', 'shōu shí', 'dọn dẹp', 395),
    ('收入', 'shōu rù', 'thu nhập', 396),
    ('收', 'shōu', 'nhận', 397),
    ('所有', 'suǒ yǒu', 'tất cả', 398),
    ('师傅', 'shī fù', 'sư phụ', 399),
    ('帅', 'shuài', 'đẹp trai', 400),
    ('实际', 'shí jì', 'thực tế', 401),
    ('实在', 'shí zài', 'thật sự', 402),
    ('孙子', 'sūn zi', 'cháu trai', 403),
    ('失败', 'shī bài', 'thất bại', 404),
    ('失望', 'shī wàng', 'thất vọng', 405),
    ('塑料袋', 'sù liào dài', 'túi ni lông', 406),
    ('商量', 'shāng liáng', 'thương lượng, bàn bạc', 407),
    ('售货员', 'shòu huò yuán', 'nhân viên bán vé', 408),
    ('受到', 'shòu dào', 'nhận được', 409),
    ('受不了', 'shòu bù liǎo', 'không chịu nổi', 410),
    ('十分', 'shí fēn', 'vô cùng', 411),
    ('勺子', 'sháo zi', 'cái thìa', 412),
    ('剩', 'shèng', 'thừa', 413),
    ('使用', 'shǐ yòng', 'sử dụng', 414),
    ('使', 'shǐ', 'khiến cho', 415),
    ('伤心', 'shāng xīn', 'tổn thương', 416),
    ('世纪', 'shì jì', 'thế kỉ', 417),
    ('台', 'tái', 'cái, chiếc', 418),
    ('通过', 'tōng guò', 'thông qua', 419),
    ('通知', 'tōng zhī', 'thông báo', 420),
    ('躺', 'tǎng', 'nằm', 421),
    ('趟', 'tàng', 'chuyến', 422),
    ('谈', 'tán', 'nói chuyện', 423),
    ('讨论', 'tǎo lùn', 'thảo luận', 424),
    ('讨厌', 'tǎo yàn', 'ghét', 425),
    ('脱', 'tuō', 'cởi', 426),
    ('糖', 'táng', 'đường', 427),
    ('特点', 'tè diǎn', 'đặc điểm', 428),
    ('汤', 'tāng', 'canh', 429),
    ('条件', 'tiáo jiàn', 'điều kiện', 430),
    ('提醒', 'tí xǐng', 'nhắc nhở', 431),
    ('提前', 'tí qián', 'trước thời hạn', 432),
    ('提供', 'tí gōng', 'cung cấp', 433),
    ('提', 'tí', 'đề ra', 434),
    ('推迟', 'tuī chí', 'kéo dài thời gian', 435),
    ('推', 'tuī', 'đẩy', 436),
    ('挺', 'tǐng', 'rất', 437),
    ('抬', 'tái', 'ngẩng', 438),
    ('态度', 'tài dù', 'thái độ', 439),
    ('弹钢琴', 'tán gāng qín', 'chơi piano', 440),
    ('填空', 'tián kòng', 'điền trống', 441),
    ('同时', 'tóng shí', 'đồng thời', 442),
    ('同情', 'tóng qíng', 'đồng tình', 443),
    ('停', 'tíng', 'dừng', 444),
    ('袜子', 'wà zi', 'tất chân', 445),
    ('误会', 'wù huì', 'hiểu lầm', 446),
    ('网站', 'wǎng zhàn', 'trang mạng', 447),
    ('网球', 'wǎng qiú', 'tennis', 448),
    ('温度', 'wēn dù', 'nhiệt độ', 449),
    ('污染', 'wū rǎn', 'ô nhiễm', 450),
    ('无论', 'wú lùn', 'bất luận', 451),
    ('无聊', 'wú liáo', 'nhàm chán', 452),
    ('无', 'wú', 'không', 453),
    ('文章', 'wén zhāng', 'bài văn', 454),
    ('往往', 'wǎng wǎng', 'thường (quá khứ)', 455),
    ('完全', 'wán quán', 'hoàn toàn', 456),
    ('味道', 'wèi dào', 'mùi vị', 457),
    ('危险', 'wēi xiǎn', 'nguy hiểm', 458),
    ('卫生间', 'wèi shēng jiān', 'phòng vệ sinh', 459),
    ('西红柿', 'xī hóng shì', 'cà chua', 460),
    ('香', 'xiāng', 'thơm', 461),
    ('醒', 'xǐng', 'tỉnh', 462),
    ('辛苦', 'xīn kǔ', 'vất vả', 463),
    ('详细', 'xiáng xì', 'tỉ mỉ', 464),
    ('许多', 'xǔ duō', 'rất nhiều', 465),
    ('行', 'xíng', 'được', 466),
    ('羡慕', 'xiàn mù', 'ngưỡng mộ', 467),
    ('笑话', 'xiào huà', 'truyện cười', 468),
    ('相同', 'xiāng tóng', 'giống nhau', 469),
    ('相反', 'xiāng fǎn', 'ngược lại', 470),
    ('现金', 'xiàn jīn', 'tiền mặt', 471),
    ('消息', 'xiāo xi', 'thông tin, tin', 472),
    ('橡皮', 'xiàng pí', 'cục tẩy', 473),
    ('效果', 'xiào guǒ', 'hiệu quả', 474),
    ('性格', 'xìng gé', 'tính cách', 475),
    ('性别', 'xìng bié', 'giới tính', 476),
    ('心情', 'xīn qíng', 'tâm trạng', 477),
    ('幸福', 'xìng fú', 'hạnh phúc', 478),
    ('小说', 'xiǎo shuō', 'tiểu thuyết', 479),
    ('小吃', 'xiǎo chī', 'đồ ăn vặt', 480),
    ('小伙子', 'xiǎo huǒ zi', 'anh chàng', 481),
    ('学期', 'xué qī', 'học kì', 482),
    ('响', 'xiǎng', 'kêu', 483),
    ('咸', 'xián', 'mặn', 484),
    ('吸引', 'xī yǐn', 'thu hút', 485),
    ('兴奋', 'xīng fèn', 'hưng phấn, hứng khởi', 486),
    ('修理', 'xiū lǐ', 'sửa chữa', 487),
    ('信息', 'xìn xī', 'thông tin', 488),
    ('信心', 'xìn xīn', 'niềm tin', 489),
    ('信封', 'xìn fēng', 'bức thư', 490),
    ('压力', 'yā lì', 'áp lực', 491),
    ('预习', 'yù xí', 'chuẩn bị trước', 492),
    ('页', 'yè', 'trang mạng', 493),
    ('阳光', 'yáng guāng', 'ánh nắng', 494),
    ('阅读', 'yuè dú', 'đọc hiểu', 495),
    ('钥匙', 'yào shi', 'chìa khóa', 496),
    ('邮局', 'yóu jú', 'bưu điện', 497),
    ('邀请', 'yāo qǐng', 'mời', 498),
    ('赢', 'yíng', 'thắng', 499),
    ('语言', 'yǔ yán', 'ngôn ngữ', 500),
    ('语法', 'yǔ fǎ', 'ngữ pháp', 501),
    ('要是', 'yào shì', 'nếu', 502),
    ('艺术', 'yì shù', 'nghệ thuật', 503),
    ('羽毛球', 'yǔ máo qiú', 'cầu lông', 504),
    ('约会', 'yuē huì', 'hẹn, cuộc hẹn', 505),
    ('研究', 'yán jiū', 'nghiên cứu', 506),
    ('眼镜', 'yǎn jìng', 'kính mắt', 507),
    ('盐', 'yán', 'muối', 508),
    ('由于', 'yóu yú', 'do', 509),
    ('由', 'yóu', 'do', 510),
    ('牙膏', 'yá gāo', 'kem đánh răng', 511),
    ('演员', 'yǎn yuán', 'diễn viên', 512),
    ('演出', 'yǎn chū', 'buổi diễn', 513),
    ('永远', 'yǒng yuǎn', 'mãi mãi', 514),
    ('样子', 'yàng zi', 'dáng ngoài,bề ngoài', 515),
    ('有趣', 'yǒu qù', 'hứng thú', 516),
    ('意见', 'yì jiàn', 'ý kiến', 517),
    ('愉快', 'yú kuài', 'vui vẻ', 518),
    ('引起', 'yǐn qǐ', 'dẫn đến, gây ra', 519),
    ('应聘', 'yìng pìn', 'ứng tuyển', 520),
    ('幽默', 'yōu mò', 'hài hước', 521),
    ('尤其', 'yóu qí', 'đặc biệt là', 522),
    ('因此', 'yīn cǐ', 'cho nên', 523),
    ('呀', 'yā', 'a', 524),
    ('叶子', 'yè zi', 'chiếc lá', 525),
    ('友谊', 'yǒu yì', 'hữu nghị', 526),
    ('友好', 'yǒu hǎo', 'hữu hảo', 527),
    ('原谅', 'yuán liàng', 'tha thứ', 528),
    ('原来', 'yuán lái', 'hóa ra, vốn, cũ', 529),
    ('原因', 'yuán yīn', 'nguyên nhân', 530),
    ('印象', 'yìn xiàng', 'ấn tượng', 531),
    ('勇敢', 'yǒng gǎn', 'dũng cảm', 532),
    ('养成', 'yǎng chéng', 'nuôi dưỡng, hình thành', 533),
    ('允许', 'yǔn xǔ', 'cho phép', 534),
    ('优秀', 'yōu xiù', 'ưu tú', 535),
    ('优点', 'yōu diǎn', 'ưu điểm', 536),
    ('以为', 'yǐ wéi', 'tưởng rằng', 537),
    ('以', 'yǐ', 'lấy', 538),
    ('亚洲', 'yà zhōu', 'châu Á', 539),
    ('云', 'yún', 'mây', 540),
    ('于是', 'yú shì', 'thế là', 541),
    ('也许', 'yě xǔ', 'có lẽ', 542),
    ('严重', 'yán zhòng', 'nghiêm trọng', 543),
    ('严格', 'yán gé', 'nghiêm khắc', 544),
    ('与', 'yǔ', 'và', 545),
    ('一切', 'yī qiè', 'tất cả', 546),
    ('杂志', 'zá zhì', 'tạp chí', 547),
    ('重视', 'zhòng shì', 'coi trọng', 548),
    ('重点', 'zhòng diǎn', 'trọng điểm', 549),
    ('重', 'zhòng', 'nặng', 550),
    ('转', 'zhuǎn', 'chuyển', 551),
    ('赚', 'zhuàn', 'kiếm', 552),
    ('质量', 'zhì liàng', 'chất lượng', 553),
    ('责任', 'zé rèn', 'trách nhiệm', 554),
    ('证明', 'zhèng míng', 'chứng minh', 555),
    ('著名', 'zhù míng', 'nổi tiếng', 556),
    ('至少', 'zhì shǎo', 'chí ít', 557),
    ('自然', 'zì rán', 'tự nhiên', 558),
    ('自信', 'zì xìn', 'tự tin', 559),
    ('脏', 'zāng', 'bẩn', 560),
    ('职业', 'zhí yè', 'nghề nghiệp', 561),
    ('租', 'zū', 'thuê', 562),
    ('祝贺', 'zhù hè', 'chúc mừng', 563),
    ('知识', 'zhī shí', 'tri thức, kiến thức', 564),
    ('真正', 'zhēn zhèng', 'thật', 565),
    ('直接', 'zhí jiē', 'trực tiếp', 566),
    ('照', 'zhào', 'chiếu', 567),
    ('正确', 'zhèng què', 'chính xác', 568),
    ('正式', 'zhèng shì', 'chính thức', 569),
    ('正常', 'zhèng cháng', 'bình thường', 570),
    ('正好', 'zhèng hǎo', 'vừa hay', 571),
    ('植物', 'zhí wù', 'thực vật', 572),
    ('最好', 'zuì hǎo', 'tốt nhất', 573),
    ('暂时', 'zàn shí', 'tạm thời', 574),
    ('整理', 'zhěng lǐ', 'chỉnh sửa', 575),
    ('支持', 'zhī chí', 'ủng hộ', 576),
    ('指', 'zhǐ', 'chỉ', 577),
    ('招聘', 'zhāo pìn', 'tuyển dụng', 578),
    ('总结', 'zǒng jié', 'tổng kết', 579),
    ('座位', 'zuò wèi', 'chỗ ngồi', 580),
    ('座', 'zuò', 'tòa', 581),
    ('左右', 'zuǒ yòu', 'khoảng', 582),
    ('尊重', 'zūn zhòng', 'tôn trọng', 583),
    ('增加', 'zēng jiā', 'tăng thêm', 584),
    ('咱们', 'zán men', 'chúng ta', 585),
    ('周围', 'zhōu wéi', 'xung quanh', 586),
    ('只要', 'zhǐ yào', 'chỉ cần', 587),
    ('只好', 'zhǐ hǎo', 'đành', 588),
    ('占线', 'zhàn xiàn', 'máy bận', 589),
    ('准确', 'zhǔn què', 'chính xác', 590),
    ('准时', 'zhǔn shí', 'đúng giờ', 591),
    ('值得', 'zhí dé', 'đáng', 592),
    ('作者', 'zuò zhě', 'tác gia', 593),
    ('作用', 'zuò yòng', 'tác dụng', 594),
    ('作家', 'zuò jiā', 'tác gia', 595),
    ('仔细', 'zǐ xì', 'cẩn thận', 596),
    ('之', 'zhī', 'chi', 597),
    ('主意', 'zhǔ yì', 'chủ ý', 598),
    ('专门', 'zhuān mén', 'chuyên môn', 599),
    ('专业', 'zhuān yè', 'chuyên ngành', 600)
) as word(chinese, pinyin, meaning_vi, position)
on conflict (template_deck_id, chinese) do update
set
  pinyin = excluded.pinyin,
  meaning_vi = excluded.meaning_vi,
  position = excluded.position;