-- HSK 2.0 Level 5: 1,300 level-specific words (2,500 cumulative through HSK5).
-- Vietnamese gloss source: https://mychinese.vn/tu-vung-hsk-5.html
insert into public.template_decks (slug, name, description, level)
values (
  'hsk5-co-ban',
  'HSK5 cơ bản',
  'Bộ 1.300 từ vựng HSK5 cơ bản, nối tiếp sau HSK1, HSK2, HSK3 và HSK4.',
  'HSK5'
)
on conflict (slug) do update
set
  name = excluded.name,
  description = excluded.description,
  level = excluded.level;

with target_deck as (
  select id from public.template_decks where slug = 'hsk5-co-ban'
)
insert into public.template_cards (
  template_deck_id,
  chinese,
  pinyin,
  meaning_vi,
  position
)
select
  target_deck.id,
  word.chinese,
  word.pinyin,
  word.meaning_vi,
  word.position
from target_deck
cross join (
  values
    ('哎', 'āi', 'thán từ', 1),
    ('爱护', 'ài hù', 'yêu thương, giữ gìn', 2),
    ('爱惜', 'ài xī', 'quí trọng', 3),
    ('爱心', 'ài xīn', 'lòng tốt', 4),
    ('暗', 'àn', 'tối', 5),
    ('岸', 'àn', 'bờ', 6),
    ('安装', 'ān zhuāng', 'lắp đặt', 7),
    ('安慰', 'ān wèi', 'an ủi', 8),
    ('唉', 'āi', 'thán từ', 9),
    ('熬夜', 'áo yè', 'thức đêm', 10),
    ('鞭炮', 'biān pào', 'pháo', 11),
    ('部门', 'bù mén', 'ban ngành', 12),
    ('避免', 'bì miǎn', 'tránh', 13),
    ('辩论', 'biàn lùn', 'biện luận', 14),
    ('被子', 'bèi zi', 'chăn', 15),
    ('表面', 'biǎo miàn', 'bề mặt, bề ngoài', 16),
    ('表达', 'biǎo dá', 'diễn đạt', 17),
    ('表现', 'biǎo xiàn', 'biểu hiện', 18),
    ('表明', 'biǎo míng', 'cho thấy', 19),
    ('表情', 'biǎo qíng', 'biểu cảm', 20),
    ('补充', 'bǔ chōng', 'bổ sung', 21),
    ('薄', 'báo', 'mỏng', 22),
    ('脖子', 'bó zi', 'cổ', 23),
    ('背景', 'bèi jǐng', 'bối cảnh', 24),
    ('背', 'bèi', 'học thuộc', 25),
    ('编辑', 'biān jí', 'biên tập', 26),
    ('病毒', 'bìng dú', 'vi rút', 27),
    ('玻璃', 'bō lí', 'thủy tinh', 28),
    ('毕竟', 'bì jìng', 'rốt cuộc', 29),
    ('比例', 'bǐ lì', 'tỉ lệ', 30),
    ('步骤', 'bù zhòu', 'bước', 31),
    ('标点', 'biāo diǎn', 'dấu', 32),
    ('标志', 'biāo zhì', 'đánh dấu', 33),
    ('本领', 'běn lǐng', 'bản lĩnh', 34),
    ('本质', 'běn zhì', 'bản chất', 35),
    ('本科', 'běn kē', 'trình độ đại học', 36),
    ('播放', 'bō fàng', 'phát sóng', 37),
    ('摆', 'bǎi', 'bày', 38),
    ('抱怨', 'bào yuàn', 'trách móc', 39),
    ('报道', 'bào dào', 'đưa tin, bản tin', 40),
    ('报社', 'bào shè', 'tòa soạn báo', 41),
    ('报告', 'bào gào', 'báo cáo', 42),
    ('报到', 'bào dào', 'điểm danh', 43),
    ('把握', 'bǎ wò', 'nắm chắc', 44),
    ('悲观', 'bēi guān', 'bi quan', 45),
    ('必要', 'bì yào', 'cần thiết, cần', 46),
    ('必然', 'bì rán', 'tất yếu', 47),
    ('彼此', 'bǐ cǐ', 'lẫn nhau, với nhau, cả hai', 48),
    ('布', 'bù', 'vải', 49),
    ('宝贵', 'bǎo guì', 'quí báu', 50),
    ('宝贝', 'bǎo bèi', 'bảo bối', 51),
    ('博物馆', 'bó wù guǎn', 'bảo tàng', 52),
    ('包裹', 'bāo guǒ', 'bưu kiện', 53),
    ('包括', 'bāo kuò', 'bao gồm', 54),
    ('包含', 'bāo hán', 'bao hàm', 55),
    ('办理', 'bàn lǐ', 'làm (thủ tục)', 56),
    ('冰激凌', 'bīng jī líng', 'kem', 57),
    ('傍晚', 'bàng wǎn', 'chiều muộn', 58),
    ('保险', 'bǎo xiǎn', 'bảo hiểm', 59),
    ('保留', 'bǎo liú', 'bảo lưu', 60),
    ('保持', 'bǎo chí', 'duy trì', 61),
    ('保存', 'bǎo cún', 'lưu giữ, bảo tồn', 62),
    ('便', 'biàn', 'liền', 63),
    ('不足', 'bù zú', 'không đủ', 64),
    ('不见得', 'bù jiàn dé', 'chưa chắc', 65),
    ('不要紧', 'bù yào jǐn', 'không sao', 66),
    ('不耐烦', 'bù nài fán', 'chán nản', 67),
    ('不然', 'bù rán', 'nếu không thì', 68),
    ('不断', 'bù duàn', 'không ngừng', 69),
    ('不得了', 'bù dé liǎo', 'vô cùng', 70),
    ('不安', 'bù ān', 'bất an', 71),
    ('不如', 'bù rú', 'không bằng', 72),
    ('财产', 'cái chǎn', 'tài sản', 73),
    ('除非', 'chú fēi', 'trừ phi', 74),
    ('除夕', 'chú xī', 'giao thừa', 75),
    ('闯', 'chuǎng', 'xông vào, xông lên', 76),
    ('长途', 'cháng tú', 'đường dài', 77),
    ('重复', 'chóng fù', 'lặp lại', 78),
    ('采访', 'cǎi fǎng', 'phỏng vấn', 79),
    ('采取', 'cǎi qǔ', 'chọn, dùng', 80),
    ('醋', 'cù', 'giấm', 81),
    ('迟早', 'chí zǎo', 'sớm muộn', 82),
    ('辞职', 'cí zhí', 'từ chức, bỏ việc', 83),
    ('车库', 'chē kù', 'nhà xe', 84),
    ('车厢', 'chē xiāng', 'toa tàu', 85),
    ('踩', 'cǎi', 'giẫm', 86),
    ('超级', 'chāo jí', 'siêu cấp', 87),
    ('趁', 'chèn', 'nhân', 88),
    ('诚恳', 'chéng kěn', 'thành khẩn', 89),
    ('词汇', 'cí huì', 'từ vựng', 90),
    ('臭', 'chòu', 'thối', 91),
    ('翅膀', 'chì bǎng', 'cánh', 92),
    ('粗糙', 'cū cāo', 'thô ráp', 93),
    ('窗帘', 'chuāng lián', 'rèm cửa', 94),
    ('程度', 'chéng dù', 'trình độ', 95),
    ('程序', 'chéng xù', 'trình tự', 96),
    ('称赞', 'chēng zàn', 'tán thưởng', 97),
    ('称呼', 'chēng hū', 'xưng hô', 98),
    ('称', 'chēng', 'cân', 99),
    ('炒', 'chǎo', 'xào', 100),
    ('潮湿', 'cháo shī', 'ẩm ướt', 101),
    ('测验', 'cè yàn', 'thí nghiệm', 102),
    ('沉默', 'chén mò', 'im lặng', 103),
    ('池塘', 'chí táng', 'ao hồ', 104),
    ('此外', 'cǐ wài', 'ngoài ra', 105),
    ('次要', 'cì yào', 'thứ yếu', 106),
    ('朝', 'cháo', 'về hướng', 107),
    ('曾经', 'céng jīng', 'đã từng', 108),
    ('操心', 'cāo xīn', 'lo lắng', 109),
    ('操场', 'cāo chǎng', 'sân vận động', 110),
    ('插', 'chā', 'cắm', 111),
    ('措施', 'cuò shī', 'sách lược, chính sách', 112),
    ('持续', 'chí xù', 'kéo dài', 113),
    ('拆', 'chāi', 'gỡ, dỡ', 114),
    ('抽象', 'chōu xiàng', 'trừu tượng', 115),
    ('抽屉', 'chōu tì', 'ngăn kéo', 116),
    ('抄', 'chāo', 'chép', 117),
    ('承认', 'chéng rèn', 'thừa nhận', 118),
    ('承担', 'chéng dān', 'chịu trách nhiệm', 119),
    ('承受', 'chéng shòu', 'chịu đựng', 120),
    ('成长', 'chéng zhǎng', 'trưởng thành', 121),
    ('成语', 'chéng yǔ', 'thành ngữ', 122),
    ('成立', 'chéng lì', 'thành lập', 123),
    ('成熟', 'chéng shú', 'thành thục', 124),
    ('成果', 'chéng guǒ', 'thành quả', 125),
    ('成就', 'chéng jiù', 'thành tựu', 126),
    ('成分', 'chéng fèn', 'thành phần', 127),
    ('成人', 'chéng rén', 'người lớn', 128),
    ('惭愧', 'cán kuì', 'hổ thẹn', 129),
    ('彻底', 'chè dǐ', 'triệt để', 130),
    ('彩虹', 'cǎi hóng', 'cầu vồng', 131),
    ('常识', 'cháng shí', 'thường thức', 132),
    ('差距', 'chā jù', 'sự khác biệt', 133),
    ('尺子', 'chǐ zi', 'thước đo', 134),
    ('宠物', 'chǒng wù', 'thú cưng', 135),
    ('存在', 'cún zài', 'tồn tại', 136),
    ('处理', 'chǔ lǐ', 'xử lý', 137),
    ('吹', 'chuī', 'thổi', 138),
    ('吵架', 'chǎo jià', 'cãi vã', 139),
    ('吵', 'chǎo', 'ồn ào', 140),
    ('吃亏', 'chī kuī', 'thiệt thòi', 141),
    ('叉子', 'chā zi', 'cái dĩa, cái xiên, cái nĩa', 142),
    ('参考', 'cān kǎo', 'tham khảo', 143),
    ('参与', 'cān yù', 'can dự', 144),
    ('匆忙', 'cōng máng', 'vội vàng', 145),
    ('刺激', 'cì jī', 'kích thích', 146),
    ('初级', 'chū jí', 'sơ cấp', 147),
    ('创造', 'chuàng zào', 'sáng tạo', 148),
    ('出色', 'chū sè', 'xuất sắc', 149),
    ('出示', 'chū shì', 'xuất trình', 150),
    ('出版', 'chū bǎn', 'xuất bản', 151),
    ('出席', 'chū xí', 'tham dự', 152),
    ('出口', 'chū kǒu', 'lối ra, cửa ra', 153),
    ('冲', 'chōng', 'xông, xô đẩy', 154),
    ('册', 'cè', 'quyển', 155),
    ('充电器', 'chōng diàn qì', 'sạc điện', 156),
    ('充满', 'chōng mǎn', 'tràn đầy', 157),
    ('充分', 'chōng fèn', 'đầy đủ', 158),
    ('催', 'cuī', 'giục', 159),
    ('促进', 'cù jìn', 'xúc tiến', 160),
    ('促使', 'cù shǐ', 'thúc đẩy', 161),
    ('传说', 'chuán shuō', 'truyền thuyết', 162),
    ('传统', 'chuán tǒng', 'truyền thống', 163),
    ('传染', 'chuán rǎn', 'nhiễm', 164),
    ('传播', 'chuán bō', 'lan truyền, lây lan', 165),
    ('从而', 'cóng ér', 'cho nên', 166),
    ('从此', 'cóng cǐ', 'từ đó', 167),
    ('从前', 'cóng qián', 'từ trước', 168),
    ('从事', 'cóng shì', 'theo đuổi', 169),
    ('产生', 'chǎn shēng', 'sản sinh, nảy sinh', 170),
    ('产品', 'chǎn pǐn', 'sản phẩm', 171),
    ('丑', 'chǒu', 'xấu', 172),
    ('答应', 'dā yìng', 'hứa', 173),
    ('顿', 'dùn', 'bữa', 174),
    ('顶', 'dǐng', 'đội, cái (lượng từ cho mũ)', 175),
    ('钓', 'diào', 'câu (cá)', 176),
    ('道理', 'dào lǐ', 'đạo lí, bài học', 177),
    ('道德', 'dào dé', 'đạo đức', 178),
    ('逗', 'dòu', 'trêu', 179),
    ('递', 'dì', 'truyền', 180),
    ('达到', 'dá dào', 'đạt đến', 181),
    ('躲藏', 'duǒ cáng', 'trốn', 182),
    ('蹲', 'dūn', 'quì', 183),
    ('贷款', 'dài kuǎn', 'vay tiền', 184),
    ('豆腐', 'dòu fǔ', 'đậu phụ', 185),
    ('胆小鬼', 'dǎn xiǎo guǐ', 'kẻ nhát gan', 186),
    ('耽误', 'dān wù', 'bỏ lỡ', 187),
    ('等待', 'děng dài', 'đợi, chờ đợi', 188),
    ('等于', 'děng yú', 'bằng', 189),
    ('的确', 'dí què', 'đúng, thật (phó từ)', 190),
    ('登记', 'dēng jì', 'đăng kí', 191),
    ('电池', 'diàn chí', 'pin', 192),
    ('电台', 'diàn tái', 'đài truyền hình', 193),
    ('独立', 'dú lì', 'độc lập', 194),
    ('独特', 'dú tè', 'độc đáo', 195),
    ('点心', 'diǎn xīn', 'điểm tâm', 196),
    ('滴', 'dī', 'giọt', 197),
    ('淡', 'dàn', 'nhạt', 198),
    ('洞', 'dòng', 'hang động', 199),
    ('朵', 'duǒ', 'bông', 200),
    ('断', 'duàn', 'đoạn, đứt', 201),
    ('敌人', 'dí rén', 'kẻ địch', 202),
    ('挡', 'dǎng', 'chắn', 203),
    ('担任', 'dān rèn', 'đảm nhiệm', 204),
    ('打工', 'dǎ gōng', 'làm thêm', 205),
    ('打喷嚏', 'dǎ pēn tì', 'hắt xì', 206),
    ('打听', 'dǎ tīng', 'hỏi thăm', 207),
    ('打交道', 'dǎ jiāo dào', 'kết bạn', 208),
    ('待遇', 'dài yù', 'đãi ngộ', 209),
    ('当心', 'dāng xīn', 'để tâm, lưu tâm', 210),
    ('当地', 'dāng dì', 'địa phương', 211),
    ('度过', 'dù guò', 'trải qua (thời kì, thời gian)', 212),
    ('岛屿', 'dǎo yǔ', 'đảo', 213),
    ('导致', 'dǎo zhì', 'gây ra', 214),
    ('导演', 'dǎo yǎn', 'đạo diễn', 215),
    ('对象', 'duì xiàng', 'đối tượng', 216),
    ('对比', 'duì bǐ', 'đối chiếu', 217),
    ('对方', 'duì fāng', 'đối phương', 218),
    ('对手', 'duì shǒu', 'đối thủ', 219),
    ('对待', 'duì dài', 'đối đãi', 220),
    ('大象', 'dà xiàng', 'voi', 221),
    ('大方', 'dà fāng', 'phóng khoáng', 222),
    ('大型', 'dà xíng', 'lớn (qui mô)', 223),
    ('大厦', 'dà shà', 'tòa nhà', 224),
    ('多余', 'duō yú', 'thừa thãi', 225),
    ('多亏', 'duō kuī', 'thiệt cho ai đó', 226),
    ('堆', 'duī', 'đống', 227),
    ('地震', 'dì zhèn', 'động đất', 228),
    ('地道', 'dì dào', 'chuẩn bản địa (ngôn ngữ, món ăn)', 229),
    ('地理', 'dì lǐ', 'địa lý', 230),
    ('地毯', 'dì tǎn', 'thảm', 231),
    ('地区', 'dì qū', 'khu vực', 232),
    ('地位', 'dì wèi', 'địa vị', 233),
    ('呆', 'dāi', 'ở lì, ở', 234),
    ('吨', 'dūn', 'tấn', 235),
    ('单调', 'dān diào', 'đơn điệu', 236),
    ('单纯', 'dān chún', 'đơn thuần,ngây thơ', 237),
    ('单独', 'dān dú', 'đơn độc', 238),
    ('单元', 'dān yuán', 'đơn nguyên, cụm', 239),
    ('单位', 'dān wèi', 'đơn vị', 240),
    ('动画片', 'dòng huà piàn', 'phim hoạt hình', 241),
    ('到达', 'dào dá', 'đến', 242),
    ('冻', 'dòng', 'đông cứng', 243),
    ('兑换', 'duì huàn', 'đổi', 244),
    ('倒霉', 'dǎo méi', 'xui xẻo', 245),
    ('代表', 'dài biǎo', 'đại diện', 246),
    ('代替', 'dài tì', 'thay thế', 247),
    ('恶劣', 'è liè', 'khắc nghiệt, hà khắc', 248),
    ('耳环', 'ěr huán', 'khuyên tai', 249),
    ('发表', 'fā biǎo', 'phát biểu, đăng, ra mắt (tác phẩm)', 250),
    ('风险', 'fēng xiǎn', 'mạo hiểm, hiểm nguy', 251),
    ('风格', 'fēng gé', 'phong cách', 252),
    ('风景', 'fēng jǐng', 'phong cảnh', 253),
    ('风俗', 'fēng sú', 'phong tục', 254),
    ('非', 'fēi', 'phi, không', 255),
    ('辅导', 'fǔ dǎo', 'phụ đạo, bổ trợ', 256),
    ('讽刺', 'fěng cì', 'châm biếm', 257),
    ('范围', 'fàn wéi', 'phạm vi', 258),
    ('肥皂', 'féi zào', 'bánh xà phòng', 259),
    ('翻', 'fān', 'lật, giở', 260),
    ('罚款', 'fá kuǎn', 'phạt tiền', 261),
    ('纷纷', 'fēn fēn', 'lũ lượt', 262),
    ('繁荣', 'fán róng', 'phồn vinh', 263),
    ('疯狂', 'fēng kuáng', 'điên rồ', 264),
    ('法院', 'fǎ yuàn', 'tòa án', 265),
    ('服装', 'fú zhuāng', 'phục trang, quần áo', 266),
    ('方案', 'fāng àn', 'phương án', 267),
    ('方式', 'fāng shì', 'phương thức', 268),
    ('方', 'fāng', 'phương', 269),
    ('扶', 'fú', 'vịn', 270),
    ('废话', 'fèi huà', 'lời nói thừa thãi', 271),
    ('幅', 'fú', 'bức (lượng từ cho tranh)', 272),
    ('妨碍', 'fáng ài', 'trở ngại, cản trở', 273),
    ('妇女', 'fù nǚ', 'phụ nữ', 274),
    ('奋斗', 'fèn dòu', 'phấn đấu', 275),
    ('复制', 'fù zhì', 'copy', 276),
    ('否认', 'fǒu rèn', 'phủ nhận', 277),
    ('否定', 'fǒu dìng', 'phủ định', 278),
    ('发达', 'fā dá', 'phát đạt, phát triển', 279),
    ('发言', 'fā yán', 'phát biểu (ý kiến)', 280),
    ('发票', 'fā piào', 'hóa đơn giá trị gia tăng', 281),
    ('发明', 'fā míng', 'phát minh', 282),
    ('发挥', 'fā huī', 'phát huy', 283),
    ('发抖', 'fā dǒu', 'run rẩy', 284),
    ('发愁', 'fā chóu', 'phát buồn, chán', 285),
    ('反而', 'fǎn ér', 'ngược lại', 286),
    ('反正', 'fǎn zhèng', 'dù sao thì', 287),
    ('反映', 'fǎn yìng', 'phản ánh', 288),
    ('反应', 'fǎn yìng', 'phản ứng', 289),
    ('反复', 'fǎn fù', 'lặp đi lặp lại', 290),
    ('分配', 'fēn pèi', 'chia sẻ, phân chia, phân công', 291),
    ('分析', 'fēn xī', 'phân tích', 292),
    ('分手', 'fēn shǒu', 'chia tay', 293),
    ('分布', 'fēn bù', 'phân bố', 294),
    ('分别', 'fēn bié', 'phân biệt, lần lượt, xa nhau', 295),
    ('仿佛', 'fǎng fú', 'dường như', 296),
    ('改革', 'gǎi gé', 'cải cách', 297),
    ('鼓舞', 'gǔ wǔ', 'cổ vũ', 298),
    ('鼓掌', 'gǔ zhǎng', 'vỗ tay', 299),
    ('高级', 'gāo jí', 'cao cấp', 300),
    ('高档', 'gāo dàng', 'cao cấp', 301),
    ('骨头', 'gǔ tou', 'xương', 302),
    ('隔壁', 'gé bì', 'sát vách, ngay cạnh', 303),
    ('锅', 'guō', 'nồi', 304),
    ('钢铁', 'gāng tiě', 'sắt thép', 305),
    ('过期', 'guò qī', 'quá hạn', 306),
    ('过敏', 'guò mǐn', 'mẫn cảm, dị ứng', 307),
    ('过分', 'guò fèn', 'quá đáng', 308),
    ('赶紧', 'gǎn jǐn', 'mau chóng', 309),
    ('赶快', 'gǎn kuài', 'mau chóng', 310),
    ('贡献', 'gòng xiàn', 'cống hiến', 311),
    ('规矩', 'guī ju', 'qui tắc', 312),
    ('规模', 'guī mó', 'qui mô', 313),
    ('规律', 'guī lǜ', 'qui luật', 314),
    ('规则', 'guī zé', 'nội qui', 315),
    ('观点', 'guān diǎn', 'quan điểm', 316),
    ('观念', 'guān niàn', 'quan niệm', 317),
    ('观察', 'guān chá', 'quan sát', 318),
    ('股票', 'gǔ piào', 'cổ phiếu', 319),
    ('管子', 'guǎn zi', 'cái ống', 320),
    ('盖', 'gài', 'đậy', 321),
    ('滚', 'gǔn', 'cút, cuộn', 322),
    ('沟通', 'gōu tōng', 'trao đổi, thấu hiểu', 323),
    ('概括', 'gài kuò', 'khái quát', 324),
    ('概念', 'gài niàn', 'khái niệm', 325),
    ('格外', 'gé wài', 'đặc biệt', 326),
    ('根本', 'gēn běn', 'vốn', 327),
    ('根', 'gēn', 'lượng từ: sợi, cành, khúc, ngón', 328),
    ('柜台', 'guì tái', 'quầy ba', 329),
    ('果然', 'guǒ rán', 'quả nhiên', 330),
    ('果实', 'guǒ shí', 'quả thật', 331),
    ('构成', 'gòu chéng', 'tạo thành, cấu thành', 332),
    ('改进', 'gǎi jìn', 'cải tiến', 333),
    ('改正', 'gǎi zhèng', 'đính chính', 334),
    ('改善', 'gǎi shàn', 'cải thiện', 335),
    ('搞', 'gǎo', 'làm', 336),
    ('挂号', 'guà hào', 'xếp số', 337),
    ('拐弯', 'guǎi wān', 'rẽ', 338),
    ('感激', 'gǎn jī', 'cảm kích, biết ơn', 339),
    ('感想', 'gǎn xiǎng', 'cảm tưởng, suy nghĩ', 340),
    ('感受', 'gǎn shòu', 'cảm nhận', 341),
    ('恭喜', 'gōng xǐ', 'chúc mừng', 342),
    ('怪不得', 'guài bù dé', 'chẳng trách', 343),
    ('归纳', 'guī nà', 'tóm tắt', 344),
    ('广泛', 'guǎng fàn', 'rộng khắp', 345),
    ('广大', 'guǎng dà', 'quảng đại, rộng lớn', 346),
    ('广场', 'guǎng chǎng', 'quảng trường', 347),
    ('干脆', 'gān cuì', 'dứt khoát', 348),
    ('干燥', 'gān zào', 'khô ráo, khô hanh', 349),
    ('干活儿', 'gàn huó ér', 'lao động', 350),
    ('工程师', 'gōng chéng shī', 'kỹ sư', 351),
    ('工厂', 'gōng chǎng', 'xưởng, xí nghiệp', 352),
    ('工具', 'gōng jù', 'công cụ', 353),
    ('工人', 'gōng rén', 'công nhân', 354),
    ('工业', 'gōng yè', 'công nghiệp', 355),
    ('官', 'guān', 'quan', 356),
    ('姑娘', 'gū niang', 'cô gái', 357),
    ('姑姑', 'gū gu', 'cô', 358),
    ('国王', 'guó wáng', 'quốc vương', 359),
    ('国庆节', 'guó qìng jié', 'quốc khánh', 360),
    ('固定', 'gù dìng', 'cố định', 361),
    ('告别', 'gào bié', 'từ biệt', 362),
    ('各自', 'gè zì', 'tự, mỗi', 363),
    ('古典', 'gǔ diǎn', 'cổ điển', 364),
    ('古代', 'gǔ dài', 'cổ đại', 365),
    ('功能', 'gōng néng', 'công năng', 366),
    ('冠军', 'guàn jūn', 'quán quân', 367),
    ('关闭', 'guān bì', 'đóng', 368),
    ('公开', 'gōng kāi', 'công khai', 369),
    ('公平', 'gōng píng', 'công bằng', 370),
    ('公布', 'gōng bù', 'công bố', 371),
    ('公寓', 'gōng yù', 'chung cư', 372),
    ('公元', 'gōng yuán', 'công nguyên', 373),
    ('公主', 'gōng zhǔ', 'công chúa', 374),
    ('光盘', 'guāng pán', 'đĩa CD, VCD,DVD', 375),
    ('光滑', 'guāng huá', 'bóng mượt', 376),
    ('光明', 'guāng míng', 'quang minh, sáng sủa', 377),
    ('光临', 'guāng lín', 'đến, có mặt', 378),
    ('乖', 'guāi', 'ngoan', 379),
    ('个性', 'gè xìng', 'cá tính', 380),
    ('个别', 'gè bié', 'cá biệt', 381),
    ('个人', 'gè rén', 'cá nhân', 382),
    ('哈', 'hā', 'ha ha', 383),
    ('黄金', 'huáng jīn', 'vàng', 384),
    ('豪华', 'háo huá', 'sang trọng', 385),
    ('话题', 'huà tí', 'chủ đề', 386),
    ('行业', 'háng yè', 'ngành nghề', 387),
    ('蝴蝶', 'hú dié', 'con bướm', 388),
    ('花生', 'huā shēng', 'lạc', 389),
    ('胡说', 'hú shuō', 'nói nhăng quậy', 390),
    ('胡同', 'hú tòng', 'ngõ, hẻm', 391),
    ('缓解', 'huǎn jiě', 'thả lỏng, giảm', 392),
    ('糊涂', 'hú tú', 'hồ đồ', 393),
    ('猴子', 'hóu zi', 'khỉ', 394),
    ('灰心', 'huī xīn', 'nản lòng', 395),
    ('灰尘', 'huī chén', 'tro bụi', 396),
    ('灰', 'huī', 'màu xám', 397),
    ('火柴', 'huǒ chái', 'diêm', 398),
    ('滑', 'huá', 'trượt, trơn', 399),
    ('海鲜', 'hǎi xiān', 'hải sản', 400),
    ('海关', 'hǎi guān', 'hải quan', 401),
    ('活跃', 'huó yuè', 'sôi nổi', 402),
    ('汇率', 'huì lǜ', 'tỷ giá', 403),
    ('核心', 'hé xīn', 'trọng tâm', 404),
    ('挥', 'huī', 'vẫy', 405),
    ('或许', 'huò xǔ', 'có lẽ', 406),
    ('慌张', 'huāng zhāng', 'hoảng sợ, rối rắm, rối', 407),
    ('恨', 'hèn', 'hận', 408),
    ('恢复', 'huī fù', 'hồi phục, khôi phục', 409),
    ('怀念', 'huái niàn', 'hoài niệm', 410),
    ('怀孕', 'huái yùn', 'mang bầu', 411),
    ('忽视', 'hū shì', 'không coi trọng (kinh tế, ngành nghề, vấn đề nhỏ, nghiên cứu)', 412),
    ('忽然', 'hū rán', 'bỗng nhiên', 413),
    ('幻想', 'huàn xiǎng', 'hoang tưởng', 414),
    ('婚礼', 'hūn lǐ', 'hôn lễ', 415),
    ('婚姻', 'hūn yīn', 'hôn nhân', 416),
    ('好客', 'hào kè', 'hiếu khách', 417),
    ('好奇', 'hào qí', 'hiếu kì', 418),
    ('壶', 'hú', 'bình, ấm', 419),
    ('喊', 'hǎn', 'hét', 420),
    ('和平', 'hé píng', 'hòa bình', 421),
    ('呼吸', 'hū xī', 'hít thở', 422),
    ('后背', 'hòu bèi', 'phía sau', 423),
    ('后果', 'hòu guǒ', 'hậu quả', 424),
    ('合理', 'hé lǐ', 'hợp lý', 425),
    ('合法', 'hé fǎ', 'hợp pháp', 426),
    ('合影', 'hé yǐng', 'chụp ảnh chung, chụp ảnh tập thể', 427),
    ('合同', 'hé tóng', 'hợp đồng', 428),
    ('合作', 'hé zuò', 'hợp tác', 429),
    ('华裔', 'huá yì', 'hoa kiều', 430),
    ('化学', 'huà xué', 'hóa học', 431),
    ('划', 'huá', 'chèo (thuyền)', 432),
    ('何必', 'hé bì', 'hà tất', 433),
    ('何况', 'hé kuàng', 'huống hồ', 434),
    ('伙伴', 'huǒ bàn', 'bạn đồng hành', 435),
    ('机器', 'jī qì', 'máy móc', 436),
    ('驾驶', 'jià shǐ', 'lái xe', 437),
    ('集合', 'jí hé', 'tập hợp', 438),
    ('集体', 'jí tǐ', 'tập thể', 439),
    ('集中', 'jí zhōng', 'tập trung', 440),
    ('阶段', 'jiē duàn', 'giai đoạn', 441),
    ('键盘', 'jiàn pán', 'bàn phím', 442),
    ('金属', 'jīn shǔ', 'kim loại', 443),
    ('酱油', 'jiàng yóu', 'xì dầu', 444),
    ('酒吧', 'jiǔ bā', 'quán ba', 445),
    ('进步', 'jìn bù', 'tiến bộ', 446),
    ('进口', 'jìn kǒu', 'nhập khẩu', 447),
    ('近代', 'jìn dài', 'cận đại', 448),
    ('谨慎', 'jǐn shèn', 'cẩn thận, thận trọng', 449),
    ('讲究', 'jiǎng jiū', 'coi trọng', 450),
    ('讲座', 'jiǎng zuò', 'buổi diễn thuyết', 451),
    ('记忆', 'jì yì', 'ký ức', 452),
    ('记录', 'jì lù', 'ghi chép', 453),
    ('计算', 'jì suàn', 'tính toán', 454),
    ('角色', 'jué sè', 'nhân vật', 455),
    ('角度', 'jiǎo dù', 'góc độ', 456),
    ('节省', 'jié shěng', 'tiết kiệm', 457),
    ('艰苦', 'jiān kǔ', 'gian khổ, gian khóa', 458),
    ('艰巨', 'jiān jù', 'khó khăn (công việc, nhiệm vụ)', 459),
    ('舅舅', 'jiù jiù', 'cậu (em mẹ)', 460),
    ('胶水', 'jiāo shuǐ', 'keo dán', 461),
    ('肩膀', 'jiān bǎng', 'bờ vai', 462),
    ('肌肉', 'jī ròu', 'cơ bắp', 463),
    ('绝对', 'jué duì', 'tuyệt đối', 464),
    ('结账', 'jié zhàng', 'thanh toán', 465),
    ('结论', 'jié lùn', 'kết luận', 466),
    ('结构', 'jié gòu', 'kết cấu', 467),
    ('结实', 'jiē shi', 'chắc chắn', 468),
    ('结合', 'jié hé', 'kết hợp', 469),
    ('经营', 'jīng yíng', 'kinh doanh (cửa hàng), vận hành (công ty)', 470),
    ('经商', 'jīng shāng', 'kinh doanh', 471),
    ('经典', 'jīng diǎn', 'kinh điển', 472),
    ('纪念', 'jì niàn', 'kỉ niệm', 473),
    ('纪律', 'jì lǜ', 'kỷ luật', 474),
    ('纪录', 'jì lù', 'kỷ lục', 475),
    ('紧急', 'jǐn jí', 'cấp bách', 476),
    ('系领带', 'jì lǐng dài', 'thắt cà vạt', 477),
    ('精神', 'jīng shén', 'tinh thần', 478),
    ('精力', 'jīng lì', 'tinh lực', 479),
    ('简直', 'jiǎn zhí', 'gần như', 480),
    ('简历', 'jiǎn lì', 'sơ yếu lý lịch', 481),
    ('甲', 'jiǎ', 'giáp', 482),
    ('狡猾', 'jiǎo huá', 'giảo hoạt', 483),
    ('激烈', 'jī liè', 'khốc liệt, kịch liệt', 484),
    ('浇', 'jiāo', 'tưới nước', 485),
    ('桔子', 'jú zi', 'quýt', 486),
    ('极其', 'jí qí', 'cực kì', 487),
    ('教训', 'jiào xùn', 'giáo huấn, bài học', 488),
    ('教练', 'jiào liàn', 'huấn luyện viên', 489),
    ('教材', 'jiào cái', 'giao trình', 490),
    ('救护车', 'jiù hù chē', 'xe cứu thương', 491),
    ('救', 'jiù', 'cứu', 492),
    ('接近', 'jiē jìn', 'tiếp cận', 493),
    ('接触', 'jiē chù', 'tiếp xúc', 494),
    ('接待', 'jiē dài', 'tiếp đãi', 495),
    ('据说', 'jù shuō', 'nghe nói, nghe đồn', 496),
    ('捡', 'jiǎn', 'nhặt', 497),
    ('捐', 'juān', 'quyên góp', 498),
    ('戒指', 'jiè zhǐ', 'nhẫn', 499),
    ('戒', 'jiè', 'cai (thuốc, rượu, nghiện)', 500),
    ('急诊', 'jí zhěn', 'cấp cứu', 501),
    ('急忙', 'jí máng', 'vội vàng', 502),
    ('建设', 'jiàn shè', 'dựng xây, xây dựng', 503),
    ('建筑', 'jiàn zhù', 'công trình xây dưng, (công ty) xây dựng, (ngành) xây dựng', 504),
    ('建立', 'jiàn lì', 'thành lập (tổ chức, trường học), thiết lập (quan hệ)', 505),
    ('巨大', 'jù dà', 'lớn (thành tựu, thay đổi, ảnh hưởng, tác hại)', 506),
    ('届', 'jiè', 'khóa', 507),
    ('居然', 'jū rán', 'không ngờ lại', 508),
    ('尽量', 'jǐn liàng', 'cố gắng', 509),
    ('尽快', 'jǐn kuài', 'mau chóng', 510),
    ('尽力', 'jìn lì', 'dốc hết sức', 511),
    ('寂寞', 'jì mò', 'cô đơn', 512),
    ('家庭', 'jiā tíng', 'gia đình', 513),
    ('家务', 'jiā wù', 'việc nhà', 514),
    ('家乡', 'jiā xiāng', 'quê hương', 515),
    ('嫁', 'jià', 'gả chồng', 516),
    ('夹子', 'jiā zi', 'cái kẹp', 517),
    ('基本', 'jī běn', 'cơ bản, căn bản', 518),
    ('坚强', 'jiān qiáng', 'kiên cường', 519),
    ('坚决', 'jiān jué', 'kiên quyết', 520),
    ('均匀', 'jūn yún', 'bình quân, trung bình', 521),
    ('嘉宾', 'jiā bīn', 'khách mời', 522),
    ('及格', 'jí gé', 'đạt điểm qua', 523),
    ('剪刀', 'jiǎn dāo', 'cái kéo', 524),
    ('决赛', 'jué sài', 'trận chung kết', 525),
    ('决心', 'jué xīn', 'quyết tâm', 526),
    ('军事', 'jūn shì', 'quân sự', 527),
    ('兼职', 'jiān zhí', 'kiêm nhiệm', 528),
    ('具备', 'jù bèi', 'chuẩn bị đủ, có đủ (tư cách, điều kiện, tinh lực)', 529),
    ('具体', 'jù tǐ', 'cụ thể', 530),
    ('健身', 'jiàn shēn', 'tập thể dục', 531),
    ('假设', 'jiǎ shè', 'giả thuyết', 532),
    ('假装', 'jiǎ zhuāng', 'giả vờ', 533),
    ('假如', 'jiǎ rú', 'giả dụ', 534),
    ('借口', 'jiè kǒu', 'cớ, lí do', 535),
    ('俱乐部', 'jù lè bù', 'câu lạc bộ', 536),
    ('价值', 'jià zhí', 'giá trị', 537),
    ('交际', 'jiāo jì', 'giao tiếp', 538),
    ('交换', 'jiāo huàn', 'trao đổi', 539),
    ('交往', 'jiāo wǎng', 'đi lại, giao thiệp', 540),
    ('卡车', 'kǎ chē', 'xe tải', 541),
    ('颗', 'kē', 'quả (lượng từ)', 542),
    ('靠', 'kào', 'dựa dẫm, dựa vào', 543),
    ('课程', 'kè chéng', 'môn học', 544),
    ('空间', 'kōng jiān', 'không gian', 545),
    ('空闲', 'kòng xián', 'rảnh rỗi (thời gian)', 546),
    ('砍', 'kǎn', 'chặt, chém', 547),
    ('看望', 'kàn wàng', 'đi thăm', 548),
    ('看不起', 'kàn bù qǐ', 'coi khinh', 549),
    ('昆虫', 'kūn chóng', 'côn trùng', 550),
    ('控制', 'kòng zhì', 'kiềm chế (cảm xúc, tình cảm), kiểm soát', 551),
    ('扩大', 'kuò dà', 'mở rộng (phạm vi, khoảng cách, thị trường)', 552),
    ('开水', 'kāi shuǐ', 'nước sôi', 553),
    ('开放', 'kāi fàng', 'mở cửa', 554),
    ('开幕式', 'kāi mù shì', 'lễ khai mạc', 555),
    ('开发', 'kāi fā', 'phát triển (hệ thống, ngành nghề, kĩ thuật, sản phẩm)', 556),
    ('宽', 'kuān', 'rộng', 557),
    ('客观', 'kè guān', 'khách quan', 558),
    ('夸张', 'kuā zhāng', 'phóng đại', 559),
    ('夸', 'kuā', 'khen', 560),
    ('可靠', 'kě kào', 'đáng tin cậy', 561),
    ('可见', 'kě jiàn', 'cho thấy (đứng đầu vế câu thứ hai)', 562),
    ('可怕', 'kě pà', 'đáng sợ', 563),
    ('口味', 'kǒu wèi', 'khẩu vị', 564),
    ('刻苦', 'kè kǔ', 'khắc khổ, chịu khó', 565),
    ('克服', 'kè fú', 'khắc phục', 566),
    ('克', 'kè', 'gram', 567),
    ('会计', 'kuàì jì', 'kế toán', 568),
    ('辣椒', 'là jiāo', 'ớt', 569),
    ('龙', 'lóng', 'rồng', 570),
    ('领导', 'lǐng dǎo', 'lãnh đạo', 571),
    ('领域', 'lǐng yù', 'lĩnh vực', 572),
    ('雷', 'léi', 'sấm', 573),
    ('零食', 'líng shí', 'đồ ăn vặt', 574),
    ('零件', 'líng jiàn', 'linh kiện', 575),
    ('陆续', 'lù xù', 'lục tục, liên tiếp', 576),
    ('陆地', 'lù dì', 'lục địa, đất liền', 577),
    ('铃', 'líng', 'chuông', 578),
    ('逻辑', 'luó jí', 'logic', 579),
    ('连续', 'lián xù', 'liên tục', 580),
    ('连忙', 'lián máng', 'vội vã', 581),
    ('轮流', 'lún liú', 'luân lưu, thay phiên', 582),
    ('论文', 'lùn wén', 'luận văn', 583),
    ('落后', 'luò hòu', 'lạc hậu', 584),
    ('良好', 'liáng hǎo', 'tốt đẹp', 585),
    ('联合', 'lián hé', 'liên hiệp', 586),
    ('老鼠', 'lǎo shǔ', 'con chuột', 587),
    ('老百姓', 'lǎo bǎi xìng', 'lão bách tính', 588),
    ('老板', 'lǎo bǎn', 'ông chủ', 589),
    ('老实', 'lǎo shí', 'thật thà', 590),
    ('老婆', 'lǎo pó', 'bà xã', 591),
    ('粮食', 'liáng shí', 'lương thực', 592),
    ('类型', 'lèi xíng', 'loại hình', 593),
    ('立即', 'lì jí', 'lập tức', 594),
    ('立刻', 'lì kè', 'lập tức', 595),
    ('离婚', 'lí hūn', 'li hôn', 596),
    ('理论', 'lǐ lùn', 'lý luận', 597),
    ('理由', 'lǐ yóu', 'lí do', 598),
    ('烂', 'làn', 'nát, loét, rách, thối rữa', 599),
    ('灵活', 'líng huó', 'linh hoạt', 600),
    ('漏', 'lòu', 'dột', 601),
    ('浏览', 'liú lǎn', 'đọc lướt', 602),
    ('流泪', 'liú lèi', 'rơi lệ', 603),
    ('流传', 'liú chuán', 'lưu truyền, lan truyền', 604),
    ('梨', 'lí', 'quả lê', 605),
    ('朗读', 'lǎng dú', 'đọc to', 606),
    ('拦', 'lán', 'ngăn, chặn', 607),
    ('恋爱', 'liàn ài', 'yêu đương', 608),
    ('录音', 'lù yīn', 'ghi âm', 609),
    ('录取', 'lù qǔ', 'tuyển chọn', 610),
    ('姥姥', 'lǎo lǎo', 'bà ngoại', 611),
    ('厘米', 'lí mǐ', 'cm', 612),
    ('劳驾', 'láo jià', 'làm ơn, xin phiền', 613),
    ('劳动', 'láo dòng', 'lao động', 614),
    ('力量', 'lì liàng', 'sức mạnh', 615),
    ('利益', 'lì yì', 'lợi ích', 616),
    ('利用', 'lì yòng', 'tận dụng, lợi dụng', 617),
    ('利润', 'lì rùn', 'lợi nhuận', 618),
    ('利息', 'lì xī', 'lợi tức', 619),
    ('列车', 'liè chē', 'tàu hỏa', 620),
    ('冷淡', 'lěng dàn', 'lãnh đạm, lạnh nhạt, lạnh lùng', 621),
    ('亮', 'liàng', 'sáng', 622),
    ('了不起', 'liǎo bù qǐ', 'giỏi giang', 623),
    ('乐观', 'lè guān', 'lạc quan', 624),
    ('临时', 'lín shí', 'lâm thời, thời vụ, tạm thời', 625),
    ('骂', 'mà', 'mắng mỏ', 626),
    ('麦克风', 'mài kè fēng', 'microphone', 627),
    ('魅力', 'mèi lì', 'sức hút', 628),
    ('馒头', 'mán tóu', 'bánh bao không nhân, màn thầu', 629),
    ('面积', 'miàn jī', 'diện tích', 630),
    ('面对', 'miàn duì', 'đối mặt (chứng cứ, tương lai, khủng khoảng, thách thức), đối diện', 631),
    ('面临', 'miàn lín', 'đứng trước (khó khăn, nguy hiểm, thách thức)', 632),
    ('陌生', 'mò shēng', 'lạ lẫm', 633),
    ('贸易', 'mào yì', 'thương mại', 634),
    ('蜜蜂', 'mì fēng', 'con ong', 635),
    ('苗条', 'miáo tiáo', 'thon thả', 636),
    ('美术', 'měi shù', 'mỹ thuật', 637),
    ('秘密', 'mì mì', 'bí mật', 638),
    ('秘书', 'mì shū', 'thư kí', 639),
    ('矛盾', 'máo dùn', 'mâu thuẫn', 640),
    ('眉毛', 'méi máo', 'lông mày', 641),
    ('目标', 'mù biāo', 'mục tiêu', 642),
    ('目录', 'mù lù', 'mục lục', 643),
    ('目前', 'mù qián', 'trước mắt, hiện nay', 644),
    ('煤炭', 'méi tàn', 'than', 645),
    ('满足', 'mǎn zú', 'đáp ứng (yêu cầu, điều kiện, tính tò mò, lòng tham)', 646),
    ('毛病', 'máo bìng', 'tật xấu, lỗi', 647),
    ('模糊', 'mó hu', 'mơ hồ', 648),
    ('模特', 'mó tè', 'người mẫu', 649),
    ('模仿', 'mó fǎng', 'bắt chước', 650),
    ('梦想', 'mèng xiǎng', 'ước mơ', 651),
    ('某', 'mǒu', 'nào đó', 652),
    ('木头', 'mù tóu', 'khúc gỗ', 653),
    ('明确', 'míng què', 'rõ ràng, rành mạch', 654),
    ('明显', 'míng xiǎn', 'rõ ràng', 655),
    ('明星', 'míng xīng', 'minh tinh', 656),
    ('敏感', 'mǐn gǎn', 'nhạy cảm', 657),
    ('摸', 'mō', 'sờ', 658),
    ('摩托车', 'mó tuō chē', 'xe máy', 659),
    ('描写', 'miáo xiě', 'miêu tả', 660),
    ('密切', 'mì qiè', 'mật thiết', 661),
    ('媒体', 'méi tǐ', 'truyền thông, báo chí', 662),
    ('命运', 'mìng yùn', 'vận mệnh', 663),
    ('命令', 'mìng lìng', 'mệnh lệnh', 664),
    ('名胜古迹', 'míng shèng gǔ jì', 'danh lam thắng cảnh', 665),
    ('名牌', 'míng pái', 'thương hiệu nổi tiếng', 666),
    ('名片', 'míng piàn', 'danh thiếp', 667),
    ('冒险', 'mào xiǎn', 'mạo hiểm', 668),
    ('哪怕', 'nǎ pà', 'cho dù', 669),
    ('难怪', 'nán guài', 'chẳng trách', 670),
    ('难免', 'nán miǎn', 'khó tránh', 671),
    ('脑袋', 'nǎo dài', 'não', 672),
    ('能源', 'néng yuán', 'tài nguyên', 673),
    ('能干', 'néng gàn', 'được việc', 674),
    ('牛仔裤', 'niú zǎi kù', 'quần bò', 675),
    ('浓', 'nóng', 'nồng, đậm', 676),
    ('念', 'niàn', 'đọc', 677),
    ('年纪', 'nián jì', 'tuổi tác', 678),
    ('年代', 'nián dài', 'thời đại', 679),
    ('宁可', 'nìng kě', 'thà', 680),
    ('嫩', 'nèn', 'mềm, non', 681),
    ('嗯', 'ńg', 'ừ, ừm', 682),
    ('农民', 'nóng mín', 'nông dân', 683),
    ('农村', 'nóng cūn', 'nông thôn', 684),
    ('农业', 'nóng yè', 'nông nghiệp', 685),
    ('内部', 'nèi bù', 'nội bộ', 686),
    ('内科', 'nèi kē', 'khoa nội', 687),
    ('女士', 'nǚ shì', 'quí cô, quí bà', 688),
    ('欧洲', 'ōu zhōu', 'châu Âu', 689),
    ('偶然', 'ǒu rán', 'ngẫu nhiên', 690),
    ('拍', 'pāi', 'vỗ', 691),
    ('飘', 'piāo', 'bay', 692),
    ('频道', 'pín dào', 'kênh', 693),
    ('配合', 'pèi hé', 'phối hợp', 694),
    ('赔偿', 'péi cháng', 'bồi thường', 695),
    ('评价', 'píng jià', 'đánh giá', 696),
    ('碰', 'pèng', 'gặp phải', 697),
    ('盼望', 'pàn wàng', 'mong chờ', 698),
    ('盆', 'pén', 'chậu', 699),
    ('疲劳', 'pí láo', 'mệt mỏi', 700),
    ('片面', 'piàn miàn', 'phiến diện', 701),
    ('片', 'piàn', 'chiếc, lát, mảnh (lượng từ cho lá, bánh mì, đất đai )', 702),
    ('派', 'pài', 'cử, phái', 703),
    ('拼音', 'pīn yīn', 'phiên âm', 704),
    ('披', 'pī', 'khoác', 705),
    ('批准', 'pī zhǔn', 'phê chuẩn, đồng ý', 706),
    ('批', 'pī', 'loạt, lô (lượng từ)', 707),
    ('平静', 'píng jìng', 'bình tĩnh', 708),
    ('平衡', 'píng héng', 'cân bằng', 709),
    ('平等', 'píng děng', 'bình đẳng', 710),
    ('平方', 'píng fāng', 'bình phương', 711),
    ('平常', 'píng cháng', 'bình thường', 712),
    ('平安', 'píng ān', 'bình an', 713),
    ('平均', 'píng jūn', 'trung bình, bình quân', 714),
    ('平', 'píng', 'bằng, đều', 715),
    ('培训', 'péi xùn', 'bồi dưỡng, tập huấn', 716),
    ('培养', 'péi yǎng', 'nuôi dưỡng, hình thành', 717),
    ('匹', 'pǐ', 'con (lượng từ cho ngựa)', 718),
    ('凭', 'píng', 'dựa vào', 719),
    ('佩服', 'pèi fú', 'khâm phục', 720),
    ('迫切', 'pò qiè', 'cấp bách', 721),
    ('青春', 'qīng chūn', 'thanh xuân', 722),
    ('青少年', 'qīng shào nián', 'thanh thiếu niên', 723),
    ('青', 'qīng', 'màu xanh non', 724),
    ('轻视', 'qīng shì', 'coi khinh, khinh thường', 725),
    ('轻易', 'qīng yì', 'dễ dàng (làm trạng ngữ), khinh suất', 726),
    ('趋势', 'qū shì', 'xu thế', 727),
    ('谦虚', 'qiān xū', 'khiêm tốn', 728),
    ('请求', 'qǐng qiú', 'thỉnh cầu', 729),
    ('群', 'qún', 'đám', 730),
    ('缺乏', 'quē fá', 'thiếu', 731),
    ('签', 'qiān', 'kí (tên)', 732),
    ('确认', 'què rèn', 'xác nhận', 733),
    ('确定', 'què dìng', 'xác định', 734),
    ('破坏', 'pò huài', 'phá hoại', 735),
    ('破产', 'pò chǎn', 'phá sản', 736),
    ('瞧', 'qiáo', 'liếc nhìn', 737),
    ('球迷', 'qiú mí', 'người hâm mộ bóng', 738),
    ('清淡', 'qīng dàn', 'thanh đạm', 739),
    ('浅', 'qiǎn', 'nhạt', 740),
    ('汽油', 'qì yóu', 'xăng', 741),
    ('气氛', 'qì fēn', 'không khí (cuộc họp, buổi tiệc)', 742),
    ('欠', 'qiàn', 'nợ', 743),
    ('枪', 'qiāng', 'súng', 744),
    ('权力', 'quán lì', 'quyền lực', 745),
    ('权利', 'quán lì', 'quyền lợi', 746),
    ('期间', 'qī jiān', 'khoảng thời gian', 747),
    ('期待', 'qī dài', 'kì vọng', 748),
    ('抢', 'qiǎng', 'cướp', 749),
    ('情绪', 'qíng xù', 'tâm trạng', 750),
    ('情景', 'qíng jǐng', 'cảnh tượng', 751),
    ('悄悄', 'qiāo qiāo', 'lặng lẽ', 752),
    ('强调', 'qiáng diào', 'nhấn mạnh', 753),
    ('强烈', 'qiáng liè', 'mãnh liệt, mạnh mẽ', 754),
    ('庆祝', 'qìng zhù', 'chúc mừng', 755),
    ('巧妙', 'qiǎo miào', 'khéo léo', 756),
    ('娶', 'qǔ', 'lấy (vợ)', 757),
    ('奇迹', 'qí jì', 'kì tích', 758),
    ('墙', 'qiáng', 'tường', 759),
    ('圈', 'quān', 'vòng', 760),
    ('启发', 'qǐ fā', 'gợi mở, gợi ý', 761),
    ('取消', 'qǔ xiāo', 'hủy bỏ', 762),
    ('去世', 'qù shì', 'tạ thế', 763),
    ('勤奋', 'qín fèn', 'cần cù', 764),
    ('劝', 'quàn', 'khuyên', 765),
    ('前途', 'qián tú', 'tiền đồ', 766),
    ('切', 'qiè', 'cắt', 767),
    ('其余', 'qí yú', 'còn lại', 768),
    ('全面', 'quán miàn', 'toàn diện', 769),
    ('企业', 'qǐ yè', 'nhà máy, xí nghiệp', 770),
    ('亲自', 'qīn zì', 'tự thân', 771),
    ('亲爱', 'qīn ài', 'thân yêu', 772),
    ('亲切', 'qīn qiè', 'thân thiết', 773),
    ('燃烧', 'rán shāo', 'đốt cháy', 774),
    ('软件', 'ruǎn jiàn', 'phần mềm', 775),
    ('软', 'ruǎn', 'mềm', 776),
    ('绕', 'rào', 'vòng vèo', 777),
    ('热爱', 'rè ài', 'yêu (cuộc sống, học sinh, thiên nhiên, âm nhạc, bạn bè, người thân)', 778),
    ('热烈', 'rè liè', 'nhiệt liệt', 779),
    ('热心', 'rè xīn', 'nhiệt tình (người, người bạn), nhiệt huyết', 780),
    ('日程', 'rì chéng', 'lịch trình', 781),
    ('日用品', 'rì yòng pǐn', 'đồ dùng', 782),
    ('日期', 'rì qī', 'ngày tháng', 783),
    ('日常', 'rì cháng', 'thường ngày', 784),
    ('日子', 'rì zi', 'ngày', 785),
    ('日历', 'rì lì', 'quyển lịch', 786),
    ('忍不住', 'rěn bù zhù', 'không nhịn được', 787),
    ('弱', 'ruò', 'yếu ớt', 788),
    ('如何', 'rú hé', 'như thế nào', 789),
    ('如今', 'rú jīn', 'hiện nay', 790),
    ('人类', 'rén lèi', 'loài người', 791),
    ('人生', 'rén shēng', 'đời người', 792),
    ('人物', 'rén wù', 'nhân vật', 793),
    ('人民币', 'rén mín bì', 'nhân dân tệ', 794),
    ('人才', 'rén cái', 'nhân tài', 795),
    ('人员', 'rén yuán', 'nhân viên', 796),
    ('人口', 'rén kǒu', 'dân số', 797),
    ('人事', 'rén shì', 'nhân sự', 798),
    ('洒', 'sǎ', 'vãi, vung', 799),
    ('鼠标', 'shǔ biāo', 'chuột máy tính', 800),
    ('首', 'shǒu', 'đầu', 801),
    ('食物', 'shí wù', 'đồ ăn', 802),
    ('随身', 'suí shēn', 'mang theo người', 803),
    ('随时', 'suí shí', 'bất cứ lúc nào', 804),
    ('随手', 'suí shǒu', 'tiện tay', 805),
    ('闪电', 'shǎn diàn', 'chớp', 806),
    ('锁', 'suǒ', 'khóa', 807),
    ('输入', 'shū rù', 'nhập', 808),
    ('身材', 'shēn cái', 'cơ thể, dáng', 809),
    ('身份', 'shēn fèn', 'thân phận', 810),
    ('说服', 'shuō fú', 'thuyết phục', 811),
    ('说不定', 'shuō bù dìng', 'chưa biết chừng', 812),
    ('诗', 'shī', 'thơ', 813),
    ('试卷', 'shì juàn', 'bài thi', 814),
    ('设计', 'shè jì', 'thiết kế', 815),
    ('设施', 'shè shī', 'cơ sở vật chất', 816),
    ('设备', 'shè bèi', 'thiết bị', 817),
    ('蛇', 'shé', 'rắn', 818),
    ('蔬菜', 'shū cài', 'rau xanh', 819),
    ('色彩', 'sè cǎi', 'màu sắc', 820),
    ('舒适', 'shū shì', 'thoải mái', 821),
    ('舍不得', 'shě bù dé', 'không nỡ lòng', 822),
    ('胜利', 'shèng lì', 'thắng lợi', 823),
    ('缩短', 'suō duǎn', 'thu hẹp (khoảng cách), rút ngắn (thời gian), cắt ngắn (câu chuyện)', 824),
    ('绳子', 'shéng zi', 'dây thừng', 825),
    ('税', 'shuì', 'thuế', 826),
    ('私人', 'sī rén', 'tư nhân', 827),
    ('神话', 'shén huà', 'thần thoại', 828),
    ('神秘', 'shén mì', 'thần bí', 829),
    ('碎', 'suì', 'vỡ vụn', 830),
    ('石头', 'shí tou', 'hòn đá', 831),
    ('省略', 'shěng lüè', 'tỉnh lược', 832),
    ('甩', 'shuǎi', 'vung, hất, bỏ lại', 833),
    ('生长', 'shēng zhǎng', 'sinh trưởng, lớn', 834),
    ('生动', 'shēng dòng', 'sinh động', 835),
    ('生产', 'shēng chǎn', 'sản xuất', 836),
    ('狮子', 'shī zi', 'sư tử', 837),
    ('熟练', 'shú liàn', 'thành thục', 838),
    ('湿润', 'shī rùn', 'ẩm ướt', 839),
    ('深刻', 'shēn kè', 'sâu sắc', 840),
    ('沙漠', 'shā mò', 'sa mạc', 841),
    ('沙滩', 'shā tān', 'bãi cát', 842),
    ('梳子', 'shū zi', 'cái lược', 843),
    ('杀', 'shā', 'giết', 844),
    ('晒', 'shài', 'phơi, tắm nắng', 845),
    ('时髦', 'shí máo', 'mốt', 846),
    ('时期', 'shí qī', 'thời kì', 847),
    ('时差', 'shí chā', 'lệch múi giờ', 848),
    ('时尚', 'shí shàng', 'thời thượng', 849),
    ('时刻', 'shí kè', 'khoảnh khắc', 850),
    ('时代', 'shí dài', 'thời đại', 851),
    ('数码', 'shù mǎ', 'kỹ thuật số', 852),
    ('数据', 'shù jù', 'số liệu', 853),
    ('数', 'shǔ', 'đếm', 854),
    ('收获', 'shōu huò', 'thu hoạch', 855),
    ('收据', 'shōu jù', 'giấy biên nhận', 856),
    ('撕', 'sī', 'xé', 857),
    ('摔倒', 'shuāi dǎo', 'ngã nhào', 858),
    ('摄影', 'shè yǐng', 'quay phim, chụp ảnh', 859),
    ('搜索', 'sōu suǒ', 'tìm kiếm', 860),
    ('损失', 'sǔn shī', 'tổn thất', 861),
    ('手续', 'shǒu xù', 'thủ tục', 862),
    ('手术', 'shǒu shù', 'phẫu thuật', 863),
    ('手指', 'shǒu zhǐ', 'ngón tay', 864),
    ('手工', 'shǒu gōng', 'thủ công', 865),
    ('手套', 'shǒu tào', 'găng tay', 866),
    ('扇子', 'shàn zi', 'cái quạt', 867),
    ('所', 'suǒ', 'trợ từ', 868),
    ('思考', 'sī kǎo', 'suy nghĩ', 869),
    ('思想', 'sī xiǎng', 'tư tưởng', 870),
    ('市场', 'shì chǎng', 'chợ', 871),
    ('属于', 'shǔ yú', 'thuộc về', 872),
    ('射击', 'shè jī', 'bắn', 873),
    ('寿命', 'shòu mìng', 'tuổi thọ', 874),
    ('宿舍', 'sù shè', 'ký túc xá', 875),
    ('实验', 'shí yàn', 'thí nghiệm', 876),
    ('实践', 'shí jiàn', 'thực tiễn', 877),
    ('实话', 'shí huà', 'lời nói thật', 878),
    ('实用', 'shí yòng', 'hữu ích', 879),
    ('实现', 'shí xiàn', 'thực hiện (kế hoạch, nguyện vọng, ước mơ)', 880),
    ('实习', 'shí xí', 'thực tập', 881),
    ('始终', 'shǐ zhōng', 'từ đầu đến cuối', 882),
    ('失眠', 'shī mián', 'mất ngủ', 883),
    ('失去', 'shī qù', 'mất đi', 884),
    ('失业', 'shī yè', 'thất nghiệp', 885),
    ('声调', 'shēng diào', 'thanh điệu', 886),
    ('士兵', 'shì bīng', 'binh sĩ', 887),
    ('嗓子', 'sǎng zi', 'cổ họng', 888),
    ('善良', 'shàn liáng', 'lương thiện, hiền lành', 889),
    ('善于', 'shàn yú', 'giỏi về việc gì đó', 890),
    ('商品', 'shāng pǐn', 'sản phẩm', 891),
    ('商务', 'shāng wù', 'thương gia (hạng, khoang),', 892),
    ('商业', 'shāng yè', 'thương mại', 893),
    ('受伤', 'shòu shāng', 'bị thương', 894),
    ('双方', 'shuāng fāng', 'hai bên, song phương', 895),
    ('升', 'shēng', 'thăng, lên, lít (đơn vị đo thể tích)', 896),
    ('删除', 'shān chú', 'xoa bỏ', 897),
    ('傻', 'shǎ', 'ngốc nghếch', 898),
    ('使劲儿', 'shǐ jìn ér', 'ra sức, lấy sức', 899),
    ('似的', 'shì de', 'giống như….', 900),
    ('似乎', 'sì hū', 'dường như', 901),
    ('伸', 'shēn', 'vươn, duỗi, kéo dài', 902),
    ('伤害', 'shāng hài', 'làm hại', 903),
    ('事物', 'shì wù', 'sự vật', 904),
    ('事实', 'shì shí', 'sự thật', 905),
    ('事先', 'shì xiān', 'trước khi việc xảy ra', 906),
    ('书架', 'shū jià', 'giá sách', 907),
    ('丝绸', 'sī chóu', 'tơ lụa', 908),
    ('丝毫', 'sī háo', 'một chút (dùng dạng phủ định)', 909),
    ('上当', 'shàng dàng', 'mắc lừa', 910),
    ('台阶', 'tái jiē', 'bậc thềm, bậc', 911),
    ('题目', 'tí mù', 'đề mục', 912),
    ('通常', 'tōng cháng', 'thông thường', 913),
    ('透明', 'tòu míng', 'trong suốt', 914),
    ('逃避', 'táo bì', 'trốn tránh', 915),
    ('逃', 'táo', 'chạy trốn', 916),
    ('退步', 'tuì bù', 'lùi bước', 917),
    ('退休', 'tuì xiū', 'nghỉ hưu', 918),
    ('退', 'tuì', 'lùi', 919),
    ('谈判', 'tán pàn', 'đàm phán', 920),
    ('调皮', 'tiáo pí', 'nghịch ngợm', 921),
    ('调整', 'tiáo zhěng', 'điều chỉnh', 922),
    ('讨价还价', 'tǎo jià huán jià', 'mặc cả', 923),
    ('统一', 'tǒng yī', 'thống nhất', 924),
    ('突出', 'tū chū', 'làm nổi bật', 925),
    ('痛苦', 'tòng kǔ', 'đau khổ', 926),
    ('痛快', 'tòng kuài', 'sung sướng', 927),
    ('疼爱', 'téng ài', 'chiều chuộng, yêu chiều', 928),
    ('特色', 'tè sè', 'đặc sắc', 929),
    ('特殊', 'tè shū', 'đặc biệt, đặc thù (quan hệ, nghi lễ, yêu cầu, đãi ngộ)', 930),
    ('特征', 'tè zhēng', 'đặc trưng', 931),
    ('烫', 'tàng', 'bỏng', 932),
    ('淘气', 'táo qì', 'tinh nghịch', 933),
    ('桃', 'táo', 'đào', 934),
    ('提问', 'tí wèn', 'hỏi', 935),
    ('提纲', 'tí gāng', 'đề cương', 936),
    ('提倡', 'tí chàng', 'đề xướng', 937),
    ('推辞', 'tuī cí', 'từ chối', 938),
    ('推荐', 'tuī jiàn', 'tiến cử', 939),
    ('推广', 'tuī guǎng', 'cuộn (danh từ)', 940),
    ('挑战', 'tiǎo zhàn', 'thách thức, thử thách, thách', 941),
    ('投资', 'tóu zī', 'đầu tư', 942),
    ('投入', 'tóu rù', 'đút vào, đầu tư vào,', 943),
    ('套', 'tào', 'bộ (quần áo), căn (nhà)', 944),
    ('太极拳', 'tài jí quán', 'thái cực quyền', 945),
    ('太太', 'tài tai', 'vợ', 946),
    ('天空', 'tiān kōng', 'bầu trời', 947),
    ('天真', 'tiān zhēn', 'hồn nhiên', 948),
    ('坦率', 'tǎn shuài', 'thẳng thắn', 949),
    ('土豆', 'tǔ dòu', 'khoai tây', 950),
    ('土地', 'tǔ dì', 'đất đai', 951),
    ('团', 'tuán', 'cuộn', 952),
    ('吐', 'tǔ/tù', 'nhổ, nôn', 953),
    ('兔子', 'tù zi', 'con thỏ', 954),
    ('偷', 'tōu', 'ăn trộm', 955),
    ('体验', 'tǐ yàn', 'trải nghiệm', 956),
    ('体贴', 'tǐ tiē', 'sống tình cảm, chu đáo', 957),
    ('体现', 'tǐ xiàn', 'thể hiện', 958),
    ('体会', 'tǐ huì', 'cảm nhận', 959),
    ('歪', 'wāi', 'xiên (nghiêng)', 960),
    ('雾', 'wù', 'sương mù', 961),
    ('闻', 'wén', 'ngửi', 962),
    ('问候', 'wèn hòu', 'hỏi thăm', 963),
    ('违反', 'wéi fǎn', 'vi phạm', 964),
    ('胃口', 'wèi kǒu', 'khẩu vị', 965),
    ('胃', 'wèi', 'dạ dày', 966),
    ('网络', 'wǎng luò', 'mạng internet', 967),
    ('维修', 'wéi xiū', 'sửa chữa', 968),
    ('稳定', 'wěn dìng', 'ổn định', 969),
    ('玩具', 'wán jù', 'đồ chơi', 970),
    ('王子', 'wáng zǐ', 'vua', 971),
    ('物质', 'wù zhì', 'vật chất', 972),
    ('物理', 'wù lǐ', 'vật lí', 973),
    ('温柔', 'wēn róu', 'hiền dịu', 974),
    ('温暖', 'wēn nuǎn', 'ấm áp', 975),
    ('武术', 'wǔ shù', 'võ thuật', 976),
    ('未来', 'wèi lái', 'tương lai', 977),
    ('未必', 'wèi bì', 'chưa chắc', 978),
    ('无数', 'wú shù', 'vô số', 979),
    ('无所谓', 'wú suǒ wèi', 'không quan tâm, không để ý', 980),
    ('无奈', 'wú nài', 'bó tay, không có cách nào', 981),
    ('文明', 'wén míng', 'văn minh', 982),
    ('文学', 'wén xué', 'văn học', 983),
    ('文字', 'wén zì', 'văn tự', 984),
    ('文具', 'wén jù', 'đồ dùng học tập', 985),
    ('文件', 'wén jiàn', 'tài liệu', 986),
    ('握手', 'wò shǒu', 'bắt tay', 987),
    ('微笑', 'wēi xiào', 'mỉm cười', 988),
    ('往返', 'wǎng fǎn', 'khứ hồi', 989),
    ('屋子', 'wū zi', 'căn nhà', 990),
    ('尾巴', 'wěi bā', 'cái đuôi', 991),
    ('完美', 'wán měi', 'hoàn hảo', 992),
    ('完整', 'wán zhěng', 'hoàn chỉnh', 993),
    ('完善', 'wán shàn', 'hoàn thiện', 994),
    ('威胁', 'wēi xié', 'uy hiếp', 995),
    ('委屈', 'wěi qu', 'tủi thân', 996),
    ('外公', 'wài gōng', 'ông ngoại', 997),
    ('外交', 'wài jiāo', 'ngoại giao', 998),
    ('围绕', 'wéi rào', 'xoay quanh, bao quanh, quay quanh', 999),
    ('围巾', 'wéi jīn', 'khăn', 1000),
    ('唯一', 'wéi yī', 'duy nhất', 1001),
    ('吻', 'wěn', 'hôn', 1002),
    ('危害', 'wēi hài', 'nguy hại', 1003),
    ('卧室', 'wò shì', 'phòng ngủ', 1004),
    ('勿', 'wù', 'đừng', 1005),
    ('位置', 'wèi zhì', 'vị trí', 1006),
    ('位于', 'wèi yú', 'nằm ở (vị trí địa lý)', 1007),
    ('伟大', 'wěi dà', 'vĩ đại', 1008),
    ('万一', 'wàn yī', 'vạn nhất, nhỡ', 1009),
    ('吸取', 'xī qǔ', 'hút, rút ra (bài học kinh nghiệm)', 1010),
    ('鲜艳', 'xiān yàn', 'tươi tắn', 1011),
    ('香肠', 'xiāng cháng', 'xúc xích', 1012),
    ('项链', 'xiàng liàn', 'dây chuyền', 1013),
    ('项目', 'xiàng mù', 'hạng mục', 1014),
    ('项', 'xiàng', 'hạng, môn (thể thao)', 1015),
    ('限制', 'xiàn zhì', 'hạn chế, giới hạn', 1016),
    ('销售', 'xiāo shòu', 'bán', 1017),
    ('迅速', 'xùn sù', 'nhanh chóng, nhanh', 1018),
    ('象棋', 'xiàng qí', 'cờ tướng', 1019),
    ('象征', 'xiàng zhēng', 'tượng trưng', 1020),
    ('询问', 'xún wèn', 'hỏi han', 1021),
    ('训练', 'xùn liàn', 'huấn luyện', 1022),
    ('行动', 'xíng dòng', 'hành động', 1023),
    ('行人', 'xíng rén', 'người đi đường', 1024),
    ('行为', 'xíng wéi', 'hành vi', 1025),
    ('血', 'xiě', 'máu', 1026),
    ('虚心', 'xū xīn', 'khiêm tốn', 1027),
    ('胸', 'xiōng', 'ngực', 1028),
    ('细节', 'xì jié', 'tình tiết', 1029),
    ('系统', 'xì tǒng', 'hệ thống', 1030),
    ('系', 'xì', 'khoa, hệ', 1031),
    ('瞎', 'xiā', 'mù', 1032),
    ('相当', 'xiāng dāng', 'tương đối', 1033),
    ('相对', 'xiāng duì', 'tương đối', 1034),
    ('相处', 'xiāng chǔ', 'ở cùng nhau, tiếp xúc nhiều', 1035),
    ('相关', 'xiāng guān', 'liên quan', 1036),
    ('相似', 'xiāng sì', 'giống', 1037),
    ('现象', 'xiàn xiàng', 'hiện tượng', 1038),
    ('现实', 'xiàn shí', 'hiện thực', 1039),
    ('现代', 'xiàn dài', 'hiện đại', 1040),
    ('消费', 'xiāo fèi', 'tiêu dùng', 1041),
    ('消极', 'xiāo jí', 'tiêu cực', 1042),
    ('消失', 'xiāo shī', 'biến mất', 1043),
    ('消化', 'xiāo huà', 'tiêu hóa', 1044),
    ('歇', 'xiē', 'nghỉ ngơi', 1045),
    ('欣赏', 'xīn shǎng', 'thưởng thức, đánh giá cao', 1046),
    ('显示', 'xiǎn shì', 'hiển thị, cho thấy, tôn lên', 1047),
    ('显然', 'xiǎn rán', 'hiển nhiên, rõ ràng', 1048),
    ('显得', 'xiǎn dé', 'lộ rõ', 1049),
    ('斜', 'xié', 'nghiêng, chéo', 1050),
    ('效率', 'xiào lǜ', 'hiệu suất', 1051),
    ('戏剧', 'xì jù', 'kịch', 1052),
    ('想象', 'xiǎng xiàng', 'tưởng tượng', 1053),
    ('想念', 'xiǎng niàn', 'nhớ nhung', 1054),
    ('性质', 'xìng zhì', 'tính chất', 1055),
    ('心脏', 'xīn zàng', 'tim', 1056),
    ('心理', 'xīn lǐ', 'tâm lí', 1057),
    ('形象', 'xíng xiàng', 'hình tượng', 1058),
    ('形状', 'xíng zhuàng', 'hình dáng, dáng', 1059),
    ('形成', 'xíng chéng', 'hình thành', 1060),
    ('形式', 'xíng shì', 'hình thức', 1061),
    ('形容', 'xíng róng', 'hình dung', 1062),
    ('形势', 'xíng shì', 'tình hình', 1063),
    ('幸运', 'xìng yùn', 'may mắn', 1064),
    ('幸亏', 'xìng kuī', 'may mà', 1065),
    ('小麦', 'xiǎo mài', 'lúa mạch', 1066),
    ('小气', 'xiǎo qì', 'keo kiệt', 1067),
    ('寻找', 'xún zhǎo', 'tìm kiếm', 1068),
    ('宣布', 'xuān bù', 'tuyên bố', 1069),
    ('宣传', 'xuān chuán', 'tuyên truyền', 1070),
    ('学问', 'xué wèn', 'học vấn', 1071),
    ('学术', 'xué shù', 'học thuật', 1072),
    ('学历', 'xué lì', 'trình độ', 1073),
    ('孝顺', 'xiào shùn', 'hiếu thảo', 1074),
    ('夏令营', 'xià lìng yíng', 'trại', 1075),
    ('吸收', 'xī shōu', 'thẩm thấu, ngấm', 1076),
    ('吓', 'xià', 'dọa', 1077),
    ('叙述', 'xù shù', 'kể, thuật', 1078),
    ('县', 'xiàn', 'huyện', 1079),
    ('写作', 'xiě zuò', 'viết', 1080),
    ('兄弟', 'xiōng dì', 'huynh đệ', 1081),
    ('修改', 'xiū gǎi', 'sửa lỗi (văn bản)', 1082),
    ('信号', 'xìn hào', 'tín hiệu', 1083),
    ('信任', 'xìn rèn', 'tín nhiệm', 1084),
    ('休闲', 'xiū xián', 'nhàn hạ, thoải mái', 1085),
    ('享受', 'xiǎng shòu', 'hưởng thụ', 1086),
    ('下载', 'xià zǎi', 'tải', 1087),
    ('押金', 'yā jīn', 'tiền cọc', 1088),
    ('预防', 'yù fáng', 'phòng, phòng chống', 1089),
    ('预订', 'yù dìng', 'đặt trước, dự định trước', 1090),
    ('预报', 'yù bào', 'dự báo', 1091),
    ('阳台', 'yáng tái', 'ban công', 1092),
    ('银', 'yín', 'bạc', 1093),
    ('遗憾', 'yí hàn', 'hối tiếc', 1094),
    ('运输', 'yùn shū', 'vận tải', 1095),
    ('运用', 'yùn yòng', 'vận dụng', 1096),
    ('运气', 'yùn qì', 'vận may', 1097),
    ('迎接', 'yíng jiē', 'nghênh đón', 1098),
    ('语气', 'yǔ qì', 'ngữ khí', 1099),
    ('议论', 'yì lùn', 'nghị luận', 1100),
    ('要不', 'yào bù', 'nếu không thì', 1101),
    ('营养', 'yíng yǎng', 'dinh dưỡng', 1102),
    ('营业', 'yíng yè', 'kinh doanh', 1103),
    ('英雄', 'yīng xióng', 'anh hùng', 1104),
    ('英俊', 'yīng jùn', 'tuấn tú', 1105),
    ('腰', 'yāo', 'lưng', 1106),
    ('移民', 'yí mín', 'di dân', 1107),
    ('移动', 'yí dòng', 'di động', 1108),
    ('硬件', 'yìng jiàn', 'phần cứng', 1109),
    ('硬', 'yìng', 'cứng', 1110),
    ('痒', 'yǎng', 'ngứa', 1111),
    ('疑问', 'yí wèn', 'nghi vấn, nghi ngờ', 1112),
    ('用途', 'yòng tú', 'cách dùng', 1113),
    ('用功', 'yòng gōng', 'dụng công, công phu', 1114),
    ('玉米', 'yù mǐ', 'ngô', 1115),
    ('犹豫', 'yóu yù', 'do dự', 1116),
    ('牙齿', 'yá chǐ', 'răng', 1117),
    ('演讲', 'yǎn jiǎng', 'diễn thuyết', 1118),
    ('游览', 'yóu lǎn', 'du ngoạn, thưởng ngoạn', 1119),
    ('油炸', 'yóu zhá', 'chiên giòn', 1120),
    ('样式', 'yàng shì', 'kiểu dáng', 1121),
    ('有利', 'yǒu lì', 'có lợi', 1122),
    ('晕', 'yūn', 'say (xe)', 1123),
    ('摇', 'yáo', 'lắc', 1124),
    ('拥挤', 'yōng jǐ', 'chen chúc, đông đúc', 1125),
    ('拥抱', 'yōng bào', 'ôm, ôm ấp', 1126),
    ('愿望', 'yuàn wàng', 'nguyện vọng', 1127),
    ('意外', 'yì wài', 'ngoài ý muốn', 1128),
    ('意义', 'yì yì', 'ý nghĩa', 1129),
    ('悠久', 'yōu jiǔ', 'lâu đời', 1130),
    ('影子', 'yǐng zi', 'cái bóng', 1131),
    ('延长', 'yán cháng', 'kéo dài (thời gian)', 1132),
    ('应用', 'yìng yòng', 'ứng dụng', 1133),
    ('应付', 'yìng fù', 'ứng phó', 1134),
    ('幼儿园', 'yòu ér yuán', 'nhà trẻ', 1135),
    ('宴会', 'yàn huì', 'yến tiệc', 1136),
    ('娱乐', 'yú lè', 'giải trí', 1137),
    ('夜', 'yè', 'đêm', 1138),
    ('圆', 'yuán', 'hình tròn', 1139),
    ('因而', 'yīn ér', 'cho nên', 1140),
    ('因素', 'yīn sù', 'nhân tố', 1141),
    ('咬', 'yǎo', 'cắn', 1142),
    ('员工', 'yuán gōng', 'nhân công', 1143),
    ('原料', 'yuán liào', 'nguyên liệu', 1144),
    ('原则', 'yuán zé', 'nguyên tắc', 1145),
    ('印刷', 'yìn shuā', 'in ấn', 1146),
    ('勇气', 'yǒng qì', 'dũng khí', 1147),
    ('元旦', 'yuán dàn', 'nguyên đán', 1148),
    ('依然', 'yī rán', 'vẫn như xưa', 1149),
    ('优美', 'yōu měi', 'trang nhã, thanh lịch, thanh nhã, đẹp, xinh xắn', 1150),
    ('优惠', 'yōu huì', 'ưu đãi', 1151),
    ('优势', 'yōu shì', 'ưu thế', 1152),
    ('以来', 'yǐ lái', 'trở lại đây (thời gian)', 1153),
    ('以及', 'yǐ jí', 'và', 1154),
    ('亿', 'yì', 'trăm triệu', 1155),
    ('乙', 'yǐ', 'ất', 1156),
    ('乐器', 'yuè qì', 'nhạc cụ', 1157),
    ('义务', 'yì wù', 'nghĩa vụ', 1158),
    ('严肃', 'yán sù', 'nghiêm túc', 1159),
    ('业务', 'yè wù', 'nghiệp vụ', 1160),
    ('业余', 'yè yú', 'nghiệp dư', 1161),
    ('与其', 'yǔ qí', '', 1162),
    ('一辈子', 'yī bèi zi', 'một đời người', 1163),
    ('一致', 'yī zhì', 'thống nhất', 1164),
    ('一旦', 'yī dàn', 'một khi', 1165),
    ('一律', 'yī lǜ', 'nhất loạt', 1166),
    ('一再', 'yī zài', 'nhiều lần', 1167),
    ('灾害', 'zāi hài', 'thiên tai', 1168),
    ('阻止', 'zǔ zhī', 'ngăn chặn, ngăn cản', 1169),
    ('阵', 'zhèn', 'trận (chiến đấu, chiến tranh), khoảng thời gian, mùi hương', 1170),
    ('长辈', 'zhǎng bèi', 'tiền bối', 1171),
    ('针对', 'zhēn duì', 'nhằm (tổ chức, người, vấn đề)', 1172),
    ('重量', 'zhòng liàng', 'trọng lượng', 1173),
    ('重大', 'zhòng dà', 'trọng đại, lớn', 1174),
    ('醉', 'zuì', 'say, say đắm', 1175),
    ('遵守', 'zūn shǒu', 'tuân thủ', 1176),
    ('造成', 'zào chéng', 'gây nên', 1177),
    ('逐渐', 'zhú jiàn', 'dần dần', 1178),
    ('逐步', 'zhú bù', 'từng bước', 1179),
    ('追求', 'zhuī qiú', 'theo đuổi', 1180),
    ('追', 'zhuī', 'đuổi theo', 1181),
    ('转告', 'zhuǎn gào', 'chuyển lời', 1182),
    ('转变', 'zhuǎn biàn', 'chuyển biến', 1183),
    ('赞美', 'zàn měi', 'ca tụng', 1184),
    ('赞成', 'zàn chéng', 'tán thành', 1185),
    ('资金', 'zī jīn', 'vốn (tiền)', 1186),
    ('资源', 'zī yuán', 'nguồn tài nguyên', 1187),
    ('资格', 'zī gé', 'tư cách', 1188),
    ('资料', 'zī liào', 'tư liệu', 1189),
    ('账户', 'zhàng hù', 'tài khoản', 1190),
    ('责备', 'zé bèi', 'trách cứ', 1191),
    ('诊断', 'zhěn duàn', 'chẩn đoán', 1192),
    ('证据', 'zhèng jù', 'chứng cứ', 1193),
    ('证件', 'zhèng jiàn', 'giấy tờ', 1194),
    ('装饰', 'zhuāng shì', 'trang hoàng, trang trí', 1195),
    ('装修', 'zhuāng xiū', 'sửa nội thất', 1196),
    ('装', 'zhuāng', 'đựng, chứa', 1197),
    ('至今', 'zhì jīn', 'đến nay', 1198),
    ('至于', 'zhì yú', 'còn như…..', 1199),
    ('自豪', 'zì háo', 'tự hào, kiêu ngạo', 1200),
    ('自觉', 'zì jué', 'tự giác', 1201),
    ('自私', 'zì sī', 'ích kỉ', 1202),
    ('自由', 'zì yóu', 'tự do', 1203),
    ('自愿', 'zì yuàn', 'tình nguyện, tự nguyện', 1204),
    ('自动', 'zì dòng', 'tự động', 1205),
    ('自从', 'zì cóng', 'từ khi….', 1206),
    ('综合', 'zōng hé', 'tổng hợp', 1207),
    ('组织', 'zǔ zhī', 'tổ chức', 1208),
    ('组成', 'zǔ chéng', 'tổ thành', 1209),
    ('组合', 'zǔ hé', 'tổ hợp, tổ hợp thành, nhóm', 1210),
    ('组', 'zǔ', 'tổ, cụm, nhóm', 1211),
    ('紫', 'zǐ', 'màu tím', 1212),
    ('糟糕', 'zāo gāo', 'tồi tệ', 1213),
    ('粘贴', 'zhān tiē', 'dính, dán', 1214),
    ('竹子', 'zhú zi', 'cây trúc', 1215),
    ('窄', 'zhǎi', 'hẹp', 1216),
    ('秩序', 'zhì xù', 'trật tự', 1217),
    ('种类', 'zhǒng lèi', 'chủng loại', 1218),
    ('祝福', 'zhù fú', 'chúc phúc', 1219),
    ('睁', 'zhēng', 'mở to mắt, trợn mắt', 1220),
    ('着火', 'zháo huǒ', 'bắt lửa, bén lửa', 1221),
    ('着凉', 'zháo liáng', 'nhiễm lạnh', 1222),
    ('真实', 'zhēn shí', 'chân thực', 1223),
    ('直', 'zhí', 'thẳng', 1224),
    ('珍惜', 'zhēn xī', 'trân trọng', 1225),
    ('猪', 'zhū', 'con lợn', 1226),
    ('状态', 'zhuàng tài', 'trạng thái', 1227),
    ('状况', 'zhuàng kuàng', 'tình trạng', 1228),
    ('煮', 'zhǔ', 'luộc, đun', 1229),
    ('照常', 'zhào cháng', 'như thường lệ', 1230),
    ('涨', 'zhàng', 'tăng lên (giá cả, lương)', 1231),
    ('注册', 'zhù cè', 'đăng kí', 1232),
    ('治疗', 'zhì liáo', 'điều trị', 1233),
    ('正', 'zhèng', 'đứng (trái )', 1234),
    ('最初', 'zuì chū', 'ban đầu', 1235),
    ('智慧', 'zhì huì', 'trí tuệ', 1236),
    ('整齐', 'zhěng qí', 'gọn gàng, ngăn nắp', 1237),
    ('整体', 'zhěng tǐ', 'tổng thể', 1238),
    ('整个', 'zhěng gè', 'cả, toàn bộ', 1239),
    ('政治', 'zhèng zhì', 'chính trị', 1240),
    ('政府', 'zhèng fǔ', 'chính phủ', 1241),
    ('支票', 'zhī piào', 'ngân phiếu', 1242),
    ('支', 'zhī', 'chiếc (lượng từ cho bút…)', 1243),
    ('撞', 'zhuàng', 'va vào, đâm vào', 1244),
    ('摘', 'zhāi', 'hái', 1245),
    ('掌握', 'zhǎng wò', 'nắm vững', 1246),
    ('振动', 'zhèn dòng', 'trấn động', 1247),
    ('挣', 'zhèng', 'tranh, giành', 1248),
    ('指挥', 'zhǐ huī', 'chỉ huy', 1249),
    ('指导', 'zhǐ dǎo', 'chỉ đạo', 1250),
    ('招待', 'zhāo dài', 'chiêu đãi', 1251),
    ('抓紧', 'zhuā jǐn', '(tay) nắm chắc, tranh thủ (thời gian)', 1252),
    ('抓', 'zhuā', 'bắt, véo', 1253),
    ('执照', 'zhí zhào', 'giấy phép', 1254),
    ('战争', 'zhàn zhēng', 'chiến tranh', 1255),
    ('总裁', 'zǒng cái', 'giám đốc', 1256),
    ('总统', 'zǒng tǒng', 'tổng thống', 1257),
    ('总算', 'zǒng suàn', 'rốt cuộc', 1258),
    ('总理', 'zǒng lǐ', 'thủ tướng', 1259),
    ('总共', 'zǒng gòng', 'tổng cộng', 1260),
    ('总之', 'zǒng zhī', 'tóm lại', 1261),
    ('志愿者', 'zhì yuàn zhě', 'tình nguyện viên', 1262),
    ('征求', 'zhēng qiú', 'trưng cầu (ý kiến, ý kiến phản hồi), xin (ý kiến lãnh đạo, đồng ý)', 1263),
    ('展览', 'zhǎn lǎn', 'triển lãm', 1264),
    ('展开', 'zhǎn kāi', 'xòe ra, triển khai', 1265),
    ('尊敬', 'zūn jìng', 'tôn kính, kính trọng', 1266),
    ('字母', 'zì mǔ', 'chữ cái', 1267),
    ('字幕', 'zì mù', 'phụ đề', 1268),
    ('姿势', 'zī shì', 'tư thế', 1269),
    ('在于', 'zài yú', 'ở chỗ', 1270),
    ('在乎', 'zài hū', 'để ý', 1271),
    ('哲学', 'zhé xué', 'triết học', 1272),
    ('咨询', 'zī xún', 'tư vấn', 1273),
    ('周到', 'zhōu dào', 'chu đáo', 1274),
    ('召开', 'zhào kāi', 'triệu tập (cuộc họp)', 1275),
    ('占', 'zhàn', 'chiếm', 1276),
    ('制造', 'zhì zào', 'sản xuất', 1277),
    ('制度', 'zhì dù', 'chế độ, chính sách', 1278),
    ('制定', 'zhì dìng', 'lập ra, thiết lập, xây dựng, lập (chính sách, qui định, kế hoạch, sách lược, phương án)', 1279),
    ('制作', 'zhì zuò', 'làm, chế tạo', 1280),
    ('则', 'zé', 'qui tắc, qui phạm', 1281),
    ('再三', 'zài sān', 'hết lần này đến lần khác', 1282),
    ('作文', 'zuò wén', 'bài viết', 1283),
    ('作品', 'zuò pǐn', 'tác phẩm', 1284),
    ('作为', 'zuò wéi', 'coi là, làm, là', 1285),
    ('争论', 'zhēng lùn', 'tranh luận', 1286),
    ('争取', 'zhēng qǔ', 'tranh thủ (ủng hộ, ý kiến)', 1287),
    ('主题', 'zhǔ tí', 'chủ đề', 1288),
    ('主观', 'zhǔ guān', 'chủ quan', 1289),
    ('主持', 'zhǔ chí', 'dẫn (chương trình),', 1290),
    ('主张', 'zhǔ zhāng', 'ý tưởng, ý kiến', 1291),
    ('主席', 'zhǔ xí', 'chủ tịch', 1292),
    ('主动', 'zhǔ dòng', 'chủ động', 1293),
    ('主任', 'zhǔ rèn', 'chủ nhiệm', 1294),
    ('主人', 'zhǔ rén', 'chủ nhân', 1295),
    ('中旬', 'zhōng xún', 'trung tuần', 1296),
    ('中心', 'zhōng xīn', 'trung tâm', 1297),
    ('中介', 'zhōng jiè', 'môi giới, trung gian', 1298),
    ('专心', 'zhuān xīn', 'chuyên tâm', 1299),
    ('专家', 'zhuān jiā', 'chuyên gia', 1300)
) as word(chinese, pinyin, meaning_vi, position)
on conflict (template_deck_id, chinese) do update
set
  pinyin = excluded.pinyin,
  meaning_vi = excluded.meaning_vi,
  position = excluded.position;
