-- Add HSK3 examples without overwriting content edited by users.
-- Uses a single CTE statement so it works in Supabase SQL Editor and migration runners
-- that do not preserve temporary tables across statements.
with hsk3_example_backfill (
  chinese,
  example_cn,
  example_pinyin,
  example_vi
) as (
  values
  ('阿姨', '老师今天教我们“阿姨”这个词。', 'Laoshi jintian jiao women āyí zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "dì, cô, người giúp việc".'),
  ('啊', '老师今天教我们“啊”这个词。', 'Laoshi jintian jiao women a zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "à, ồ, trợ từ cảm thán".'),
  ('矮', '老师今天教我们“矮”这个词。', 'Laoshi jintian jiao women ǎi zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "thấp, lùn".'),
  ('爱好', '老师今天教我们“爱好”这个词。', 'Laoshi jintian jiao women àihào zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "sở thích".'),
  ('安静', '老师今天教我们“安静”这个词。', 'Laoshi jintian jiao women ānjìng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "yên tĩnh".'),
  ('把', '老师今天教我们“把”这个词。', 'Laoshi jintian jiao women bǎ zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "cầm, đem, trợ từ xử lý tân ngữ".'),
  ('搬', '老师今天教我们“搬”这个词。', 'Laoshi jintian jiao women bān zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "chuyển, dọn".'),
  ('班', '老师今天教我们“班”这个词。', 'Laoshi jintian jiao women bān zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "lớp, ca làm".'),
  ('半', '老师今天教我们“半”这个词。', 'Laoshi jintian jiao women bàn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "một nửa, rưỡi".'),
  ('办法', '老师今天教我们“办法”这个词。', 'Laoshi jintian jiao women bànfǎ zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "cách, biện pháp".'),
  ('办公室', '老师今天教我们“办公室”这个词。', 'Laoshi jintian jiao women bàngōngshì zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "văn phòng".'),
  ('帮忙', '老师今天教我们“帮忙”这个词。', 'Laoshi jintian jiao women bāngmáng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "giúp đỡ".'),
  ('包', '老师今天教我们“包”这个词。', 'Laoshi jintian jiao women bāo zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "túi, bao, gói".'),
  ('饱', '老师今天教我们“饱”这个词。', 'Laoshi jintian jiao women bǎo zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "no".'),
  ('北方', '老师今天教我们“北方”这个词。', 'Laoshi jintian jiao women běifāng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "phía bắc".'),
  ('被', '老师今天教我们“被”这个词。', 'Laoshi jintian jiao women bèi zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "bị, được bởi".'),
  ('鼻子', '老师今天教我们“鼻子”这个词。', 'Laoshi jintian jiao women bízi zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "mũi".'),
  ('比较', '老师今天教我们“比较”这个词。', 'Laoshi jintian jiao women bǐjiào zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "khá, tương đối, so sánh".'),
  ('比赛', '老师今天教我们“比赛”这个词。', 'Laoshi jintian jiao women bǐsài zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "cuộc thi, trận đấu".'),
  ('必须', '老师今天教我们“必须”这个词。', 'Laoshi jintian jiao women bìxū zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "phải, bắt buộc".'),
  ('变化', '老师今天教我们“变化”这个词。', 'Laoshi jintian jiao women biànhuà zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "sự thay đổi".'),
  ('表示', '老师今天教我们“表示”这个词。', 'Laoshi jintian jiao women biǎoshì zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "biểu thị, bày tỏ".'),
  ('表演', '老师今天教我们“表演”这个词。', 'Laoshi jintian jiao women biǎoyǎn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "biểu diễn".'),
  ('别人', '老师今天教我们“别人”这个词。', 'Laoshi jintian jiao women biérén zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "người khác".'),
  ('宾馆', '老师今天教我们“宾馆”这个词。', 'Laoshi jintian jiao women bīnguǎn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "khách sạn".'),
  ('冰箱', '老师今天教我们“冰箱”这个词。', 'Laoshi jintian jiao women bīngxiāng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "tủ lạnh".'),
  ('才', '老师今天教我们“才”这个词。', 'Laoshi jintian jiao women cái zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "mới, vừa mới, tài năng".'),
  ('菜单', '老师今天教我们“菜单”这个词。', 'Laoshi jintian jiao women càidān zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "thực đơn".'),
  ('参加', '老师今天教我们“参加”这个词。', 'Laoshi jintian jiao women cānjiā zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "tham gia".'),
  ('草', '老师今天教我们“草”这个词。', 'Laoshi jintian jiao women cǎo zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "cỏ".'),
  ('层', '老师今天教我们“层”这个词。', 'Laoshi jintian jiao women céng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "tầng, lớp".'),
  ('差', '老师今天教我们“差”这个词。', 'Laoshi jintian jiao women chà zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "kém, thiếu, sai lệch".'),
  ('超市', '老师今天教我们“超市”这个词。', 'Laoshi jintian jiao women chāoshì zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "siêu thị".'),
  ('衬衫', '老师今天教我们“衬衫”这个词。', 'Laoshi jintian jiao women chènshān zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "áo sơ mi".'),
  ('成绩', '老师今天教我们“成绩”这个词。', 'Laoshi jintian jiao women chéngjì zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "thành tích, điểm số".'),
  ('城市', '老师今天教我们“城市”这个词。', 'Laoshi jintian jiao women chéngshì zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "thành phố".'),
  ('迟到', '老师今天教我们“迟到”这个词。', 'Laoshi jintian jiao women chídào zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "đến muộn".'),
  ('除了', '老师今天教我们“除了”这个词。', 'Laoshi jintian jiao women chúle zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "ngoài ra, trừ ra".'),
  ('船', '老师今天教我们“船”这个词。', 'Laoshi jintian jiao women chuán zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "thuyền".'),
  ('春', '老师今天教我们“春”这个词。', 'Laoshi jintian jiao women chūn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "mùa xuân".'),
  ('词语', '老师今天教我们“词语”这个词。', 'Laoshi jintian jiao women cíyǔ zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "từ ngữ".'),
  ('聪明', '老师今天教我们“聪明”这个词。', 'Laoshi jintian jiao women cōngming zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "thông minh".'),
  ('打扫', '老师今天教我们“打扫”这个词。', 'Laoshi jintian jiao women dǎsǎo zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "quét dọn".'),
  ('打算', '老师今天教我们“打算”这个词。', 'Laoshi jintian jiao women dǎsuan zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "dự định, tính toán".'),
  ('带', '老师今天教我们“带”这个词。', 'Laoshi jintian jiao women dài zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "mang theo, dẫn theo".'),
  ('担心', '老师今天教我们“担心”这个词。', 'Laoshi jintian jiao women dānxīn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "lo lắng".'),
  ('蛋糕', '老师今天教我们“蛋糕”这个词。', 'Laoshi jintian jiao women dàngāo zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "bánh kem".'),
  ('当然', '老师今天教我们“当然”这个词。', 'Laoshi jintian jiao women dāngrán zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "đương nhiên".'),
  ('地', '老师今天教我们“地”这个词。', 'Laoshi jintian jiao women de zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "trợ từ trạng ngữ".'),
  ('灯', '老师今天教我们“灯”这个词。', 'Laoshi jintian jiao women dēng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "đèn".'),
  ('低', '老师今天教我们“低”这个词。', 'Laoshi jintian jiao women dī zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "thấp".'),
  ('地方', '老师今天教我们“地方”这个词。', 'Laoshi jintian jiao women dìfang zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "nơi, địa phương".'),
  ('地铁', '老师今天教我们“地铁”这个词。', 'Laoshi jintian jiao women dìtiě zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "tàu điện ngầm".'),
  ('地图', '老师今天教我们“地图”这个词。', 'Laoshi jintian jiao women dìtú zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "bản đồ".'),
  ('电梯', '老师今天教我们“电梯”这个词。', 'Laoshi jintian jiao women diàntī zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "thang máy".'),
  ('电子邮件', '老师今天教我们“电子邮件”这个词。', 'Laoshi jintian jiao women diànzǐ yóujiàn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "email, thư điện tử".'),
  ('东', '老师今天教我们“东”这个词。', 'Laoshi jintian jiao women dōng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "phía đông".'),
  ('冬', '老师今天教我们“冬”这个词。', 'Laoshi jintian jiao women dōng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "mùa đông".'),
  ('动物', '老师今天教我们“动物”这个词。', 'Laoshi jintian jiao women dòngwù zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "động vật".'),
  ('短', '老师今天教我们“短”这个词。', 'Laoshi jintian jiao women duǎn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "ngắn".'),
  ('段', '老师今天教我们“段”这个词。', 'Laoshi jintian jiao women duàn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "đoạn, khoảng".'),
  ('锻炼', '老师今天教我们“锻炼”这个词。', 'Laoshi jintian jiao women duànliàn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "rèn luyện, tập thể dục".'),
  ('多么', '老师今天教我们“多么”这个词。', 'Laoshi jintian jiao women duōme zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "biết bao, thật là".'),
  ('饿', '老师今天教我们“饿”这个词。', 'Laoshi jintian jiao women è zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "đói".'),
  ('耳朵', '老师今天教我们“耳朵”这个词。', 'Laoshi jintian jiao women ěrduo zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "tai".'),
  ('发', '老师今天教我们“发”这个词。', 'Laoshi jintian jiao women fā zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "gửi, phát ra".'),
  ('发现', '老师今天教我们“发现”这个词。', 'Laoshi jintian jiao women fāxiàn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "phát hiện".'),
  ('方便', '老师今天教我们“方便”这个词。', 'Laoshi jintian jiao women fāngbiàn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "tiện lợi".'),
  ('放', '老师今天教我们“放”这个词。', 'Laoshi jintian jiao women fàng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "đặt, để, thả".'),
  ('放心', '老师今天教我们“放心”这个词。', 'Laoshi jintian jiao women fàngxīn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "yên tâm".'),
  ('分', '老师今天教我们“分”这个词。', 'Laoshi jintian jiao women fēn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "phút, điểm, chia".'),
  ('附近', '老师今天教我们“附近”这个词。', 'Laoshi jintian jiao women fùjìn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "gần đây, lân cận".'),
  ('复习', '老师今天教我们“复习”这个词。', 'Laoshi jintian jiao women fùxí zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "ôn tập".'),
  ('干净', '老师今天教我们“干净”这个词。', 'Laoshi jintian jiao women gānjìng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "sạch sẽ".'),
  ('感冒', '老师今天教我们“感冒”这个词。', 'Laoshi jintian jiao women gǎnmào zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "cảm cúm".'),
  ('感兴趣', '老师今天教我们“感兴趣”这个词。', 'Laoshi jintian jiao women gǎn xìngqù zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "có hứng thú".'),
  ('刚才', '老师今天教我们“刚才”这个词。', 'Laoshi jintian jiao women gāngcái zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "vừa nãy".'),
  ('个子', '老师今天教我们“个子”这个词。', 'Laoshi jintian jiao women gèzi zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "vóc dáng, chiều cao".'),
  ('根据', '老师今天教我们“根据”这个词。', 'Laoshi jintian jiao women gēnjù zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "dựa theo, căn cứ".'),
  ('跟', '老师今天教我们“跟”这个词。', 'Laoshi jintian jiao women gēn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "với, theo".'),
  ('更', '老师今天教我们“更”这个词。', 'Laoshi jintian jiao women gèng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "hơn, càng".'),
  ('公园', '老师今天教我们“公园”这个词。', 'Laoshi jintian jiao women gōngyuán zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "công viên".'),
  ('故事', '老师今天教我们“故事”这个词。', 'Laoshi jintian jiao women gùshi zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "câu chuyện".'),
  ('刮风', '老师今天教我们“刮风”这个词。', 'Laoshi jintian jiao women guā fēng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "có gió, gió thổi".'),
  ('关', '老师今天教我们“关”这个词。', 'Laoshi jintian jiao women guān zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "đóng, tắt".'),
  ('关系', '老师今天教我们“关系”这个词。', 'Laoshi jintian jiao women guānxi zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "quan hệ, mối quan hệ".'),
  ('关心', '老师今天教我们“关心”这个词。', 'Laoshi jintian jiao women guānxīn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "quan tâm".'),
  ('关于', '老师今天教我们“关于”这个词。', 'Laoshi jintian jiao women guānyú zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "về, liên quan đến".'),
  ('国家', '老师今天教我们“国家”这个词。', 'Laoshi jintian jiao women guójiā zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "quốc gia".'),
  ('果汁', '老师今天教我们“果汁”这个词。', 'Laoshi jintian jiao women guǒzhī zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "nước ép trái cây".'),
  ('过去', '老师今天教我们“过去”这个词。', 'Laoshi jintian jiao women guòqù zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "quá khứ, đi qua".'),
  ('还是', '老师今天教我们“还是”这个词。', 'Laoshi jintian jiao women háishi zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "hay là, vẫn là".'),
  ('害怕', '老师今天教我们“害怕”这个词。', 'Laoshi jintian jiao women hàipà zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "sợ hãi".'),
  ('河', '老师今天教我们“河”这个词。', 'Laoshi jintian jiao women hé zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "sông".'),
  ('黑板', '老师今天教我们“黑板”这个词。', 'Laoshi jintian jiao women hēibǎn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "bảng đen".'),
  ('护照', '老师今天教我们“护照”这个词。', 'Laoshi jintian jiao women hùzhào zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "hộ chiếu".'),
  ('花', '老师今天教我们“花”这个词。', 'Laoshi jintian jiao women huā zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "hoa, tiêu tiền".'),
  ('花园', '老师今天教我们“花园”这个词。', 'Laoshi jintian jiao women huāyuán zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "vườn hoa".'),
  ('画', '老师今天教我们“画”这个词。', 'Laoshi jintian jiao women huà zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "vẽ, tranh".'),
  ('坏', '老师今天教我们“坏”这个词。', 'Laoshi jintian jiao women huài zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "xấu, hỏng".'),
  ('欢迎', '老师今天教我们“欢迎”这个词。', 'Laoshi jintian jiao women huānyíng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "hoan nghênh, chào đón".'),
  ('环境', '老师今天教我们“环境”这个词。', 'Laoshi jintian jiao women huánjìng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "môi trường".'),
  ('换', '老师今天教我们“换”这个词。', 'Laoshi jintian jiao women huàn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "đổi, thay".'),
  ('黄', '老师今天教我们“黄”这个词。', 'Laoshi jintian jiao women huáng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "màu vàng".'),
  ('会议', '老师今天教我们“会议”这个词。', 'Laoshi jintian jiao women huìyì zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "cuộc họp, hội nghị".'),
  ('或者', '老师今天教我们“或者”这个词。', 'Laoshi jintian jiao women huòzhě zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "hoặc, hoặc là".'),
  ('机会', '老师今天教我们“机会”这个词。', 'Laoshi jintian jiao women jīhuì zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "cơ hội".'),
  ('极', '老师今天教我们“极”这个词。', 'Laoshi jintian jiao women jí zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "cực kỳ, rất".'),
  ('记得', '老师今天教我们“记得”这个词。', 'Laoshi jintian jiao women jìde zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "nhớ, nhớ rằng".'),
  ('季节', '老师今天教我们“季节”这个词。', 'Laoshi jintian jiao women jìjié zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "mùa".'),
  ('检查', '老师今天教我们“检查”这个词。', 'Laoshi jintian jiao women jiǎnchá zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "kiểm tra".'),
  ('简单', '老师今天教我们“简单”这个词。', 'Laoshi jintian jiao women jiǎndān zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "đơn giản".'),
  ('见面', '老师今天教我们“见面”这个词。', 'Laoshi jintian jiao women jiànmiàn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "gặp mặt".'),
  ('健康', '老师今天教我们“健康”这个词。', 'Laoshi jintian jiao women jiànkāng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "khỏe mạnh, sức khỏe".'),
  ('讲', '老师今天教我们“讲”这个词。', 'Laoshi jintian jiao women jiǎng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "giảng, nói".'),
  ('脚', '老师今天教我们“脚”这个词。', 'Laoshi jintian jiao women jiǎo zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "bàn chân".'),
  ('角', '老师今天教我们“角”这个词。', 'Laoshi jintian jiao women jiǎo zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "góc, hào".'),
  ('接', '老师今天教我们“接”这个词。', 'Laoshi jintian jiao women jiē zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "đón, nhận, nối".'),
  ('街道', '老师今天教我们“街道”这个词。', 'Laoshi jintian jiao women jiēdào zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "đường phố".'),
  ('结婚', '老师今天教我们“结婚”这个词。', 'Laoshi jintian jiao women jiéhūn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "kết hôn".'),
  ('结束', '老师今天教我们“结束”这个词。', 'Laoshi jintian jiao women jiéshù zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "kết thúc".'),
  ('节目', '老师今天教我们“节目”这个词。', 'Laoshi jintian jiao women jiémù zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "chương trình".'),
  ('节日', '老师今天教我们“节日”这个词。', 'Laoshi jintian jiao women jiérì zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "ngày lễ".'),
  ('解决', '老师今天教我们“解决”这个词。', 'Laoshi jintian jiao women jiějué zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "giải quyết".'),
  ('借', '老师今天教我们“借”这个词。', 'Laoshi jintian jiao women jiè zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "mượn, cho mượn".'),
  ('经常', '老师今天教我们“经常”这个词。', 'Laoshi jintian jiao women jīngcháng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "thường xuyên".'),
  ('经过', '老师今天教我们“经过”这个词。', 'Laoshi jintian jiao women jīngguò zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "đi qua, trải qua".'),
  ('经理', '老师今天教我们“经理”这个词。', 'Laoshi jintian jiao women jīnglǐ zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "giám đốc, quản lý".'),
  ('久', '老师今天教我们“久”这个词。', 'Laoshi jintian jiao women jiǔ zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "lâu".'),
  ('旧', '老师今天教我们“旧”这个词。', 'Laoshi jintian jiao women jiù zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "cũ".'),
  ('句子', '老师今天教我们“句子”这个词。', 'Laoshi jintian jiao women jùzi zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "câu văn".'),
  ('决定', '老师今天教我们“决定”这个词。', 'Laoshi jintian jiao women juédìng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "quyết định".'),
  ('可爱', '老师今天教我们“可爱”这个词。', 'Laoshi jintian jiao women kěài zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "đáng yêu".'),
  ('渴', '老师今天教我们“渴”这个词。', 'Laoshi jintian jiao women kě zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "khát".'),
  ('刻', '老师今天教我们“刻”这个词。', 'Laoshi jintian jiao women kè zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "mười lăm phút, khắc".'),
  ('客人', '老师今天教我们“客人”这个词。', 'Laoshi jintian jiao women kèrén zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "khách".'),
  ('空调', '老师今天教我们“空调”这个词。', 'Laoshi jintian jiao women kōngtiáo zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "máy điều hòa".'),
  ('口', '老师今天教我们“口”这个词。', 'Laoshi jintian jiao women kǒu zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "miệng, khẩu".'),
  ('哭', '老师今天教我们“哭”这个词。', 'Laoshi jintian jiao women kū zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "khóc".'),
  ('裤子', '老师今天教我们“裤子”这个词。', 'Laoshi jintian jiao women kùzi zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "quần".'),
  ('筷子', '老师今天教我们“筷子”这个词。', 'Laoshi jintian jiao women kuàizi zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "đũa".'),
  ('蓝', '老师今天教我们“蓝”这个词。', 'Laoshi jintian jiao women lán zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "màu xanh lam".'),
  ('老', '老师今天教我们“老”这个词。', 'Laoshi jintian jiao women lǎo zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "già, cũ".'),
  ('离开', '老师今天教我们“离开”这个词。', 'Laoshi jintian jiao women líkāi zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "rời khỏi".'),
  ('礼物', '老师今天教我们“礼物”这个词。', 'Laoshi jintian jiao women lǐwù zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "quà tặng".'),
  ('历史', '老师今天教我们“历史”这个词。', 'Laoshi jintian jiao women lìshǐ zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "lịch sử".'),
  ('脸', '老师今天教我们“脸”这个词。', 'Laoshi jintian jiao women liǎn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "mặt".'),
  ('练习', '老师今天教我们“练习”这个词。', 'Laoshi jintian jiao women liànxí zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "luyện tập".'),
  ('辆', '老师今天教我们“辆”这个词。', 'Laoshi jintian jiao women liàng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "lượng từ cho xe".'),
  ('了解', '老师今天教我们“了解”这个词。', 'Laoshi jintian jiao women liǎojiě zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "hiểu, tìm hiểu".'),
  ('邻居', '老师今天教我们“邻居”这个词。', 'Laoshi jintian jiao women línjū zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "hàng xóm".'),
  ('楼', '老师今天教我们“楼”这个词。', 'Laoshi jintian jiao women lóu zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "tòa nhà, lầu".'),
  ('绿', '老师今天教我们“绿”这个词。', 'Laoshi jintian jiao women lǜ zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "màu xanh lá".'),
  ('马', '老师今天教我们“马”这个词。', 'Laoshi jintian jiao women mǎ zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "con ngựa".'),
  ('马上', '老师今天教我们“马上”这个词。', 'Laoshi jintian jiao women mǎshàng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "ngay lập tức".'),
  ('满意', '老师今天教我们“满意”这个词。', 'Laoshi jintian jiao women mǎnyì zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "hài lòng".'),
  ('帽子', '老师今天教我们“帽子”这个词。', 'Laoshi jintian jiao women màozi zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "mũ".'),
  ('米', '老师今天教我们“米”这个词。', 'Laoshi jintian jiao women mǐ zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "gạo, mét".'),
  ('面包', '老师今天教我们“面包”这个词。', 'Laoshi jintian jiao women miànbāo zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "bánh mì".'),
  ('明白', '老师今天教我们“明白”这个词。', 'Laoshi jintian jiao women míngbai zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "hiểu, rõ".'),
  ('拿', '老师今天教我们“拿”这个词。', 'Laoshi jintian jiao women ná zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "cầm, lấy".'),
  ('奶奶', '老师今天教我们“奶奶”这个词。', 'Laoshi jintian jiao women nǎinai zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "bà nội".'),
  ('南', '老师今天教我们“南”这个词。', 'Laoshi jintian jiao women nán zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "phía nam".'),
  ('难', '老师今天教我们“难”这个词。', 'Laoshi jintian jiao women nán zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "khó".'),
  ('难过', '老师今天教我们“难过”这个词。', 'Laoshi jintian jiao women nánguò zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "buồn, khó chịu".'),
  ('年级', '老师今天教我们“年级”这个词。', 'Laoshi jintian jiao women niánjí zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "khối lớp, niên cấp".'),
  ('年轻', '老师今天教我们“年轻”这个词。', 'Laoshi jintian jiao women niánqīng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "trẻ".'),
  ('鸟', '老师今天教我们“鸟”这个词。', 'Laoshi jintian jiao women niǎo zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "chim".'),
  ('努力', '老师今天教我们“努力”这个词。', 'Laoshi jintian jiao women nǔlì zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "cố gắng".'),
  ('爬山', '老师今天教我们“爬山”这个词。', 'Laoshi jintian jiao women pá shān zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "leo núi".'),
  ('盘子', '老师今天教我们“盘子”这个词。', 'Laoshi jintian jiao women pánzi zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "cái đĩa".'),
  ('胖', '老师今天教我们“胖”这个词。', 'Laoshi jintian jiao women pàng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "béo, mập".'),
  ('啤酒', '老师今天教我们“啤酒”这个词。', 'Laoshi jintian jiao women píjiǔ zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "bia".'),
  ('皮鞋', '老师今天教我们“皮鞋”这个词。', 'Laoshi jintian jiao women píxié zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "giày da".'),
  ('瓶子', '老师今天教我们“瓶子”这个词。', 'Laoshi jintian jiao women píngzi zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "cái chai".'),
  ('其实', '老师今天教我们“其实”这个词。', 'Laoshi jintian jiao women qíshí zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "thật ra".'),
  ('其他', '老师今天教我们“其他”这个词。', 'Laoshi jintian jiao women qítā zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "khác, những cái khác".'),
  ('奇怪', '老师今天教我们“奇怪”这个词。', 'Laoshi jintian jiao women qíguài zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "kỳ lạ".'),
  ('骑', '老师今天教我们“骑”这个词。', 'Laoshi jintian jiao women qí zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "cưỡi, đi xe".'),
  ('起飞', '老师今天教我们“起飞”这个词。', 'Laoshi jintian jiao women qǐfēi zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "cất cánh".'),
  ('清楚', '老师今天教我们“清楚”这个词。', 'Laoshi jintian jiao women qīngchu zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "rõ ràng".'),
  ('秋', '老师今天教我们“秋”这个词。', 'Laoshi jintian jiao women qiū zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "mùa thu".'),
  ('裙子', '老师今天教我们“裙子”这个词。', 'Laoshi jintian jiao women qúnzi zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "váy".'),
  ('然后', '老师今天教我们“然后”这个词。', 'Laoshi jintian jiao women ránhòu zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "sau đó".'),
  ('认为', '老师今天教我们“认为”这个词。', 'Laoshi jintian jiao women rènwéi zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "cho rằng, nghĩ rằng".'),
  ('认真', '老师今天教我们“认真”这个词。', 'Laoshi jintian jiao women rènzhēn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "nghiêm túc".'),
  ('容易', '老师今天教我们“容易”这个词。', 'Laoshi jintian jiao women róngyì zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "dễ dàng".'),
  ('如果', '老师今天教我们“如果”这个词。', 'Laoshi jintian jiao women rúguǒ zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "nếu".'),
  ('伞', '老师今天教我们“伞”这个词。', 'Laoshi jintian jiao women sǎn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "ô, dù".'),
  ('上网', '老师今天教我们“上网”这个词。', 'Laoshi jintian jiao women shàng wǎng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "lên mạng".'),
  ('生气', '老师今天教我们“生气”这个词。', 'Laoshi jintian jiao women shēngqì zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "tức giận".'),
  ('声音', '老师今天教我们“声音”这个词。', 'Laoshi jintian jiao women shēngyīn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "âm thanh, giọng nói".'),
  ('使', '老师今天教我们“使”这个词。', 'Laoshi jintian jiao women shǐ zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "khiến, làm cho".'),
  ('世界', '老师今天教我们“世界”这个词。', 'Laoshi jintian jiao women shìjiè zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "thế giới".'),
  ('试', '老师今天教我们“试”这个词。', 'Laoshi jintian jiao women shì zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "thử".'),
  ('瘦', '老师今天教我们“瘦”这个词。', 'Laoshi jintian jiao women shòu zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "gầy".'),
  ('舒服', '老师今天教我们“舒服”这个词。', 'Laoshi jintian jiao women shūfu zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "thoải mái".'),
  ('树', '老师今天教我们“树”这个词。', 'Laoshi jintian jiao women shù zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "cây".'),
  ('数学', '老师今天教我们“数学”这个词。', 'Laoshi jintian jiao women shùxué zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "toán học".'),
  ('刷牙', '老师今天教我们“刷牙”这个词。', 'Laoshi jintian jiao women shuā yá zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "đánh răng".'),
  ('双', '老师今天教我们“双”这个词。', 'Laoshi jintian jiao women shuāng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "đôi, cặp".'),
  ('水平', '老师今天教我们“水平”这个词。', 'Laoshi jintian jiao women shuǐpíng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "trình độ, mức độ".'),
  ('司机', '老师今天教我们“司机”这个词。', 'Laoshi jintian jiao women sījī zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "tài xế".'),
  ('太阳', '老师今天教我们“太阳”这个词。', 'Laoshi jintian jiao women tàiyáng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "mặt trời".'),
  ('特别', '老师今天教我们“特别”这个词。', 'Laoshi jintian jiao women tèbié zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "đặc biệt".'),
  ('疼', '老师今天教我们“疼”这个词。', 'Laoshi jintian jiao women téng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "đau".'),
  ('提高', '老师今天教我们“提高”这个词。', 'Laoshi jintian jiao women tígāo zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "nâng cao".'),
  ('体育', '老师今天教我们“体育”这个词。', 'Laoshi jintian jiao women tǐyù zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "thể dục, thể thao".'),
  ('甜', '老师今天教我们“甜”这个词。', 'Laoshi jintian jiao women tián zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "ngọt".'),
  ('条', '老师今天教我们“条”这个词。', 'Laoshi jintian jiao women tiáo zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "lượng từ cho vật dài".'),
  ('同事', '老师今天教我们“同事”这个词。', 'Laoshi jintian jiao women tóngshì zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "đồng nghiệp".'),
  ('同意', '老师今天教我们“同意”这个词。', 'Laoshi jintian jiao women tóngyì zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "đồng ý".'),
  ('头发', '老师今天教我们“头发”这个词。', 'Laoshi jintian jiao women tóufa zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "tóc".'),
  ('突然', '老师今天教我们“突然”这个词。', 'Laoshi jintian jiao women tūrán zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "đột nhiên".'),
  ('图书馆', '老师今天教我们“图书馆”这个词。', 'Laoshi jintian jiao women túshūguǎn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "thư viện".'),
  ('腿', '老师今天教我们“腿”这个词。', 'Laoshi jintian jiao women tuǐ zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "chân".'),
  ('完成', '老师今天教我们“完成”这个词。', 'Laoshi jintian jiao women wánchéng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "hoàn thành".'),
  ('碗', '老师今天教我们“碗”这个词。', 'Laoshi jintian jiao women wǎn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "cái bát".'),
  ('万', '老师今天教我们“万”这个词。', 'Laoshi jintian jiao women wàn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "mười nghìn".'),
  ('忘记', '老师今天教我们“忘记”这个词。', 'Laoshi jintian jiao women wàngjì zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "quên".'),
  ('为', '老师今天教我们“为”这个词。', 'Laoshi jintian jiao women wèi zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "vì, cho".'),
  ('为了', '老师今天教我们“为了”这个词。', 'Laoshi jintian jiao women wèile zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "để, vì mục đích".'),
  ('位', '老师今天教我们“位”这个词。', 'Laoshi jintian jiao women wèi zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "vị, lượng từ lịch sự cho người".'),
  ('文化', '老师今天教我们“文化”这个词。', 'Laoshi jintian jiao women wénhuà zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "văn hóa".'),
  ('西', '老师今天教我们“西”这个词。', 'Laoshi jintian jiao women xī zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "phía tây".'),
  ('习惯', '老师今天教我们“习惯”这个词。', 'Laoshi jintian jiao women xíguàn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "thói quen, quen với".'),
  ('洗手间', '老师今天教我们“洗手间”这个词。', 'Laoshi jintian jiao women xǐshǒujiān zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "nhà vệ sinh".'),
  ('洗澡', '老师今天教我们“洗澡”这个词。', 'Laoshi jintian jiao women xǐ zǎo zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "tắm".'),
  ('夏', '老师今天教我们“夏”这个词。', 'Laoshi jintian jiao women xià zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "mùa hè".'),
  ('先', '老师今天教我们“先”这个词。', 'Laoshi jintian jiao women xiān zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "trước, trước tiên".'),
  ('香蕉', '老师今天教我们“香蕉”这个词。', 'Laoshi jintian jiao women xiāngjiāo zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "chuối".'),
  ('相同', '老师今天教我们“相同”这个词。', 'Laoshi jintian jiao women xiāngtóng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "giống nhau".'),
  ('相信', '老师今天教我们“相信”这个词。', 'Laoshi jintian jiao women xiāngxìn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "tin tưởng".'),
  ('像', '老师今天教我们“像”这个词。', 'Laoshi jintian jiao women xiàng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "giống như, hình ảnh".'),
  ('小心', '老师今天教我们“小心”这个词。', 'Laoshi jintian jiao women xiǎoxīn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "cẩn thận".'),
  ('校长', '老师今天教我们“校长”这个词。', 'Laoshi jintian jiao women xiàozhǎng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "hiệu trưởng".'),
  ('新闻', '老师今天教我们“新闻”这个词。', 'Laoshi jintian jiao women xīnwén zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "tin tức".'),
  ('新鲜', '老师今天教我们“新鲜”这个词。', 'Laoshi jintian jiao women xīnxiān zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "tươi mới".'),
  ('信', '老师今天教我们“信”这个词。', 'Laoshi jintian jiao women xìn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "thư, tin".'),
  ('行李箱', '老师今天教我们“行李箱”这个词。', 'Laoshi jintian jiao women xínglixiāng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "vali".'),
  ('兴趣', '老师今天教我们“兴趣”这个词。', 'Laoshi jintian jiao women xìngqù zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "hứng thú, sở thích".'),
  ('熊猫', '老师今天教我们“熊猫”这个词。', 'Laoshi jintian jiao women xióngmāo zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "gấu trúc".'),
  ('需要', '老师今天教我们“需要”这个词。', 'Laoshi jintian jiao women xūyào zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "cần, cần thiết".'),
  ('选择', '老师今天教我们“选择”这个词。', 'Laoshi jintian jiao women xuǎnzé zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "lựa chọn".'),
  ('要求', '老师今天教我们“要求”这个词。', 'Laoshi jintian jiao women yāoqiú zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "yêu cầu".'),
  ('爷爷', '老师今天教我们“爷爷”这个词。', 'Laoshi jintian jiao women yéye zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "ông nội".'),
  ('一般', '老师今天教我们“一般”这个词。', 'Laoshi jintian jiao women yìbān zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "bình thường, thông thường".'),
  ('一边', '老师今天教我们“一边”这个词。', 'Laoshi jintian jiao women yìbiān zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "một bên, vừa... vừa...".'),
  ('一定', '老师今天教我们“一定”这个词。', 'Laoshi jintian jiao women yídìng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "nhất định".'),
  ('一共', '老师今天教我们“一共”这个词。', 'Laoshi jintian jiao women yígòng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "tổng cộng".'),
  ('一会儿', '老师今天教我们“一会儿”这个词。', 'Laoshi jintian jiao women yíhuìr zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "một lát".'),
  ('一样', '老师今天教我们“一样”这个词。', 'Laoshi jintian jiao women yíyàng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "giống nhau".'),
  ('以后', '老师今天教我们“以后”这个词。', 'Laoshi jintian jiao women yǐhòu zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "sau này, về sau".'),
  ('以前', '老师今天教我们“以前”这个词。', 'Laoshi jintian jiao women yǐqián zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "trước đây".'),
  ('以为', '老师今天教我们“以为”这个词。', 'Laoshi jintian jiao women yǐwéi zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "tưởng rằng".'),
  ('银行', '老师今天教我们“银行”这个词。', 'Laoshi jintian jiao women yínháng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "ngân hàng".'),
  ('音乐', '老师今天教我们“音乐”这个词。', 'Laoshi jintian jiao women yīnyuè zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "âm nhạc".'),
  ('应该', '老师今天教我们“应该”这个词。', 'Laoshi jintian jiao women yīnggāi zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "nên, phải".'),
  ('影响', '老师今天教我们“影响”这个词。', 'Laoshi jintian jiao women yǐngxiǎng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "ảnh hưởng".'),
  ('用', '老师今天教我们“用”这个词。', 'Laoshi jintian jiao women yòng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "dùng, sử dụng".'),
  ('游戏', '老师今天教我们“游戏”这个词。', 'Laoshi jintian jiao women yóuxì zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "trò chơi".'),
  ('有名', '老师今天教我们“有名”这个词。', 'Laoshi jintian jiao women yǒumíng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "nổi tiếng".'),
  ('又', '老师今天教我们“又”这个词。', 'Laoshi jintian jiao women yòu zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "lại, vừa... vừa...".'),
  ('遇到', '老师今天教我们“遇到”这个词。', 'Laoshi jintian jiao women yùdào zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "gặp phải, gặp được".'),
  ('元', '老师今天教我们“元”这个词。', 'Laoshi jintian jiao women yuán zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "đồng, nhân dân tệ".'),
  ('愿意', '老师今天教我们“愿意”这个词。', 'Laoshi jintian jiao women yuànyì zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "sẵn lòng, bằng lòng".'),
  ('越', '老师今天教我们“越”这个词。', 'Laoshi jintian jiao women yuè zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "càng".'),
  ('月亮', '老师今天教我们“月亮”这个词。', 'Laoshi jintian jiao women yuèliang zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "mặt trăng".'),
  ('云', '老师今天教我们“云”这个词。', 'Laoshi jintian jiao women yún zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "mây".'),
  ('站', '老师今天教我们“站”这个词。', 'Laoshi jintian jiao women zhàn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "trạm, đứng".'),
  ('长', '老师今天教我们“长”这个词。', 'Laoshi jintian jiao women zhǎng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "lớn lên, trưởng thành".'),
  ('着急', '老师今天教我们“着急”这个词。', 'Laoshi jintian jiao women zháojí zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "lo lắng, sốt ruột".'),
  ('照顾', '老师今天教我们“照顾”这个词。', 'Laoshi jintian jiao women zhàogu zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "chăm sóc".'),
  ('照片', '老师今天教我们“照片”这个词。', 'Laoshi jintian jiao women zhàopiàn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "bức ảnh".'),
  ('照相机', '老师今天教我们“照相机”这个词。', 'Laoshi jintian jiao women zhàoxiàngjī zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "máy ảnh".'),
  ('只', '老师今天教我们“只”这个词。', 'Laoshi jintian jiao women zhǐ zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "chỉ, chỉ có".'),
  ('只好', '老师今天教我们“只好”这个词。', 'Laoshi jintian jiao women zhǐhǎo zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "đành phải".'),
  ('只有', '老师今天教我们“只有”这个词。', 'Laoshi jintian jiao women zhǐyǒu zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "chỉ có".'),
  ('种', '老师今天教我们“种”这个词。', 'Laoshi jintian jiao women zhǒng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "loại, chủng loại".'),
  ('重要', '老师今天教我们“重要”这个词。', 'Laoshi jintian jiao women zhòngyào zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "quan trọng".'),
  ('周末', '老师今天教我们“周末”这个词。', 'Laoshi jintian jiao women zhōumò zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "cuối tuần".'),
  ('主要', '老师今天教我们“主要”这个词。', 'Laoshi jintian jiao women zhǔyào zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "chủ yếu".'),
  ('注意', '老师今天教我们“注意”这个词。', 'Laoshi jintian jiao women zhùyì zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "chú ý".'),
  ('自己', '老师今天教我们“自己”这个词。', 'Laoshi jintian jiao women zìjǐ zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "bản thân, tự mình".'),
  ('自行车', '老师今天教我们“自行车”这个词。', 'Laoshi jintian jiao women zìxíngchē zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "xe đạp".'),
  ('总是', '老师今天教我们“总是”这个词。', 'Laoshi jintian jiao women zǒngshì zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "luôn luôn".'),
  ('嘴', '老师今天教我们“嘴”这个词。', 'Laoshi jintian jiao women zuǐ zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "miệng".'),
  ('最后', '老师今天教我们“最后”这个词。', 'Laoshi jintian jiao women zuìhòu zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "cuối cùng".'),
  ('最近', '老师今天教我们“最近”这个词。', 'Laoshi jintian jiao women zuìjìn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "gần đây".'),
  ('作业', '老师今天教我们“作业”这个词。', 'Laoshi jintian jiao women zuòyè zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "bài tập".'),
  ('作用', '老师今天教我们“作用”这个词。', 'Laoshi jintian jiao women zuòyòng zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "tác dụng, vai trò".'),
  ('笔记本', '老师今天教我们“笔记本”这个词。', 'Laoshi jintian jiao women bǐjìběn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "sổ tay, vở ghi chép".'),
  ('不但', '老师今天教我们“不但”这个词。', 'Laoshi jintian jiao women búdàn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "không những".'),
  ('而且', '老师今天教我们“而且”这个词。', 'Laoshi jintian jiao women érqiě zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "hơn nữa, mà còn".'),
  ('词典', '老师今天教我们“词典”这个词。', 'Laoshi jintian jiao women cídiǎn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "từ điển".'),
  ('发烧', '老师今天教我们“发烧”这个词。', 'Laoshi jintian jiao women fāshāo zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "bị sốt".'),
  ('公斤', '老师今天教我们“公斤”这个词。', 'Laoshi jintian jiao women gōngjīn zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "ki-lô-gam".'),
  ('后来', '老师今天教我们“后来”这个词。', 'Laoshi jintian jiao women hòulái zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "sau đó, về sau".'),
  ('回答', '老师今天教我们“回答”这个词。', 'Laoshi jintian jiao women huídá zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "trả lời".'),
  ('几乎', '老师今天教我们“几乎”这个词。', 'Laoshi jintian jiao women jīhū zhe ge ci.', 'Hôm nay giáo viên dạy chúng tôi từ "gần như, hầu như".')
),
updated_template_cards as (
  update public.template_cards as card
  set
    example_cn = coalesce(nullif(btrim(card.example_cn), ''), example.example_cn),
    example_pinyin = coalesce(nullif(btrim(card.example_pinyin), ''), example.example_pinyin),
    example_vi = coalesce(nullif(btrim(card.example_vi), ''), example.example_vi)
  from public.template_decks as deck,
    hsk3_example_backfill as example
  where card.template_deck_id = deck.id
    and deck.slug = 'hsk3-co-ban'
    and card.chinese = example.chinese
    and (
      nullif(btrim(card.example_cn), '') is null
      or nullif(btrim(card.example_pinyin), '') is null
      or nullif(btrim(card.example_vi), '') is null
    )
  returning card.id
)
update public.cards as card
set
  example_cn = coalesce(nullif(btrim(card.example_cn), ''), example.example_cn),
  example_pinyin = coalesce(nullif(btrim(card.example_pinyin), ''), example.example_pinyin),
  example_vi = coalesce(nullif(btrim(card.example_vi), ''), example.example_vi)
from public.decks as deck,
  hsk3_example_backfill as example
where card.deck_id = deck.id
  and card.user_id = deck.user_id
  and (
    deck.source_template_slug = 'hsk3-co-ban'
    or (deck.source_template_slug is null and deck.name = 'HSK3 cơ bản')
  )
  and card.chinese = example.chinese
  and (
    nullif(btrim(card.example_cn), '') is null
    or nullif(btrim(card.example_pinyin), '') is null
    or nullif(btrim(card.example_vi), '') is null
  );
