-- Add HSK4 examples without overwriting content edited by users.
-- Uses a single CTE statement so it works in Supabase SQL Editor and migration runners
-- that do not preserve temporary tables across statements.
with hsk4_example_backfill (
  chinese,
  example_cn,
  example_pinyin,
  example_vi
) as (
  values
  ('爱情', '很多电影都是爱情故事。', 'Hen duo dianying dou shi aiqing gushi.', 'Việc này liên quan đến tình yêu.'),
  ('按照', '请按照要求完成作业。', 'Qing anzhao yaoqiu wancheng zuoye.', 'Việc này liên quan đến dựa vào, theo.'),
  ('按时', '他每天按时上班。', 'Ta meitian anshi shangban.', 'Việc này liên quan đến đúng hạn.'),
  ('安排', '我来安排明天的会议。', 'Wo lai anpai mingtian de huiyi.', 'Việc này liên quan đến sắp xếp.'),
  ('安全', '晚上一个人回家要注意安全。', 'Wanshang yi ge ren huijia yao zhuyi anquan.', 'Việc này liên quan đến an toàn.'),
  ('百分之', '任务完成百分之八十了。', 'Renwu wancheng baifenzhi bashi le.', 'Nhiệm vụ đã hoàn thành tám mươi phần trăm.'),
  ('饼干', '孩子们喜欢吃饼干。', 'Haizimen xihuan chi binggan.', 'Việc này liên quan đến bánh.'),
  ('部分', '只有一部分学生参加了活动。', 'Zhiyou yi bufen xuesheng canjia le huodong.', 'Việc này liên quan đến bộ phận, phần.'),
  ('遍', '这本书我看了一遍。', 'Zhe ben shu wo kan le yi bian.', 'Việc này liên quan đến lần, lượt.'),
  ('表示', '他点头表示同意。', 'Ta diantou biaoshi tongyi.', 'Việc này liên quan đến biểu thị, cho thấy.'),
  ('表演', '孩子们在舞台上表演。', 'Haizimen zai wutai shang biaoyan.', 'Việc này liên quan đến biểu diễn.'),
  ('表格', '这件事和表格有关。', 'Zhe jian shi he biǎo gé youguan.', 'Việc này liên quan đến bảng biểu.'),
  ('表扬', '这件事和表扬有关。', 'Zhe jian shi he biǎo yáng youguan.', 'Việc này liên quan đến tuyên dương.'),
  ('笨', '这件事和笨有关。', 'Zhe jian shi he bèn youguan.', 'Việc này liên quan đến ngốc nghếch.'),
  ('毕业', '这件事和毕业有关。', 'Zhe jian shi he bì yè youguan.', 'Việc này liên quan đến tốt nghiệp.'),
  ('比如', '这件事和比如有关。', 'Zhe jian shi he bǐ rú youguan.', 'Việc này liên quan đến ví dụ như.'),
  ('棒', '这件事和棒有关。', 'Zhe jian shi he bàng youguan.', 'Việc này liên quan đến cây gậy.'),
  ('标准', '这件事和标准有关。', 'Zhe jian shi he biāo zhǔn youguan.', 'Việc này liên quan đến tiêu chuẩn.'),
  ('本来', '这件事和本来有关。', 'Zhe jian shi he běn lái youguan.', 'Việc này liên quan đến vốn có.'),
  ('抱歉', '这件事和抱歉有关。', 'Zhe jian shi he bào qiàn youguan.', 'Việc này liên quan đến xin lỗi.'),
  ('抱', '这件事和抱有关。', 'Zhe jian shi he bào youguan.', 'Việc này liên quan đến ôm.'),
  ('报名', '这件事和报名有关。', 'Zhe jian shi he bào míng youguan.', 'Việc này liên quan đến đăng kí.'),
  ('并且', '这件事和并且有关。', 'Zhe jian shi he bìng qiě youguan.', 'Việc này liên quan đến đồng thời.'),
  ('博士', '这件事和博士有关。', 'Zhe jian shi he bó shì youguan.', 'Việc này liên quan đến tiến sĩ.'),
  ('包子', '这件事和包子有关。', 'Zhe jian shi he bāo zi youguan.', 'Việc này liên quan đến bánh bao.'),
  ('倍', '这件事和倍有关。', 'Zhe jian shi he bèi youguan.', 'Việc này liên quan đến lần.'),
  ('保证', '这件事和保证有关。', 'Zhe jian shi he bǎo zhèng youguan.', 'Việc này liên quan đến đảm bảo, cam đoan.'),
  ('保护', '这件事和保护有关。', 'Zhe jian shi he bǎo hù youguan.', 'Việc này liên quan đến che chở, bảo vệ.'),
  ('不过', '这件事和不过有关。', 'Zhe jian shi he bù guò youguan.', 'Việc này liên quan đến nhưng.'),
  ('不管', '这件事和不管有关。', 'Zhe jian shi he bù guǎn youguan.', 'Việc này liên quan đến bất kể.'),
  ('不得不', '这件事和不得不有关。', 'Zhe jian shi he bù dé bù youguan.', 'Việc này liên quan đến đành.'),
  ('不仅', '这件事和不仅有关。', 'Zhe jian shi he bù jǐn youguan.', 'Việc này liên quan đến không những.'),
  ('擦', '这件事和擦有关。', 'Zhe jian shi he cā youguan.', 'Việc này liên quan đến lau.'),
  ('餐厅', '这件事和餐厅有关。', 'Zhe jian shi he cān tīng youguan.', 'Việc này liên quan đến căng tin, nhà ăn.'),
  ('长江', '这件事和长江有关。', 'Zhe jian shi he cháng jiāng youguan.', 'Việc này liên quan đến Trường Giang.'),
  ('长城', '这件事和长城有关。', 'Zhe jian shi he cháng chéng youguan.', 'Việc này liên quan đến Trường Thành.'),
  ('错误', '这件事和错误有关。', 'Zhe jian shi he cuò wù youguan.', 'Việc này liên quan đến sai lầm.'),
  ('重新', '这件事和重新有关。', 'Zhe jian shi he chóng xīn youguan.', 'Việc này liên quan đến làm lại.'),
  ('超过', '这件事和超过有关。', 'Zhe jian shi he chāo guò youguan.', 'Việc này liên quan đến vượt trên.'),
  ('诚实', '这件事和诚实有关。', 'Zhe jian shi he chéng shí youguan.', 'Việc này liên quan đến trung thực.'),
  ('词语', '这件事和词语有关。', 'Zhe jian shi he cí yǔ youguan.', 'Việc này liên quan đến từ ngữ.'),
  ('粗心', '这件事和粗心有关。', 'Zhe jian shi he cū xīn youguan.', 'Việc này liên quan đến thô lỗ, cẩu thả.'),
  ('窗户', '这件事和窗户有关。', 'Zhe jian shi he chuāng hù youguan.', 'Việc này liên quan đến cửa sổ.'),
  ('猜', '这件事和猜有关。', 'Zhe jian shi he cāi youguan.', 'Việc này liên quan đến đoán.'),
  ('材料', '这件事和材料有关。', 'Zhe jian shi he cái liào youguan.', 'Việc này liên quan đến tài liệu.'),
  ('抽烟', '这件事和抽烟有关。', 'Zhe jian shi he chōu yān youguan.', 'Việc này liên quan đến hút thuốc.'),
  ('成功', '这件事和成功有关。', 'Zhe jian shi he chéng gōng youguan.', 'Việc này liên quan đến thành công.'),
  ('成为', '这件事和成为有关。', 'Zhe jian shi he chéng wéi youguan.', 'Việc này liên quan đến trở thành.'),
  ('差不多', '这件事和差不多有关。', 'Zhe jian shi he chà bù duō youguan.', 'Việc này liên quan đến gần như.'),
  ('尝', '这件事和尝有关。', 'Zhe jian shi he cháng youguan.', 'Việc này liên quan đến nếm thử.'),
  ('存', '这件事和存有关。', 'Zhe jian shi he cún youguan.', 'Việc này liên quan đến giữ, tiết kiệm, tồn.'),
  ('场', '这件事和场有关。', 'Zhe jian shi he chǎng youguan.', 'Việc này liên quan đến trận, suất.'),
  ('吃惊', '这件事和吃惊有关。', 'Zhe jian shi he chī jīng youguan.', 'Việc này liên quan đến ngạc nhiên.'),
  ('参观', '这件事和参观有关。', 'Zhe jian shi he cān guān youguan.', 'Việc này liên quan đến tham quan.'),
  ('厨房', '这件事和厨房有关。', 'Zhe jian shi he chú fáng youguan.', 'Việc này liên quan đến phòng bếp.'),
  ('厕所', '这件事和厕所有关。', 'Zhe jian shi he cè suǒ youguan.', 'Việc này liên quan đến phòng vệ sinh.'),
  ('出生', '这件事和出生有关。', 'Zhe jian shi he chū shēng youguan.', 'Việc này liên quan đến ra đời.'),
  ('出现', '这件事和出现有关。', 'Zhe jian shi he chū xiàn youguan.', 'Việc này liên quan đến xuất hiện.'),
  ('出差', '这件事和出差有关。', 'Zhe jian shi he chū chāi youguan.', 'Việc này liên quan đến đi công tác.'),
  ('出发', '这件事和出发有关。', 'Zhe jian shi he chū fā youguan.', 'Việc này liên quan đến xuất phát.'),
  ('传真', '这件事和传真有关。', 'Zhe jian shi he chuán zhēn youguan.', 'Việc này liên quan đến fax, bản fax.'),
  ('从来', '这件事和从来有关。', 'Zhe jian shi he cóng lái youguan.', 'Việc này liên quan đến từ trước đến nay.'),
  ('乘坐', '这件事和乘坐有关。', 'Zhe jian shi he chéng zuò youguan.', 'Việc này liên quan đến ngồi xe.'),
  ('答案', '这件事和答案有关。', 'Zhe jian shi he dá àn youguan.', 'Việc này liên quan đến đáp án.'),
  ('道歉', '这件事和道歉有关。', 'Zhe jian shi he dào qiàn youguan.', 'Việc này liên quan đến xin lỗi.'),
  ('调查', '这件事和调查有关。', 'Zhe jian shi he diào chá youguan.', 'Việc này liên quan đến điều tra.'),
  ('肚子', '这件事和肚子有关。', 'Zhe jian shi he dù zi youguan.', 'Việc này liên quan đến bụng.'),
  ('等（助词）', '这件事和等（助词）有关。', 'Zhe jian shi he děng （ zhù cí ） youguan.', 'Việc này liên quan đến vân vân.'),
  ('短信', '这件事和短信有关。', 'Zhe jian shi he duǎn xìn youguan.', 'Việc này liên quan đến tin nhắn.'),
  ('登机牌', '这件事和登机牌有关。', 'Zhe jian shi he dēng jī pái youguan.', 'Việc này liên quan đến thẻ lên tàu.'),
  ('掉', '这件事和掉有关。', 'Zhe jian shi he diào youguan.', 'Việc này liên quan đến rơi.'),
  ('打针', '这件事和打针有关。', 'Zhe jian shi he dǎ zhēn youguan.', 'Việc này liên quan đến tiêm.'),
  ('打招呼', '这件事和打招呼有关。', 'Zhe jian shi he dǎ zhāo hū youguan.', 'Việc này liên quan đến chào hỏi.'),
  ('打折', '这件事和打折有关。', 'Zhe jian shi he dǎ zhé youguan.', 'Việc này liên quan đến giảm giá.'),
  ('打扰', '这件事和打扰有关。', 'Zhe jian shi he dǎ rǎo youguan.', 'Việc này liên quan đến làm phiền.'),
  ('打扮', '这件事和打扮有关。', 'Zhe jian shi he dǎ bàn youguan.', 'Việc này liên quan đến trau chuốt, trang điểm.'),
  ('打印', '这件事和打印有关。', 'Zhe jian shi he dǎ yìn youguan.', 'Việc này liên quan đến in ấn.'),
  ('戴', '这件事和戴有关。', 'Zhe jian shi he dài youguan.', 'Việc này liên quan đến đeo.'),
  ('得意', '这件事和得意有关。', 'Zhe jian shi he dé yì youguan.', 'Việc này liên quan đến đắc ý.'),
  ('得（助动词）', '这件事和得（助动词）有关。', 'Zhe jian shi he de（ zhù dòng cí) youguan.', 'Việc này liên quan đến trợ từ.'),
  ('当时', '这件事和当时有关。', 'Zhe jian shi he dāng shí youguan.', 'Việc này liên quan đến lúc đó.'),
  ('当', '这件事和当有关。', 'Zhe jian shi he dāng youguan.', 'Việc này liên quan đến làm.'),
  ('底', '这件事和底有关。', 'Zhe jian shi he dǐ youguan.', 'Việc này liên quan đến đáy.'),
  ('导游', '这件事和导游有关。', 'Zhe jian shi he dǎo yóu youguan.', 'Việc này liên quan đến hướng dẫn viên du lịch.'),
  ('对面', '这件事和对面有关。', 'Zhe jian shi he duì miàn youguan.', 'Việc này liên quan đến đối diện.'),
  ('对话', '这件事和对话有关。', 'Zhe jian shi he duì huà youguan.', 'Việc này liên quan đến hội thoại, đối thoại.'),
  ('对于', '这件事和对于有关。', 'Zhe jian shi he duì yú youguan.', 'Việc này liên quan đến về (vấn đề gì đó).'),
  ('大约', '这件事和大约有关。', 'Zhe jian shi he dà yuē youguan.', 'Việc này liên quan đến khoảng.'),
  ('大概', '这件事和大概有关。', 'Zhe jian shi he dà gài youguan.', 'Việc này liên quan đến khoảng.'),
  ('大夫', '这件事和大夫有关。', 'Zhe jian shi he dài fū youguan.', 'Việc này liên quan đến bác sĩ, đại phu.'),
  ('大使馆', '这件事和大使馆有关。', 'Zhe jian shi he dà shǐ guǎn youguan.', 'Việc này liên quan đến đại sứ quán.'),
  ('堵车', '这件事和堵车有关。', 'Zhe jian shi he dǔ chē youguan.', 'Việc này liên quan đến tắc đường.'),
  ('地球', '这件事和地球有关。', 'Zhe jian shi he dì qiú youguan.', 'Việc này liên quan đến địa cầu.'),
  ('地点', '这件事和地点有关。', 'Zhe jian shi he dì diǎn youguan.', 'Việc này liên quan đến địa điểm.'),
  ('地址', '这件事和地址有关。', 'Zhe jian shi he dì zhǐ youguan.', 'Việc này liên quan đến địa chỉ.'),
  ('动作', '这件事和动作有关。', 'Zhe jian shi he dòng zuò youguan.', 'Việc này liên quan đến động tác.'),
  ('到底', '这件事和到底有关。', 'Zhe jian shi he dào dǐ youguan.', 'Việc này liên quan đến cuối cùng.'),
  ('到处', '这件事和到处有关。', 'Zhe jian shi he dào chù youguan.', 'Việc này liên quan đến khắp nơi.'),
  ('刀', '这件事和刀有关。', 'Zhe jian shi he dāo youguan.', 'Việc này liên quan đến cái dao.'),
  ('倒', '这件事和倒有关。', 'Zhe jian shi he dǎo youguan.', 'Việc này liên quan đến đổ, ngã.'),
  ('低', '这件事和低有关。', 'Zhe jian shi he dī youguan.', 'Việc này liên quan đến thấp.'),
  ('丢', '这件事和丢有关。', 'Zhe jian shi he diū youguan.', 'Việc này liên quan đến mất.'),
  ('儿童', '这件事和儿童有关。', 'Zhe jian shi he ér tóng youguan.', 'Việc này liên quan đến trẻ con.'),
  ('而', '这件事和而有关。', 'Zhe jian shi he ér youguan.', 'Việc này liên quan đến còn.'),
  ('发生', '这件事和发生有关。', 'Zhe jian shi he fā shēng youguan.', 'Việc này liên quan đến xảy ra.'),
  ('负责', '这件事和负责有关。', 'Zhe jian shi he fù zé youguan.', 'Việc này liên quan đến phụ trách.'),
  ('翻译', '这件事和翻译有关。', 'Zhe jian shi he fān yì youguan.', 'Việc này liên quan đến phiên dịch.'),
  ('符合', '这件事和符合有关。', 'Zhe jian shi he fú hé youguan.', 'Việc này liên quan đến phù hợp.'),
  ('父亲', '这件事和父亲有关。', 'Zhe jian shi he fù qīn youguan.', 'Việc này liên quan đến bố.'),
  ('烦恼', '这件事和烦恼有关。', 'Zhe jian shi he fán nǎo youguan.', 'Việc này liên quan đến phiền não.'),
  ('法律', '这件事和法律有关。', 'Zhe jian shi he fǎ lǜ youguan.', 'Việc này liên quan đến pháp luật.'),
  ('方面', '这件事和方面有关。', 'Zhe jian shi he fāng miàn youguan.', 'Việc này liên quan đến phương diện.'),
  ('方法', '这件事和方法有关。', 'Zhe jian shi he fāng fǎ youguan.', 'Việc này liên quan đến phương pháp.'),
  ('方向', '这件事和方向有关。', 'Zhe jian shi he fāng xiàng youguan.', 'Việc này liên quan đến phương hướng.'),
  ('放松', '这件事和放松有关。', 'Zhe jian shi he fàng sōng youguan.', 'Việc này liên quan đến thư giãn.'),
  ('放暑假', '这件事和放暑假有关。', 'Zhe jian shi he fàng shǔ jià youguan.', 'Việc này liên quan đến nghỉ hè.'),
  ('放弃', '这件事和放弃有关。', 'Zhe jian shi he fàng qì youguan.', 'Việc này liên quan đến vứt bỏ, từ bỏ.'),
  ('房东', '这件事和房东有关。', 'Zhe jian shi he fáng dōng youguan.', 'Việc này liên quan đến chủ nhà.'),
  ('富', '这件事和富有关。', 'Zhe jian shi he fù youguan.', 'Việc này liên quan đến giàu.'),
  ('复杂', '这件事和复杂有关。', 'Zhe jian shi he fù zá youguan.', 'Việc này liên quan đến phức tạp.'),
  ('复印', '这件事和复印有关。', 'Zhe jian shi he fù yìn youguan.', 'Việc này liên quan đến phô tô.'),
  ('否则', '这件事和否则有关。', 'Zhe jian shi he fǒu zé youguan.', 'Việc này liên quan đến nếu không thì.'),
  ('发展', '这件事和发展有关。', 'Zhe jian shi he fā zhǎn youguan.', 'Việc này liên quan đến phát triển.'),
  ('反对', '这件事和反对有关。', 'Zhe jian shi he fǎn duì youguan.', 'Việc này liên quan đến phản đối.'),
  ('份', '这件事和份有关。', 'Zhe jian shi he fèn youguan.', 'Việc này liên quan đến phần.'),
  ('付款', '这件事和付款有关。', 'Zhe jian shi he fù kuǎn youguan.', 'Việc này liên quan đến thanh toán.'),
  ('丰富', '这件事和丰富有关。', 'Zhe jian shi he fēng fù youguan.', 'Việc này liên quan đến phong phú.'),
  ('改变', '这件事和改变有关。', 'Zhe jian shi he gǎi biàn youguan.', 'Việc này liên quan đến thay đổi.'),
  ('鼓励', '这件事和鼓励有关。', 'Zhe jian shi he gǔ lì youguan.', 'Việc này liên quan đến cổ vũ.'),
  ('高速公路', '这件事和高速公路有关。', 'Zhe jian shi he gāo sù gōng lù youguan.', 'Việc này liên quan đến đường cao tốc.'),
  ('顾客', '这件事和顾客有关。', 'Zhe jian shi he gù kè youguan.', 'Việc này liên quan đến khách hàng.'),
  ('逛', '这件事和逛有关。', 'Zhe jian shi he guàng youguan.', 'Việc này liên quan đến đi dạo.'),
  ('过程', '这件事和过程有关。', 'Zhe jian shi he guò chéng youguan.', 'Việc này liên quan đến quá trình.'),
  ('赶', '这件事和赶有关。', 'Zhe jian shi he gǎn youguan.', 'Việc này liên quan đến đuổi theo.'),
  ('购物', '这件事和购物有关。', 'Zhe jian shi he gòu wù youguan.', 'Việc này liên quan đến mua sắm.'),
  ('规定', '这件事和规定有关。', 'Zhe jian shi he guī dìng youguan.', 'Việc này liên quan đến qui định.'),
  ('观众', '这件事和观众有关。', 'Zhe jian shi he guān zhòng youguan.', 'Việc này liên quan đến khán giả.'),
  ('胳膊', '这件事和胳膊有关。', 'Zhe jian shi he gē bo youguan.', 'Việc này liên quan đến cánh tay.'),
  ('管理', '这件事和管理有关。', 'Zhe jian shi he guǎn lǐ youguan.', 'Việc này liên quan đến quản lý.'),
  ('果汁', '这件事和果汁有关。', 'Zhe jian shi he guǒ zhī youguan.', 'Việc này liên quan đến nước hoa quả.'),
  ('敢', '这件事和敢有关。', 'Zhe jian shi he gǎn youguan.', 'Việc này liên quan đến dám.'),
  ('故意', '这件事和故意有关。', 'Zhe jian shi he gù yì youguan.', 'Việc này liên quan đến cố ý.'),
  ('挂', '这件事和挂有关。', 'Zhe jian shi he guà youguan.', 'Việc này liên quan đến treo.'),
  ('感谢', '这件事和感谢有关。', 'Zhe jian shi he gǎn xiè youguan.', 'Việc này liên quan đến cảm ơn.'),
  ('感觉', '这件事和感觉有关。', 'Zhe jian shi he gǎn jué youguan.', 'Việc này liên quan đến cảm giác.'),
  ('感情', '这件事和感情有关。', 'Zhe jian shi he gǎn qíng youguan.', 'Việc này liên quan đến tình cảm.'),
  ('感动', '这件事和感动有关。', 'Zhe jian shi he gǎn dòng youguan.', 'Việc này liên quan đến cảm động.'),
  ('广播', '这件事和广播有关。', 'Zhe jian shi he guǎng bō youguan.', 'Việc này liên quan đến phát thanh.'),
  ('广告', '这件事和广告有关。', 'Zhe jian shi he guǎng gào youguan.', 'Việc này liên quan đến quảng cáo.'),
  ('干杯', '这件事和干杯有关。', 'Zhe jian shi he gān bēi youguan.', 'Việc này liên quan đến cạn ly.'),
  ('干', '这件事和干有关。', 'Zhe jian shi he gān youguan.', 'Việc này liên quan đến khô.'),
  ('工资', '这件事和工资有关。', 'Zhe jian shi he gōng zī youguan.', 'Việc này liên quan đến lương.'),
  ('够', '这件事和够有关。', 'Zhe jian shi he gòu youguan.', 'Việc này liên quan đến đủ.'),
  ('国际', '这件事和国际有关。', 'Zhe jian shi he guó jì youguan.', 'Việc này liên quan đến quốc tế.'),
  ('国籍', '这件事和国籍有关。', 'Zhe jian shi he guó jí youguan.', 'Việc này liên quan đến quốc tịch.'),
  ('各', '这件事和各有关。', 'Zhe jian shi he gè youguan.', 'Việc này liên quan đến các.'),
  ('功夫', '这件事和功夫有关。', 'Zhe jian shi he gōng fū youguan.', 'Việc này liên quan đến công phu.'),
  ('刚', '这件事和刚有关。', 'Zhe jian shi he gāng youguan.', 'Việc này liên quan đến vừa mới.'),
  ('关键', '这件事和关键有关。', 'Zhe jian shi he guān jiàn youguan.', 'Việc này liên quan đến quan trọng.'),
  ('共同', '这件事和共同有关。', 'Zhe jian shi he gòng tóng youguan.', 'Việc này liên quan đến giống nhau.'),
  ('公里', '这件事和公里有关。', 'Zhe jian shi he gōng lǐ youguan.', 'Việc này liên quan đến km.'),
  ('光', '这件事和光有关。', 'Zhe jian shi he guāng youguan.', 'Việc này liên quan đến chỉ, hết.'),
  ('估计', '这件事和估计有关。', 'Zhe jian shi he gū jì youguan.', 'Việc này liên quan đến ước lượng.'),
  ('海洋', '这件事和海洋有关。', 'Zhe jian shi he hǎi yáng youguan.', 'Việc này liên quan đến đại dương.'),
  ('获得', '这件事和获得有关。', 'Zhe jian shi he huò dé youguan.', 'Việc này liên quan đến giành được.'),
  ('航班', '这件事和航班有关。', 'Zhe jian shi he háng bān youguan.', 'Việc này liên quan đến chuyến bay.'),
  ('盒子', '这件事和盒子有关。', 'Zhe jian shi he hé zi youguan.', 'Việc này liên quan đến cái hộp.'),
  ('火', '这件事和火有关。', 'Zhe jian shi he huǒ youguan.', 'Việc này liên quan đến lửa.'),
  ('活泼', '这件事和活泼有关。', 'Zhe jian shi he huó pō youguan.', 'Việc này liên quan đến hoạt bát.'),
  ('活动', '这件事和活动有关。', 'Zhe jian shi he huó dòng youguan.', 'Việc này liên quan đến hoạt động.'),
  ('汗', '这件事和汗有关。', 'Zhe jian shi he hàn youguan.', 'Việc này liên quan đến mồ hôi.'),
  ('护士', '这件事和护士有关。', 'Zhe jian shi he hù shì youguan.', 'Việc này liên quan đến y tá.'),
  ('怀疑', '这件事和怀疑有关。', 'Zhe jian shi he huái yí youguan.', 'Việc này liên quan đến nghi ngờ.'),
  ('寒假', '这件事和寒假有关。', 'Zhe jian shi he hán jià youguan.', 'Việc này liên quan đến kì nghỉ đông.'),
  ('害羞', '这件事和害羞有关。', 'Zhe jian shi he hài xiū youguan.', 'Việc này liên quan đến xấu hổ.'),
  ('好处', '这件事和好处有关。', 'Zhe jian shi he hǎo chù youguan.', 'Việc này liên quan đến cái tốt.'),
  ('好像', '这件事和好像有关。', 'Zhe jian shi he hǎo xiàng youguan.', 'Việc này liên quan đến dường như.'),
  ('回忆', '这件事和回忆有关。', 'Zhe jian shi he huí yì youguan.', 'Việc này liên quan đến hồi ức, nhớ lại.'),
  ('后悔', '这件事和后悔有关。', 'Zhe jian shi he hòu huǐ youguan.', 'Việc này liên quan đến hối hận.'),
  ('合适', '这件事和合适有关。', 'Zhe jian shi he hé shì youguan.', 'Việc này liên quan đến thích hợp.'),
  ('合格', '这件事和合格有关。', 'Zhe jian shi he hé gé youguan.', 'Việc này liên quan đến đạt yêu cầu.'),
  ('号码', '这件事和号码有关。', 'Zhe jian shi he hào mǎ youguan.', 'Việc này liên quan đến số.'),
  ('厚', '这件事和厚有关。', 'Zhe jian shi he hòu youguan.', 'Việc này liên quan đến dày.'),
  ('互联网', '这件事和互联网有关。', 'Zhe jian shi he hù lián wǎng youguan.', 'Việc này liên quan đến mạng internet.'),
  ('互相', '这件事和互相有关。', 'Zhe jian shi he hù xiāng youguan.', 'Việc này liên quan đến lẫn nhau.'),
  ('积极', '这件事和积极有关。', 'Zhe jian shi he jī jí youguan.', 'Việc này liên quan đến tích cực.'),
  ('骄傲', '这件事和骄傲有关。', 'Zhe jian shi he jiāo ào youguan.', 'Việc này liên quan đến tự hào, kiêu ngạo.'),
  ('饺子', '这件事和饺子有关。', 'Zhe jian shi he jiǎo zi youguan.', 'Việc này liên quan đến sủi cảo.'),
  ('降落', '这件事和降落有关。', 'Zhe jian shi he jiàng luò youguan.', 'Việc này liên quan đến hạ cánh.'),
  ('降低', '这件事和降低有关。', 'Zhe jian shi he jiàng dī youguan.', 'Việc này liên quan đến hạ thấp.'),
  ('镜子', '这件事和镜子有关。', 'Zhe jian shi he jìng zi youguan.', 'Việc này liên quan đến kính.'),
  ('郊区', '这件事和郊区有关。', 'Zhe jian shi he jiāo qū youguan.', 'Việc này liên quan đến ngoại ô.'),
  ('进行', '这件事和进行有关。', 'Zhe jian shi he jìn xíng youguan.', 'Việc này liên quan đến tiến hành.'),
  ('距离', '这件事和距离有关。', 'Zhe jian shi he jù lí youguan.', 'Việc này liên quan đến khoảng cách.'),
  ('记者', '这件事和记者有关。', 'Zhe jian shi he jì zhě youguan.', 'Việc này liên quan đến phóng viên.'),
  ('计划', '这件事和计划有关。', 'Zhe jian shi he jì huà youguan.', 'Việc này liên quan đến kế hoạch.'),
  ('警察', '这件事和警察有关。', 'Zhe jian shi he jǐng chá youguan.', 'Việc này liên quan đến cảnh sát.'),
  ('解释', '这件事和解释有关。', 'Zhe jian shi he jiě shì youguan.', 'Việc này liên quan đến giải thích.'),
  ('节约', '这件事和节约有关。', 'Zhe jian shi he jié yuē youguan.', 'Việc này liên quan đến tiết kiệm.'),
  ('节', '这件事和节有关。', 'Zhe jian shi he jié youguan.', 'Việc này liên quan đến tiết.'),
  ('聚会', '这件事和聚会有关。', 'Zhe jian shi he jù huì youguan.', 'Việc này liên quan đến tụ tập.'),
  ('继续', '这件事和继续有关。', 'Zhe jian shi he jì xù youguan.', 'Việc này liên quan đến tiếp tục.'),
  ('结果', '这件事和结果有关。', 'Zhe jian shi he jié guǒ youguan.', 'Việc này liên quan đến kết quả.'),
  ('经验', '这件事和经验有关。', 'Zhe jian shi he jīng yàn youguan.', 'Việc này liên quan đến kinh nghiệm.'),
  ('经济', '这件事和经济有关。', 'Zhe jian shi he jīng jì youguan.', 'Việc này liên quan đến kinh tế.'),
  ('经历', '这件事和经历有关。', 'Zhe jian shi he jīng lì youguan.', 'Việc này liên quan đến trải qua, kinh qua.'),
  ('紧张', '这件事和紧张有关。', 'Zhe jian shi he jǐn zhāng youguan.', 'Việc này liên quan đến căng thẳng.'),
  ('精彩', '这件事和精彩有关。', 'Zhe jian shi he jīng cǎi youguan.', 'Việc này liên quan đến hấp dẫn.'),
  ('竟然', '这件事和竟然有关。', 'Zhe jian shi he jìng rán youguan.', 'Việc này liên quan đến mà lại.'),
  ('竞争', '这件事和竞争有关。', 'Zhe jian shi he jìng zhēng youguan.', 'Việc này liên quan đến cạnh tranh.'),
  ('究竟', '这件事和究竟有关。', 'Zhe jian shi he jiū jìng youguan.', 'Việc này liên quan đến rốt cuộc.'),
  ('积累', '这件事和积累有关。', 'Zhe jian shi he jī lěi youguan.', 'Việc này liên quan đến tích lũy.'),
  ('禁止', '这件事和禁止有关。', 'Zhe jian shi he jìn zhǐ youguan.', 'Việc này liên quan đến cấm.'),
  ('激动', '这件事和激动有关。', 'Zhe jian shi he jī dòng youguan.', 'Việc này liên quan đến xúc động.'),
  ('景色', '这件事和景色有关。', 'Zhe jian shi he jǐng sè youguan.', 'Việc này liên quan đến cảnh sắc.'),
  ('既然', '这件事和既然有关。', 'Zhe jian shi he jì rán youguan.', 'Việc này liên quan đến đã…..'),
  ('教育', '这件事和教育有关。', 'Zhe jian shi he jiào yù youguan.', 'Việc này liên quan đến giáo dục.'),
  ('教授', '这件事和教授有关。', 'Zhe jian shi he jiào shòu youguan.', 'Việc này liên quan đến giáo sư.'),
  ('接着', '这件事和接着有关。', 'Zhe jian shi he jiē zhe youguan.', 'Việc này liên quan đến tiếp theo.'),
  ('接受', '这件事和接受有关。', 'Zhe jian shi he jiē shòu youguan.', 'Việc này liên quan đến tiếp nhận.'),
  ('拒绝', '这件事和拒绝有关。', 'Zhe jian shi he jù jué youguan.', 'Việc này liên quan đến từ chối.'),
  ('技术', '这件事和技术有关。', 'Zhe jian shi he jì shù youguan.', 'Việc này liên quan đến kỹ thuật.'),
  ('建议', '这件事和建议有关。', 'Zhe jian shi he jiàn yì youguan.', 'Việc này liên quan đến kiến nghị.'),
  ('尽管', '这件事和尽管有关。', 'Zhe jian shi he jǐn guǎn youguan.', 'Việc này liên quan đến tuy rằng.'),
  ('将来', '这件事和将来有关。', 'Zhe jian shi he jiāng lái youguan.', 'Việc này liên quan đến tương lai.'),
  ('寄', '这件事和寄有关。', 'Zhe jian shi he jì youguan.', 'Việc này liên quan đến gửi.'),
  ('家具', '这件事和家具有关。', 'Zhe jian shi he jiā jù youguan.', 'Việc này liên quan đến đồ gia dụng.'),
  ('奖金', '这件事和奖金有关。', 'Zhe jian shi he jiǎng jīn youguan.', 'Việc này liên quan đến học bổng.'),
  ('基础', '这件事和基础有关。', 'Zhe jian shi he jī chǔ youguan.', 'Việc này liên quan đến cơ sở, căn bản.'),
  ('坚持', '这件事和坚持有关。', 'Zhe jian shi he jiān chí youguan.', 'Việc này liên quan đến kiên trì.'),
  ('及时', '这件事和及时有关。', 'Zhe jian shi he jí shí youguan.', 'Việc này liên quan đến kịp thời.'),
  ('即使', '这件事和即使有关。', 'Zhe jian shi he jí shǐ youguan.', 'Việc này liên quan đến cho dù.'),
  ('加班', '这件事和加班有关。', 'Zhe jian shi he jiā bān youguan.', 'Việc này liên quan đến tăng ca.'),
  ('加油站', '这件事和加油站有关。', 'Zhe jian shi he jiā yóu zhàn youguan.', 'Việc này liên quan đến cây xăng.'),
  ('减肥', '这件事和减肥有关。', 'Zhe jian shi he jiǎn féi youguan.', 'Việc này liên quan đến giảm béo.'),
  ('减少', '这件事和减少有关。', 'Zhe jian shi he jiǎn shǎo youguan.', 'Việc này liên quan đến cắt giảm.'),
  ('假', '这件事和假有关。', 'Zhe jian shi he jiǎ youguan.', 'Việc này liên quan đến giả.'),
  ('价格', '这件事和价格有关。', 'Zhe jian shi he jià gé youguan.', 'Việc này liên quan đến giá cả.'),
  ('京剧', '这件事和京剧有关。', 'Zhe jian shi he jīng jù youguan.', 'Việc này liên quan đến kinh kịch.'),
  ('交通', '这件事和交通有关。', 'Zhe jian shi he jiāo tōng youguan.', 'Việc này liên quan đến giao thông.'),
  ('交流', '这件事和交流有关。', 'Zhe jian shi he jiāo liú youguan.', 'Việc này liên quan đến giao lưu.'),
  ('交', '这件事和交有关。', 'Zhe jian shi he jiāo youguan.', 'Việc này liên quan đến giao.'),
  ('举行', '这件事和举行有关。', 'Zhe jian shi he jǔ xíng youguan.', 'Việc này liên quan đến tổ chức.'),
  ('举办', '这件事和举办有关。', 'Zhe jian shi he jǔ bàn youguan.', 'Việc này liên quan đến tổ chức.'),
  ('举', '这件事和举有关。', 'Zhe jian shi he jǔ youguan.', 'Việc này liên quan đến giơ, nâng.'),
  ('开玩笑', '这件事和开玩笑有关。', 'Zhe jian shi he kāi wán xiào youguan.', 'Việc này liên quan đến đùa.'),
  ('苦', '这件事和苦有关。', 'Zhe jian shi he kǔ youguan.', 'Việc này liên quan đến khổ, đắng.'),
  ('肯定', '这件事和肯定有关。', 'Zhe jian shi he kěn dìng youguan.', 'Việc này liên quan đến khẳng định.'),
  ('考虑', '这件事和考虑有关。', 'Zhe jian shi he kǎo lǜ youguan.', 'Việc này liên quan đến suy nghĩ.'),
  ('空气', '这件事和空气有关。', 'Zhe jian shi he kōng qì youguan.', 'Việc này liên quan đến không khí.'),
  ('空', '这件事和空有关。', 'Zhe jian shi he kōng youguan.', 'Việc này liên quan đến trống rỗng.'),
  ('科学', '这件事和科学有关。', 'Zhe jian shi he kē xué youguan.', 'Việc này liên quan đến khoa học.'),
  ('矿泉水', '这件事和矿泉水有关。', 'Zhe jian shi he kuàng quán shuǐ youguan.', 'Việc này liên quan đến nước khoáng.'),
  ('看法', '这件事和看法有关。', 'Zhe jian shi he kàn fǎ youguan.', 'Việc này liên quan đến quan điểm.'),
  ('烤鸭', '这件事和烤鸭有关。', 'Zhe jian shi he kǎo yā youguan.', 'Việc này liên quan đến vịt quay.'),
  ('棵', '这件事和棵有关。', 'Zhe jian shi he kē youguan.', 'Việc này liên quan đến lượng từ cho cây.'),
  ('恐怕', '这件事和恐怕有关。', 'Zhe jian shi he kǒng pà youguan.', 'Việc này liên quan đến e rằng.'),
  ('开心', '这件事和开心有关。', 'Zhe jian shi he kāi xīn youguan.', 'Việc này liên quan đến vui vẻ.'),
  ('客厅', '这件事和客厅有关。', 'Zhe jian shi he kè tīng youguan.', 'Việc này liên quan đến phòng khách.'),
  ('困难', '这件事和困难有关。', 'Zhe jian shi he kùn nán youguan.', 'Việc này liên quan đến khó khăn.'),
  ('困', '这件事和困有关。', 'Zhe jian shi he kùn youguan.', 'Việc này liên quan đến buồn ngủ.'),
  ('咳嗽', '这件事和咳嗽有关。', 'Zhe jian shi he ké sou youguan.', 'Việc này liên quan đến ho.'),
  ('可是', '这件事和可是有关。', 'Zhe jian shi he kě shì youguan.', 'Việc này liên quan đến nhưng.'),
  ('可惜', '这件事和可惜有关。', 'Zhe jian shi he kě xī youguan.', 'Việc này liên quan đến đáng tiếc.'),
  ('可怜', '这件事和可怜有关。', 'Zhe jian shi he kě lián youguan.', 'Việc này liên quan đến đáng thương.'),
  ('垃圾桶', '这件事和垃圾桶有关。', 'Zhe jian shi he lā jī tǒng youguan.', 'Việc này liên quan đến thùng rác.'),
  ('零钱', '这件事和零钱有关。', 'Zhe jian shi he líng qián youguan.', 'Việc này liên quan đến tiền lẻ.'),
  ('连', '这件事和连有关。', 'Zhe jian shi he lián youguan.', 'Việc này liên quan đến liên kết, nối.'),
  ('辣', '这件事和辣有关。', 'Zhe jian shi he là youguan.', 'Việc này liên quan đến cay.'),
  ('联系', '这件事和联系有关。', 'Zhe jian shi he lián xì youguan.', 'Việc này liên quan đến liên hệ.'),
  ('老虎', '这件事和老虎有关。', 'Zhe jian shi he lǎo hǔ youguan.', 'Việc này liên quan đến hổ.'),
  ('礼貌', '这件事和礼貌有关。', 'Zhe jian shi he lǐ mào youguan.', 'Việc này liên quan đến lễ phép, lịch sự.'),
  ('礼拜天', '这件事和礼拜天有关。', 'Zhe jian shi he lǐ bài tiān youguan.', 'Việc này liên quan đến chủ nhật.'),
  ('留', '这件事和留有关。', 'Zhe jian shi he liú youguan.', 'Việc này liên quan đến lưu lại, ở lại.'),
  ('理解', '这件事和理解有关。', 'Zhe jian shi he lǐ jiě youguan.', 'Việc này liên quan đến lý giải, hiểu.'),
  ('理想', '这件事和理想有关。', 'Zhe jian shi he lǐ xiǎng youguan.', 'Việc này liên quan đến lý tưởng.'),
  ('理发', '这件事和理发有关。', 'Zhe jian shi he lǐ fà youguan.', 'Việc này liên quan đến cắt tóc.'),
  ('浪费', '这件事和浪费有关。', 'Zhe jian shi he làng fèi youguan.', 'Việc này liên quan đến lãng phí.'),
  ('浪漫', '这件事和浪漫有关。', 'Zhe jian shi he làng màn youguan.', 'Việc này liên quan đến lãng mạn.'),
  ('流行', '这件事和流行有关。', 'Zhe jian shi he liú xíng youguan.', 'Việc này liên quan đến thịnh hành.'),
  ('流利', '这件事和流利有关。', 'Zhe jian shi he liú lì youguan.', 'Việc này liên quan đến lưu loát.'),
  ('来自', '这件事和来自有关。', 'Zhe jian shi he lái zì youguan.', 'Việc này liên quan đến đến từ.'),
  ('来得及', '这件事和来得及有关。', 'Zhe jian shi he lái de jí youguan.', 'Việc này liên quan đến kịp.'),
  ('来不及', '这件事和来不及有关。', 'Zhe jian shi he lái bù jí youguan.', 'Việc này liên quan đến không kịp.'),
  ('旅行', '这件事和旅行有关。', 'Zhe jian shi he lǚ xíng youguan.', 'Việc này liên quan đến du lịch.'),
  ('拉', '这件事和拉有关。', 'Zhe jian shi he lā youguan.', 'Việc này liên quan đến kéo.'),
  ('懒', '这件事和懒有关。', 'Zhe jian shi he lǎn youguan.', 'Việc này liên quan đến lười biếng.'),
  ('律师', '这件事和律师有关。', 'Zhe jian shi he lǜ shī youguan.', 'Việc này liên quan đến luật sư.'),
  ('另外', '这件事和另外有关。', 'Zhe jian shi he lìng wài youguan.', 'Việc này liên quan đến ngoài ra, còn lại.'),
  ('厉害', '这件事和厉害有关。', 'Zhe jian shi he lì hài youguan.', 'Việc này liên quan đến lợi hại.'),
  ('力气', '这件事和力气有关。', 'Zhe jian shi he lì qì youguan.', 'Việc này liên quan đến sức lực.'),
  ('凉快', '这件事和凉快有关。', 'Zhe jian shi he liáng kuài youguan.', 'Việc này liên quan đến mát mẻ.'),
  ('冷静', '这件事和冷静有关。', 'Zhe jian shi he lěng jìng youguan.', 'Việc này liên quan đến bình tĩnh.'),
  ('俩', '这件事和俩有关。', 'Zhe jian shi he liǎ youguan.', 'Việc này liên quan đến hai người.'),
  ('例如', '这件事和例如有关。', 'Zhe jian shi he lì rú youguan.', 'Việc này liên quan đến ví dụ.'),
  ('乱', '这件事和乱有关。', 'Zhe jian shi he luàn youguan.', 'Việc này liên quan đến loạn.'),
  ('麻烦', '这件事和麻烦有关。', 'Zhe jian shi he má fan youguan.', 'Việc này liên quan đến phiền phức, làm phiền.'),
  ('马虎', '这件事和马虎有关。', 'Zhe jian shi he mǎ hu youguan.', 'Việc này liên quan đến qua loa.'),
  ('迷路', '这件事和迷路有关。', 'Zhe jian shi he mí lù youguan.', 'Việc này liên quan đến lạc đường.'),
  ('美丽', '这件事和美丽有关。', 'Zhe jian shi he měi lì youguan.', 'Việc này liên quan đến đẹp.'),
  ('秒', '这件事和秒有关。', 'Zhe jian shi he miǎo youguan.', 'Việc này liên quan đến giây.'),
  ('目的', '这件事和目的有关。', 'Zhe jian shi he mù dì youguan.', 'Việc này liên quan đến mục đích.'),
  ('满', '这件事和满有关。', 'Zhe jian shi he mǎn youguan.', 'Việc này liên quan đến đầy.'),
  ('民族', '这件事和民族有关。', 'Zhe jian shi he mín zú youguan.', 'Việc này liên quan đến dân tộc.'),
  ('毛巾', '这件事和毛巾有关。', 'Zhe jian shi he máo jīn youguan.', 'Việc này liên quan đến khăn bông.'),
  ('毛', '这件事和毛有关。', 'Zhe jian shi he máo youguan.', 'Việc này liên quan đến lông.'),
  ('母亲', '这件事和母亲有关。', 'Zhe jian shi he mǔ qin youguan.', 'Việc này liên quan đến mẹ.'),
  ('梦', '这件事和梦有关。', 'Zhe jian shi he mèng youguan.', 'Việc này liên quan đến giấc mơ, mơ.'),
  ('密码', '这件事和密码有关。', 'Zhe jian shi he mì mǎ youguan.', 'Việc này liên quan đến mật khẩu.'),
  ('免费', '这件事和免费有关。', 'Zhe jian shi he miǎn fèi youguan.', 'Việc này liên quan đến miễn phí.'),
  ('耐心', '这件事和耐心有关。', 'Zhe jian shi he nài xīn youguan.', 'Việc này liên quan đến nhẫn nại.'),
  ('难道', '这件事和难道有关。', 'Zhe jian shi he nán dào youguan.', 'Việc này liên quan đến lẽ nào.'),
  ('难受', '这件事和难受有关。', 'Zhe jian shi he nán shòu youguan.', 'Việc này liên quan đến buồn.'),
  ('能力', '这件事和能力有关。', 'Zhe jian shi he néng lì youguan.', 'Việc này liên quan đến năng lực.'),
  ('暖和', '这件事和暖和有关。', 'Zhe jian shi he nuǎn huo youguan.', 'Việc này liên quan đến ấm áp.'),
  ('弄', '这件事和弄有关。', 'Zhe jian shi he nòng youguan.', 'Việc này liên quan đến làm.'),
  ('年龄', '这件事和年龄有关。', 'Zhe jian shi he nián líng youguan.', 'Việc này liên quan đến tuổi tác.'),
  ('内容', '这件事和内容有关。', 'Zhe jian shi he nèi róng youguan.', 'Việc này liên quan đến nội dung.'),
  ('内', '这件事和内有关。', 'Zhe jian shi he nèi youguan.', 'Việc này liên quan đến bên trong.'),
  ('偶尔', '这件事和偶尔有关。', 'Zhe jian shi he ǒu ěr youguan.', 'Việc này liên quan đến đôi khi.'),
  ('排队', '这件事和排队有关。', 'Zhe jian shi he pái duì youguan.', 'Việc này liên quan đến xếp hàng.'),
  ('骗', '这件事和骗有关。', 'Zhe jian shi he piàn youguan.', 'Việc này liên quan đến lừa.'),
  ('陪', '这件事和陪有关。', 'Zhe jian shi he péi youguan.', 'Việc này liên quan đến cùng.'),
  ('葡萄', '这件事和葡萄有关。', 'Zhe jian shi he pú táo youguan.', 'Việc này liên quan đến nho.'),
  ('脾气', '这件事和脾气有关。', 'Zhe jian shi he pí qì youguan.', 'Việc này liên quan đến tính khí.'),
  ('篇', '这件事和篇有关。', 'Zhe jian shi he piān youguan.', 'Việc này liên quan đến lượng từ cho bài viết.'),
  ('破', '这件事和破有关。', 'Zhe jian shi he pò youguan.', 'Việc này liên quan đến rách, nổ.'),
  ('皮肤', '这件事和皮肤有关。', 'Zhe jian shi he pí fū youguan.', 'Việc này liên quan đến da.'),
  ('普遍', '这件事和普遍有关。', 'Zhe jian shi he pǔ biàn youguan.', 'Việc này liên quan đến phổ biến.'),
  ('普通话', '这件事和普通话有关。', 'Zhe jian shi he pǔ tōng huà youguan.', 'Việc này liên quan đến tiếng phổ thông.'),
  ('排列', '这件事和排列有关。', 'Zhe jian shi he pái liè youguan.', 'Việc này liên quan đến liệt kê.'),
  ('批评', '这件事和批评有关。', 'Zhe jian shi he pī píng youguan.', 'Việc này liên quan đến phê bình.'),
  ('平时', '这件事和平时有关。', 'Zhe jian shi he píng shí youguan.', 'Việc này liên quan đến bình thường.'),
  ('判断', '这件事和判断有关。', 'Zhe jian shi he pàn duàn youguan.', 'Việc này liên quan đến phán đoán.'),
  ('乒乓球', '这件事和乒乓球有关。', 'Zhe jian shi he pīng pāng qiú youguan.', 'Việc này liên quan đến bóng bàn.'),
  ('其次', '这件事和其次有关。', 'Zhe jian shi he qí cì youguan.', 'Việc này liên quan đến tiếp theo.'),
  ('轻松', '这件事和轻松有关。', 'Zhe jian shi he qīng sōng youguan.', 'Việc này liên quan đến thoải mái.'),
  ('轻', '这件事和轻有关。', 'Zhe jian shi he qīng youguan.', 'Việc này liên quan đến nhẹ.'),
  ('缺点', '这件事和缺点有关。', 'Zhe jian shi he quē diǎn youguan.', 'Việc này liên quan đến khuyết điểm.'),
  ('缺少', '这件事和缺少有关。', 'Zhe jian shi he quē shǎo youguan.', 'Việc này liên quan đến thiếu.'),
  ('签证', '这件事和签证有关。', 'Zhe jian shi he qiān zhèng youguan.', 'Việc này liên quan đến visa.'),
  ('穷', '这件事和穷有关。', 'Zhe jian shi he qióng youguan.', 'Việc này liên quan đến nghèo.'),
  ('确实', '这件事和确实有关。', 'Zhe jian shi he què shí youguan.', 'Việc này liên quan đến thật sự.'),
  ('气候', '这件事和气候有关。', 'Zhe jian shi he qì hòu youguan.', 'Việc này liên quan đến khí hậu.'),
  ('桥', '这件事和桥有关。', 'Zhe jian shi he qiáo youguan.', 'Việc này liên quan đến cầu.'),
  ('敲', '这件事和敲有关。', 'Zhe jian shi he qiāo youguan.', 'Việc này liên quan đến gõ.'),
  ('情况', '这件事和情况有关。', 'Zhe jian shi he qíng kuàng youguan.', 'Việc này liên quan đến tình hình.'),
  ('巧克力', '这件事和巧克力有关。', 'Zhe jian shi he qiǎo kè lì youguan.', 'Việc này liên quan đến sô cô la.'),
  ('取', '这件事和取有关。', 'Zhe jian shi he qǔ youguan.', 'Việc này liên quan đến lấy.'),
  ('却', '这件事和却有关。', 'Zhe jian shi he què youguan.', 'Việc này liên quan đến lại.'),
  ('千万', '这件事和千万有关。', 'Zhe jian shi he qiān wàn youguan.', 'Việc này liên quan đến nhất thiết.'),
  ('区别', '这件事和区别有关。', 'Zhe jian shi he qū bié youguan.', 'Việc này liên quan đến khác biệt.'),
  ('其中', '这件事和其中有关。', 'Zhe jian shi he qí zhōng youguan.', 'Việc này liên quan đến trong đó.'),
  ('全部', '这件事和全部有关。', 'Zhe jian shi he quán bù youguan.', 'Việc này liên quan đến toàn bộ.'),
  ('亲戚', '这件事和亲戚有关。', 'Zhe jian shi he qīn qi youguan.', 'Việc này liên quan đến họ hàng.'),
  ('然而', '这件事和然而有关。', 'Zhe jian shi he rán ér youguan.', 'Việc này liên quan đến vậy mà.'),
  ('热闹', '这件事和热闹有关。', 'Zhe jian shi he rè nào youguan.', 'Việc này liên quan đến náo nhiệt.'),
  ('日记', '这件事和日记有关。', 'Zhe jian shi he rì jì youguan.', 'Việc này liên quan đến nhật kí.'),
  ('扔', '这件事和扔有关。', 'Zhe jian shi he rēng youguan.', 'Việc này liên quan đến ném.'),
  ('入口', '这件事和入口有关。', 'Zhe jian shi he rù kǒu youguan.', 'Việc này liên quan đến cửa vào.'),
  ('任务', '这件事和任务有关。', 'Zhe jian shi he rèn wù youguan.', 'Việc này liên quan đến nhiệm vụ.'),
  ('任何', '这件事和任何有关。', 'Zhe jian shi he rèn hé youguan.', 'Việc này liên quan đến bất kì.'),
  ('仍然', '这件事和仍然有关。', 'Zhe jian shi he réng rán youguan.', 'Việc này liên quan đến vẫn.'),
  ('散步', '这件事和散步有关。', 'Zhe jian shi he sàn bù youguan.', 'Việc này liên quan đến tản bộ.'),
  ('首都', '这件事和首都有关。', 'Zhe jian shi he shǒu dū youguan.', 'Việc này liên quan đến thủ đô.'),
  ('首先', '这件事和首先有关。', 'Zhe jian shi he shǒu xiān youguan.', 'Việc này liên quan đến đầu tiên.'),
  ('顺序', '这件事和顺序有关。', 'Zhe jian shi he shùn xù youguan.', 'Việc này liên quan đến thứ tự.'),
  ('顺利', '这件事和顺利有关。', 'Zhe jian shi he shùn lì youguan.', 'Việc này liên quan đến thuận lợi.'),
  ('顺便', '这件事和顺便有关。', 'Zhe jian shi he shùn biàn youguan.', 'Việc này liên quan đến nhân tiện.'),
  ('随着', '这件事和随着有关。', 'Zhe jian shi he suí zhe youguan.', 'Việc này liên quan đến cùng với.'),
  ('随便', '这件事和随便有关。', 'Zhe jian shi he suí biàn youguan.', 'Việc này liên quan đến tùy tiện, tự nhiên.'),
  ('酸', '这件事和酸有关。', 'Zhe jian shi he suān youguan.', 'Việc này liên quan đến chua.'),
  ('速度', '这件事和速度有关。', 'Zhe jian shi he sù dù youguan.', 'Việc này liên quan đến tốc độ.'),
  ('适应', '这件事和适应有关。', 'Zhe jian shi he shì yìng youguan.', 'Việc này liên quan đến thích nghi.'),
  ('适合', '这件事和适合有关。', 'Zhe jian shi he shì hé youguan.', 'Việc này liên quan đến thích hợp.'),
  ('输', '这件事和输有关。', 'Zhe jian shi he shū youguan.', 'Việc này liên quan đến thua.'),
  ('说明', '这件事和说明有关。', 'Zhe jian shi he shuō míng youguan.', 'Việc này liên quan đến nói rõ.'),
  ('稍微', '这件事和稍微有关。', 'Zhe jian shi he shāo wēi youguan.', 'Việc này liên quan đến một chút.'),
  ('社会', '这件事和社会有关。', 'Zhe jian shi he shè huì youguan.', 'Việc này liên quan đến xã hội.'),
  ('硕士', '这件事和硕士有关。', 'Zhe jian shi he shuò shì youguan.', 'Việc này liên quan đến thạc sĩ.'),
  ('省', '这件事和省有关。', 'Zhe jian shi he shěng youguan.', 'Việc này liên quan đến tỉnh thành.'),
  ('申请', '这件事和申请有关。', 'Zhe jian shi he shēn qǐng youguan.', 'Việc này liên quan đến xin.'),
  ('生活', '这件事和生活有关。', 'Zhe jian shi he shēng huó youguan.', 'Việc này liên quan đến cuộc sống.'),
  ('生意', '这件事和生意有关。', 'Zhe jian shi he shēng yì youguan.', 'Việc này liên quan đến kinh doanh.'),
  ('生命', '这件事和生命有关。', 'Zhe jian shi he shēng mìng youguan.', 'Việc này liên quan đến tính mạng.'),
  ('甚至', '这件事和甚至有关。', 'Zhe jian shi he shèn zhì youguan.', 'Việc này liên quan đến thậm chí.'),
  ('熟悉', '这件事和熟悉有关。', 'Zhe jian shi he shú xī youguan.', 'Việc này liên quan đến quen thuộc.'),
  ('深', '这件事和深有关。', 'Zhe jian shi he shēn youguan.', 'Việc này liên quan đến sâu.'),
  ('沙发', '这件事和沙发有关。', 'Zhe jian shi he shā fā youguan.', 'Việc này liên quan đến ghế sô pha.'),
  ('死', '这件事和死有关。', 'Zhe jian shi he sǐ youguan.', 'Việc này liên quan đến chết.'),
  ('森林', '这件事和森林有关。', 'Zhe jian shi he sēn lín youguan.', 'Việc này liên quan đến rừng sâu.'),
  ('是否', '这件事和是否有关。', 'Zhe jian shi he shì fǒu youguan.', 'Việc này liên quan đến liệu có phải.'),
  ('数量', '这件事和数量有关。', 'Zhe jian shi he shù liàng youguan.', 'Việc này liên quan đến số lượng.'),
  ('数字', '这件事和数字有关。', 'Zhe jian shi he shù zi youguan.', 'Việc này liên quan đến con cố.'),
  ('收拾', '这件事和收拾有关。', 'Zhe jian shi he shōu shí youguan.', 'Việc này liên quan đến dọn dẹp.'),
  ('收入', '这件事和收入有关。', 'Zhe jian shi he shōu rù youguan.', 'Việc này liên quan đến thu nhập.'),
  ('收', '这件事和收有关。', 'Zhe jian shi he shōu youguan.', 'Việc này liên quan đến nhận.'),
  ('所有', '这件事和所有有关。', 'Zhe jian shi he suǒ yǒu youguan.', 'Việc này liên quan đến tất cả.'),
  ('师傅', '这件事和师傅有关。', 'Zhe jian shi he shī fù youguan.', 'Việc này liên quan đến sư phụ.'),
  ('帅', '这件事和帅有关。', 'Zhe jian shi he shuài youguan.', 'Việc này liên quan đến đẹp trai.'),
  ('实际', '这件事和实际有关。', 'Zhe jian shi he shí jì youguan.', 'Việc này liên quan đến thực tế.'),
  ('实在', '这件事和实在有关。', 'Zhe jian shi he shí zài youguan.', 'Việc này liên quan đến thật sự.'),
  ('孙子', '这件事和孙子有关。', 'Zhe jian shi he sūn zi youguan.', 'Việc này liên quan đến cháu trai.'),
  ('失败', '这件事和失败有关。', 'Zhe jian shi he shī bài youguan.', 'Việc này liên quan đến thất bại.'),
  ('失望', '这件事和失望有关。', 'Zhe jian shi he shī wàng youguan.', 'Việc này liên quan đến thất vọng.'),
  ('塑料袋', '这件事和塑料袋有关。', 'Zhe jian shi he sù liào dài youguan.', 'Việc này liên quan đến túi ni lông.'),
  ('商量', '这件事和商量有关。', 'Zhe jian shi he shāng liáng youguan.', 'Việc này liên quan đến thương lượng, bàn bạc.'),
  ('售货员', '这件事和售货员有关。', 'Zhe jian shi he shòu huò yuán youguan.', 'Việc này liên quan đến nhân viên bán vé.'),
  ('受到', '这件事和受到有关。', 'Zhe jian shi he shòu dào youguan.', 'Việc này liên quan đến nhận được.'),
  ('受不了', '这件事和受不了有关。', 'Zhe jian shi he shòu bù liǎo youguan.', 'Việc này liên quan đến không chịu nổi.'),
  ('十分', '这件事和十分有关。', 'Zhe jian shi he shí fēn youguan.', 'Việc này liên quan đến vô cùng.'),
  ('勺子', '这件事和勺子有关。', 'Zhe jian shi he sháo zi youguan.', 'Việc này liên quan đến cái thìa.'),
  ('剩', '这件事和剩有关。', 'Zhe jian shi he shèng youguan.', 'Việc này liên quan đến thừa.'),
  ('使用', '这件事和使用有关。', 'Zhe jian shi he shǐ yòng youguan.', 'Việc này liên quan đến sử dụng.'),
  ('使', '这件事和使有关。', 'Zhe jian shi he shǐ youguan.', 'Việc này liên quan đến khiến cho.'),
  ('伤心', '这件事和伤心有关。', 'Zhe jian shi he shāng xīn youguan.', 'Việc này liên quan đến tổn thương.'),
  ('世纪', '这件事和世纪有关。', 'Zhe jian shi he shì jì youguan.', 'Việc này liên quan đến thế kỉ.'),
  ('台', '这件事和台有关。', 'Zhe jian shi he tái youguan.', 'Việc này liên quan đến cái, chiếc.'),
  ('通过', '这件事和通过有关。', 'Zhe jian shi he tōng guò youguan.', 'Việc này liên quan đến thông qua.'),
  ('通知', '这件事和通知有关。', 'Zhe jian shi he tōng zhī youguan.', 'Việc này liên quan đến thông báo.'),
  ('躺', '这件事和躺有关。', 'Zhe jian shi he tǎng youguan.', 'Việc này liên quan đến nằm.'),
  ('趟', '这件事和趟有关。', 'Zhe jian shi he tàng youguan.', 'Việc này liên quan đến chuyến.'),
  ('谈', '这件事和谈有关。', 'Zhe jian shi he tán youguan.', 'Việc này liên quan đến nói chuyện.'),
  ('讨论', '这件事和讨论有关。', 'Zhe jian shi he tǎo lùn youguan.', 'Việc này liên quan đến thảo luận.'),
  ('讨厌', '这件事和讨厌有关。', 'Zhe jian shi he tǎo yàn youguan.', 'Việc này liên quan đến ghét.'),
  ('脱', '这件事和脱有关。', 'Zhe jian shi he tuō youguan.', 'Việc này liên quan đến cởi.'),
  ('糖', '这件事和糖有关。', 'Zhe jian shi he táng youguan.', 'Việc này liên quan đến đường.'),
  ('特点', '这件事和特点有关。', 'Zhe jian shi he tè diǎn youguan.', 'Việc này liên quan đến đặc điểm.'),
  ('汤', '这件事和汤有关。', 'Zhe jian shi he tāng youguan.', 'Việc này liên quan đến canh.'),
  ('条件', '这件事和条件有关。', 'Zhe jian shi he tiáo jiàn youguan.', 'Việc này liên quan đến điều kiện.'),
  ('提醒', '这件事和提醒有关。', 'Zhe jian shi he tí xǐng youguan.', 'Việc này liên quan đến nhắc nhở.'),
  ('提前', '这件事和提前有关。', 'Zhe jian shi he tí qián youguan.', 'Việc này liên quan đến trước thời hạn.'),
  ('提供', '这件事和提供有关。', 'Zhe jian shi he tí gōng youguan.', 'Việc này liên quan đến cung cấp.'),
  ('提', '这件事和提有关。', 'Zhe jian shi he tí youguan.', 'Việc này liên quan đến đề ra.'),
  ('推迟', '这件事和推迟有关。', 'Zhe jian shi he tuī chí youguan.', 'Việc này liên quan đến kéo dài thời gian.'),
  ('推', '这件事和推有关。', 'Zhe jian shi he tuī youguan.', 'Việc này liên quan đến đẩy.'),
  ('挺', '这件事和挺有关。', 'Zhe jian shi he tǐng youguan.', 'Việc này liên quan đến rất.'),
  ('抬', '这件事和抬有关。', 'Zhe jian shi he tái youguan.', 'Việc này liên quan đến ngẩng.'),
  ('态度', '这件事和态度有关。', 'Zhe jian shi he tài dù youguan.', 'Việc này liên quan đến thái độ.'),
  ('弹钢琴', '这件事和弹钢琴有关。', 'Zhe jian shi he tán gāng qín youguan.', 'Việc này liên quan đến chơi piano.'),
  ('填空', '这件事和填空有关。', 'Zhe jian shi he tián kòng youguan.', 'Việc này liên quan đến điền trống.'),
  ('同时', '这件事和同时有关。', 'Zhe jian shi he tóng shí youguan.', 'Việc này liên quan đến đồng thời.'),
  ('同情', '这件事和同情有关。', 'Zhe jian shi he tóng qíng youguan.', 'Việc này liên quan đến đồng tình.'),
  ('停', '这件事和停有关。', 'Zhe jian shi he tíng youguan.', 'Việc này liên quan đến dừng.'),
  ('袜子', '这件事和袜子有关。', 'Zhe jian shi he wà zi youguan.', 'Việc này liên quan đến tất chân.'),
  ('误会', '这件事和误会有关。', 'Zhe jian shi he wù huì youguan.', 'Việc này liên quan đến hiểu lầm.'),
  ('网站', '这件事和网站有关。', 'Zhe jian shi he wǎng zhàn youguan.', 'Việc này liên quan đến trang mạng.'),
  ('网球', '这件事和网球有关。', 'Zhe jian shi he wǎng qiú youguan.', 'Việc này liên quan đến tennis.'),
  ('温度', '这件事和温度有关。', 'Zhe jian shi he wēn dù youguan.', 'Việc này liên quan đến nhiệt độ.'),
  ('污染', '这件事和污染有关。', 'Zhe jian shi he wū rǎn youguan.', 'Việc này liên quan đến ô nhiễm.'),
  ('无论', '这件事和无论有关。', 'Zhe jian shi he wú lùn youguan.', 'Việc này liên quan đến bất luận.'),
  ('无聊', '这件事和无聊有关。', 'Zhe jian shi he wú liáo youguan.', 'Việc này liên quan đến nhàm chán.'),
  ('无', '这件事和无有关。', 'Zhe jian shi he wú youguan.', 'Việc này liên quan đến không.'),
  ('文章', '这件事和文章有关。', 'Zhe jian shi he wén zhāng youguan.', 'Việc này liên quan đến bài văn.'),
  ('往往', '这件事和往往有关。', 'Zhe jian shi he wǎng wǎng youguan.', 'Việc này liên quan đến thường (quá khứ).'),
  ('完全', '这件事和完全有关。', 'Zhe jian shi he wán quán youguan.', 'Việc này liên quan đến hoàn toàn.'),
  ('味道', '这件事和味道有关。', 'Zhe jian shi he wèi dào youguan.', 'Việc này liên quan đến mùi vị.'),
  ('危险', '这件事和危险有关。', 'Zhe jian shi he wēi xiǎn youguan.', 'Việc này liên quan đến nguy hiểm.'),
  ('卫生间', '这件事和卫生间有关。', 'Zhe jian shi he wèi shēng jiān youguan.', 'Việc này liên quan đến phòng vệ sinh.'),
  ('西红柿', '这件事和西红柿有关。', 'Zhe jian shi he xī hóng shì youguan.', 'Việc này liên quan đến cà chua.'),
  ('香', '这件事和香有关。', 'Zhe jian shi he xiāng youguan.', 'Việc này liên quan đến thơm.'),
  ('醒', '这件事和醒有关。', 'Zhe jian shi he xǐng youguan.', 'Việc này liên quan đến tỉnh.'),
  ('辛苦', '这件事和辛苦有关。', 'Zhe jian shi he xīn kǔ youguan.', 'Việc này liên quan đến vất vả.'),
  ('详细', '这件事和详细有关。', 'Zhe jian shi he xiáng xì youguan.', 'Việc này liên quan đến tỉ mỉ.'),
  ('许多', '这件事和许多有关。', 'Zhe jian shi he xǔ duō youguan.', 'Việc này liên quan đến rất nhiều.'),
  ('行', '这件事和行有关。', 'Zhe jian shi he xíng youguan.', 'Việc này liên quan đến được.'),
  ('羡慕', '这件事和羡慕有关。', 'Zhe jian shi he xiàn mù youguan.', 'Việc này liên quan đến ngưỡng mộ.'),
  ('笑话', '这件事和笑话有关。', 'Zhe jian shi he xiào huà youguan.', 'Việc này liên quan đến truyện cười.'),
  ('相同', '这件事和相同有关。', 'Zhe jian shi he xiāng tóng youguan.', 'Việc này liên quan đến giống nhau.'),
  ('相反', '这件事和相反有关。', 'Zhe jian shi he xiāng fǎn youguan.', 'Việc này liên quan đến ngược lại.'),
  ('现金', '这件事和现金有关。', 'Zhe jian shi he xiàn jīn youguan.', 'Việc này liên quan đến tiền mặt.'),
  ('消息', '这件事和消息有关。', 'Zhe jian shi he xiāo xi youguan.', 'Việc này liên quan đến thông tin, tin.'),
  ('橡皮', '这件事和橡皮有关。', 'Zhe jian shi he xiàng pí youguan.', 'Việc này liên quan đến cục tẩy.'),
  ('效果', '这件事和效果有关。', 'Zhe jian shi he xiào guǒ youguan.', 'Việc này liên quan đến hiệu quả.'),
  ('性格', '这件事和性格有关。', 'Zhe jian shi he xìng gé youguan.', 'Việc này liên quan đến tính cách.'),
  ('性别', '这件事和性别有关。', 'Zhe jian shi he xìng bié youguan.', 'Việc này liên quan đến giới tính.'),
  ('心情', '这件事和心情有关。', 'Zhe jian shi he xīn qíng youguan.', 'Việc này liên quan đến tâm trạng.'),
  ('幸福', '这件事和幸福有关。', 'Zhe jian shi he xìng fú youguan.', 'Việc này liên quan đến hạnh phúc.'),
  ('小说', '这件事和小说有关。', 'Zhe jian shi he xiǎo shuō youguan.', 'Việc này liên quan đến tiểu thuyết.'),
  ('小吃', '这件事和小吃有关。', 'Zhe jian shi he xiǎo chī youguan.', 'Việc này liên quan đến đồ ăn vặt.'),
  ('小伙子', '这件事和小伙子有关。', 'Zhe jian shi he xiǎo huǒ zi youguan.', 'Việc này liên quan đến anh chàng.'),
  ('学期', '这件事和学期有关。', 'Zhe jian shi he xué qī youguan.', 'Việc này liên quan đến học kì.'),
  ('响', '这件事和响有关。', 'Zhe jian shi he xiǎng youguan.', 'Việc này liên quan đến kêu.'),
  ('咸', '这件事和咸有关。', 'Zhe jian shi he xián youguan.', 'Việc này liên quan đến mặn.'),
  ('吸引', '这件事和吸引有关。', 'Zhe jian shi he xī yǐn youguan.', 'Việc này liên quan đến thu hút.'),
  ('兴奋', '这件事和兴奋有关。', 'Zhe jian shi he xīng fèn youguan.', 'Việc này liên quan đến hưng phấn, hứng khởi.'),
  ('修理', '这件事和修理有关。', 'Zhe jian shi he xiū lǐ youguan.', 'Việc này liên quan đến sửa chữa.'),
  ('信息', '这件事和信息有关。', 'Zhe jian shi he xìn xī youguan.', 'Việc này liên quan đến thông tin.'),
  ('信心', '这件事和信心有关。', 'Zhe jian shi he xìn xīn youguan.', 'Việc này liên quan đến niềm tin.'),
  ('信封', '这件事和信封有关。', 'Zhe jian shi he xìn fēng youguan.', 'Việc này liên quan đến bức thư.'),
  ('压力', '这件事和压力有关。', 'Zhe jian shi he yā lì youguan.', 'Việc này liên quan đến áp lực.'),
  ('预习', '这件事和预习有关。', 'Zhe jian shi he yù xí youguan.', 'Việc này liên quan đến chuẩn bị trước.'),
  ('页', '这件事和页有关。', 'Zhe jian shi he yè youguan.', 'Việc này liên quan đến trang mạng.'),
  ('阳光', '这件事和阳光有关。', 'Zhe jian shi he yáng guāng youguan.', 'Việc này liên quan đến ánh nắng.'),
  ('阅读', '这件事和阅读有关。', 'Zhe jian shi he yuè dú youguan.', 'Việc này liên quan đến đọc hiểu.'),
  ('钥匙', '这件事和钥匙有关。', 'Zhe jian shi he yào shi youguan.', 'Việc này liên quan đến chìa khóa.'),
  ('邮局', '这件事和邮局有关。', 'Zhe jian shi he yóu jú youguan.', 'Việc này liên quan đến bưu điện.'),
  ('邀请', '这件事和邀请有关。', 'Zhe jian shi he yāo qǐng youguan.', 'Việc này liên quan đến mời.'),
  ('赢', '这件事和赢有关。', 'Zhe jian shi he yíng youguan.', 'Việc này liên quan đến thắng.'),
  ('语言', '这件事和语言有关。', 'Zhe jian shi he yǔ yán youguan.', 'Việc này liên quan đến ngôn ngữ.'),
  ('语法', '这件事和语法有关。', 'Zhe jian shi he yǔ fǎ youguan.', 'Việc này liên quan đến ngữ pháp.'),
  ('要是', '这件事和要是有关。', 'Zhe jian shi he yào shì youguan.', 'Việc này liên quan đến nếu.'),
  ('艺术', '这件事和艺术有关。', 'Zhe jian shi he yì shù youguan.', 'Việc này liên quan đến nghệ thuật.'),
  ('羽毛球', '这件事和羽毛球有关。', 'Zhe jian shi he yǔ máo qiú youguan.', 'Việc này liên quan đến cầu lông.'),
  ('约会', '这件事和约会有关。', 'Zhe jian shi he yuē huì youguan.', 'Việc này liên quan đến hẹn, cuộc hẹn.'),
  ('研究', '这件事和研究有关。', 'Zhe jian shi he yán jiū youguan.', 'Việc này liên quan đến nghiên cứu.'),
  ('眼镜', '这件事和眼镜有关。', 'Zhe jian shi he yǎn jìng youguan.', 'Việc này liên quan đến kính mắt.'),
  ('盐', '这件事和盐有关。', 'Zhe jian shi he yán youguan.', 'Việc này liên quan đến muối.'),
  ('由于', '这件事和由于有关。', 'Zhe jian shi he yóu yú youguan.', 'Việc này liên quan đến do.'),
  ('由', '这件事和由有关。', 'Zhe jian shi he yóu youguan.', 'Việc này liên quan đến do.'),
  ('牙膏', '这件事和牙膏有关。', 'Zhe jian shi he yá gāo youguan.', 'Việc này liên quan đến kem đánh răng.'),
  ('演员', '这件事和演员有关。', 'Zhe jian shi he yǎn yuán youguan.', 'Việc này liên quan đến diễn viên.'),
  ('演出', '这件事和演出有关。', 'Zhe jian shi he yǎn chū youguan.', 'Việc này liên quan đến buổi diễn.'),
  ('永远', '这件事和永远有关。', 'Zhe jian shi he yǒng yuǎn youguan.', 'Việc này liên quan đến mãi mãi.'),
  ('样子', '这件事和样子有关。', 'Zhe jian shi he yàng zi youguan.', 'Việc này liên quan đến dáng ngoài,bề ngoài.'),
  ('有趣', '这件事和有趣有关。', 'Zhe jian shi he yǒu qù youguan.', 'Việc này liên quan đến hứng thú.'),
  ('意见', '这件事和意见有关。', 'Zhe jian shi he yì jiàn youguan.', 'Việc này liên quan đến ý kiến.'),
  ('愉快', '这件事和愉快有关。', 'Zhe jian shi he yú kuài youguan.', 'Việc này liên quan đến vui vẻ.'),
  ('引起', '这件事和引起有关。', 'Zhe jian shi he yǐn qǐ youguan.', 'Việc này liên quan đến dẫn đến, gây ra.'),
  ('应聘', '这件事和应聘有关。', 'Zhe jian shi he yìng pìn youguan.', 'Việc này liên quan đến ứng tuyển.'),
  ('幽默', '这件事和幽默有关。', 'Zhe jian shi he yōu mò youguan.', 'Việc này liên quan đến hài hước.'),
  ('尤其', '这件事和尤其有关。', 'Zhe jian shi he yóu qí youguan.', 'Việc này liên quan đến đặc biệt là.'),
  ('因此', '这件事和因此有关。', 'Zhe jian shi he yīn cǐ youguan.', 'Việc này liên quan đến cho nên.'),
  ('呀', '这件事和呀有关。', 'Zhe jian shi he yā youguan.', 'Việc này liên quan đến a.'),
  ('叶子', '这件事和叶子有关。', 'Zhe jian shi he yè zi youguan.', 'Việc này liên quan đến chiếc lá.'),
  ('友谊', '这件事和友谊有关。', 'Zhe jian shi he yǒu yì youguan.', 'Việc này liên quan đến hữu nghị.'),
  ('友好', '这件事和友好有关。', 'Zhe jian shi he yǒu hǎo youguan.', 'Việc này liên quan đến hữu hảo.'),
  ('原谅', '这件事和原谅有关。', 'Zhe jian shi he yuán liàng youguan.', 'Việc này liên quan đến tha thứ.'),
  ('原来', '这件事和原来有关。', 'Zhe jian shi he yuán lái youguan.', 'Việc này liên quan đến hóa ra, vốn, cũ.'),
  ('原因', '这件事和原因有关。', 'Zhe jian shi he yuán yīn youguan.', 'Việc này liên quan đến nguyên nhân.'),
  ('印象', '这件事和印象有关。', 'Zhe jian shi he yìn xiàng youguan.', 'Việc này liên quan đến ấn tượng.'),
  ('勇敢', '这件事和勇敢有关。', 'Zhe jian shi he yǒng gǎn youguan.', 'Việc này liên quan đến dũng cảm.'),
  ('养成', '这件事和养成有关。', 'Zhe jian shi he yǎng chéng youguan.', 'Việc này liên quan đến nuôi dưỡng, hình thành.'),
  ('允许', '这件事和允许有关。', 'Zhe jian shi he yǔn xǔ youguan.', 'Việc này liên quan đến cho phép.'),
  ('优秀', '这件事和优秀有关。', 'Zhe jian shi he yōu xiù youguan.', 'Việc này liên quan đến ưu tú.'),
  ('优点', '这件事和优点有关。', 'Zhe jian shi he yōu diǎn youguan.', 'Việc này liên quan đến ưu điểm.'),
  ('以为', '这件事和以为有关。', 'Zhe jian shi he yǐ wéi youguan.', 'Việc này liên quan đến tưởng rằng.'),
  ('以', '这件事和以有关。', 'Zhe jian shi he yǐ youguan.', 'Việc này liên quan đến lấy.'),
  ('亚洲', '这件事和亚洲有关。', 'Zhe jian shi he yà zhōu youguan.', 'Việc này liên quan đến châu Á.'),
  ('云', '这件事和云有关。', 'Zhe jian shi he yún youguan.', 'Việc này liên quan đến mây.'),
  ('于是', '这件事和于是有关。', 'Zhe jian shi he yú shì youguan.', 'Việc này liên quan đến thế là.'),
  ('也许', '这件事和也许有关。', 'Zhe jian shi he yě xǔ youguan.', 'Việc này liên quan đến có lẽ.'),
  ('严重', '这件事和严重有关。', 'Zhe jian shi he yán zhòng youguan.', 'Việc này liên quan đến nghiêm trọng.'),
  ('严格', '这件事和严格有关。', 'Zhe jian shi he yán gé youguan.', 'Việc này liên quan đến nghiêm khắc.'),
  ('与', '这件事和与有关。', 'Zhe jian shi he yǔ youguan.', 'Việc này liên quan đến và.'),
  ('一切', '这件事和一切有关。', 'Zhe jian shi he yī qiè youguan.', 'Việc này liên quan đến tất cả.'),
  ('杂志', '这件事和杂志有关。', 'Zhe jian shi he zá zhì youguan.', 'Việc này liên quan đến tạp chí.'),
  ('重视', '这件事和重视有关。', 'Zhe jian shi he zhòng shì youguan.', 'Việc này liên quan đến coi trọng.'),
  ('重点', '这件事和重点有关。', 'Zhe jian shi he zhòng diǎn youguan.', 'Việc này liên quan đến trọng điểm.'),
  ('重', '这件事和重有关。', 'Zhe jian shi he zhòng youguan.', 'Việc này liên quan đến nặng.'),
  ('转', '这件事和转有关。', 'Zhe jian shi he zhuǎn youguan.', 'Việc này liên quan đến chuyển.'),
  ('赚', '这件事和赚有关。', 'Zhe jian shi he zhuàn youguan.', 'Việc này liên quan đến kiếm.'),
  ('质量', '这件事和质量有关。', 'Zhe jian shi he zhì liàng youguan.', 'Việc này liên quan đến chất lượng.'),
  ('责任', '这件事和责任有关。', 'Zhe jian shi he zé rèn youguan.', 'Việc này liên quan đến trách nhiệm.'),
  ('证明', '这件事和证明有关。', 'Zhe jian shi he zhèng míng youguan.', 'Việc này liên quan đến chứng minh.'),
  ('著名', '这件事和著名有关。', 'Zhe jian shi he zhù míng youguan.', 'Việc này liên quan đến nổi tiếng.'),
  ('至少', '这件事和至少有关。', 'Zhe jian shi he zhì shǎo youguan.', 'Việc này liên quan đến chí ít.'),
  ('自然', '这件事和自然有关。', 'Zhe jian shi he zì rán youguan.', 'Việc này liên quan đến tự nhiên.'),
  ('自信', '这件事和自信有关。', 'Zhe jian shi he zì xìn youguan.', 'Việc này liên quan đến tự tin.'),
  ('脏', '这件事和脏有关。', 'Zhe jian shi he zāng youguan.', 'Việc này liên quan đến bẩn.'),
  ('职业', '这件事和职业有关。', 'Zhe jian shi he zhí yè youguan.', 'Việc này liên quan đến nghề nghiệp.'),
  ('租', '这件事和租有关。', 'Zhe jian shi he zū youguan.', 'Việc này liên quan đến thuê.'),
  ('祝贺', '这件事和祝贺有关。', 'Zhe jian shi he zhù hè youguan.', 'Việc này liên quan đến chúc mừng.'),
  ('知识', '这件事和知识有关。', 'Zhe jian shi he zhī shí youguan.', 'Việc này liên quan đến tri thức, kiến thức.'),
  ('真正', '这件事和真正有关。', 'Zhe jian shi he zhēn zhèng youguan.', 'Việc này liên quan đến thật.'),
  ('直接', '这件事和直接有关。', 'Zhe jian shi he zhí jiē youguan.', 'Việc này liên quan đến trực tiếp.'),
  ('照', '这件事和照有关。', 'Zhe jian shi he zhào youguan.', 'Việc này liên quan đến chiếu.'),
  ('正确', '这件事和正确有关。', 'Zhe jian shi he zhèng què youguan.', 'Việc này liên quan đến chính xác.'),
  ('正式', '这件事和正式有关。', 'Zhe jian shi he zhèng shì youguan.', 'Việc này liên quan đến chính thức.'),
  ('正常', '这件事和正常有关。', 'Zhe jian shi he zhèng cháng youguan.', 'Việc này liên quan đến bình thường.'),
  ('正好', '这件事和正好有关。', 'Zhe jian shi he zhèng hǎo youguan.', 'Việc này liên quan đến vừa hay.'),
  ('植物', '这件事和植物有关。', 'Zhe jian shi he zhí wù youguan.', 'Việc này liên quan đến thực vật.'),
  ('最好', '你最好早点休息。', 'Ni zuihao zaodian xiuxi.', 'Việc này liên quan đến tốt nhất.'),
  ('暂时', '这个问题暂时没有办法解决。', 'Zhe ge wenti zanshi mei you banfa jiejue.', 'Việc này liên quan đến tạm thời.'),
  ('整理', '我周末整理房间。', 'Wo zhoumo zhengli fangjian.', 'Việc này liên quan đến chỉnh sửa.'),
  ('支持', '我支持你的决定。', 'Wo zhichi ni de jueding.', 'Việc này liên quan đến ủng hộ.'),
  ('指', '这件事和指有关。', 'Zhe jian shi he zhǐ youguan.', 'Việc này liên quan đến chỉ.'),
  ('招聘', '这家公司正在招聘老师。', 'Zhe jia gongsi zhengzai zhaopin laoshi.', 'Việc này liên quan đến tuyển dụng.'),
  ('总结', '这件事和总结有关。', 'Zhe jian shi he zǒng jié youguan.', 'Việc này liên quan đến tổng kết.'),
  ('座位', '这个座位有人吗？', 'Zhe ge zuowei you ren ma?', 'Việc này liên quan đến chỗ ngồi.'),
  ('座', '这件事和座有关。', 'Zhe jian shi he zuò youguan.', 'Việc này liên quan đến tòa.'),
  ('左右', '会议大约三点左右开始。', 'Huiyi dayue san dian zuoyou kaishi.', 'Việc này liên quan đến khoảng.'),
  ('尊重', '我们应该尊重别人的意见。', 'Women yinggai zunzhong bieren de yijian.', 'Việc này liên quan đến tôn trọng.'),
  ('增加', '运动可以增加身体的力量。', 'Yundong keyi zengjia shenti de liliang.', 'Việc này liên quan đến tăng thêm.'),
  ('咱们', '咱们一起去吃饭吧。', 'Zanmen yiqi qu chifan ba.', 'Việc này liên quan đến chúng ta.'),
  ('周围', '学校周围有很多商店。', 'Xuexiao zhouwei you hen duo shangdian.', 'Việc này liên quan đến xung quanh.'),
  ('只要', '只要努力，就会进步。', 'Zhiyao nuli, jiu hui jinbu.', 'Việc này liên quan đến chỉ cần.'),
  ('只好', '车坏了，我只好走路回家。', 'Che huai le, wo zhihao zoulu huijia.', 'Việc này liên quan đến đành.'),
  ('占线', '我打电话给他，可是一直占线。', 'Wo da dianhua gei ta, keshi yizhi zhanxian.', 'Việc này liên quan đến máy bận.'),
  ('准确', '这个答案很准确。', 'Zhe ge daan hen zhunque.', 'Việc này liên quan đến chính xác.'),
  ('准时', '请大家准时到教室。', 'Qing dajia zhunshi dao jiaoshi.', 'Việc này liên quan đến đúng giờ.'),
  ('值得', '这本书值得一读。', 'Zhe ben shu zhide yi du.', 'Việc này liên quan đến đáng.'),
  ('作者', '这本书的作者很有名。', 'Zhe ben shu de zuozhe hen youming.', 'Việc này liên quan đến tác gia.'),
  ('作用', '运动对健康有很大的作用。', 'Yundong dui jiankang you hen da de zuoyong.', 'Việc này liên quan đến tác dụng.'),
  ('作家', '他想成为一名作家。', 'Ta xiang chengwei yi ming zuojia.', 'Việc này liên quan đến tác gia.'),
  ('仔细', '请仔细看这个表格。', 'Qing zixi kan zhe ge biaoge.', 'Việc này liên quan đến cẩn thận.'),
  ('之', '这件事和之有关。', 'Zhe jian shi he zhī youguan.', 'Việc này liên quan đến chi.'),
  ('主意', '这个主意不错。', 'Zhe ge zhuyi bucuo.', 'Việc này liên quan đến chủ ý.'),
  ('专门', '他专门来帮我。', 'Ta zhuanmen lai bang wo.', 'Việc này liên quan đến chuyên môn.'),
  ('专业', '我的专业是中文。', 'Wo de zhuanye shi Zhongwen.', 'Việc này liên quan đến chuyên ngành.')
),
updated_template_cards as (
  update public.template_cards as card
  set
    example_cn = coalesce(nullif(btrim(card.example_cn), ''), example.example_cn),
    example_pinyin = coalesce(nullif(btrim(card.example_pinyin), ''), example.example_pinyin),
    example_vi = coalesce(nullif(btrim(card.example_vi), ''), example.example_vi)
  from public.template_decks as deck,
    hsk4_example_backfill as example
  where card.template_deck_id = deck.id
    and deck.slug = 'hsk4-co-ban'
    and card.chinese = example.chinese
    and (
      nullif(btrim(card.example_cn), '') is null
      or nullif(btrim(card.example_pinyin), '') is null
      or nullif(btrim(card.example_vi), '') is null
    )
  returning card.id
)
update public.cards as card
set
  example_cn = coalesce(nullif(btrim(card.example_cn), ''), example.example_cn),
  example_pinyin = coalesce(nullif(btrim(card.example_pinyin), ''), example.example_pinyin),
  example_vi = coalesce(nullif(btrim(card.example_vi), ''), example.example_vi)
from public.decks as deck,
  hsk4_example_backfill as example
where card.deck_id = deck.id
  and card.user_id = deck.user_id
  and (
    deck.source_template_slug = 'hsk4-co-ban'
    or (deck.source_template_slug is null and deck.name = 'HSK4 cơ bản')
  )
  and card.chinese = example.chinese
  and (
    nullif(btrim(card.example_cn), '') is null
    or nullif(btrim(card.example_pinyin), '') is null
    or nullif(btrim(card.example_vi), '') is null
  );
