-- Replace generic HSK3 examples with contextual, unique examples.
-- Template HSK3 is refreshed. User cards are updated only when the old generic
-- placeholder is still present or the example is blank.
with hsk3_context_examples (
  chinese,
  example_cn,
  example_pinyin,
  example_vi
) as (
  values
    ('阿姨', '阿姨今天来我家吃午饭。', 'Ayi jintian lai wo jia chi wufan.', 'Dì hôm nay đến nhà tôi ăn trưa.'),
    ('啊', '啊，原来你也住在这儿。', 'A, yuanlai ni ye zhu zai zher.', 'À, hóa ra bạn cũng sống ở đây.'),
    ('矮', '这张桌子有点矮，写字不太舒服。', 'Zhe zhang zhuozi youdian ai, xiezi bu tai shufu.', 'Cái bàn này hơi thấp, viết chữ không thoải mái lắm.'),
    ('爱好', '我的爱好是下班后练习中文。', 'Wo de aihao shi xiaban hou lianxi Zhongwen.', 'Sở thích của tôi là luyện tiếng Trung sau khi tan làm.'),
    ('安静', '图书馆里很安静，大家都在看书。', 'Tushuguan li hen anjing, dajia dou zai kanshu.', 'Trong thư viện rất yên tĩnh, mọi người đều đang đọc sách.'),
    ('把', '请把你的手机放在包里。', 'Qing ba ni de shouji fang zai bao li.', 'Hãy để điện thoại của bạn vào trong túi.'),
    ('搬', '我们周末要搬到新的房子。', 'Women zhoumo yao ban dao xin de fangzi.', 'Cuối tuần chúng tôi sẽ chuyển đến nhà mới.'),
    ('班', '我们班今天有两个同学生病了。', 'Women ban jintian you liang ge tongxue shengbing le.', 'Lớp chúng tôi hôm nay có hai bạn bị ốm.'),
    ('半', '我每天早上跑半个小时。', 'Wo meitian zaoshang pao ban ge xiaoshi.', 'Mỗi sáng tôi chạy nửa tiếng.'),
    ('办法', '别着急，我们一定能想到办法。', 'Bie zhaoji, women yiding neng xiangdao banfa.', 'Đừng sốt ruột, chúng ta nhất định nghĩ ra cách.'),
    ('办公室', '经理正在办公室里开会。', 'Jingli zhengzai bangongshi li kaihui.', 'Giám đốc đang họp trong văn phòng.'),
    ('帮忙', '你有时间的话，能帮忙搬桌子吗？', 'Ni you shijian de hua, neng bangmang ban zhuozi ma?', 'Nếu bạn có thời gian, có thể giúp chuyển bàn không?'),
    ('包', '我把护照放在这个黑色的包里。', 'Wo ba huzhao fang zai zhe ge heise de bao li.', 'Tôi để hộ chiếu trong chiếc túi màu đen này.'),
    ('饱', '我已经吃饱了，不想再吃蛋糕。', 'Wo yijing chi bao le, bu xiang zai chi dangao.', 'Tôi đã ăn no rồi, không muốn ăn thêm bánh kem nữa.'),
    ('北方', '冬天北方比南方冷得多。', 'Dongtian beifang bi nanfang leng de duo.', 'Mùa đông miền bắc lạnh hơn miền nam nhiều.'),
    ('被', '我的伞被同事拿走了。', 'Wo de san bei tongshi nazou le.', 'Cái ô của tôi bị đồng nghiệp lấy đi rồi.'),
    ('鼻子', '感冒以后，他的鼻子一直不舒服。', 'Ganmao yihou, ta de bizi yizhi bu shufu.', 'Sau khi bị cảm, mũi của anh ấy cứ khó chịu.'),
    ('比较', '这家宾馆比较安静，适合休息。', 'Zhe jia binguan bijiao anjing, shihe xiuxi.', 'Khách sạn này khá yên tĩnh, thích hợp để nghỉ ngơi.'),
    ('比赛', '今晚的比赛八点开始。', 'Jinwan de bisai ba dian kaishi.', 'Trận đấu tối nay bắt đầu lúc tám giờ.'),
    ('必须', '明天出差，你必须带上护照。', 'Mingtian chuchai, ni bixu dai shang huzhao.', 'Ngày mai đi công tác, bạn bắt buộc phải mang hộ chiếu.'),
    ('变化', '这座城市这几年变化很大。', 'Zhe zuo chengshi zhe ji nian bianhua hen da.', 'Thành phố này mấy năm gần đây thay đổi rất nhiều.'),
    ('表示', '他点头表示同意我的想法。', 'Ta diantou biaoshi tongyi wo de xiangfa.', 'Anh ấy gật đầu tỏ ý đồng ý với suy nghĩ của tôi.'),
    ('表演', '孩子们晚上要在学校表演节目。', 'Haizimen wanshang yao zai xuexiao biaoyan jiemu.', 'Bọn trẻ tối nay sẽ biểu diễn tiết mục ở trường.'),
    ('别人', '不要总是拿自己和别人比较。', 'Bu yao zongshi na ziji he bieren bijiao.', 'Đừng lúc nào cũng so sánh bản thân với người khác.'),
    ('宾馆', '我们在火车站附近订了一家宾馆。', 'Women zai huochezhan fujin ding le yi jia binguan.', 'Chúng tôi đặt một khách sạn gần ga tàu.'),
    ('冰箱', '牛奶在冰箱里，想喝就拿。', 'Niunai zai bingxiang li, xiang he jiu na.', 'Sữa ở trong tủ lạnh, muốn uống thì lấy.'),
    ('才', '他晚上十一点才完成作业。', 'Ta wanshang shiyi dian cai wancheng zuoye.', 'Anh ấy đến mười một giờ tối mới làm xong bài tập.'),
    ('菜单', '服务员，请给我们看一下菜单。', 'Fuwuyuan, qing gei women kan yixia caidan.', 'Nhân viên ơi, cho chúng tôi xem thực đơn một chút.'),
    ('参加', '我想参加下周的中文比赛。', 'Wo xiang canjia xia zhou de Zhongwen bisai.', 'Tôi muốn tham gia cuộc thi tiếng Trung tuần sau.'),
    ('草', '公园里的草刚下过雨，很绿。', 'Gongyuan li de cao gang xiaguo yu, hen lu.', 'Cỏ trong công viên vừa được mưa tưới nên rất xanh.'),
    ('层', '我的办公室在这栋楼的十五层。', 'Wo de bangongshi zai zhe dong lou de shiwu ceng.', 'Văn phòng của tôi ở tầng mười lăm của tòa nhà này.'),
    ('差', '这次考试我只差两分就及格了。', 'Zhe ci kaoshi wo zhi cha liang fen jiu jige le.', 'Kỳ thi này tôi chỉ thiếu hai điểm là đạt.'),
    ('超市', '下班后我去超市买水果。', 'Xiaban hou wo qu chaoshi mai shuiguo.', 'Sau khi tan làm tôi đi siêu thị mua trái cây.'),
    ('衬衫', '这件白衬衫适合明天的会议。', 'Zhe jian bai chenshan shihe mingtian de huiyi.', 'Chiếc áo sơ mi trắng này hợp với cuộc họp ngày mai.'),
    ('成绩', '她这次考试成绩提高了很多。', 'Ta zhe ci kaoshi chengji tigao le henduo.', 'Điểm thi lần này của cô ấy đã tăng lên rất nhiều.'),
    ('城市', '我喜欢这个城市的生活节奏。', 'Wo xihuan zhe ge chengshi de shenghuo jiezou.', 'Tôi thích nhịp sống của thành phố này.'),
    ('迟到', '地铁坏了，所以我上班迟到了。', 'Ditie huai le, suoyi wo shangban chidao le.', 'Tàu điện ngầm hỏng nên tôi đi làm muộn.'),
    ('除了', '除了咖啡，我还点了一块蛋糕。', 'Chule kafei, wo hai dian le yi kuai dangao.', 'Ngoài cà phê, tôi còn gọi một miếng bánh kem.'),
    ('船', '我们坐船去河对面的公园。', 'Women zuo chuan qu he duimian de gongyuan.', 'Chúng tôi đi thuyền đến công viên bên kia sông.'),
    ('春', '春天到了，花园里的花都开了。', 'Chuntian dao le, huayuan li de hua dou kai le.', 'Mùa xuân đến rồi, hoa trong vườn đều nở.'),
    ('词语', '这篇课文里有很多新的词语。', 'Zhe pian kewen li you henduo xin de ciyu.', 'Trong bài khóa này có rất nhiều từ ngữ mới.'),
    ('聪明', '这个孩子很聪明，问题一听就明白。', 'Zhe ge haizi hen congming, wenti yi ting jiu mingbai.', 'Đứa trẻ này rất thông minh, nghe vấn đề là hiểu ngay.'),
    ('打扫', '客人来以前，我们先打扫客厅。', 'Keren lai yiqian, women xian dasao keting.', 'Trước khi khách đến, chúng tôi dọn phòng khách trước.'),
    ('打算', '你毕业以后打算做什么工作？', 'Ni biye yihou dasuan zuo shenme gongzuo?', 'Sau khi tốt nghiệp bạn dự định làm công việc gì?'),
    ('带', '明天爬山，记得带一瓶水。', 'Mingtian pashan, jide dai yi ping shui.', 'Ngày mai leo núi, nhớ mang một chai nước.'),
    ('担心', '孩子还没回家，妈妈很担心。', 'Haizi hai mei huijia, mama hen danxin.', 'Con vẫn chưa về nhà nên mẹ rất lo.'),
    ('蛋糕', '生日会上，大家一起吃蛋糕。', 'Shengri hui shang, dajia yiqi chi dangao.', 'Trong buổi sinh nhật, mọi người cùng ăn bánh kem.'),
    ('当然', '你需要帮助的时候，我当然会来。', 'Ni xuyao bangzhu de shihou, wo dangran hui lai.', 'Khi bạn cần giúp đỡ, tất nhiên tôi sẽ đến.'),
    ('地', '他认真地检查了每一个答案。', 'Ta renzhen de jiancha le mei yi ge daan.', 'Anh ấy kiểm tra từng đáp án một cách nghiêm túc.'),
    ('灯', '睡觉前请把客厅的灯关掉。', 'Shuijiao qian qing ba keting de deng guan diao.', 'Trước khi ngủ hãy tắt đèn phòng khách.'),
    ('低', '这家店的价格比附近的低。', 'Zhe jia dian de jiage bi fujin de di.', 'Giá của cửa hàng này thấp hơn chỗ gần đây.'),
    ('地方', '这个地方很安静，适合学习。', 'Zhe ge difang hen anjing, shihe xuexi.', 'Nơi này rất yên tĩnh, thích hợp để học.'),
    ('地铁', '坐地铁去公司比开车方便。', 'Zuo ditie qu gongsi bi kaiche fangbian.', 'Đi tàu điện ngầm đến công ty tiện hơn lái xe.'),
    ('地图', '没有网络时，我会先看地图。', 'Meiyou wangluo shi, wo hui xian kan ditu.', 'Khi không có mạng, tôi sẽ xem bản đồ trước.'),
    ('电梯', '电梯坏了，我们只好走楼梯。', 'Dianti huai le, women zhihao zou louti.', 'Thang máy hỏng rồi, chúng tôi đành đi cầu thang.'),
    ('电子邮件', '我已经把资料发到你的电子邮件了。', 'Wo yijing ba ziliao fa dao ni de dianzi youjian le.', 'Tôi đã gửi tài liệu vào email của bạn rồi.'),
    ('东', '学校东边有一家小咖啡店。', 'Xuexiao dongbian you yi jia xiao kafei dian.', 'Phía đông trường học có một quán cà phê nhỏ.'),
    ('冬', '冬天我喜欢喝热茶。', 'Dongtian wo xihuan he re cha.', 'Mùa đông tôi thích uống trà nóng.'),
    ('动物', '孩子们周末去公园看动物。', 'Haizimen zhoumo qu gongyuan kan dongwu.', 'Bọn trẻ cuối tuần đi công viên xem động vật.'),
    ('短', '这条裤子有点短，我想换一条。', 'Zhe tiao kuzi youdian duan, wo xiang huan yi tiao.', 'Cái quần này hơi ngắn, tôi muốn đổi cái khác.'),
    ('段', '请你再读一遍第一段。', 'Qing ni zai du yi bian di yi duan.', 'Bạn hãy đọc lại đoạn thứ nhất một lần nữa.'),
    ('锻炼', '爷爷每天早上在公园锻炼。', 'Yeye meitian zaoshang zai gongyuan duanlian.', 'Ông nội mỗi sáng tập thể dục trong công viên.'),
    ('多么', '你看，今晚的月亮多么漂亮！', 'Ni kan, jinwan de yueliang duome piaoliang!', 'Bạn nhìn xem, trăng tối nay đẹp biết bao!'),
    ('饿', '开了一上午会，我已经很饿了。', 'Kai le yi shangwu hui, wo yijing hen e le.', 'Họp cả buổi sáng, tôi đã rất đói rồi.'),
    ('耳朵', '他的耳朵有点疼，想去医院检查。', 'Ta de erduo youdian teng, xiang qu yiyuan jiancha.', 'Tai anh ấy hơi đau, muốn đi bệnh viện kiểm tra.'),
    ('发', '请把会议地址发给大家。', 'Qing ba huiyi dizhi fa gei dajia.', 'Hãy gửi địa chỉ cuộc họp cho mọi người.'),
    ('发现', '我发现这家店的面包很好吃。', 'Wo faxian zhe jia dian de mianbao hen haochi.', 'Tôi phát hiện bánh mì của tiệm này rất ngon.'),
    ('方便', '这里离地铁站很近，生活很方便。', 'Zheli li ditie zhan hen jin, shenghuo hen fangbian.', 'Ở đây gần ga tàu điện ngầm nên sinh hoạt rất tiện.'),
    ('放', '请把行李箱放在门口。', 'Qing ba xinglixiang fang zai menkou.', 'Hãy đặt vali ở cửa ra vào.'),
    ('放心', '你放心，我会照顾好奶奶。', 'Ni fangxin, wo hui zhaogu hao nainai.', 'Bạn yên tâm, tôi sẽ chăm sóc tốt bà nội.'),
    ('分', '电影还有五分就开始了。', 'Dianying haiyou wu fen jiu kaishi le.', 'Bộ phim còn năm phút nữa là bắt đầu.'),
    ('附近', '公司附近新开了一家超市。', 'Gongsi fujin xin kai le yi jia chaoshi.', 'Gần công ty mới mở một siêu thị.'),
    ('复习', '考试以前，我每天晚上复习两个小时。', 'Kaoshi yiqian, wo meitian wanshang fuxi liang ge xiaoshi.', 'Trước kỳ thi, mỗi tối tôi ôn tập hai tiếng.'),
    ('干净', '这家宾馆的房间很干净。', 'Zhe jia binguan de fangjian hen ganjing.', 'Phòng của khách sạn này rất sạch sẽ.'),
    ('感冒', '天气变冷了，你别感冒。', 'Tianqi bian leng le, ni bie ganmao.', 'Trời lạnh hơn rồi, bạn đừng để bị cảm.'),
    ('感兴趣', '我对中国历史很感兴趣。', 'Wo dui Zhongguo lishi hen ganxingqu.', 'Tôi rất có hứng thú với lịch sử Trung Quốc.'),
    ('刚才', '刚才是谁给我打电话？', 'Gangcai shi shei gei wo da dianhua?', 'Vừa nãy ai gọi điện cho tôi vậy?'),
    ('个子', '他个子很高，站在人群里很好找。', 'Ta gezi hen gao, zhan zai renqun li hen hao zhao.', 'Anh ấy vóc dáng rất cao, đứng trong đám người rất dễ tìm.'),
    ('根据', '根据地图，银行就在前面。', 'Genju ditu, yinhang jiu zai qianmian.', 'Dựa theo bản đồ, ngân hàng ở ngay phía trước.'),
    ('跟', '下课后，我跟同学一起去图书馆。', 'Xiake hou, wo gen tongxue yiqi qu tushuguan.', 'Sau giờ học, tôi đi thư viện cùng bạn học.'),
    ('更', '慢慢听会让发音更清楚。', 'Manman ting hui rang fayin geng qingchu.', 'Nghe chậm sẽ làm phát âm rõ hơn.'),
    ('公园', '周末我们在公园散步。', 'Zhoumo women zai gongyuan sanbu.', 'Cuối tuần chúng tôi đi dạo trong công viên.'),
    ('故事', '奶奶喜欢给我讲小时候的故事。', 'Nainai xihuan gei wo jiang xiaoshihou de gushi.', 'Bà nội thích kể cho tôi nghe chuyện hồi nhỏ.'),
    ('刮风', '外面刮风了，记得关窗户。', 'Waimian gua feng le, jide guan chuanghu.', 'Bên ngoài có gió rồi, nhớ đóng cửa sổ.'),
    ('关', '离开办公室前，请关电脑。', 'Likai bangongshi qian, qing guan diannao.', 'Trước khi rời văn phòng, hãy tắt máy tính.'),
    ('关系', '我和邻居的关系很好。', 'Wo he linju de guanxi hen hao.', 'Quan hệ giữa tôi và hàng xóm rất tốt.'),
    ('关心', '老师很关心每个学生的进步。', 'Laoshi hen guanxin mei ge xuesheng de jinbu.', 'Giáo viên rất quan tâm đến tiến bộ của từng học sinh.'),
    ('关于', '这本书是关于中国文化的。', 'Zhe ben shu shi guanyu Zhongguo wenhua de.', 'Cuốn sách này nói về văn hóa Trung Quốc.'),
    ('国家', '每个国家都有自己的文化。', 'Mei ge guojia dou you ziji de wenhua.', 'Mỗi quốc gia đều có văn hóa riêng của mình.'),
    ('果汁', '我不喝啤酒，只要一杯果汁。', 'Wo bu he pijiu, zhi yao yi bei guozhi.', 'Tôi không uống bia, chỉ cần một ly nước ép trái cây.'),
    ('过去', '请往前走，然后从银行门口过去。', 'Qing wang qian zou, ranhou cong yinhang menkou guoqu.', 'Hãy đi về phía trước, rồi đi qua cửa ngân hàng.'),
    ('还是', '你想坐地铁还是坐出租车？', 'Ni xiang zuo ditie haishi zuo chuzuche?', 'Bạn muốn đi tàu điện ngầm hay đi taxi?'),
    ('害怕', '第一次上台表演时，我有点害怕。', 'Di yi ci shangtai biaoyan shi, wo youdian haipa.', 'Lần đầu lên sân khấu biểu diễn, tôi hơi sợ.'),
    ('河', '这条河旁边有很多高楼。', 'Zhe tiao he pangbian you henduo gaolou.', 'Bên cạnh con sông này có rất nhiều tòa nhà cao.'),
    ('黑板', '老师把新词写在黑板上。', 'Laoshi ba xinci xie zai heiban shang.', 'Giáo viên viết từ mới lên bảng.'),
    ('护照', '去机场以前，我检查了护照和机票。', 'Qu jichang yiqian, wo jiancha le huzhao he jipiao.', 'Trước khi ra sân bay, tôi kiểm tra hộ chiếu và vé máy bay.'),
    ('花', '她在花园里种了很多花。', 'Ta zai huayuan li zhong le henduo hua.', 'Cô ấy trồng rất nhiều hoa trong vườn.'),
    ('花园', '饭后我们在花园里聊天。', 'Fan hou women zai huayuan li liaotian.', 'Sau bữa ăn chúng tôi trò chuyện trong vườn hoa.'),
    ('画', '妹妹喜欢画学校旁边的河。', 'Meimei xihuan hua xuexiao pangbian de he.', 'Em gái thích vẽ con sông bên cạnh trường.'),
    ('坏', '我的照相机坏了，不能拍照片。', 'Wo de zhaoxiangji huai le, bu neng pai zhaopian.', 'Máy ảnh của tôi hỏng rồi, không thể chụp ảnh.'),
    ('欢迎', '欢迎你下周来我家做客。', 'Huanying ni xia zhou lai wo jia zuoke.', 'Hoan nghênh bạn tuần sau đến nhà tôi làm khách.'),
    ('环境', '学校的环境很安静，适合学习。', 'Xuexiao de huanjing hen anjing, shihe xuexi.', 'Môi trường của trường rất yên tĩnh, thích hợp học tập.'),
    ('换', '这双皮鞋太小了，我想换一双。', 'Zhe shuang pixie tai xiao le, wo xiang huan yi shuang.', 'Đôi giày da này nhỏ quá, tôi muốn đổi đôi khác.'),
    ('黄', '秋天到了，树叶慢慢变黄了。', 'Qiutian dao le, shuye manman bian huang le.', 'Mùa thu đến rồi, lá cây dần chuyển vàng.'),
    ('会议', '下午三点有一个重要会议。', 'Xiawu san dian you yi ge zhongyao huiyi.', 'Ba giờ chiều có một cuộc họp quan trọng.'),
    ('或者', '你可以今天来，或者明天上午来。', 'Ni keyi jintian lai, huozhe mingtian shangwu lai.', 'Bạn có thể đến hôm nay hoặc sáng mai đến.'),
    ('机会', '这次比赛给了我一个练习的机会。', 'Zhe ci bisai gei le wo yi ge lianxi de jihui.', 'Cuộc thi lần này cho tôi một cơ hội luyện tập.'),
    ('极', '今天的天气好极了，我们去公园吧。', 'Jintian de tianqi hao ji le, women qu gongyuan ba.', 'Thời tiết hôm nay cực kỳ tốt, chúng ta đi công viên nhé.'),
    ('记得', '出门前记得带钥匙。', 'Chumen qian jide dai yaoshi.', 'Trước khi ra ngoài nhớ mang chìa khóa.'),
    ('季节', '我最喜欢的季节是春天。', 'Wo zui xihuan de jijie shi chuntian.', 'Mùa tôi thích nhất là mùa xuân.'),
    ('检查', '医生给我的耳朵做了检查。', 'Yisheng gei wo de erduo zuo le jiancha.', 'Bác sĩ đã kiểm tra tai cho tôi.'),
    ('简单', '这个问题很简单，大家都会回答。', 'Zhe ge wenti hen jiandan, dajia dou hui huida.', 'Vấn đề này rất đơn giản, mọi người đều biết trả lời.'),
    ('见面', '我们明天在地铁站门口见面。', 'Women mingtian zai ditiezhan menkou jianmian.', 'Ngày mai chúng ta gặp nhau ở cửa ga tàu điện ngầm.'),
    ('健康', '多锻炼对健康有好处。', 'Duo duanlian dui jiankang you haochu.', 'Tập thể dục nhiều có lợi cho sức khỏe.'),
    ('讲', '经理在会议上讲了新的计划。', 'Jingli zai huiyi shang jiang le xin de jihua.', 'Giám đốc đã nói về kế hoạch mới trong cuộc họp.'),
    ('脚', '爬山以后，我的脚有点疼。', 'Pashan yihou, wo de jiao youdian teng.', 'Sau khi leo núi, chân tôi hơi đau.'),
    ('角', '请在街道的那个角等我。', 'Qing zai jiedao de na ge jiao deng wo.', 'Hãy đợi tôi ở góc phố kia.'),
    ('接', '我下午去机场接朋友。', 'Wo xiawu qu jichang jie pengyou.', 'Chiều nay tôi ra sân bay đón bạn.'),
    ('街道', '这条街道晚上特别热闹。', 'Zhe tiao jiedao wanshang tebie renao.', 'Con phố này buổi tối đặc biệt náo nhiệt.'),
    ('结婚', '他们打算明年春天结婚。', 'Tamen dasuan mingnian chuntian jiehun.', 'Họ dự định kết hôn vào mùa xuân năm sau.'),
    ('结束', '会议结束以后，我们一起去吃饭。', 'Huiyi jieshu yihou, women yiqi qu chifan.', 'Sau khi cuộc họp kết thúc, chúng tôi cùng đi ăn.'),
    ('节目', '今晚电视上有一个音乐节目。', 'Jinwan dianshi shang you yi ge yinyue jiemu.', 'Tối nay trên tivi có một chương trình âm nhạc.'),
    ('节日', '春节是中国很重要的节日。', 'Chunjie shi Zhongguo hen zhongyao de jieri.', 'Tết xuân là một ngày lễ rất quan trọng của Trung Quốc.'),
    ('解决', '我们一起想办法解决这个问题。', 'Women yiqi xiang banfa jiejue zhe ge wenti.', 'Chúng ta cùng nghĩ cách giải quyết vấn đề này.'),
    ('借', '我可以借你的词典用一下吗？', 'Wo keyi jie ni de cidian yong yixia ma?', 'Tôi có thể mượn từ điển của bạn dùng một chút không?'),
    ('经常', '他经常下班后去公园跑步。', 'Ta jingchang xiaban hou qu gongyuan paobu.', 'Anh ấy thường chạy bộ trong công viên sau giờ làm.'),
    ('经过', '我每天上班都会经过这家超市。', 'Wo meitian shangban dou hui jingguo zhe jia chaoshi.', 'Mỗi ngày đi làm tôi đều đi qua siêu thị này.'),
    ('经理', '经理请大家下午到办公室开会。', 'Jingli qing dajia xiawu dao bangongshi kaihui.', 'Giám đốc mời mọi người chiều đến văn phòng họp.'),
    ('久', '我们已经很久没有见面了。', 'Women yijing hen jiu meiyou jianmian le.', 'Chúng tôi đã rất lâu không gặp nhau rồi.'),
    ('旧', '这台旧电脑还能继续用。', 'Zhe tai jiu diannao hai neng jixu yong.', 'Chiếc máy tính cũ này vẫn còn dùng tiếp được.'),
    ('句子', '请用这个词语写一个句子。', 'Qing yong zhe ge ciyu xie yi ge juzi.', 'Hãy dùng từ này viết một câu.'),
    ('决定', '我决定每天早上复习十个词。', 'Wo jueding meitian zaoshang fuxi shi ge ci.', 'Tôi quyết định mỗi sáng ôn mười từ.'),
    ('可爱', '邻居家的孩子说话很可爱。', 'Linju jia de haizi shuohua hen keai.', 'Đứa trẻ nhà hàng xóm nói chuyện rất đáng yêu.'),
    ('渴', '跑步以后，我特别渴。', 'Paobu yihou, wo tebie ke.', 'Sau khi chạy bộ, tôi rất khát.'),
    ('刻', '现在三点一刻，我们还来得及。', 'Xianzai san dian yi ke, women hai laideji.', 'Bây giờ là ba giờ mười lăm, chúng ta vẫn kịp.'),
    ('客人', '客人到了，请把茶拿出来。', 'Keren dao le, qing ba cha na chulai.', 'Khách đến rồi, hãy lấy trà ra.'),
    ('空调', '房间太热了，可以开空调吗？', 'Fangjian tai re le, keyi kai kongtiao ma?', 'Phòng nóng quá, có thể bật điều hòa không?'),
    ('口', '练口语时，要大胆开口。', 'Lian kouyu shi, yao dadan kaikou.', 'Khi luyện khẩu ngữ, phải mạnh dạn mở miệng nói.'),
    ('哭', '电影太感人了，她看着看着就哭了。', 'Dianying tai ganren le, ta kanzhe kanzhe jiu ku le.', 'Bộ phim quá cảm động, cô ấy xem một lúc rồi khóc.'),
    ('裤子', '这条裤子颜色很好看。', 'Zhe tiao kuzi yanse hen haokan.', 'Cái quần này màu sắc rất đẹp.'),
    ('筷子', '刚开始学中文时，我不会用筷子。', 'Gang kaishi xue Zhongwen shi, wo bu hui yong kuaizi.', 'Khi mới học tiếng Trung, tôi chưa biết dùng đũa.'),
    ('蓝', '她买了一条蓝裙子。', 'Ta mai le yi tiao lan qunzi.', 'Cô ấy mua một chiếc váy màu xanh lam.'),
    ('老', '这条老街道有很多小饭馆。', 'Zhe tiao lao jiedao you henduo xiao fanguan.', 'Con phố cũ này có rất nhiều quán ăn nhỏ.'),
    ('离开', '请不要在会议结束前离开。', 'Qing bu yao zai huiyi jieshu qian likai.', 'Xin đừng rời đi trước khi cuộc họp kết thúc.'),
    ('礼物', '我给奶奶买了一件生日礼物。', 'Wo gei nainai mai le yi jian shengri liwu.', 'Tôi mua cho bà nội một món quà sinh nhật.'),
    ('历史', '他对中国历史非常感兴趣。', 'Ta dui Zhongguo lishi feichang ganxingqu.', 'Anh ấy rất hứng thú với lịch sử Trung Quốc.'),
    ('脸', '天气太冷了，我的脸有点红。', 'Tianqi tai leng le, wo de lian youdian hong.', 'Trời lạnh quá, mặt tôi hơi đỏ.'),
    ('练习', '每天练习听力会提高水平。', 'Meitian lianxi tingli hui tigao shuiping.', 'Luyện nghe mỗi ngày sẽ nâng cao trình độ.'),
    ('辆', '门口停着两辆出租车。', 'Menkou tingzhe liang liang chuzuche.', 'Cửa ra vào đang đỗ hai chiếc taxi.'),
    ('了解', '我想了解一下这座城市的文化。', 'Wo xiang liaojie yixia zhe zuo chengshi de wenhua.', 'Tôi muốn tìm hiểu một chút văn hóa của thành phố này.'),
    ('邻居', '我的邻居经常帮我收快递。', 'Wo de linju jingchang bang wo shou kuaidi.', 'Hàng xóm của tôi thường giúp tôi nhận hàng.'),
    ('楼', '银行在这栋楼的第一层。', 'Yinhang zai zhe dong lou de di yi ceng.', 'Ngân hàng ở tầng một của tòa nhà này.'),
    ('绿', '春天来了，公园里的草变绿了。', 'Chuntian lai le, gongyuan li de cao bian lu le.', 'Mùa xuân đến rồi, cỏ trong công viên chuyển xanh.'),
    ('马', '孩子第一次骑马，有点害怕。', 'Haizi di yi ci qi ma, youdian haipa.', 'Đứa trẻ lần đầu cưỡi ngựa nên hơi sợ.'),
    ('马上', '你等一下，我马上就到。', 'Ni deng yixia, wo mashang jiu dao.', 'Bạn đợi một chút, tôi sẽ đến ngay.'),
    ('满意', '客人对这家宾馆的服务很满意。', 'Keren dui zhe jia binguan de fuwu hen manyi.', 'Khách rất hài lòng với dịch vụ của khách sạn này.'),
    ('帽子', '外面太阳很大，记得戴帽子。', 'Waimian taiyang hen da, jide dai maozi.', 'Ngoài trời nắng to, nhớ đội mũ.'),
    ('米', '这座桥大约有三百米长。', 'Zhe zuo qiao dayue you sanbai mi chang.', 'Cây cầu này dài khoảng ba trăm mét.'),
    ('面包', '早上我只吃了一个面包。', 'Zaoshang wo zhi chi le yi ge mianbao.', 'Buổi sáng tôi chỉ ăn một cái bánh mì.'),
    ('明白', '你说慢一点，我就能明白。', 'Ni shuo man yidian, wo jiu neng mingbai.', 'Bạn nói chậm một chút thì tôi có thể hiểu.'),
    ('拿', '请帮我拿一下桌上的笔记本。', 'Qing bang wo na yixia zhuo shang de bijiben.', 'Hãy giúp tôi lấy quyển sổ trên bàn.'),
    ('奶奶', '奶奶每天晚上给我打电话。', 'Nainai meitian wanshang gei wo da dianhua.', 'Bà nội mỗi tối gọi điện cho tôi.'),
    ('南', '我们学校南边有一个大公园。', 'Women xuexiao nanbian you yi ge da gongyuan.', 'Phía nam trường chúng tôi có một công viên lớn.'),
    ('难', '这道数学题有点难。', 'Zhe dao shuxue ti youdian nan.', 'Bài toán này hơi khó.'),
    ('难过', '朋友要离开这个城市了，我很难过。', 'Pengyou yao likai zhe ge chengshi le, wo hen nanguo.', 'Bạn tôi sắp rời thành phố này, tôi rất buồn.'),
    ('年级', '他现在上三年级，中文说得很好。', 'Ta xianzai shang san nianji, Zhongwen shuo de hen hao.', 'Cậu ấy hiện học lớp ba, nói tiếng Trung rất tốt.'),
    ('年轻', '这位年轻经理工作很认真。', 'Zhe wei nianqing jingli gongzuo hen renzhen.', 'Vị giám đốc trẻ này làm việc rất nghiêm túc.'),
    ('鸟', '早上窗外有鸟在唱歌。', 'Zaoshang chuangwai you niao zai changge.', 'Buổi sáng ngoài cửa sổ có chim đang hót.'),
    ('努力', '只要努力练习，你的中文会进步。', 'Zhiyao nuli lianxi, ni de Zhongwen hui jinbu.', 'Chỉ cần cố gắng luyện tập, tiếng Trung của bạn sẽ tiến bộ.'),
    ('爬山', '我们打算周末和同事去爬山。', 'Women dasuan zhoumo he tongshi qu pashan.', 'Chúng tôi dự định cuối tuần đi leo núi cùng đồng nghiệp.'),
    ('盘子', '请把水果放在这个盘子里。', 'Qing ba shuiguo fang zai zhe ge panzi li.', 'Hãy đặt trái cây vào cái đĩa này.'),
    ('胖', '最近他不运动，所以有点胖了。', 'Zuijin ta bu yundong, suoyi youdian pang le.', 'Gần đây anh ấy không vận động nên hơi béo lên.'),
    ('啤酒', '晚饭时爸爸喝了一瓶啤酒。', 'Wanfan shi baba he le yi ping pijiu.', 'Lúc ăn tối bố uống một chai bia.'),
    ('皮鞋', '面试的时候，他穿了一双黑皮鞋。', 'Mianshi de shihou, ta chuan le yi shuang hei pixie.', 'Khi phỏng vấn, anh ấy mang một đôi giày da màu đen.'),
    ('瓶子', '这个瓶子里还有一点果汁。', 'Zhe ge pingzi li haiyou yidian guozhi.', 'Trong cái chai này vẫn còn một ít nước ép.'),
    ('其实', '其实我以前不喜欢喝咖啡。', 'Qishi wo yiqian bu xihuan he kafei.', 'Thật ra trước đây tôi không thích uống cà phê.'),
    ('其他', '这本书我买了，其他的以后再看。', 'Zhe ben shu wo mai le, qita de yihou zai kan.', 'Cuốn sách này tôi mua rồi, những cái khác để sau xem.'),
    ('奇怪', '今天办公室很安静，真奇怪。', 'Jintian bangongshi hen anjing, zhen qiguai.', 'Hôm nay văn phòng rất yên tĩnh, thật kỳ lạ.'),
    ('骑', '他每天骑自行车去学校。', 'Ta meitian qi zixingche qu xuexiao.', 'Anh ấy mỗi ngày đạp xe đi học.'),
    ('起飞', '飞机十分钟以后起飞。', 'Feiji shi fenzhong yihou qifei.', 'Máy bay sẽ cất cánh sau mười phút.'),
    ('清楚', '请说清楚一点，我没有听懂。', 'Qing shuo qingchu yidian, wo meiyou tingdong.', 'Hãy nói rõ hơn một chút, tôi chưa nghe hiểu.'),
    ('秋', '秋天的天气不冷也不热。', 'Qiutian de tianqi bu leng ye bu re.', 'Thời tiết mùa thu không lạnh cũng không nóng.'),
    ('裙子', '她穿着一条蓝色的裙子参加聚会。', 'Ta chuanzhe yi tiao lanse de qunzi canjia juhui.', 'Cô ấy mặc một chiếc váy xanh tham gia buổi tụ họp.'),
    ('然后', '我们先吃饭，然后去看电影。', 'Women xian chifan, ranhou qu kan dianying.', 'Chúng tôi ăn cơm trước, sau đó đi xem phim.'),
    ('认为', '我认为每天复习比一次学很多更好。', 'Wo renwei meitian fuxi bi yi ci xue henduo geng hao.', 'Tôi cho rằng ôn mỗi ngày tốt hơn học thật nhiều một lần.'),
    ('认真', '他做作业很认真，几乎没有错。', 'Ta zuo zuoye hen renzhen, jihu meiyou cuo.', 'Anh ấy làm bài tập rất nghiêm túc, gần như không sai.'),
    ('容易', '这个句子很容易，你一定能明白。', 'Zhe ge juzi hen rongyi, ni yiding neng mingbai.', 'Câu này rất dễ, bạn nhất định có thể hiểu.'),
    ('如果', '如果明天下雨，我们就在家复习。', 'Ruguo mingtian xiayu, women jiu zai jia fuxi.', 'Nếu ngày mai mưa, chúng tôi sẽ ở nhà ôn tập.'),
    ('伞', '外面下雨了，别忘了带伞。', 'Waimian xiayu le, bie wangle dai san.', 'Bên ngoài mưa rồi, đừng quên mang ô.'),
    ('上网', '晚上我常常上网查中文资料。', 'Wanshang wo changchang shangwang cha Zhongwen ziliao.', 'Buổi tối tôi thường lên mạng tra tài liệu tiếng Trung.'),
    ('生气', '他迟到了一个小时，妈妈很生气。', 'Ta chidao le yi ge xiaoshi, mama hen shengqi.', 'Anh ấy đến muộn một tiếng, mẹ rất tức giận.'),
    ('声音', '这个音频的声音太小了。', 'Zhe ge yinpin de shengyin tai xiao le.', 'Âm thanh của file audio này quá nhỏ.'),
    ('使', '这次经历使我更努力学习。', 'Zhe ci jingli shi wo geng nuli xuexi.', 'Trải nghiệm lần này khiến tôi học chăm hơn.'),
    ('世界', '我想去看看更大的世界。', 'Wo xiang qu kankan geng da de shijie.', 'Tôi muốn đi nhìn ngắm thế giới rộng lớn hơn.'),
    ('试', '这双皮鞋不错，你可以试一下。', 'Zhe shuang pixie bucuo, ni keyi shi yixia.', 'Đôi giày da này khá tốt, bạn có thể thử một chút.'),
    ('瘦', '他最近经常锻炼，变瘦了。', 'Ta zuijin jingchang duanlian, bian shou le.', 'Gần đây anh ấy thường tập thể dục nên gầy đi.'),
    ('舒服', '这把椅子很舒服，我想买一把。', 'Zhe ba yizi hen shufu, wo xiang mai yi ba.', 'Cái ghế này rất thoải mái, tôi muốn mua một cái.'),
    ('树', '教室外面有一棵很高的树。', 'Jiaoshi waimian you yi ke hen gao de shu.', 'Bên ngoài phòng học có một cái cây rất cao.'),
    ('数学', '我弟弟最喜欢的课是数学。', 'Wo didi zui xihuan de ke shi shuxue.', 'Môn học em trai tôi thích nhất là toán.'),
    ('刷牙', '睡觉前一定要刷牙。', 'Shuijiao qian yiding yao shuaya.', 'Trước khi ngủ nhất định phải đánh răng.'),
    ('双', '我想买一双适合跑步的鞋。', 'Wo xiang mai yi shuang shihe paobu de xie.', 'Tôi muốn mua một đôi giày phù hợp để chạy bộ.'),
    ('水平', '他的中文水平提高得很快。', 'Ta de Zhongwen shuiping tigao de hen kuai.', 'Trình độ tiếng Trung của anh ấy nâng cao rất nhanh.'),
    ('司机', '司机告诉我们前面堵车。', 'Siji gaosu women qianmian duche.', 'Tài xế nói với chúng tôi phía trước kẹt xe.'),
    ('太阳', '太阳出来了，房间里亮了很多。', 'Taiyang chulai le, fangjian li liang le henduo.', 'Mặt trời lên rồi, trong phòng sáng hơn nhiều.'),
    ('特别', '今天的晚饭特别好吃。', 'Jintian de wanfan tebie haochi.', 'Bữa tối hôm nay đặc biệt ngon.'),
    ('疼', '走了一天路，我的腿很疼。', 'Zou le yi tian lu, wo de tui hen teng.', 'Đi bộ cả ngày, chân tôi rất đau.'),
    ('提高', '多听中文可以提高听力。', 'Duo ting Zhongwen keyi tigao tingli.', 'Nghe tiếng Trung nhiều có thể nâng cao kỹ năng nghe.'),
    ('体育', '我们学校每周都有体育课。', 'Women xuexiao mei zhou dou you tiyu ke.', 'Trường chúng tôi mỗi tuần đều có tiết thể dục.'),
    ('甜', '这个苹果很甜，你尝尝。', 'Zhe ge pingguo hen tian, ni changchang.', 'Quả táo này rất ngọt, bạn nếm thử đi.'),
    ('条', '我给爷爷买了一条围巾。', 'Wo gei yeye mai le yi tiao weijin.', 'Tôi mua cho ông nội một chiếc khăn quàng.'),
    ('同事', '我的同事帮我解决了电脑问题。', 'Wo de tongshi bang wo jiejue le diannao wenti.', 'Đồng nghiệp của tôi giúp tôi giải quyết vấn đề máy tính.'),
    ('同意', '妈妈同意我周末去参加比赛。', 'Mama tongyi wo zhoumo qu canjia bisai.', 'Mẹ đồng ý cho tôi cuối tuần đi tham gia cuộc thi.'),
    ('头发', '她的头发又长又黑。', 'Ta de toufa you chang you hei.', 'Tóc của cô ấy vừa dài vừa đen.'),
    ('突然', '会议中，灯突然关了。', 'Huiyi zhong, deng turan guan le.', 'Trong cuộc họp, đèn đột nhiên tắt.'),
    ('图书馆', '我下午在图书馆复习历史。', 'Wo xiawu zai tushuguan fuxi lishi.', 'Chiều nay tôi ôn lịch sử ở thư viện.'),
    ('腿', '爬山以后，我的腿有点累。', 'Pashan yihou, wo de tui youdian lei.', 'Sau khi leo núi, chân tôi hơi mỏi.'),
    ('完成', '他终于完成了这篇作业。', 'Ta zhongyu wancheng le zhe pian zuoye.', 'Cuối cùng anh ấy đã hoàn thành bài tập này.'),
    ('碗', '我早上喝了一碗热汤。', 'Wo zaoshang he le yi wan re tang.', 'Buổi sáng tôi uống một bát canh nóng.'),
    ('万', '这辆车大约十万元。', 'Zhe liang che dayue shi wan yuan.', 'Chiếc xe này khoảng một trăm nghìn tệ.'),
    ('忘记', '我忘记把电子邮件发给经理了。', 'Wo wangji ba dianzi youjian fa gei jingli le.', 'Tôi quên gửi email cho giám đốc rồi.'),
    ('为', '这杯茶是为客人准备的。', 'Zhe bei cha shi wei keren zhunbei de.', 'Ly trà này được chuẩn bị cho khách.'),
    ('为了', '为了提高口语，我每天跟朋友练习。', 'Weile tigao kouyu, wo meitian gen pengyou lianxi.', 'Để nâng cao khẩu ngữ, mỗi ngày tôi luyện tập với bạn.'),
    ('位', '今天有三位客人来公司参观。', 'Jintian you san wei keren lai gongsi canguan.', 'Hôm nay có ba vị khách đến công ty tham quan.'),
    ('文化', '学语言也要了解当地文化。', 'Xue yuyan ye yao liaojie dangdi wenhua.', 'Học ngôn ngữ cũng cần tìm hiểu văn hóa địa phương.'),
    ('西', '太阳从西边慢慢落下。', 'Taiyang cong xibian manman luoxia.', 'Mặt trời từ phía tây chậm rãi lặn xuống.'),
    ('习惯', '我已经习惯每天早起复习。', 'Wo yijing xiguan meitian zaoqi fuxi.', 'Tôi đã quen với việc dậy sớm ôn tập mỗi ngày.'),
    ('洗手间', '请问，洗手间在几楼？', 'Qingwen, xishoujian zai ji lou?', 'Xin hỏi, nhà vệ sinh ở tầng mấy?'),
    ('洗澡', '运动以后，我想先洗澡。', 'Yundong yihou, wo xiang xian xizao.', 'Sau khi vận động, tôi muốn tắm trước.'),
    ('夏', '夏天去海边旅行很舒服。', 'Xiatian qu haibian luxing hen shufu.', 'Mùa hè đi du lịch biển rất thoải mái.'),
    ('先', '我们先吃饭，再讨论工作。', 'Women xian chifan, zai taolun gongzuo.', 'Chúng ta ăn cơm trước, rồi bàn công việc.'),
    ('香蕉', '我每天早上吃一根香蕉。', 'Wo meitian zaoshang chi yi gen xiangjiao.', 'Mỗi sáng tôi ăn một quả chuối.'),
    ('相同', '这两道题的答案相同。', 'Zhe liang dao ti de daan xiangtong.', 'Đáp án của hai câu này giống nhau.'),
    ('相信', '我相信你一定能通过考试。', 'Wo xiangxin ni yiding neng tongguo kaoshi.', 'Tôi tin bạn nhất định có thể vượt qua kỳ thi.'),
    ('像', '这张照片里的他很像爸爸。', 'Zhe zhang zhaopian li de ta hen xiang baba.', 'Anh ấy trong bức ảnh này rất giống bố.'),
    ('小心', '路上有水，走路要小心。', 'Lu shang you shui, zoulu yao xiaoxin.', 'Trên đường có nước, đi bộ phải cẩn thận.'),
    ('校长', '校长今天来我们班听课。', 'Xiaozhang jintian lai women ban tingke.', 'Hiệu trưởng hôm nay đến lớp chúng tôi dự giờ.'),
    ('新闻', '爸爸每天晚上看新闻。', 'Baba meitian wanshang kan xinwen.', 'Bố mỗi tối xem tin tức.'),
    ('新鲜', '这家超市的水果很新鲜。', 'Zhe jia chaoshi de shuiguo hen xinxian.', 'Trái cây của siêu thị này rất tươi.'),
    ('信', '我收到了一封爷爷写的信。', 'Wo shoudao le yi feng yeye xie de xin.', 'Tôi nhận được một bức thư do ông nội viết.'),
    ('行李箱', '我的行李箱太重了，搬不动。', 'Wo de xinglixiang tai zhong le, ban bu dong.', 'Vali của tôi nặng quá, không chuyển nổi.'),
    ('兴趣', '她对音乐和历史都有兴趣。', 'Ta dui yinyue he lishi dou you xingqu.', 'Cô ấy đều có hứng thú với âm nhạc và lịch sử.'),
    ('熊猫', '孩子们最想在动物园看熊猫。', 'Haizimen zui xiang zai dongwuyuan kan xiongmao.', 'Bọn trẻ muốn xem gấu trúc nhất ở sở thú.'),
    ('需要', '如果需要帮助，可以给我打电话。', 'Ruguo xuyao bangzhu, keyi gei wo da dianhua.', 'Nếu cần giúp đỡ, bạn có thể gọi điện cho tôi.'),
    ('选择', '菜单上有很多菜，我不知道怎么选择。', 'Caidan shang you henduo cai, wo bu zhidao zenme xuanze.', 'Trên thực đơn có nhiều món, tôi không biết chọn thế nào.'),
    ('要求', '老师要求我们明天交作业。', 'Laoshi yaoqiu women mingtian jiao zuoye.', 'Giáo viên yêu cầu chúng tôi ngày mai nộp bài tập.'),
    ('爷爷', '爷爷喜欢早上去公园锻炼。', 'Yeye xihuan zaoshang qu gongyuan duanlian.', 'Ông nội thích buổi sáng đi công viên tập thể dục.'),
    ('一般', '这家饭馆味道一般，但是很便宜。', 'Zhe jia fanguan weidao yiban, danshi hen pianyi.', 'Quán ăn này vị bình thường nhưng rất rẻ.'),
    ('一边', '她一边听音乐，一边打扫房间。', 'Ta yibian ting yinyue, yibian dasao fangjian.', 'Cô ấy vừa nghe nhạc vừa dọn phòng.'),
    ('一定', '明天的会议你一定要准时到。', 'Mingtian de huiyi ni yiding yao zhunshi dao.', 'Cuộc họp ngày mai bạn nhất định phải đến đúng giờ.'),
    ('一共', '这些水果一共三十五元。', 'Zhexie shuiguo yigong sanshiwu yuan.', 'Số trái cây này tổng cộng ba mươi lăm tệ.'),
    ('一会儿', '你先坐一会儿，我马上回来。', 'Ni xian zuo yihuir, wo mashang huilai.', 'Bạn ngồi một lát trước, tôi quay lại ngay.'),
    ('一样', '这两个瓶子的颜色一样。', 'Zhe liang ge pingzi de yanse yiyang.', 'Màu của hai cái chai này giống nhau.'),
    ('以后', '以后有问题，可以直接问我。', 'Yihou you wenti, keyi zhijie wen wo.', 'Sau này có vấn đề, bạn có thể hỏi trực tiếp tôi.'),
    ('以前', '以前我住在学校附近。', 'Yiqian wo zhu zai xuexiao fujin.', 'Trước đây tôi sống gần trường.'),
    ('以为', '我以为今天没有体育课。', 'Wo yiwei jintian meiyou tiyu ke.', 'Tôi tưởng hôm nay không có tiết thể dục.'),
    ('银行', '银行下午五点关门。', 'Yinhang xiawu wu dian guanmen.', 'Ngân hàng đóng cửa lúc năm giờ chiều.'),
    ('音乐', '安静的音乐能让我放松。', 'Anjing de yinyue neng rang wo fangsong.', 'Âm nhạc nhẹ nhàng có thể làm tôi thư giãn.'),
    ('应该', '感冒了就应该多喝水。', 'Ganmao le jiu yinggai duo he shui.', 'Bị cảm thì nên uống nhiều nước.'),
    ('影响', '睡得太晚会影响第二天的学习。', 'Shui de tai wan hui yingxiang di er tian de xuexi.', 'Ngủ quá muộn sẽ ảnh hưởng đến việc học ngày hôm sau.'),
    ('用', '我用手机查了地铁路线。', 'Wo yong shouji cha le ditie luxian.', 'Tôi dùng điện thoại tra tuyến tàu điện ngầm.'),
    ('游戏', '他完成作业以后才玩游戏。', 'Ta wancheng zuoye yihou cai wan youxi.', 'Anh ấy làm xong bài tập rồi mới chơi trò chơi.'),
    ('有名', '这个城市因为美食很有名。', 'Zhe ge chengshi yinwei meishi hen youming.', 'Thành phố này nổi tiếng vì ẩm thực.'),
    ('又', '今天又下雨了，我忘带伞了。', 'Jintian you xiayu le, wo wang dai san le.', 'Hôm nay lại mưa rồi, tôi quên mang ô.'),
    ('遇到', '路上遇到老师，我跟她打了招呼。', 'Lu shang yudao laoshi, wo gen ta da le zhaohu.', 'Trên đường gặp giáo viên, tôi đã chào cô ấy.'),
    ('元', '这杯果汁十五元。', 'Zhe bei guozhi shiwu yuan.', 'Ly nước ép này mười lăm tệ.'),
    ('愿意', '如果你愿意，我们周末一起复习。', 'Ruguo ni yuanyi, women zhoumo yiqi fuxi.', 'Nếu bạn sẵn lòng, cuối tuần chúng ta cùng ôn tập.'),
    ('越', '中文越学越有意思。', 'Zhongwen yue xue yue you yisi.', 'Tiếng Trung càng học càng thú vị.'),
    ('月亮', '今晚的月亮又大又圆。', 'Jinwan de yueliang you da you yuan.', 'Trăng tối nay vừa to vừa tròn.'),
    ('云', '天上的云很多，可能要下雨。', 'Tianshang de yun henduo, keneng yao xiayu.', 'Trên trời có nhiều mây, có thể sắp mưa.'),
    ('站', '请在门口站一会儿，老师马上来。', 'Qing zai menkou zhan yihuir, laoshi mashang lai.', 'Hãy đứng ở cửa một lát, giáo viên sẽ đến ngay.'),
    ('长', '孩子长得很快，裤子又短了。', 'Haizi zhang de hen kuai, kuzi you duan le.', 'Đứa trẻ lớn rất nhanh, quần lại ngắn rồi.'),
    ('着急', '别着急，地铁十分钟后就到。', 'Bie zhaoji, ditie shi fenzhong hou jiu dao.', 'Đừng sốt ruột, tàu điện ngầm mười phút nữa sẽ đến.'),
    ('照顾', '妈妈出差时，我照顾弟弟。', 'Mama chuchai shi, wo zhaogu didi.', 'Khi mẹ đi công tác, tôi chăm sóc em trai.'),
    ('照片', '这张照片是去年春天拍的。', 'Zhe zhang zhaopian shi qunian chuntian pai de.', 'Bức ảnh này được chụp vào mùa xuân năm ngoái.'),
    ('照相机', '旅行前，我买了一台新照相机。', 'Luxing qian, wo mai le yi tai xin zhaoxiangji.', 'Trước chuyến du lịch, tôi mua một chiếc máy ảnh mới.'),
    ('只', '今天我只喝了一杯咖啡。', 'Jintian wo zhi he le yi bei kafei.', 'Hôm nay tôi chỉ uống một ly cà phê.'),
    ('只好', '电梯坏了，我们只好走上十层。', 'Dianti huai le, women zhihao zou shang shi ceng.', 'Thang máy hỏng, chúng tôi đành đi bộ lên tầng mười.'),
    ('只有', '只有认真复习，考试才会更有信心。', 'Zhiyou renzhen fuxi, kaoshi cai hui geng you xinxin.', 'Chỉ có ôn tập nghiêm túc thì khi thi mới tự tin hơn.'),
    ('种', '超市里有很多种新鲜水果。', 'Chaoshi li you henduo zhong xinxian shuiguo.', 'Trong siêu thị có rất nhiều loại trái cây tươi.'),
    ('重要', '睡觉以前刷牙很重要。', 'Shuijiao yiqian shuaya hen zhongyao.', 'Đánh răng trước khi ngủ rất quan trọng.'),
    ('周末', '周末我们打算去朋友家吃饭。', 'Zhoumo women dasuan qu pengyou jia chifan.', 'Cuối tuần chúng tôi dự định đến nhà bạn ăn cơm.'),
    ('主要', '这次会议主要讨论新计划。', 'Zhe ci huiyi zhuyao taolun xin jihua.', 'Cuộc họp lần này chủ yếu thảo luận kế hoạch mới.'),
    ('注意', '过马路时一定要注意安全。', 'Guo malu shi yiding yao zhuyi anquan.', 'Khi qua đường nhất định phải chú ý an toàn.'),
    ('自己', '这件事我想自己解决。', 'Zhe jian shi wo xiang ziji jiejue.', 'Việc này tôi muốn tự mình giải quyết.'),
    ('自行车', '他骑自行车去附近的公园。', 'Ta qi zixingche qu fujin de gongyuan.', 'Anh ấy đạp xe đến công viên gần đó.'),
    ('总是', '他总是忘记带笔记本。', 'Ta zongshi wangji dai bijiben.', 'Anh ấy luôn quên mang sổ ghi chép.'),
    ('嘴', '吃完蛋糕以后，孩子的嘴都是奶油。', 'Chi wan dangao yihou, haizi de zui dou shi naiyou.', 'Sau khi ăn bánh kem, miệng đứa trẻ toàn là kem.'),
    ('最后', '最后一个问题比较难。', 'Zuihou yi ge wenti bijiao nan.', 'Câu hỏi cuối cùng khá khó.'),
    ('最近', '最近我每天都在练习听力。', 'Zuijin wo meitian dou zai lianxi tingli.', 'Gần đây tôi ngày nào cũng luyện nghe.'),
    ('作业', '老师要求我们今晚完成作业。', 'Laoshi yaoqiu women jinwan wancheng zuoye.', 'Giáo viên yêu cầu chúng tôi tối nay hoàn thành bài tập.'),
    ('作用', '好的习惯对学习有很大作用。', 'Hao de xiguan dui xuexi you hen da zuoyong.', 'Thói quen tốt có tác dụng rất lớn đối với việc học.'),
    ('笔记本', '我把今天的新词写在笔记本上。', 'Wo ba jintian de xinci xie zai bijiben shang.', 'Tôi viết từ mới hôm nay vào sổ ghi chép.'),
    ('不但', '她不但会说中文，还会说英语。', 'Ta budan hui shuo Zhongwen, hai hui shuo Yingyu.', 'Cô ấy không những biết nói tiếng Trung mà còn biết nói tiếng Anh.'),
    ('而且', '这家饭馆便宜，而且味道很好。', 'Zhe jia fanguan pianyi, erqie weidao hen hao.', 'Quán ăn này rẻ, hơn nữa hương vị rất ngon.'),
    ('词典', '我用词典查这个词的意思。', 'Wo yong cidian cha zhe ge ci de yisi.', 'Tôi dùng từ điển tra nghĩa của từ này.'),
    ('发烧', '他昨晚发烧了，今天没来上课。', 'Ta zuowan fashao le, jintian mei lai shangke.', 'Tối qua anh ấy bị sốt nên hôm nay không đến lớp.'),
    ('公斤', '这个西瓜大约三公斤。', 'Zhe ge xigua dayue san gongjin.', 'Quả dưa hấu này khoảng ba ki-lô-gam.'),
    ('后来', '我开始不明白，后来慢慢听懂了。', 'Wo kaishi bu mingbai, houlai manman tingdong le.', 'Ban đầu tôi không hiểu, sau đó dần dần nghe hiểu.'),
    ('回答', '请你用中文回答这个问题。', 'Qing ni yong Zhongwen huida zhe ge wenti.', 'Hãy dùng tiếng Trung trả lời câu hỏi này.'),
    ('几乎', '这条街我几乎每天都经过。', 'Zhe tiao jie wo jihu meitian dou jingguo.', 'Con phố này gần như ngày nào tôi cũng đi qua.')
),
updated_template_cards as (
  update public.template_cards as card
  set
    example_cn = example.example_cn,
    example_pinyin = example.example_pinyin,
    example_vi = example.example_vi,
    sentence_audio_url = null
  from public.template_decks as deck,
    hsk3_context_examples as example
  where card.template_deck_id = deck.id
    and deck.slug = 'hsk3-co-ban'
    and card.chinese = example.chinese
  returning card.id
)
update public.cards as card
set
  example_cn = example.example_cn,
  example_pinyin = example.example_pinyin,
  example_vi = example.example_vi,
  sentence_audio_url = null
from public.decks as deck,
  hsk3_context_examples as example
where card.deck_id = deck.id
  and card.user_id = deck.user_id
  and (
    deck.source_template_slug = 'hsk3-co-ban'
    or (deck.source_template_slug is null and deck.name = 'HSK3 cơ bản')
  )
  and card.chinese = example.chinese
  and (
    nullif(btrim(card.example_cn), '') is null
    or card.example_cn like '老师今天教我们%'
    or card.example_pinyin like 'Laoshi jintian jiao women % zhe ge ci.'
  );
