-- Replace HSK4 examples with contextual, unique examples.
-- Template HSK4 is refreshed. User cards are updated only when the old generic
-- placeholder is still present or the example is blank.
with hsk4_context_examples (
  chinese,
  example_cn,
  example_pinyin,
  example_vi
) as (
  values
    ('爱情', '他们的爱情故事让大家都感动。', 'Tāmen de àiqíng gùshì ràng dàjiā dōu gǎndòng.', 'Câu chuyện tình yêu của họ làm mọi người đều xúc động.'),
    ('按照', '请按照说明书操作机器。', 'Qǐng ànzhào shuōmíngshū cāozuò jīqì.', 'Vui lòng vận hành máy theo hướng dẫn sử dụng.'),
    ('按时', '我们必须按时完成这项任务。', 'Wǒmen bìxū ànshí wánchéng zhè xiàng rènwu.', 'Chúng ta phải hoàn thành nhiệm vụ này đúng hạn.'),
    ('安排', '老师安排了明天的考试时间。', 'Lǎoshī ānpái le míngtiān de kǎoshì shíjiān.', 'Giáo viên đã sắp xếp thời gian thi vào ngày mai.'),
    ('安全', '在工厂工作时，请注意安全。', 'Zài gōngchǎng gōngzuò shí, qǐng zhùyì ānquán.', 'Khi làm việc trong nhà máy, xin hãy chú ý an toàn.'),
    ('百分之', '这道题有百分之八十的人答对了。', 'Zhè dào tí yǒu bǎifēnzhī bāshí de rén dá duì le.', 'Có 80 phần trăm người trả lời đúng câu hỏi này.'),
    ('饼干', '我喜欢和茶一起吃饼干。', 'Wǒ xǐhuān hé chá yīqǐ chī bǐnggān.', 'Tôi thích ăn bánh quy cùng với trà.'),
    ('部分', '这部分材料很重要，要仔细阅读。', 'Zhè bùfèn cáiliào hěn zhòngyào, yào zǐxì yuèdú.', 'Phần tài liệu này rất quan trọng, cần đọc kỹ.'),
    ('遍', '请把这篇文章读一遍。', 'Qǐng bǎ zhè piān wénzhāng dú yí biàn.', 'Xin hãy đọc bài văn này một lượt.'),
    ('表示', '他用微笑表示感谢。', 'Tā yòng wēixiào biǎoshì gǎnxiè.', 'Anh ấy dùng nụ cười để biểu thị lòng biết ơn.'),
    ('表演', '我们班准备下个月进行一次精彩的表演。', 'Wǒmen bān zhǔnbèi xià gè yuè jìnxíng yí cì jīngcǎi de biǎoyǎn.', 'Lớp chúng tôi chuẩn bị có một buổi biểu diễn tuyệt vời vào tháng tới.'),
    ('表格', '请填写这张表格以便我们核对信息。', 'Qǐng tiánxiě zhè zhāng biǎogé yǐbiàn wǒmen héduì xìnxī.', 'Vui lòng điền vào bảng biểu này để chúng tôi kiểm tra thông tin.'),
    ('表扬', '老师表扬了他在课堂上的积极表现。', 'Lǎoshī biǎoyáng le tā zài kètáng shàng de jījí biǎoxiàn.', 'Giáo viên đã tuyên dương sự tích cực của cậu ấy trong lớp học.'),
    ('笨', '别说自己笨，多练习就会进步。', 'Bié shuō zìjǐ bèn, duō liànxí jiù huì jìnbù.', 'Đừng nói mình ngốc, luyện tập nhiều sẽ tiến bộ thôi.'),
    ('毕业', '他今年夏天从大学毕业了。', 'Tā jīnnián xiàtiān cóng dàxué bìyè le.', 'Anh ấy tốt nghiệp đại học vào mùa hè năm nay.'),
    ('比如', '我们学习很多实用的知识，比如如何写商业计划。', 'Wǒmen xuéxí hěn duō shíyòng de zhīshì, bǐrú rúhé xiě shāngyè jìhuà.', 'Chúng tôi học nhiều kiến thức thực tế, ví dụ như cách viết kế hoạch kinh doanh.'),
    ('棒', '孩子用棒子在地上画画。', 'Háizi yòng bàngzi zài dìshàng huà huà.', 'Đứa trẻ dùng cây gậy để vẽ trên đất.'),
    ('标准', '这款产品符合国际质量标准。', 'Zhè kuǎn chǎnpǐn fúhé guójì zhìliàng biāozhǔn.', 'Sản phẩm này đáp ứng tiêu chuẩn chất lượng quốc tế.'),
    ('本来', '我本来打算早点来，可是遇到了交通堵塞。', 'Wǒ běnlái dǎsuàn zǎodiǎn lái, kěshì yùdào le jiāotōng dǔsè.', 'Tôi vốn định đến sớm, nhưng lại gặp phải tắc đường.'),
    ('抱歉', '抱歉，我忘了带你的书。', 'Bàoqiàn, wǒ wàng le dài nǐ de shū.', 'Xin lỗi, tôi đã quên mang cuốn sách của bạn.'),
    ('抱', '她生病了，我去医院抱了她。', 'Tā shēngbìng le, wǒ qù yīyuàn bào le tā.', 'Cô ấy bị ốm, tôi đã đến bệnh viện ôm cô ấy.'),
    ('报名', '我准备报名下个月的汉语考试。', 'Wǒ zhǔnbèi bàomíng xià gè yuè de hànyǔ kǎoshì.', 'Tôi chuẩn bị đăng ký kỳ thi tiếng Trung vào tháng tới.'),
    ('并且', '他不仅会说英语，并且会说法语。', 'Tā bù jǐn huì shuō yīngyǔ, bìngqiě huì shuō fǎyǔ.', 'Anh ấy không chỉ biết nói tiếng Anh mà còn biết nói tiếng Pháp.'),
    ('博士', '她去年完成了博士学位的论文。', 'Tā qùnián wánchéng le bóshì xuéwèi de lùnwén.', 'Cô ấy đã hoàn thành luận án tiến sĩ vào năm ngoái.'),
    ('包子', '早餐我买了几个新鲜的包子。', 'Zǎocān wǒ mǎi le jǐ gè xīnxiān de bāozi.', 'Sáng nay tôi đã mua vài chiếc bánh bao tươi.'),
    ('倍', '今年的销售额比去年增加了两倍。', 'Jīnnián de xiāoshòu''é bǐ qùnián zēngjiā le liǎng bèi.', 'Doanh số năm nay tăng gấp đôi so với năm ngoái.'),
    ('保证', '公司保证产品质量不会有问题。', 'Gōngsī bǎozhèng chǎnpǐn zhìliàng bú huì yǒu wèntí.', 'Công ty đảm bảo chất lượng sản phẩm sẽ không có vấn đề.'),
    ('保护', '我们应该保护环境，减少污染。', 'Wǒmen yīnggāi bǎohù huánjìng, jiǎnshǎo wūrǎn.', 'Chúng ta nên bảo vệ môi trường, giảm thiểu ô nhiễm.'),
    ('不过', '我想去旅行，不过工作太忙没时间。', 'Wǒ xiǎng qù lǚxíng, bùguò gōngzuò tài máng méi shíjiān.', 'Tôi muốn đi du lịch, nhưng công việc quá bận nên không có thời gian.'),
    ('不管', '不管天气怎么样，我们明天都去爬山。', 'Bùguǎn tiānqì zěnmeyàng, wǒmen míngtiān dōu qù páshān.', 'Bất kể thời tiết thế nào, chúng ta ngày mai đều đi leo núi.'),
    ('不得不', '今天下雨了，所以我不得不取消旅行计划。', 'Jīntiān xiàyǔ le, suǒyǐ wǒ bùdébù qǔxiāo lǚxíng jìhuà.', 'Hôm nay trời mưa, nên tôi đành phải hủy kế hoạch du lịch.'),
    ('不仅', '这家餐厅不仅价格合理，而且菜很好吃。', 'Zhè jiā cāntīng bùjǐn jiàgé hélǐ, érqiě cài hěn hǎochī.', 'Nhà hàng này không những giá cả hợp lý, mà món ăn còn rất ngon.'),
    ('擦', '请用布擦一下桌子，保持清洁。', 'Qǐng yòng bù cā yíxià zhuōzi, bǎochí qīngjié.', 'Làm ơn dùng khăn lau cái bàn nhé, giữ cho sạch sẽ.'),
    ('餐厅', '学生们中午都去学校的餐厅吃饭。', 'Xuéshēngmen zhōngwǔ dōu qù xuéxiào de cāntīng chīfàn.', 'Học sinh đều đi căng tin của trường ăn trưa.'),
    ('长江', '长江是中国最长的河流。', 'Chángjiāng shì Zhōngguó zuì cháng de héliú.', 'Trường Giang là con sông dài nhất ở Trung Quốc.'),
    ('长城', '去年我有机会参观了著名的长城。', 'Qùnián wǒ yǒu jīhuì cānguān le zhùmíng de Chángchéng.', 'Năm ngoái tôi có cơ hội tham quan Vạn Lý Trường Thành nổi tiếng.'),
    ('错误', '老师帮我改正了作文中的错误。', 'Lǎoshī bāng wǒ gǎizhèng le zuòwén zhōng de cuòwù.', 'Giáo viên đã giúp tôi sửa những sai lầm trong bài viết.'),
    ('重新', '因为文件丢失，我不得不重新写报告。', 'Yīnwèi wénjiàn diūshī, wǒ bùdébù chóngxīn xiě bàogào.', 'Vì tài liệu bị mất, tôi đành phải viết lại báo cáo.'),
    ('超过', '他跑步的速度已经超过了所有人。', 'Tā pǎobù de sùdù yǐjīng chāoguò le suǒyǒu rén.', 'Tốc độ chạy của anh ấy đã vượt qua tất cả mọi người.'),
    ('诚实', '诚实是我们必须遵守的原则。', 'Chéngshí shì wǒmen bìxū zūnshǒu de yuánzé.', 'Trung thực là nguyên tắc mà chúng ta phải tuân theo.'),
    ('词语', '学生们在课上学习新的词语。', 'Xuéshēng men zài kè shàng xuéxí xīn de cíyǔ.', 'Học sinh trong lớp học các từ ngữ mới.'),
    ('粗心', '他因为粗心把作业写错了。', 'Tā yīnwèi cūxīn bǎ zuòyè xiě cuò le.', 'Anh ấy vì cẩu thả đã viết sai bài tập.'),
    ('窗户', '请把窗户打开，让空气流通。', 'Qǐng bǎ chuānghù dǎkāi, ràng kōngqì liútōng.', 'Xin hãy mở cửa sổ để không khí lưu thông.'),
    ('猜', '我猜你明天会来。', 'Wǒ cāi nǐ míngtiān huì lái.', 'Tôi đoán bạn sẽ đến vào ngày mai.'),
    ('材料', '老师给我们发了考试的复习材料。', 'Lǎoshī gěi wǒmen fā le kǎoshì de fùxí cáiliào.', 'Giáo viên phát tài liệu ôn thi cho chúng tôi.'),
    ('抽烟', '公共场所禁止抽烟。', 'Gōnggòng chǎngsuǒ jìnzhǐ chōuyān.', 'Nơi công cộng cấm hút thuốc.'),
    ('成功', '他通过努力终于获得了成功。', 'Tā tōngguò nǔlì zhōngyú huòdé le chénggōng.', 'Anh ấy cuối cùng đã thành công nhờ sự cố gắng.'),
    ('成为', '她希望成为一名医生。', 'Tā xīwàng chéngwéi yī míng yīshēng.', 'Cô ấy hy vọng trở thành bác sĩ.'),
    ('差不多', '我们到达的时间差不多是晚上七点。', 'Wǒmen dàodá de shíjiān chàbùduō shì wǎnshàng qī diǎn.', 'Thời gian chúng tôi đến gần như là 7 giờ tối.'),
    ('尝', '你想尝尝这道新菜吗？', 'Nǐ xiǎng cháng cháng zhè dào xīn cài ma?', 'Bạn muốn nếm thử món ăn mới này không?'),
    ('存', '我每个月都会存一部分工资。', 'Wǒ měi gè yuè dūhuì cún yī bùfen gōngzī.', 'Tôi sẽ tiết kiệm một phần lương mỗi tháng.'),
    ('场', '今天晚上有一场重要的足球比赛。', 'Jīntiān wǎnshàng yǒu yì chǎng zhòngyào de zúqiú bǐsài.', 'Tối nay có một trận đấu bóng đá quan trọng.'),
    ('吃惊', '听说他搬到国外了，我很吃惊。', 'Tīngshuō tā bān dào guówài le, wǒ hěn chī jīng.', 'Nghe nói anh ấy đã chuyển ra nước ngoài, tôi rất ngạc nhiên.'),
    ('参观', '我们计划下周参观那个历史博物馆。', 'Wǒmen jìhuà xià zhōu cānguān nàgè lìshǐ bówùguǎn.', 'Chúng tôi dự định vào tuần tới tham quan bảo tàng lịch sử đó.'),
    ('厨房', '她在厨房做了很多美味的菜。', 'Tā zài chúfáng zuò le hěn duō měiwèi de cài.', 'Cô ấy đã nấu rất nhiều món ngon trong phòng bếp.'),
    ('厕所', '请问，厕所在哪里？', 'Qǐngwèn, cèsuǒ zài nǎlǐ?', 'Xin hỏi, nhà vệ sinh ở đâu?'),
    ('出生', '他出生在一个美丽的海边城市。', 'Tā chūshēng zài yí gè měilì de hǎibiān chéngshì.', 'Anh ấy sinh ra tại một thành phố ven biển xinh đẹp.'),
    ('出现', '会议中突然出现了一些技术问题。', 'Huìyì zhōng túrán chūxiàn le yìxiē jìshù wèntí.', 'Trong cuộc họp đột nhiên xuất hiện một số vấn đề kỹ thuật.'),
    ('出差', '下个月我需要去北京出差两周。', 'Xià gè yuè wǒ xūyào qù Běijīng chūchāi liǎng zhōu.', 'Tháng tới tôi cần đi công tác ở Bắc Kinh hai tuần.'),
    ('出发', '我们打算明天一早出发去机场。', 'Wǒmen dǎsuàn míngtiān yì zǎo chūfā qù jīchǎng.', 'Chúng tôi dự định ngày mai sáng sớm xuất phát đến sân bay.'),
    ('传真', '请把合同通过传真发给我。', 'Qǐng bǎ hétóng tōngguò chuánzhēn fā gěi wǒ.', 'Vui lòng gửi hợp đồng cho tôi qua fax.'),
    ('从来', '他从来没有迟到过。', 'Tā cónglái méiyǒu chídào guò.', 'Anh ấy từ trước đến nay chưa bao giờ đến muộn.'),
    ('乘坐', '我们明天打算乘坐火车去北京。', 'Wǒmen míngtiān dǎsuàn chéngzuò huǒchē qù Běijīng.', 'Chúng tôi dự định ngày mai ngồi tàu đi Bắc Kinh.'),
    ('答案', '请把答案写在试卷上。', 'Qǐng bǎ dá''àn xiě zài shìjuàn shàng.', 'Vui lòng viết đáp án lên giấy thi.'),
    ('道歉', '他向老师道歉因为迟到了。', 'Tā xiàng lǎoshī dàoqiàn yīnwèi chídào le.', 'Anh ấy xin lỗi giáo viên vì đến muộn.'),
    ('调查', '公司正在对市场进行调查。', 'Gōngsī zhèngzài duì shìchǎng jìnxíng diàochá.', 'Công ty đang tiến hành điều tra thị trường.'),
    ('肚子', '我肚子疼，需要去医院。', 'Wǒ dùzi téng, xūyào qù yīyuàn.', 'Tôi bị đau bụng, cần đi bệnh viện.'),
    ('等（助词）', '老师说要准备笔、纸等文具。', 'Lǎoshī shuō yào zhǔnbèi bǐ, zhǐ děng wénjù.', 'Giáo viên nói cần chuẩn bị bút, giấy và các văn phòng phẩm khác.'),
    ('短信', '我刚收到你的短信，谢谢！', 'Wǒ gāng shōudào nǐ de duǎnxìn, xièxiè!', 'Tôi vừa nhận được tin nhắn của bạn, cảm ơn!'),
    ('登机牌', '请出示你的登机牌和护照。', 'Qǐng chūshì nǐ de dēngjīpái hé hùzhào.', 'Vui lòng xuất trình thẻ lên tàu và hộ chiếu của bạn.'),
    ('掉', '我的手机今天不小心掉了。', 'Wǒ de shǒujī jīntiān bù xiǎoxīn diào le.', 'Điện thoại của tôi hôm nay vô tình bị rơi.'),
    ('打针', '医生给小孩打针以防感冒。', 'Yīshēng gěi xiǎohái dǎ zhēn yǐ fáng gǎnmào.', 'Bác sĩ tiêm cho trẻ để phòng cảm.'),
    ('打招呼', '见到老师要主动打招呼。', 'Jiàn dào lǎoshī yào zhǔdòng dǎ zhāo hū.', 'Gặp thầy cô nên chủ động chào hỏi.'),
    ('打折', '这个商店周末会打折促销。', 'Zhège shāngdiàn zhōumò huì dǎ zhé cùxiāo.', 'Cửa hàng này cuối tuần sẽ giảm giá khuyến mãi.'),
    ('打扰', '很抱歉打扰您工作了。', 'Hěn bàoqiàn dǎrǎo nín gōngzuò le.', 'Rất xin lỗi đã làm phiền công việc của bạn.'),
    ('打扮', '她今天打扮得非常漂亮。', 'Tā jīntiān dǎbàn de fēicháng piàoliang.', 'Cô ấy hôm nay trang điểm rất đẹp.'),
    ('打印', '请帮我打印这份文件。', 'Qǐng bāng wǒ dǎyìn zhè fèn wénjiàn.', 'Làm ơn giúp tôi in tài liệu này.'),
    ('戴', '外出时记得戴口罩。', 'Wàichū shí jìde dài kǒuzhào.', 'Khi ra ngoài nhớ đeo khẩu trang.'),
    ('得意', '他考试得了高分，非常得意。', 'Tā kǎoshì dé le gāofēn, fēicháng déyì.', 'Anh ấy kiểm tra được điểm cao, rất đắc ý.'),
    ('得（助动词）', '你说得很清楚，我明白了。', 'Nǐ shuō de hěn qīngchu, wǒ míngbái le.', 'Bạn nói rất rõ, tôi hiểu rồi.'),
    ('当时', '那个项目当时非常受欢迎。', 'Nàgè xiàngmù dāngshí fēicháng shòu huānyíng.', 'Dự án đó lúc đó rất được ưa chuộng.'),
    ('当', '我想当老师教学生中文。', 'Wǒ xiǎng dāng lǎoshī jiào xuéshēng zhōngwén.', 'Tôi muốn làm giáo viên dạy học sinh tiếng Trung.'),
    ('底', '请把书放在桌子的底下。', 'Qǐng bǎ shū fàng zài zhuōzi de dǐ xià.', 'Xin hãy để sách dưới đáy bàn.'),
    ('导游', '导游带我们参观了名胜古迹。', 'Dǎoyóu dài wǒmen cānguānle míngshèng gǔjì.', 'Hướng dẫn viên du lịch dẫn chúng tôi tham quan các thắng cảnh nổi tiếng.'),
    ('对面', '学校对面有一家很好的餐厅。', 'Xuéxiào duìmiàn yǒu yī jiā hěn hǎo de cāntīng.', 'Đối diện trường có một nhà hàng rất ngon.'),
    ('对话', '我们通过对话提高了口语水平。', 'Wǒmen tōngguò duìhuà tígāole kǒuyǔ shuǐpíng.', 'Chúng tôi nâng cao trình độ nói qua hội thoại.'),
    ('对于', '对于这个问题，我有不同的看法。', 'Duìyú zhège wèntí, wǒ yǒu bùtóng de kànfǎ.', 'Về vấn đề này, tôi có quan điểm khác.'),
    ('大约', '会议大约在下午三点开始。', 'Huìyì dàyuē zài xiàwǔ sān diǎn kāishǐ.', 'Cuộc họp khoảng lúc 3 giờ chiều bắt đầu.'),
    ('大概', '他大概已经回家了。', 'Tā dàgài yǐjīng huí jiā le.', 'Anh ấy khoảng đã về nhà rồi.'),
    ('大夫', '大夫建议我多休息。', 'Dàifu jiànyì wǒ duō xiūxí.', 'Bác sĩ khuyên tôi nghỉ ngơi nhiều hơn.'),
    ('大使馆', '我们明天要去大使馆办理签证。', 'Wǒmen míngtiān yào qù dàshǐguǎn bànlǐ qiānzhèng.', 'Ngày mai chúng tôi sẽ đến đại sứ quán làm visa.'),
    ('堵车', '因为堵车，我迟到了半个小时。', 'Yīnwèi dǔchē, wǒ chídào le bàn gè xiǎoshí.', 'Vì tắc đường, tôi đã trễ nửa tiếng.'),
    ('地球', '地球是我们唯一的家园，我们要保护它。', 'Dìqiú shì wǒmen wéiyī de jiāyuán, wǒmen yào bǎohù tā.', 'Địa cầu là ngôi nhà duy nhất của chúng ta, chúng ta phải bảo vệ nó.'),
    ('地点', '开会的地点已经确定在图书馆。', 'Kāihuì de dìdiǎn yǐjīng quèdìng zài túshūguǎn.', 'Địa điểm cuộc họp đã được xác định ở thư viện.'),
    ('地址', '请告诉我你的详细地址，方便邮寄。', 'Qǐng gàosu wǒ nǐ de xiángxì dìzhǐ, fāngbiàn yóujì.', 'Xin hãy cho tôi biết địa chỉ chi tiết của bạn để tiện gửi thư.'),
    ('动作', '他的动作很快，完成了所有任务。', 'Tā de dòngzuò hěn kuài, wánchéng le suǒyǒu rènwù.', 'Động tác của anh ấy rất nhanh, đã hoàn thành tất cả nhiệm vụ.'),
    ('到底', '你到底为什么不接电话？', 'Nǐ dàodǐ wèishénme bù jiē diànhuà?', 'Rốt cuộc tại sao bạn không nghe điện thoại?'),
    ('到处', '春天来了，花儿开到处都是。', 'Chūntiān lái le, huā er kāi dàochù dōu shì.', 'Mùa xuân đến, hoa nở khắp nơi.'),
    ('刀', '厨房里有一把锋利的刀。', 'Chúfáng lǐ yǒu yī bǎ fēnglì de dāo.', 'Trong bếp có một con dao sắc.'),
    ('倒', '他不小心倒了一杯水。', 'Tā bù xiǎoxīn dào le yī bēi shuǐ.', 'Anh ấy vô tình đổ một cốc nước.'),
    ('低', '这个桌子的高度太低了，我不舒服。', 'Zhè ge zhuōzi de gāodù tài dī le, wǒ bù shūfu.', 'Chiều cao của cái bàn này quá thấp, tôi cảm thấy không thoải mái.'),
    ('丢', '我昨天丢了我的手机，很着急。', 'Wǒ zuótiān diū le wǒ de shǒujī, hěn zháojí.', 'Hôm qua tôi bị mất điện thoại, rất lo lắng.'),
    ('儿童', '这个公园适合儿童玩耍，环境很安全。', 'Zhè ge gōngyuán shìhé értóng wánshuǎ, huánjìng hěn ānquán.', 'Công viên này thích hợp cho trẻ con chơi, môi trường rất an toàn.'),
    ('而', '他喜欢运动，而我更喜欢看书。', 'Tā xǐhuān yùndòng, ér wǒ gèng xǐhuān kàn shū.', 'Anh ấy thích thể thao, còn tôi thích đọc sách hơn.'),
    ('发生', '昨天小区里发生了一起交通事故。', 'Zuótiān xiǎoqū lǐ fāshēng le yī qǐ jiāotōng shìgù.', 'Hôm qua đã xảy ra một vụ tai nạn giao thông trong khu dân cư.'),
    ('负责', '他负责公司的市场宣传工作。', 'Tā fùzé gōngsī de shìchǎng xuānchuán gōngzuò.', 'Anh ấy phụ trách công việc quảng bá thị trường của công ty.'),
    ('翻译', '她在会议上做中文到英文的翻译。', 'Tā zài huìyì shàng zuò zhōngwén dào yīngwén de fānyì.', 'Cô ấy làm phiên dịch từ tiếng Trung sang tiếng Anh trong cuộc họp.'),
    ('符合', '这份简历符合公司的招聘要求。', 'Zhè fèn jiǎnlì fúhé gōngsī de zhāopìn yāoqiú.', 'Bản sơ yếu lý lịch này phù hợp với yêu cầu tuyển dụng của công ty.'),
    ('父亲', '我周末会和父亲一起去钓鱼。', 'Wǒ zhōumò huì hé fùqīn yīqǐ qù diàoyú.', 'Cuối tuần tôi sẽ đi câu cá cùng bố.'),
    ('烦恼', '工作压力让我有很多烦恼。', 'Gōngzuò yālì ràng wǒ yǒu hěn duō fánnǎo.', 'Áp lực công việc khiến tôi có nhiều phiền não.'),
    ('法律', '我们必须遵守国家的法律。', 'Wǒmen bìxū zūnshǒu guójiā de fǎlǜ.', 'Chúng ta phải tuân theo pháp luật của quốc gia.'),
    ('方面', '在学习方面，她非常努力。', 'Zài xuéxí fāngmiàn, tā fēicháng nǔlì.', 'Về phương diện học tập, cô ấy rất chăm chỉ.'),
    ('方法', '这个方法可以帮助你提高汉语水平。', 'Zhège fāngfǎ kěyǐ bāngzhù nǐ tígāo hànyǔ shuǐpíng.', 'Phương pháp này có thể giúp bạn nâng cao trình độ tiếng Trung.'),
    ('方向', '请告诉我去火车站的方向。', 'Qǐng gàosu wǒ qù huǒchē zhàn de fāngxiàng.', 'Xin hãy chỉ cho tôi phương hướng đến ga tàu.'),
    ('放松', '工作了一天后，我喜欢听音乐放松。', 'Gōngzuò le yītiān hòu, wǒ xǐhuān tīng yīnyuè fàngsōng.', 'Sau một ngày làm việc, tôi thích nghe nhạc để thư giãn.'),
    ('放暑假', '学生们很期待放暑假去旅行。', 'Xuéshēngmen hěn qídài fàng shǔjià qù lǚxíng.', 'Các học sinh rất mong chờ kỳ nghỉ hè đi du lịch.'),
    ('放弃', '他从来不轻易放弃自己的梦想。', 'Tā cónglái bù qīngyì fàngqì zìjǐ de mèngxiǎng.', 'Anh ấy không bao giờ dễ dàng từ bỏ ước mơ của mình.'),
    ('房东', '我们和房东商量了租房的问题。', 'Wǒmen hé fángdōng shāngliáng le zūfáng de wèntí.', 'Chúng tôi đã thảo luận với chủ nhà về vấn đề thuê nhà.'),
    ('富', '努力工作让他变得更加富有。', 'Nǔlì gōngzuò ràng tā biàn de gèngjiā fùyǒu.', 'Làm việc chăm chỉ đã khiến anh ấy trở nên giàu có hơn.'),
    ('复杂', '这个问题比想象中更复杂。', 'Zhège wèntí bǐ xiǎngxiàng zhōng gèng fùzá.', 'Vấn đề này phức tạp hơn so với tưởng tượng.'),
    ('复印', '请在前台复印这份文件。', 'Qǐng zài qiántái fùyìn zhè fèn wénjiàn.', 'Vui lòng phô tô tài liệu này ở quầy lễ tân.'),
    ('否则', '你得快点走，否则会迟到。', 'Nǐ děi kuài diǎn zǒu, fǒuzé huì chídào.', 'Bạn phải đi nhanh lên, nếu không thì sẽ bị trễ.'),
    ('发展', '公司正在积极发展新的市场。', 'Gōngsī zhèngzài jījí fāzhǎn xīn de shìchǎng.', 'Công ty đang tích cực phát triển thị trường mới.'),
    ('反对', '他反对这个计划的实施。', 'Tā fǎnduì zhège jìhuà de shíshī.', 'Anh ấy phản đối việc thực hiện kế hoạch này.'),
    ('份', '我点了一份炒饭。', 'Wǒ diǎn le yí fèn chǎofàn.', 'Tôi gọi một phần cơm chiên.'),
    ('付款', '你可以在这里付款。', 'Nǐ kěyǐ zài zhèlǐ fùkuǎn.', 'Bạn có thể thanh toán ở đây.'),
    ('丰富', '图书馆的藏书很丰富。', 'Túshūguǎn de cángshū hěn fēngfù.', 'Kho sách của thư viện rất phong phú.'),
    ('改变', '我决定改变我的生活方式。', 'Wǒ juédìng gǎibiàn wǒ de shēnghuó fāngshì.', 'Tôi quyết định thay đổi cách sống của mình.'),
    ('鼓励', '老师鼓励我们多练习口语。', 'Lǎoshī gǔlì wǒmen duō liànxí kǒuyǔ.', 'Giáo viên cổ vũ chúng tôi luyện nói nhiều hơn.'),
    ('高速公路', '我们开车在高速公路上旅行。', 'Wǒmen kāichē zài gāosù gōnglù shàng lǚxíng.', 'Chúng tôi lái xe đi du lịch trên đường cao tốc.'),
    ('顾客', '商店里的顾客都很满意服务。', 'Shāngdiàn lǐ de gùkè dōu hěn mǎnyì fúwù.', 'Khách hàng trong cửa hàng đều rất hài lòng với dịch vụ.'),
    ('逛', '我们下午去公园逛了一圈。', 'Wǒmen xiàwǔ qù gōngyuán guàng le yī quān.', 'Chiều nay chúng tôi đi dạo một vòng công viên.'),
    ('过程', '学习汉语的过程需要耐心。', 'Xuéxí Hànyǔ de guòchéng xūyào nàixīn.', 'Quá trình học tiếng Trung cần kiên nhẫn.'),
    ('赶', '他赶火车快要迟到了。', 'Tā gǎn huǒchē kuàiyào chídào le.', 'Anh ấy đang đuổi theo tàu để không bị trễ.'),
    ('购物', '周末我和朋友去商场购物。', 'Zhōumò wǒ hé péngyǒu qù shāngchǎng gòuwù.', 'Cuối tuần tôi và bạn đi mua sắm ở trung tâm thương mại.'),
    ('规定', '公司规定员工每天工作八小时。', 'Gōngsī guīdìng yuángōng měitiān gōngzuò bā xiǎoshí.', 'Công ty quy định nhân viên làm việc tám tiếng mỗi ngày.'),
    ('观众', '演唱会吸引了很多观众。', 'Yǎnchànghuì xīyǐn le hěn duō guānzhòng.', 'Buổi hòa nhạc thu hút rất nhiều khán giả.'),
    ('胳膊', '他胳膊受伤了，不能举重。', 'Tā gēbo shòushāng le, bùnéng jǔzhòng.', 'Cánh tay anh ấy bị thương, không thể nâng tạ.'),
    ('管理', '她负责管理公司的财务。', 'Tā fùzé guǎnlǐ gōngsī de cáiwù.', 'Cô ấy phụ trách quản lý tài chính công ty.'),
    ('果汁', '早餐时我喜欢喝橙子果汁。', 'Zǎocān shí wǒ xǐhuan hē chéngzi guǒzhī.', 'Tôi thích uống nước cam vào bữa sáng.'),
    ('敢', '你敢晚上一个人去那个公园吗？', 'Nǐ gǎn wǎnshàng yīgè rén qù nàgè gōngyuán ma?', 'Bạn dám đi một mình vào công viên đó vào buổi tối không?'),
    ('故意', '他故意迟到是为了引起注意。', 'Tā gùyì chídào shì wèile yǐnqǐ zhùyì.', 'Anh ấy cố ý đến muộn để gây chú ý.'),
    ('挂', '请把你的外套挂在门后面。', 'Qǐng bǎ nǐ de wàitào guà zài mén hòumiàn.', 'Vui lòng treo áo khoác của bạn sau cửa.'),
    ('感谢', '我非常感谢你的帮助。', 'Wǒ fēicháng gǎnxiè nǐ de bāngzhù.', 'Tôi rất cảm ơn sự giúp đỡ của bạn.'),
    ('感觉', '这首歌让我感觉很开心。', 'Zhè shǒu gē ràng wǒ gǎnjué hěn kāixīn.', 'Bài hát này khiến tôi cảm thấy rất vui.'),
    ('感情', '他们之间有很深的感情。', 'Tāmen zhījiān yǒu hěn shēn de gǎnqíng.', 'Giữa họ có tình cảm rất sâu sắc.'),
    ('感动', '他的故事让我很感动。', 'Tā de gùshì ràng wǒ hěn gǎndòng.', 'Câu chuyện của anh ấy làm tôi rất cảm động.'),
    ('广播', '学校每天早上有广播节目。', 'Xuéxiào měitiān zǎoshang yǒu guǎngbō jiémù.', 'Trường học có chương trình phát thanh mỗi buổi sáng.'),
    ('广告', '我喜欢看创意的电视广告。', 'Wǒ xǐhuān kàn chuàngyì de diànshì guǎnggào.', 'Tôi thích xem các quảng cáo truyền hình sáng tạo.'),
    ('干杯', '为了成功，我们一起干杯吧！', 'Wèile chénggōng, wǒmen yīqǐ gānbēi ba!', 'Vì thành công, chúng ta cùng nhau cạn ly nhé!'),
    ('干', '这个季节空气很干，记得多喝水。', 'Zhè ge jìjié kōngqì hěn gān, jìdé duō hē shuǐ.', 'Mùa này không khí rất khô, nhớ uống nhiều nước.'),
    ('工资', '公司每月按时发放员工的工资。', 'Gōngsī měi yuè àn shí fāfàng yuángōng de gōngzī.', 'Công ty trả lương cho nhân viên đúng hạn hàng tháng.'),
    ('够', '这笔钱够支付所有的旅行费用了。', 'Zhè bǐ qián gòu zhīfù suǒyǒu de lǚxíng fèiyòng le.', 'Số tiền này đủ để trả tất cả chi phí du lịch.'),
    ('国际', '他计划去参加一个国际会议。', 'Tā jìhuà qù cānjiā yí gè guójì huìyì.', 'Anh ấy dự định đi tham dự một hội nghị quốc tế.'),
    ('国籍', '入学时需要提供你的国籍证明。', 'Rùxué shí xūyào tígōng nǐ de guójí zhèngmíng.', 'Khi nhập học cần cung cấp giấy chứng minh quốc tịch của bạn.'),
    ('各', '各位同学请排好队，准备考试。', 'Gè wèi tóngxué qǐng pái hǎo duì, zhǔnbèi kǎoshì.', 'Mỗi bạn học sinh hãy xếp hàng chuẩn bị thi.'),
    ('功夫', '他从小学习功夫，现在功夫很好。', 'Tā cóng xiǎo xuéxí gōngfū, xiànzài gōngfū hěn hǎo.', 'Anh ấy từ nhỏ học công phu, bây giờ công phu rất tốt.'),
    ('刚', '我刚到家，你打电话来了。', 'Wǒ gāng dào jiā, nǐ dǎ diànhuà lái le.', 'Tôi vừa mới về nhà, bạn gọi điện đến.'),
    ('关键', '时间管理是成功的关键因素。', 'Shíjiān guǎnlǐ shì chénggōng de guānjiàn yīnsù.', 'Quản lý thời gian là yếu tố quan trọng để thành công.'),
    ('共同', '我们有一个共同的目标，那就是提高成绩。', 'Wǒmen yǒu yí gè gòngtóng de mùbiāo, nà jiù shì tígāo chéngjì.', 'Chúng ta có một mục tiêu giống nhau, đó là nâng cao thành tích.'),
    ('公里', '我们家到学校有三公里远。', 'Wǒmen jiā dào xuéxiào yǒu sān gōnglǐ yuǎn.', 'Nhà chúng tôi cách trường học ba km.'),
    ('光', '他的作业写光了，没有留空白。', 'Tā de zuòyè xiě guāng le, méiyǒu liú kòngbái.', 'Bài tập của anh ấy viết hết rồi, không để trống chỗ nào.'),
    ('估计', '我估计明天下雨，最好带伞。', 'Wǒ gūjì míngtiān xià yǔ, zuì hǎo dài sǎn.', 'Tôi ước lượng ngày mai sẽ mưa, tốt nhất nên mang ô.'),
    ('海洋', '科学家们研究了很多海洋生物。', 'Kēxuéjiāmen yánjiū le hěn duō hǎiyáng shēngwù.', 'Các nhà khoa học đã nghiên cứu nhiều sinh vật đại dương.'),
    ('获得', '他因为努力学习获得了奖学金。', 'Tā yīnwèi nǔlì xuéxí huòdé le jiǎngxuéjīn.', 'Anh ấy đã giành được học bổng nhờ học tập chăm chỉ.'),
    ('航班', '我的航班因为天气原因延误了。', 'Wǒ de hángbān yīnwèi tiānqì yuányīn yánwù le.', 'Chuyến bay của tôi bị hoãn vì lý do thời tiết.'),
    ('盒子', '请把礼物放进那个盒子里。', 'Qǐng bǎ lǐwù fàng jìn nàgè hézi lǐ.', 'Xin hãy cho quà vào trong cái hộp kia.'),
    ('火', '晚饭后我们围着火聊天。', 'Wǎnfàn hòu wǒmen wéizhe huǒ liáotiān.', 'Sau bữa tối, chúng tôi ngồi quanh lửa trò chuyện.'),
    ('活泼', '她是一个非常活泼的孩子。', 'Tā shì yí gè fēicháng huópō de háizi.', 'Cô ấy là một đứa trẻ rất hoạt bát.'),
    ('活动', '学校组织了很多运动活动。', 'Xuéxiào zǔzhī le hěn duō yùndòng huódòng.', 'Trường tổ chức nhiều hoạt động thể thao.'),
    ('汗', '运动后，他的汗已经湿透了衣服。', 'Yùndòng hòu, tā de hàn yǐjīng shī tòu le yīfú.', 'Sau khi vận động, mồ hôi anh ấy đã làm ướt đẫm quần áo.'),
    ('护士', '护士每天都照顾医院里的病人。', 'Hùshì měi tiān dōu zhàogù yīyuàn lǐ de bìngrén.', 'Y tá hàng ngày chăm sóc các bệnh nhân trong bệnh viện.'),
    ('怀疑', '我怀疑他没说实话。', 'Wǒ huáiyí tā méi shuō shíhuà.', 'Tôi nghi ngờ anh ấy không nói sự thật.'),
    ('寒假', '我们寒假计划去滑雪。', 'Wǒmen hánjià jìhuà qù huáxuě.', 'Chúng tôi dự định đi trượt tuyết vào kỳ nghỉ đông.'),
    ('害羞', '女孩在演讲时很害羞。', 'Nǚhái zài yǎnjiǎng shí hěn hàixiū.', 'Cô bé rất xấu hổ khi phát biểu.'),
    ('好处', '早睡有很多好处，比如精神更好。', 'Zǎo shuì yǒu hěn duō hǎochù, bǐrú jīngshén gèng hǎo.', 'Ngủ sớm có nhiều cái tốt, ví dụ như tinh thần tốt hơn.'),
    ('好像', '这件衣服好像很适合你。', 'Zhè jiàn yīfu hǎoxiàng hěn shìhé nǐ.', 'Cái áo này dường như rất hợp với bạn.'),
    ('回忆', '看这些照片让我想起美好的回忆。', 'Kàn zhèxiē zhàopiàn ràng wǒ xiǎngqǐ měihǎo de huíyì.', 'Nhìn những bức ảnh này làm tôi nhớ lại những hồi ức đẹp.'),
    ('后悔', '我后悔没有早点学习汉语。', 'Wǒ hòuhuǐ méiyǒu zǎodiǎn xuéxí Hànyǔ.', 'Tôi hối hận vì chưa học tiếng Trung sớm hơn.'),
    ('合适', '这双鞋子很合适我每天穿。', 'Zhè shuāng xiézi hěn héshì wǒ měitiān chuān.', 'Đôi giày này rất thích hợp để tôi mang hàng ngày.'),
    ('合格', '只有成绩合格的学生才能参加毕业典礼。', 'Zhǐ yǒu chéngjì hégé de xuéshēng cáinéng cānjiā bìyè diǎnlǐ.', 'Chỉ học sinh đạt yêu cầu mới có thể tham dự lễ tốt nghiệp.'),
    ('号码', '请告诉我你的电话号码，我会打电话给你。', 'Qǐng gàosù wǒ nǐ de diànhuà hàomǎ, wǒ huì dǎ diànhuà gěi nǐ.', 'Vui lòng cho tôi biết số điện thoại của bạn, tôi sẽ gọi cho bạn.'),
    ('厚', '这本书的封面很厚，感觉很结实。', 'Zhè běn shū de fēngmiàn hěn hòu, gǎnjué hěn jiēshí.', 'Bìa quyển sách này rất dày, cảm giác rất chắc chắn.'),
    ('互联网', '现在很多人通过互联网学习新的知识。', 'Xiànzài hěn duō rén tōngguò hùliánwǎng xuéxí xīn de zhīshì.', 'Bây giờ rất nhiều người học kiến thức mới thông qua mạng internet.'),
    ('互相', '同学们要互相帮助，共同完成任务。', 'Tóngxuémen yào hùxiāng bāngzhù, gòngtóng wánchéng rènwu.', 'Các bạn học sinh phải giúp đỡ lẫn nhau để hoàn thành nhiệm vụ cùng nhau.'),
    ('积极', '老师鼓励我们积极参加各种课外活动。', 'Lǎoshī gǔlì wǒmen jījí cānjiā gèzhǒng kèwài huódòng.', 'Giáo viên khuyến khích chúng tôi tích cực tham gia các hoạt động ngoại khóa.'),
    ('骄傲', '她对自己的成绩感到非常骄傲。', 'Tā duì zìjǐ de chéngjī gǎndào fēicháng jiāo''ào.', 'Cô ấy rất tự hào về thành tích của mình.'),
    ('饺子', '春节时，家家户户都会包饺子庆祝。', 'Chūnjié shí, jiājiāhùhù dōu huì bāo jiǎozi qìngzhù.', 'Vào dịp Tết Nguyên Đán, các gia đình đều sẽ gói sủi cảo để ăn mừng.'),
    ('降落', '飞机将在三十分钟后降落。', 'Fēijī jiāng zài sānshí fēnzhōng hòu jiàngluò.', 'Máy bay sẽ hạ cánh sau ba mươi phút nữa.'),
    ('降低', '为了安全，必须降低行车速度。', 'Wèile ānquán, bìxū jiàngdī xíngchē sùdù.', 'Để đảm bảo an toàn, cần phải hạ thấp tốc độ lái xe.'),
    ('镜子', '我每天早上都会照镜子整理头发。', 'Wǒ měi tiān zǎo shang dōu huì zhào jìng zi zhěng lǐ tóu fa.', 'Tôi mỗi sáng đều soi gương chỉnh tóc.'),
    ('郊区', '周末我们打算去郊区爬山放松一下。', 'Zhōu mò wǒmen dǎ suàn qù jiāo qū pá shān fàng sōng yí xià.', 'Cuối tuần chúng tôi dự định ra ngoại ô leo núi thư giãn.'),
    ('进行', '公司正在进行一个新的项目开发。', 'Gōng sī zhèng zài jìn xíng yí gè xīn de xiàng mù kāi fā.', 'Công ty đang tiến hành phát triển một dự án mới.'),
    ('距离', '学校距离我家不远，骑自行车只要十分钟。', 'Xué xiào jù lí wǒ jiā bù yuǎn, qí zì xíng chē zhǐ yào shí fēn zhōng.', 'Trường học cách nhà tôi không xa, đi xe đạp chỉ mất mười phút.'),
    ('记者', '记者采访了这位著名演员的最新电影。', 'Jì zhě cǎi fǎng le zhè wèi zhù míng yǎn yuán de zuì xīn diàn yǐng.', 'Phóng viên đã phỏng vấn diễn viên nổi tiếng này về bộ phim mới nhất.'),
    ('计划', '我们已经制定了明年的旅行计划。', 'Wǒ men yǐ jīng zhì dìng le míng nián de lǚ xíng jì huà.', 'Chúng tôi đã lập kế hoạch du lịch cho năm tới.'),
    ('警察', '警察帮助找回了丢失的钱包。', 'Jǐng chá bāng zhù zhǎo huí le diū shī de qián bāo.', 'Cảnh sát đã giúp tìm lại chiếc ví bị mất.'),
    ('解释', '老师认真解释了那道语法题的用法。', 'Lǎo shī rèn zhēn jiě shì le nà dào yǔ fǎ tí de yòng fǎ.', 'Thầy cô đã giải thích cẩn thận cách dùng câu ngữ pháp đó.'),
    ('节约', '节约用水是非常重要的环保措施。', 'Jié yuē yòng shuǐ shì fēi cháng zhòng yào de huán bǎo cuò shī.', 'Tiết kiệm nước là biện pháp bảo vệ môi trường rất quan trọng.'),
    ('节', '明天我们有两节汉语课，老师很严格。', 'Míng tiān wǒ men yǒu liǎng jié hàn yǔ kè, lǎo shī hěn yán gé.', 'Ngày mai chúng ta có hai tiết học tiếng Hán, giáo viên rất nghiêm khắc.'),
    ('聚会', '我们下周末有一个朋友聚会。', 'Wǒmen xià zhōumò yǒu yí gè péngyǒu jùhuì.', 'Cuối tuần tới chúng tôi có một buổi tụ tập bạn bè.'),
    ('继续', '请继续讲你的故事。', 'Qǐng jìxù jiǎng nǐ de gùshì.', 'Xin bạn tiếp tục kể câu chuyện của bạn.'),
    ('结果', '考试的结果比我预想的好。', 'Kǎoshì de jiéguǒ bǐ wǒ yùxiǎng de hǎo.', 'Kết quả kỳ thi tốt hơn tôi tưởng.'),
    ('经验', '他有丰富的工作经验。', 'Tā yǒu fēngfù de gōngzuò jīngyàn.', 'Anh ấy có nhiều kinh nghiệm làm việc.'),
    ('经济', '这个国家的经济正在快速发展。', 'Zhège guójiā de jīngjì zhèngzài kuàisù fāzhǎn.', 'Nền kinh tế của quốc gia này đang phát triển nhanh chóng.'),
    ('经历', '他的旅行经历很丰富。', 'Tā de lǚxíng jīnglì hěn fēngfù.', 'Anh ấy có nhiều trải nghiệm du lịch phong phú.'),
    ('紧张', '考试前我感到非常紧张。', 'Kǎoshì qián wǒ gǎndào fēicháng jǐnzhāng.', 'Tôi cảm thấy rất căng thẳng trước kỳ thi.'),
    ('精彩', '这场电影非常精彩。', 'Zhè chǎng diànyǐng fēicháng jīngcǎi.', 'Bộ phim này rất hấp dẫn.'),
    ('竟然', '他竟然忘了重要的会议时间。', 'Tā jìngrán wàngle zhòngyào de huìyì shíjiān.', 'Anh ấy mà lại quên thời gian cuộc họp quan trọng.'),
    ('竞争', '这家公司在市场上竞争很激烈。', 'Zhè jiā gōngsī zài shìchǎng shàng jìngzhēng hěn jīliè.', 'Công ty này cạnh tranh rất gay gắt trên thị trường.'),
    ('究竟', '你究竟喜欢什么样的音乐？', 'Nǐ jiūjìng xǐhuan shénme yàng de yīnyuè?', 'Rốt cuộc bạn thích loại nhạc nào?'),
    ('积累', '学习需要时间和经验的积累。', 'Xuéxí xūyào shíjiān hé jīngyàn de jīlěi.', 'Học tập cần sự tích lũy về thời gian và kinh nghiệm.'),
    ('禁止', '这里禁止吸烟，请注意保护环境。', 'Zhèlǐ jìnzhǐ xīyān, qǐng zhùyì bǎohù huánjìng.', 'Ở đây cấm hút thuốc, xin chú ý bảo vệ môi trường.'),
    ('激动', '她收到录取通知，十分激动。', 'Tā shōudào lùqǔ tōngzhī, shífēn jīdòng.', 'Cô ấy nhận được thông báo trúng tuyển, rất xúc động.'),
    ('景色', '爬山的时候可以看到美丽的景色。', 'Pá shān de shíhòu kěyǐ kàn dào měilì de jǐngsè.', 'Khi leo núi có thể nhìn thấy cảnh sắc đẹp.'),
    ('既然', '既然天气不好，我们就不去郊游了。', 'Jìrán tiānqì bù hǎo, wǒmen jiù bù qù jiāoyóu le.', 'Đã trời không đẹp, chúng ta không đi dã ngoại nữa.'),
    ('教育', '父母对孩子的教育非常重要。', 'Fùmǔ duì háizi de jiàoyù fēicháng zhòngyào.', 'Giáo dục của cha mẹ đối với con cái rất quan trọng.'),
    ('教授', '这位教授在大学里教中文。', 'Zhè wèi jiàoshòu zài dàxué lǐ jiāo zhōngwén.', 'Giáo sư này dạy tiếng Trung ở trường đại học.'),
    ('接着', '他先介绍自己，接着讲了项目计划。', 'Tā xiān jièshào zìjǐ, jiēzhe jiǎng le xiàngmù jìhuà.', 'Anh ấy trước hết giới thiệu bản thân, tiếp theo nói về kế hoạch dự án.'),
    ('接受', '她很勇敢地接受了新的挑战。', 'Tā hěn yǒnggǎn de jiēshòu le xīn de tiǎozhàn.', 'Cô ấy rất dũng cảm tiếp nhận thử thách mới.'),
    ('拒绝', '他拒绝了这份工作邀请。', 'Tā jùjué le zhè fèn gōngzuò yāoqǐng.', 'Anh ấy đã từ chối lời mời làm việc này.'),
    ('技术', '他学习了很多电脑技术。', 'Tā xuéxí le hěn duō diànnǎo jìshù.', 'Anh ấy đã học rất nhiều kỹ thuật máy tính.'),
    ('建议', '老师建议我们多读书。', 'Lǎoshī jiànyì wǒmen duō dúshū.', 'Giáo viên khuyên chúng tôi nên đọc nhiều sách hơn.'),
    ('尽管', '尽管天气不好，我们还是去旅行了。', 'Jǐnguǎn tiānqì bù hǎo, wǒmen háishì qù lǚxíng le.', 'Tuy rằng thời tiết không tốt, chúng tôi vẫn đi du lịch.'),
    ('将来', '将来我想成为一名医生。', 'Jiānglái wǒ xiǎng chéngwéi yī míng yīshēng.', 'Tương lai tôi muốn trở thành bác sĩ.'),
    ('寄', '我寄了一封信给朋友。', 'Wǒ jì le yī fēng xìn gěi péngyǒu.', 'Tôi đã gửi một lá thư cho bạn.'),
    ('家具', '新房子里有很多漂亮的家具。', 'Xīn fángzi lǐ yǒu hěn duō piàoliang de jiājù.', 'Trong nhà mới có rất nhiều đồ gia dụng đẹp.'),
    ('奖金', '他因为表现好得到了奖金。', 'Tā yīnwèi biǎoxiàn hǎo dédào le jiǎngjīn.', 'Anh ấy đã nhận được học bổng vì表现 tốt.'),
    ('基础', '学习好需要有坚实的基础。', 'Xuéxí hǎo xūyào yǒu jiānshí de jīchǔ.', 'Học tốt cần có nền tảng vững chắc.'),
    ('坚持', '她每天坚持跑步一个小时。', 'Tā měitiān jiānchí pǎobù yī gè xiǎoshí.', 'Cô ấy kiên trì chạy bộ một giờ mỗi ngày.'),
    ('及时', '医生及时救治了病人。', 'Yīshēng jíshí jiùzhì le bìngrén.', 'Bác sĩ đã cứu chữa bệnh nhân kịp thời.'),
    ('即使', '即使下雨，我也要去跑步。', 'Jíshǐ xiàyǔ, wǒ yě yào qù pǎobù.', 'Cho dù trời mưa, tôi vẫn sẽ đi chạy bộ.'),
    ('加班', '公司决定这个月底加班完成项目。', 'Gōngsī juédìng zhège yuèdǐ jiābān wánchéng xiàngmù.', 'Công ty quyết định tăng ca để hoàn thành dự án vào cuối tháng này.'),
    ('加油站', '我们在加油站停下来加满了油。', 'Wǒmen zài jiāyóuzhàn tíng xiàlái jiā mǎn le yóu.', 'Chúng tôi đã dừng lại ở cây xăng để đổ đầy xăng.'),
    ('减肥', '她正在努力减肥，减少甜食摄入。', 'Tā zhèngzài nǔlì jiǎnféi, jiǎnshǎo tiánshí shèrù.', 'Cô ấy đang nỗ lực giảm béo, cắt giảm lượng đồ ngọt.'),
    ('减少', '为了环保，我们需要减少塑料使用。', 'Wèile huánbǎo, wǒmen xūyào jiǎnshǎo sùliào shǐyòng.', 'Để bảo vệ môi trường, chúng ta cần giảm sử dụng nhựa.'),
    ('假', '这件衣服是假的，不是名牌。', 'Zhè jiàn yīfu shì jiǎ de, bù shì míngpái.', 'Chiếc áo này là hàng giả, không phải hàng hiệu.'),
    ('价格', '这家店的价格比别的地方便宜。', 'Zhè jiā diàn de jiàgé bǐ bié de dìfang piányi.', 'Giá cả của cửa hàng này rẻ hơn nơi khác.'),
    ('京剧', '我喜欢看京剧里的传统表演。', 'Wǒ xǐhuan kàn jīngjù lǐ de chuántǒng biǎoyǎn.', 'Tôi thích xem các màn trình diễn truyền thống trong kinh kịch.'),
    ('交通', '早上交通很拥堵，上班迟到了。', 'Zǎoshang jiāotōng hěn yōngdǔ, shàngbān chídào le.', 'Giao thông buổi sáng rất tắc nghẽn, tôi đi làm bị trễ.'),
    ('交流', '我们班组织了一个文化交流活动。', 'Wǒmen bān zǔzhī le yí gè wénhuà jiāoliú huódòng.', 'Lớp chúng tôi tổ chức một hoạt động giao lưu văn hóa.'),
    ('交', '请你明天交作业给老师。', 'Qǐng nǐ míngtiān jiāo zuòyè gěi lǎoshī.', 'Ngày mai bạn hãy nộp bài tập cho cô giáo.'),
    ('举行', '学校将在大厅举行毕业典礼。', 'Xuéxiào jiāng zài dàtīng jǔxíng bìyè diǎnlǐ.', 'Trường sẽ tổ chức lễ tốt nghiệp ở phòng lớn.'),
    ('举办', '他公司经常举办各种展览会。', 'Tā gōngsī jīngcháng jǔbàn gè zhǒng zhǎnlǎn huì.', 'Công ty của anh ấy thường xuyên tổ chức các triển lãm khác nhau.'),
    ('举', '请你举手回答老师的问题。', 'Qǐng nǐ jǔ shǒu huídá lǎoshī de wèntí.', 'Xin bạn giơ tay trả lời câu hỏi của thầy cô.'),
    ('开玩笑', '别生气，我只是开玩笑。', 'Bié shēngqì, wǒ zhǐshì kāi wánxiào.', 'Đừng giận, tôi chỉ đang đùa thôi.'),
    ('苦', '这种药虽然苦，但很有效。', 'Zhè zhǒng yào suīrán kǔ, dàn hěn yǒuxiào.', 'Loại thuốc này mặc dù đắng nhưng rất hiệu quả.'),
    ('肯定', '我肯定他已经完成了任务。', 'Wǒ kěndìng tā yǐjīng wánchéng le rènwù.', 'Tôi khẳng định anh ấy đã hoàn thành nhiệm vụ rồi.'),
    ('考虑', '请你认真考虑这个提议。', 'Qǐng nǐ rènzhēn kǎolǜ zhège tíyì.', 'Xin bạn suy nghĩ kỹ về đề xuất này.'),
    ('空气', '这里的空气很新鲜，适合运动。', 'Zhèlǐ de kōngqì hěn xīnxiān, shìhé yùndòng.', 'Không khí ở đây rất trong lành, phù hợp để tập thể dục.'),
    ('空', '教室里有两个空位，你可以坐那里。', 'Jiàoshì lǐ yǒu liǎng gè kōng wèi, nǐ kěyǐ zuò nàlǐ.', 'Trong lớp học có hai chỗ trống, bạn có thể ngồi đó.'),
    ('科学', '科学告诉我们每天锻炼对健康有好处。', 'Kēxué gàosù wǒmen měitiān duànliàn duì jiànkāng yǒu hǎochù.', 'Khoa học nói với chúng ta rằng tập thể dục mỗi ngày có lợi cho sức khỏe.'),
    ('矿泉水', '登山时请带足够的矿泉水。', 'Dēngshān shí qǐng dài zúgòu de kuàngquánshuǐ.', 'Khi leo núi hãy mang đủ nước khoáng.'),
    ('看法', '老师对这个问题有不同的看法。', 'Lǎoshī duì zhège wèntí yǒu bùtóng de kànfǎ.', 'Giáo viên có quan điểm khác nhau về vấn đề này.'),
    ('烤鸭', '我们打算晚上去餐厅吃烤鸭。', 'Wǒmen dǎsuàn wǎnshàng qù cāntīng chī kǎoyā.', 'Chúng tôi dự định tối nay đi nhà hàng ăn vịt quay.'),
    ('棵', '花园里有三棵苹果树。', 'Huāyuán lǐ yǒu sān kē píngguǒ shù.', 'Trong vườn có ba cây táo.'),
    ('恐怕', '恐怕明天会下雨，我们改天去吧。', 'Kǒngpà míngtiān huì xiàyǔ, wǒmen gǎitiān qù ba.', 'E rằng ngày mai sẽ mưa, chúng ta đi vào ngày khác nhé.'),
    ('开心', '听到好消息，她非常开心。', 'Tīngdào hǎo xiāoxi, tā fēicháng kāixīn.', 'Nghe tin vui, cô ấy rất vui vẻ.'),
    ('客厅', '客厅里摆着一张大沙发。', 'Kètīng lǐ bǎizhe yī zhāng dà shāfā.', 'Trong phòng khách có một chiếc ghế sofa lớn.'),
    ('困难', '学汉语有时会遇到困难，但不能放弃。', 'Xué Hànyǔ yǒu shí huì yù dào kùnnán, dàn bùnéng fàngqì.', 'Học tiếng Trung đôi khi gặp khó khăn, nhưng không được bỏ cuộc.'),
    ('困', '我昨天没睡好，今天觉得很困。', 'Wǒ zuótiān méi shuì hǎo, jīntiān juéde hěn kùn.', 'Hôm qua tôi không ngủ ngon, hôm nay cảm thấy rất buồn ngủ.'),
    ('咳嗽', '他感冒了，一直在咳嗽。', 'Tā gǎnmào le, yīzhí zài késou.', 'Anh ấy bị cảm, cứ ho mãi.'),
    ('可是', '我想去旅游，可是现在没有时间。', 'Wǒ xiǎng qù lǚyóu, kěshì xiànzài méiyǒu shíjiān.', 'Tôi muốn đi du lịch, nhưng bây giờ không có thời gian.'),
    ('可惜', '你没来参加晚会，真可惜。', 'Nǐ méi lái cānjiā wǎnhuì, zhēn kěxī.', 'Bạn không đến tham gia tiệc tối, thật đáng tiếc.'),
    ('可怜', '那只小猫看起来很可怜。', 'Nà zhī xiǎo māo kàn qǐlái hěn kělián.', 'Con mèo nhỏ đó trông rất đáng thương.'),
    ('垃圾桶', '请把垃圾扔进垃圾桶里。', 'Qǐng bǎ lājītǒng rēng jìn lājītǒng lǐ.', 'Xin hãy bỏ rác vào thùng rác.'),
    ('零钱', '我没有零钱，只能付现金了。', 'Wǒ méiyǒu língqián, zhǐ néng fù xiànjīn le.', 'Tôi không có tiền lẻ, chỉ có thể trả tiền mặt.'),
    ('连', '他连饭都没有吃就去上班了。', 'Tā lián fàn dōu méiyǒu chī jiù qù shàngbān le.', 'Anh ấy连 cơm cũng không ăn đã đi làm.'),
    ('辣', '这道菜很辣，你确定要试吗？', 'Zhè dào cài hěn là, nǐ quèdìng yào shì ma?', 'Món ăn này rất cay, bạn chắc chắn muốn thử không?'),
    ('联系', '如果有问题，请随时联系我。', 'Rúguǒ yǒu wèntí, qǐng suíshí liánxì wǒ.', 'Nếu có vấn đề, xin hãy liên hệ với tôi bất cứ lúc nào.'),
    ('老虎', '动物园里的老虎看起来非常凶猛。', 'Dòngwùyuán lǐ de lǎohǔ kàn qǐlái fēicháng xiōngměng.', 'Con hổ trong sở thú trông rất hung dữ.'),
    ('礼貌', '和别人交谈时，一定要注意礼貌。', 'Hé biérén jiāotán shí, yídìng yào zhùyì lǐmào.', 'Khi nói chuyện với người khác, nhất định phải chú ý lễ phép.'),
    ('礼拜天', '我们礼拜天去公园散步好吗？', 'Wǒmen lǐbàitiān qù gōngyuán sànbù hǎo ma?', 'Chủ nhật chúng ta đi công viên đi dạo nhé?'),
    ('留', '请你留在教室里完成作业。', 'Qǐng nǐ liú zài jiàoshì lǐ wánchéng zuòyè.', 'Xin bạn hãy ở lại trong lớp làm bài tập.'),
    ('理解', '老师说话的时候，我们要努力理解内容。', 'Lǎoshī shuōhuà de shíhòu, wǒmen yào nǔlì lǐjiě nèiróng.', 'Khi cô giáo nói, chúng ta phải cố gắng hiểu nội dung.'),
    ('理想', '他的理想是成为一名医生帮助别人。', 'Tā de lǐxiǎng shì chéngwéi yī míng yīshēng bāngzhù biérén.', 'Lý tưởng của anh ấy là trở thành bác sĩ để giúp người khác.'),
    ('理发', '我明天下午去理发，想换个新发型。', 'Wǒ míngtiān xiàwǔ qù lǐfà, xiǎng huàn gè xīn fàxíng.', 'Chiều mai tôi sẽ đi cắt tóc, muốn thay kiểu tóc mới.'),
    ('浪费', '不要浪费食物，要珍惜每一口饭。', 'Bù yào làngfèi shíwù, yào zhēnxī měi yī kǒu fàn.', 'Đừng lãng phí thức ăn, phải trân trọng từng miếng cơm.'),
    ('浪漫', '他们在海边度过了一个浪漫的晚上。', 'Tāmen zài hǎibiān dùguòle yí gè làngmàn de wǎnshàng.', 'Họ đã trải qua một buổi tối lãng mạn bên bờ biển.'),
    ('流行', '这种音乐最近非常流行，很多年轻人喜欢。', 'Zhè zhǒng yīnyuè zuìjìn fēicháng liúxíng, hěn duō niánqīng rén xǐhuan.', 'Loại nhạc này gần đây rất thịnh hành, nhiều người trẻ thích.'),
    ('流利', '他说英语很流利，能和外国人自如交流。', 'Tā shuō Yīngyǔ hěn liúlì, néng hé wàiguó rén zìrú jiāoliú.', 'Anh ấy nói tiếng Anh rất lưu loát, có thể giao tiếp tự nhiên với người nước ngoài.'),
    ('来自', '她来自北京，现在在上海工作。', 'Tā láizì Běijīng, xiànzài zài Shànghǎi gōngzuò.', 'Cô ấy đến từ Bắc Kinh, hiện đang làm việc ở Thượng Hải.'),
    ('来得及', '我们快走，应该来得及赶上电影开场。', 'Wǒmen kuài zǒu, yīnggāi láidejí gǎn shàng diànyǐng kāichǎng.', 'Chúng ta đi nhanh, có thể kịp xem phim bắt đầu.'),
    ('来不及', '他迟到了，已经来不及参加会议了。', 'Tā chídào le, yǐjīng láibují cānjiā huìyì le.', 'Anh ấy đến muộn, đã không kịp tham gia cuộc họp.'),
    ('旅行', '我计划今年夏天去欧洲旅行。', 'Wǒ jìhuà jīnnián xiàtiān qù Ōuzhōu lǚxíng.', 'Tôi dự định hè này đi du lịch châu Âu.'),
    ('拉', '请帮我拉开这扇窗户。', 'Qǐng bāng wǒ lā kāi zhè shàn chuānghù.', 'Làm ơn giúp tôi kéo mở cửa sổ này.'),
    ('懒', '他这个星期天太懒了，一整天都没起床。', 'Tā zhège xīngqītiān tài lǎn le, yī zhěng tiān dōu méi qǐchuáng.', 'Anh ấy chủ nhật này rất lười, cả ngày không dậy.'),
    ('律师', '我的姐姐是一名律师，专门处理合同问题。', 'Wǒ de jiějie shì yī míng lǜshī, zhuānmén chǔlǐ hétong wèntí.', 'Chị gái tôi là luật sư, chuyên xử lý các vấn đề hợp đồng.'),
    ('另外', '我们买了水果，另外还买了一些面包。', 'Wǒmen mǎi le shuǐguǒ, lìngwài hái mǎi le yìxiē miànbāo.', 'Chúng tôi đã mua hoa quả, ngoài ra còn mua một ít bánh mì.'),
    ('厉害', '他的篮球技术很厉害，经常得分最高。', 'Tā de lánqiú jìshù hěn lìhài, jīngcháng défēn zuì gāo.', 'Kỹ thuật bóng rổ của anh ấy rất lợi hại, thường xuyên ghi điểm cao nhất.'),
    ('力气', '他搬这个箱子需要很大的力气。', 'Tā bān zhè ge xiāngzi xūyào hěn dà de lìqi.', 'Anh ấy cần rất nhiều sức lực để khiêng cái hộp này.'),
    ('凉快', '晚上公园里的空气非常凉快。', 'Wǎnshàng gōngyuán lǐ de kōngqì fēicháng liángkuai.', 'Không khí trong công viên buổi tối rất mát mẻ.'),
    ('冷静', '遇到困难时要保持冷静思考。', 'Yù dào kùnnan shí yào bǎochí lěngjìng sīkǎo.', 'Khi gặp khó khăn cần giữ bình tĩnh suy nghĩ.'),
    ('俩', '那俩人是好朋友，经常一起学习。', 'Nà liǎ ge rén shì hǎo péngyǒu, jīngcháng yìqǐ xuéxí.', 'Hai người đó là bạn tốt, thường học cùng nhau.'),
    ('例如', '我们要学习各种水果，例如苹果和香蕉。', 'Wǒmen yào xuéxí gè zhǒng shuǐguǒ, lìrú píngguǒ hé xiāngjiāo.', 'Chúng ta cần học các loại trái cây khác nhau, ví dụ như táo và chuối.'),
    ('乱', '他的房间很乱，需要整理一下。', 'Tā de fángjiān hěn luàn, xūyào zhěnglǐ yíxià.', 'Phòng của anh ấy rất lộn xộn, cần dọn dẹp một chút.'),
    ('麻烦', '请你帮我一个忙，不想麻烦别人。', 'Qǐng nǐ bāng wǒ yí ge máng, bù xiǎng máfan biérén.', 'Làm ơn giúp tôi một việc, tôi không muốn làm phiền người khác.'),
    ('马虎', '做作业不能马虎，要认真检查。', 'Zuò zuòyè bù néng mǎhu, yào rènzhēn jiǎnchá.', 'Làm bài tập không thể qua loa, phải kiểm tra cẩn thận.'),
    ('迷路', '他在大城市里迷路了，找不到回家的路。', 'Tā zài dà chéngshì lǐ mílù le, zhǎo bù dào huíjiā de lù.', 'Anh ấy bị lạc đường trong thành phố lớn, không tìm được đường về nhà.'),
    ('美丽', '这座城市的风景非常美丽。', 'Zhè zuò chéngshì de fēngjǐng fēicháng měilì.', 'Phong cảnh của thành phố này rất đẹp.'),
    ('秒', '电影只用了几秒就显示了结局。', 'Diànyǐng zhǐ yòngle jǐ miǎo jiù xiǎnshìle jiéjú.', 'Bộ phim chỉ mất vài giây đã hiển thị kết thúc.'),
    ('目的', '我们旅行的目的就是放松心情。', 'Wǒmen lǚxíng de mùdì jiùshì fàngsōng xīnqíng.', 'Mục đích của chuyến du lịch của chúng tôi là thư giãn tinh thần.'),
    ('满', '杯子里水满了，别再加了。', 'Bēizi lǐ shuǐ mǎnle, bié zài jiāle.', 'Trong cốc nước đã đầy, đừng thêm nữa.'),
    ('民族', '中国有五十六个民族。', 'Zhōngguó yǒu wǔshíliù gè mínzú.', 'Trung Quốc có 56 dân tộc.'),
    ('毛巾', '请帮我拿一条干净的毛巾。', 'Qǐng bāng wǒ ná yì tiáo gānjìng de máojīn.', 'Làm ơn lấy cho tôi một chiếc khăn bông sạch.'),
    ('毛', '猫的毛非常柔软。', 'Māo de máo fēicháng róuruǎn.', 'Lông mèo rất mềm mại.'),
    ('母亲', '母亲节我给母亲买了花。', 'Mǔqīn jié wǒ gěi mǔqīn mǎile huā.', 'Ngày của mẹ tôi đã mua hoa cho mẹ.'),
    ('梦', '昨晚我做了一个奇怪的梦。', 'Zuówǎn wǒ zuòle yí gè qíguài de mèng.', 'Tối qua tôi đã mơ một giấc mơ kỳ lạ.'),
    ('密码', '请不要告诉别人你的密码。', 'Qǐng bú yào gàosu biérén nǐ de mìmǎ.', 'Xin đừng nói mật khẩu của bạn cho người khác.'),
    ('免费', '这家咖啡店提供免费的Wi-Fi。', 'Zhè jiā kāfēidiàn tígōng miǎnfèi de Wi-Fi.', 'Quán cà phê này cung cấp Wi-Fi miễn phí.'),
    ('耐心', '学习新技能需要耐心和坚持。', 'Xué xí xīn jì néng xū yào nài xīn hé jiān chí.', 'Học kỹ năng mới cần có sự nhẫn nại và kiên trì.'),
    ('难道', '难道你不想参加这个比赛吗？', 'Nán dào nǐ bù xiǎng cān jiā zhè gè bǐ sài ma?', 'Lẽ nào bạn không muốn tham gia cuộc thi này sao?'),
    ('难受', '我感冒了，头很难受。', 'Wǒ gǎn mào le, tóu hěn nán shòu.', 'Tôi bị cảm, đầu rất khó chịu.'),
    ('能力', '他的工作能力让老板很满意。', 'Tā de gōng zuò néng lì ràng lǎo bǎn hěn mǎn yì.', 'Năng lực làm việc của anh ấy khiến sếp rất hài lòng.'),
    ('暖和', '春天的天气终于暖和起来了。', 'Chūn tiān de tiān qì zhōng yú nuǎn huo qǐ lái le.', 'Thời tiết mùa xuân cuối cùng cũng ấm áp trở lại.'),
    ('弄', '别弄坏了这个贵重的东西。', 'Bié nòng huài le zhè gè guì zhòng de dōng xī.', 'Đừng làm hỏng đồ vật quý giá này.'),
    ('年龄', '年龄不是学习的障碍。', 'Nián líng bú shì xué xí de zhàng ài.', 'Tuổi tác không phải là trở ngại cho việc học.'),
    ('内容', '请你检查一下这篇文章的内容。', 'Qǐng nǐ jiǎn chá yī xià zhè piān wén zhāng de nèi róng.', 'Hãy kiểm tra nội dung bài viết này.'),
    ('内', '公司的重要资料都保存在安全的柜子内。', 'Gōng sī de zhòng yào zī liào dōu bǎo cún zài ān quán de guì zi nèi.', 'Tài liệu quan trọng của công ty đều được bảo quản bên trong tủ an toàn.'),
    ('偶尔', '我偶尔会去附近的公园散步。', 'Wǒ ǒu ěr huì qù fù jìn de gōng yuán sàn bù.', 'Tôi đôi khi sẽ đi dạo trong công viên gần đây.'),
    ('排队', '请大家排队等候买票。', 'Qǐng dàjiā páiduì děnghòu mǎi piào.', 'Mọi người hãy xếp hàng chờ mua vé.'),
    ('骗', '他不应该骗朋友的钱。', 'Tā bù yīnggāi piàn péngyǒu de qián.', 'Anh ta không nên lừa tiền bạn bè.'),
    ('陪', '我这个周末会陪你去看电影。', 'Wǒ zhège zhōumò huì péi nǐ qù kàn diànyǐng.', 'Cuối tuần này tôi sẽ cùng bạn đi xem phim.'),
    ('葡萄', '葡萄是我最喜欢的水果。', 'Pútáo shì wǒ zuì xǐhuān de shuǐguǒ.', 'Nho là loại trái cây tôi thích nhất.'),
    ('脾气', '他脾气不好，很容易生气。', 'Tā píqì bù hǎo, hěn róngyì shēngqì.', 'Anh ấy tính khí không tốt, rất dễ nổi giận.'),
    ('篇', '老师让我们写一篇日记。', 'Lǎoshī ràng wǒmen xiě yì piān rìjì.', 'Giáo viên yêu cầu chúng tôi viết một bài nhật ký.'),
    ('破', '我的鞋子破了，得买一双新的。', 'Wǒ de xiézi pò le, děi mǎi yì shuāng xīn de.', 'Đôi giày của tôi bị rách, phải mua đôi mới.'),
    ('皮肤', '夏天晒太阳太久对皮肤不好。', 'Xiàtiān shài tàiyáng tài jiǔ duì pífū bù hǎo.', 'Mùa hè phơi nắng quá lâu không tốt cho da.'),
    ('普遍', '使用手机在年轻人中很普遍。', 'Shǐyòng shǒujī zài niánqīng rén zhōng hěn pǔbiàn.', 'Việc sử dụng điện thoại rất phổ biến trong giới trẻ.'),
    ('普通话', '学校要求学生说普通话。', 'Xuéxiào yāoqiú xuéshēng shuō pǔtōnghuà.', 'Trường học yêu cầu học sinh nói tiếng phổ thông.'),
    ('排列', '请帮我把这些书按照颜色排列。', 'Qǐng bāng wǒ bǎ zhèxiē shū ànzhào yánsè páiliè.', 'Làm ơn giúp tôi xếp những cuốn sách này theo màu sắc.'),
    ('批评', '老师批评了同学们作业的错误。', 'Lǎoshī pīpíng le tóngxuémen zuòyè de cuòwù.', 'Giáo viên đã phê bình lỗi của các bạn học sinh trong bài tập.'),
    ('平时', '我平时喜欢早上跑步锻炼身体。', 'Wǒ píngshí xǐhuān zǎoshang pǎobù duànliàn shēntǐ.', 'Bình thường tôi thích chạy bộ buổi sáng để tập thể dục.'),
    ('判断', '根据他的表现，我判断他很努力学习。', 'Gēnjù tā de biǎoxiàn, wǒ pànduàn tā hěn nǔlì xuéxí.', 'Dựa vào表现 của anh ấy, tôi phán đoán anh ấy học rất chăm chỉ.'),
    ('乒乓球', '我们周末去公园打乒乓球吧。', 'Wǒmen zhōumò qù gōngyuán dǎ pīngpāngqiú ba.', 'Cuối tuần chúng ta đi công viên chơi bóng bàn nhé.'),
    ('其次', '首先我要感谢大家，其次分享我的经验。', 'Shǒuxiān wǒ yào gǎnxiè dàjiā, qícì fēnxiǎng wǒ de jīngyàn.', 'Trước hết tôi muốn cảm ơn mọi người, tiếp theo chia sẻ kinh nghiệm của tôi.'),
    ('轻松', '假期里我感觉生活很轻松，没有压力。', 'Jiàqī lǐ wǒ gǎnjué shēnghuó hěn qīngsōng, méiyǒu yālì.', 'Trong kỳ nghỉ tôi cảm thấy cuộc sống rất thoải mái, không có áp lực.'),
    ('轻', '这只箱子很轻，一个人也能提。', 'Zhè zhī xiāngzi hěn qīng, yī ge rén yě néng tí.', 'Chiếc vali này rất nhẹ, một người cũng có thể xách.'),
    ('缺点', '每个人都有缺点，重要的是努力改正。', 'Měi gèrén dōu yǒu quēdiǎn, zhòngyào de shì nǔlì gǎizhèng.', 'Mỗi người đều có khuyết điểm, điều quan trọng là cố gắng sửa chữa.'),
    ('缺少', '这个菜缺少一点盐，味道不够浓。', 'Zhège cài quēshǎo yīdiǎn yán, wèidào bú gòu nóng.', 'Món ăn này thiếu một chút muối, vị không đủ đậm đà.'),
    ('签证', '我已经办好了去法国的签证。', 'Wǒ yǐjīng bàn hǎo le qù Fǎguó de qiānzhèng.', 'Tôi đã làm xong visa đi Pháp.'),
    ('穷', '那家商店的老板年轻但很穷。', 'Nà jiā shāngdiàn de lǎobǎn niánqīng dàn hěn qióng.', 'Chủ cửa hàng đó còn trẻ nhưng rất nghèo.'),
    ('确实', '他的建议确实有帮助。', 'Tā de jiànyì quèshí yǒu bāngzhù.', 'Lời khuyên của anh ấy thật sự có ích.'),
    ('气候', '这个城市的气候很适合种花。', 'Zhège chéngshì de qìhòu hěn shìhé zhòng huā.', 'Khí hậu của thành phố này rất thích hợp để trồng hoa.'),
    ('桥', '我们一起走过那座古老的桥。', 'Wǒmen yīqǐ zǒuguò nà zuò gǔlǎo de qiáo.', 'Chúng ta đã cùng nhau đi qua cây cầu cổ đó.'),
    ('敲', '请你敲门后再进去。', 'Qǐng nǐ qiāo mén hòu zài jìnrù.', 'Xin bạn hãy gõ cửa rồi mới vào.'),
    ('情况', '公司现在的经济情况很稳定。', 'Gōngsī xiànzài de jīngjì qíngkuàng hěn wěndìng.', 'Tình hình kinh tế của công ty hiện giờ rất ổn định.'),
    ('巧克力', '她喜欢吃黑巧克力。', 'Tā xǐhuān chī hēi qiǎokèlì.', 'Cô ấy thích ăn sô cô la đen.'),
    ('取', '你可以去银行取钱。', 'Nǐ kěyǐ qù yínháng qǔ qián.', 'Bạn có thể đi ngân hàng lấy tiền.'),
    ('却', '他本来想去旅游，却突然生病了。', 'Tā běnlái xiǎng qù lǚyóu, què túrán shēngbìng le.', 'Anh ấy ban đầu định đi du lịch, nhưng lại đột nhiên bị ốm.'),
    ('千万', '你千万别忘了明天的会议。', 'Nǐ qiān wàn bié wàng le míng tiān de huì yì.', 'Bạn nhất thiết không được quên cuộc họp ngày mai.'),
    ('区别', '这两种水果的区别很明显。', 'Zhè liǎng zhǒng shuǐ guǒ de qū bié hěn míng xiǎn.', 'Sự khác biệt giữa hai loại trái cây này rất rõ ràng.'),
    ('其中', '我买了五本书，其中三本是小说。', 'Wǒ mǎi le wǔ běn shū, qí zhōng sān běn shì xiǎo shuō.', 'Tôi đã mua năm cuốn sách, trong đó ba cuốn là tiểu thuyết.'),
    ('全部', '他们完成了全部的工作任务。', 'Tā men wán chéng le quán bù de gōng zuò rèn wu.', 'Họ đã hoàn thành toàn bộ nhiệm vụ công việc.'),
    ('亲戚', '今年春节我会和亲戚们一起庆祝。', 'Jīn nián chūn jié wǒ huì hé qīn qi men yì qǐ qìng zhù.', 'Năm nay Tết tôi sẽ ăn Tết cùng với họ hàng.'),
    ('然而', '他很努力，然而成绩不理想。', 'Tā hěn nǔ lì, rán ér chéng jì bù lǐ xiǎng.', 'Anh ấy rất cố gắng, vậy mà kết quả không như ý.'),
    ('热闹', '晚上市场非常热闹，有很多小吃摊。', 'Wǎn shàng shì chǎng fēi cháng rè nào, yǒu hěn duō xiǎo chī tān.', 'Buổi tối chợ rất náo nhiệt, có nhiều quầy ăn vặt.'),
    ('日记', '我每天晚上都会写日记。', 'Wǒ měi tiān wǎn shàng dōu huì xiě rì jì.', 'Tôi đều viết nhật kí mỗi tối.'),
    ('扔', '请不要随地扔垃圾。', 'Qǐng bù yào suí dì rēng lā jī.', 'Xin đừng vứt rác bừa bãi.'),
    ('入口', '商场的入口在左边。', 'Shāng chǎng de rù kǒu zài zuǒ biān.', 'Cửa vào của trung tâm thương mại ở bên trái.'),
    ('任务', '经理交给我一个新的任务。', 'Jīnglǐ jiāo gěi wǒ yī gè xīn de rènwù.', 'Quản lý giao cho tôi một nhiệm vụ mới.'),
    ('任何', '你可以在任何时间联系我。', 'Nǐ kěyǐ zài rènhé shíjiān liánxì wǒ.', 'Bạn có thể liên lạc với tôi vào bất kỳ thời gian nào.'),
    ('仍然', '尽管下雨，他仍然去跑步。', 'Jǐnguǎn xià yǔ, tā réngrán qù pǎobù.', 'Mặc dù trời mưa, anh ấy vẫn đi chạy bộ.'),
    ('散步', '晚上我们去公园散步吧。', 'Wǎnshàng wǒmen qù gōngyuán sànbù ba.', 'Buổi tối chúng ta đi công viên tản bộ nhé.'),
    ('首都', '北京是中国的首都。', 'Běijīng shì Zhōngguó de shǒudū.', 'Bắc Kinh là thủ đô của Trung Quốc.'),
    ('首先', '首先，请大家安静。', 'Shǒuxiān, qǐng dàjiā ānjìng.', 'Đầu tiên, xin mọi người im lặng.'),
    ('顺序', '请按顺序排队进入教室。', 'Qǐng àn shùnxù páiduì jìnrù jiàoshì.', 'Xin hãy xếp hàng theo thứ tự vào lớp học.'),
    ('顺利', '会议进行得很顺利。', 'Huìyì jìnxíng de hěn shùnlì.', 'Cuộc họp tiến hành rất thuận lợi.'),
    ('顺便', '我去超市，顺便买点水果。', 'Wǒ qù chāoshì, shùnbiàn mǎi diǎn shuǐguǒ.', 'Tôi đi siêu thị, nhân tiện mua ít trái cây.'),
    ('随着', '随着年龄增长，他变得更成熟。', 'Suízhe niánlíng zēngzhǎng, tā biàn dé gèng chéngshú.', 'Cùng với tuổi tác tăng lên, anh ấy trở nên trưởng thành hơn.'),
    ('随便', '你想吃什么菜？随便，我都喜欢。', 'Nǐ xiǎng chī shénme cài? Suíbiàn, wǒ dōu xǐhuān.', 'Bạn muốn ăn món gì? Tùy tiện, tôi đều thích.'),
    ('酸', '这个柠檬太酸了，不好吃。', 'Zhège níngméng tài suān le, bù hǎo chī.', 'Quả chanh này quá chua, không ngon.'),
    ('速度', '开车时请注意控制速度。', 'Kāichē shí qǐng zhùyì kòngzhì sùdù.', 'Khi lái xe hãy chú ý kiểm soát tốc độ.'),
    ('适应', '我正在努力适应新的工作环境。', 'Wǒ zhèngzài nǔlì shìyìng xīn de gōngzuò huánjìng.', 'Tôi đang cố gắng thích nghi với môi trường làm việc mới.'),
    ('适合', '这件衣服很适合你，颜色也好看。', 'Zhè jiàn yīfu hěn shìhé nǐ, yánsè yě hǎokàn.', 'Chiếc áo này rất thích hợp với bạn, màu cũng đẹp.'),
    ('输', '比赛很激烈，我们最后输了。', 'Bǐsài hěn jīliè, wǒmen zuìhòu shū le.', 'Trận đấu rất căng thẳng, cuối cùng chúng tôi thua.'),
    ('说明', '请你详细说明这个问题的原因。', 'Qǐng nǐ xiángxì shuōmíng zhège wèntí de yuányīn.', 'Xin bạn nói rõ nguyên nhân của vấn đề này.'),
    ('稍微', '天气稍微冷了一点，记得多穿衣服。', 'Tiānqì shāowēi lěng le yīdiǎn, jìde duō chuān yīfu.', 'Thời tiết hơi lạnh một chút, nhớ mặc thêm quần áo.'),
    ('社会', '我们应该关心更多社会问题。', 'Wǒmen yīnggāi guānxīn gèng duō shèhuì wèntí.', 'Chúng ta nên quan tâm đến nhiều vấn đề xã hội hơn.'),
    ('硕士', '他刚刚获得了硕士学位。', 'Tā gānggāng huòdé le shuòshì xuéwèi.', 'Anh ấy vừa mới nhận bằng thạc sĩ.'),
    ('省', '我来自广东省，那里风景很好。', 'Wǒ láizì Guǎngdōng shěng, nàlǐ fēngjǐng hěn hǎo.', 'Tôi đến từ tỉnh Quảng Đông, nơi đó cảnh đẹp lắm.'),
    ('申请', '他打算申请这所大学的奖学金。', 'Tā dǎsuàn shēnqǐng zhè suǒ dàxué de jiǎngxuéjīn.', 'Anh ấy dự định xin học bổng của trường đại học này.'),
    ('生活', '大城市的生活节奏很快，但是机会也多。', 'Dà chéngshì de shēnghuó jiézòu hěn kuài, dànshì jīhuì yě duō.', 'Nhịp sống ở thành phố lớn rất nhanh, nhưng cũng có nhiều cơ hội.'),
    ('生意', '他的生意越来越好，准备开第二家店。', 'Tā de shēngyì yuè lái yuè hǎo, zhǔnbèi kāi dì èr jiā diàn.', 'Kinh doanh của anh ấy càng ngày càng tốt, chuẩn bị mở cửa hàng thứ hai.'),
    ('生命', '医生说保护生命比什么都重要。', 'Yīshēng shuō bǎohù shēngmìng bǐ shénme dōu zhòngyào.', 'Bác sĩ nói bảo vệ tính mạng quan trọng hơn mọi thứ.'),
    ('甚至', '他忙得连吃饭时间都没有，甚至忘记喝水。', 'Tā máng de lián chīfàn shíjiān dōu méiyǒu, shènzhì wàngjì hē shuǐ.', 'Anh ấy bận đến mức không có cả thời gian ăn cơm, thậm chí quên uống nước.'),
    ('熟悉', '我对这座城市的街道非常熟悉。', 'Wǒ duì zhè zuò chéngshì de jiēdào fēicháng shúxī.', 'Tôi rất quen thuộc với các con đường của thành phố này.'),
    ('深', '这条河很深，不适合游泳。', 'Zhè tiáo hé hěn shēn, bù shìhé yóuyǒng.', 'Con sông này rất sâu, không thích hợp để bơi.'),
    ('沙发', '客厅里有一个大沙发，大家可以一起坐。', 'Kètīng lǐ yǒu yí gè dà shāfā, dàjiā kěyǐ yìqǐ zuò.', 'Trong phòng khách có một cái ghế sô pha to, mọi người có thể ngồi cùng nhau.'),
    ('死', '后来他因为事故不幸死了。', 'Hòulái tā yīnwèi shìgù bùxìng sǐ le.', 'Sau đó anh ấy không may chết vì tai nạn.'),
    ('森林', '我们周末去森林里露营吧。', 'Wǒmen zhōumò qù sēnlín lǐ lùyíng ba.', 'Cuối tuần chúng ta đi cắm trại trong rừng sâu nhé.'),
    ('是否', '你是否准备好参加考试？', 'Nǐ shìfǒu zhǔnbèi hǎo cānjiā kǎoshì?', 'Bạn đã chuẩn bị sẵn sàng để tham gia kỳ thi chưa?'),
    ('数量', '这次订单的数量比上次多。', 'Zhè cì dìngdān de shùliàng bǐ shàng cì duō.', 'Số lượng đơn hàng lần này nhiều hơn lần trước.'),
    ('数字', '请在表格里填写正确的数字。', 'Qǐng zài biǎogé lǐ tiánxiě zhèngquè de shùzì.', 'Vui lòng điền con số chính xác vào bảng.'),
    ('收拾', '下课后我们一起收拾教室。', 'Xiàkè hòu wǒmen yīqǐ shōushi jiàoshì.', 'Sau giờ học chúng ta cùng nhau dọn dẹp lớp học.'),
    ('收入', '他的收入主要来自兼职工作。', 'Tā de shōurù zhǔyào láizì jiānzhí gōngzuò.', 'Thu nhập của anh ấy chủ yếu đến từ công việc làm thêm.'),
    ('收', '我已经收到了你的邮件。', 'Wǒ yǐjīng shōu dào le nǐ de yóujiàn.', 'Tôi đã nhận được thư của bạn rồi.'),
    ('所有', '所有学生都必须参加这次考试。', 'Suǒyǒu xuéshēng dōu bìxū cānjiā zhè cì kǎoshì.', 'Tất cả học sinh đều phải tham gia kỳ thi lần này.'),
    ('师傅', '师傅，请帮我修理这个自行车。', 'Shīfu, qǐng bāng wǒ xiūlǐ zhège zìxíngchē.', 'Sư phụ, xin hãy giúp tôi sửa chiếc xe đạp này.'),
    ('帅', '他是班里最帅的男生。', 'Tā shì bān lǐ zuì shuài de nánshēng.', 'Anh ấy là chàng trai đẹp trai nhất lớp.'),
    ('实际', '我们应该根据实际情况来做决定。', 'Wǒmen yīnggāi gēnjù shíjì qíngkuàng lái zuò juédìng.', 'Chúng ta nên quyết định dựa trên tình hình thực tế.'),
    ('实在', '我实在累了，想休息一下。', 'Wǒ shízài lèi le, xiǎng xiūxi yīxià.', 'Tôi thật sự mệt rồi, muốn nghỉ một lát.'),
    ('孙子', '我的孙子今年上小学一年级。', 'Wǒ de sūnzi jīnnián shàng xiǎoxué yī niánjí.', 'Cháu trai tôi năm nay học lớp một tiểu học.'),
    ('失败', '这次比赛他没有失败，表现得很出色。', 'Zhè cì bǐsài tā méiyǒu shībài, biǎoxiàn de hěn chūsè.', 'Lần thi này anh ấy không thất bại, biểu hiện rất xuất sắc.'),
    ('失望', '考试成绩出来后，他感到很失望。', 'Kǎoshì chéngjì chūlái hòu, tā gǎndào hěn shīwàng.', 'Sau khi kết quả thi ra, anh ấy cảm thấy rất thất vọng.'),
    ('塑料袋', '请不要使用塑料袋，保护环境很重要。', 'Qǐng bùyào shǐyòng sùliào dài, bǎohù huánjìng hěn zhòngyào.', 'Xin đừng dùng túi ni lông, bảo vệ môi trường rất quan trọng.'),
    ('商量', '我们明天去商量一下项目的计划。', 'Wǒmen míngtiān qù shāngliáng yīxià xiàngmù de jìhuà.', 'Ngày mai chúng ta đi bàn bạc kế hoạch dự án nhé.'),
    ('售货员', '售货员帮我找到我喜欢的那件衣服。', 'Shòuhuòyuán bāng wǒ zhǎodào wǒ xǐhuān de nà jiàn yīfu.', 'Nhân viên bán hàng giúp tôi tìm được chiếc áo mình thích.'),
    ('受到', '他因为努力工作，受到了老板的表扬。', 'Tā yīnwèi nǔlì gōngzuò, shòudào le lǎobǎn de biǎoyáng.', 'Anh ấy vì làm việc chăm chỉ nên đã nhận được lời khen từ sếp.'),
    ('受不了', '夏天的炎热让我受不了，想去海边避暑。', 'Xiàtiān de yánrè ràng wǒ shòubuliǎo, xiǎng qù hǎibiān bìshǔ.', 'Cái nóng mùa hè làm tôi không chịu nổi, tôi muốn đi biển tránh nóng.'),
    ('十分', '这次考试我觉得自己准备得十分充分。', 'Zhè cì kǎo shì wǒ jué de zì jǐ zhǔn bèi de shí fēn chōng fèn.', 'Kỳ thi này tôi cảm thấy mình đã chuẩn bị vô cùng đầy đủ.'),
    ('勺子', '请给我一把勺子，我想喝汤。', 'Qǐng gěi wǒ yī bǎ sháo zi, wǒ xiǎng hē tāng.', 'Làm ơn đưa tôi một cái thìa, tôi muốn uống súp.'),
    ('剩', '晚饭吃不了这么多，剩的我明天吃。', 'Wǎn fàn chī bù liǎo zhè me duō, shèng de wǒ míng tiān chī.', 'Bữa tối không ăn hết nhiều như vậy, phần thừa tôi sẽ ăn vào ngày mai.'),
    ('使用', '我们应该正确使用电脑保护眼睛。', 'Wǒ men yīng gāi zhèng què shǐ yòng diàn nǎo bǎo hù yǎn jīng.', 'Chúng ta nên sử dụng máy tính đúng cách để bảo vệ mắt.'),
    ('使', '这件事使我感到非常开心。', 'Zhè jiàn shì shǐ wǒ gǎn dào fēi cháng kāi xīn.', 'Việc này khiến tôi cảm thấy rất vui.'),
    ('伤心', '听到这个消息，他非常伤心。', 'Tīng dào zhè ge xiāo xī, tā fēi cháng shāng xīn.', 'Nghe tin này, anh ấy rất tổn thương.'),
    ('世纪', '二十一世纪科技发展很快。', 'Èr shí yī shì jì kē jì fā zhǎn hěn kuài.', 'Công nghệ thế kỷ 21 phát triển rất nhanh.'),
    ('台', '他买了一台新电脑用来学习。', 'Tā mǎi le yī tái xīn diàn nǎo yòng lái xué xí.', 'Anh ấy mua một chiếc máy tính mới để học tập.'),
    ('通过', '他通过考试获得了奖学金。', 'Tā tōng guò kǎo shì huò dé le jiǎng xué jīn.', 'Anh ấy thông qua kỳ thi và nhận học bổng.'),
    ('通知', '学校已经通过邮件通知家长开会时间。', 'Xué xiào yǐ jīng tōng guò yóu jiàn tōng zhī jiā zhǎng kāi huì shí jiān.', 'Trường học đã thông báo thời gian họp phụ huynh qua email.'),
    ('躺', '晚上我喜欢躺在沙发上看书。', 'Wǎnshàng wǒ xǐhuān tǎng zài shāfā shàng kàn shū.', 'Buổi tối tôi thích nằm trên ghế sofa đọc sách.'),
    ('趟', '我今天去了两趟超市买菜。', 'Wǒ jīntiān qùle liǎng tàng chāoshì mǎi cài.', 'Hôm nay tôi đã đi hai chuyến siêu thị để mua đồ.'),
    ('谈', '我们在咖啡店谈了很多关于工作的事情。', 'Wǒmen zài kāfēidiàn tánle hěn duō guānyú gōngzuò de shìqíng.', 'Chúng tôi đã nói chuyện nhiều về công việc ở quán cà phê.'),
    ('讨论', '老师让同学们讨论这个问题的解决方法。', 'Lǎoshī ràng tóngxuémen tǎolùn zhège wèntí de jiějué fāngfǎ.', 'Giáo viên yêu cầu các bạn học sinh thảo luận cách giải quyết vấn đề này.'),
    ('讨厌', '我讨厌下雨天出门很麻烦。', 'Wǒ tǎoyàn xiàyǔ tiān chūmén hěn máfan.', 'Tôi ghét những ngày mưa vì ra ngoài rất phiền phức.'),
    ('脱', '进屋后，请先脱鞋子。', 'Jìn wū hòu, qǐng xiān tuō xiézi.', 'Vào nhà xin hãy cởi giày trước nhé.'),
    ('糖', '妈妈给我买了很多喜欢的糖果。', 'Māma gěi wǒ mǎile hěn duō xǐhuān de tángguǒ.', 'Mẹ đã mua cho tôi rất nhiều kẹo yêu thích.'),
    ('特点', '这款手机的特点是电池非常耐用。', 'Zhè kuǎn shǒujī de tèdiǎn shì diànchí fēicháng nàiyòng.', 'Đặc điểm của chiếc điện thoại này là pin rất bền.'),
    ('汤', '冬天喝一碗热汤很舒服。', 'Dōngtiān hē yì wǎn rè tāng hěn shūfú.', 'Mùa đông uống một bát canh nóng rất dễ chịu.'),
    ('条件', '我需要改善学习的条件才能取得好成绩。', 'Wǒ xūyào gǎishàn xuéxí de tiáojiàn cáinéng qǔdé hǎo chéngjì.', 'Tôi cần cải thiện điều kiện học tập mới có thể đạt kết quả tốt.'),
    ('提醒', '老师提醒我们明天交作业。', 'Lǎoshī tíxǐng wǒmen míngtiān jiāo zuòyè.', 'Giáo viên nhắc chúng tôi nộp bài tập vào ngày mai.'),
    ('提前', '我们计划提前完成项目。', 'Wǒmen jìhuà tíqián wánchéng xiàngmù.', 'Chúng tôi dự định hoàn thành dự án trước thời hạn.'),
    ('提供', '这家公司提供免费的Wifi服务。', 'Zhè jiā gōngsī tígōng miǎnfèi de Wifi fúwù.', 'Công ty này cung cấp dịch vụ Wifi miễn phí.'),
    ('提', '请你提一个问题给大家讨论。', 'Qǐng nǐ tí yí gè wèntí gěi dàjiā tǎolùn.', 'Hãy đề ra một câu hỏi để mọi người thảo luận.'),
    ('推迟', '会议因为天气原因推迟了。', 'Huìyì yīnwèi tiānqì yuányīn tuīchí le.', 'Cuộc họp bị kéo dài thời gian do lý do thời tiết.'),
    ('推', '请帮我推开这扇门。', 'Qǐng bāng wǒ tuī kāi zhè shàn mén.', 'Làm ơn giúp tôi đẩy cửa này ra.'),
    ('挺', '这部电影挺有意思的。', 'Zhè bù diànyǐng tǐng yǒu yìsi de.', 'Bộ phim này rất thú vị.'),
    ('抬', '请抬头看看前面的路。', 'Qǐng tái tóu kàn kàn qiánmiàn de lù.', 'Hãy ngẩng đầu lên nhìn con đường phía trước.'),
    ('态度', '他的工作态度非常认真。', 'Tā de gōngzuò tàidù fēicháng rènzhēn.', 'Thái độ làm việc của anh ấy rất nghiêm túc.'),
    ('弹钢琴', '我每天晚上都会弹钢琴练习。', 'Wǒ měitiān wǎnshàng dōu huì tán gāngqín liànxí.', 'Tôi đều luyện tập chơi piano mỗi tối.'),
    ('填空', '老师让我们在卷子上做填空题。', 'Lǎoshī ràng wǒmen zài juànzi shàng zuò tiánkòng tí.', 'Giáo viên yêu cầu chúng tôi làm bài điền trống trên bài kiểm tra.'),
    ('同时', '我可以做饭，同时听音乐。', 'Wǒ kěyǐ zuò fàn, tóngshí tīng yīnyuè.', 'Tôi có thể nấu ăn đồng thời nghe nhạc.'),
    ('同情', '我对他的困难表示同情。', 'Wǒ duì tā de kùnnan biǎoshì tóngqíng.', 'Tôi bày tỏ sự đồng tình với khó khăn của anh ấy.'),
    ('停', '请在红灯时停车。', 'Qǐng zài hóng dēng shí tíng chē.', 'Xin hãy dừng xe khi đèn đỏ.'),
    ('袜子', '他买了一双新袜子。', 'Tā mǎile yī shuāng xīn wàzi.', 'Anh ấy đã mua một đôi tất mới.'),
    ('误会', '我们之间有一个小误会。', 'Wǒmen zhījiān yǒu yīgè xiǎo wùhuì.', 'Giữa chúng tôi có một chút hiểu lầm nhỏ.'),
    ('网站', '这个网站提供很多学习资料。', 'Zhège wǎngzhàn tígōng hěn duō xuéxí zīliào.', 'Trang mạng này cung cấp nhiều tài liệu học tập.'),
    ('网球', '周末我喜欢打网球。', 'Zhōumò wǒ xǐhuān dǎ wǎngqiú.', 'Cuối tuần tôi thích chơi tennis.'),
    ('温度', '今天的温度很适合户外运动。', 'Jīntiān de wēndù hěn shìhé hùwài yùndòng.', 'Nhiệt độ hôm nay rất phù hợp để vận động ngoài trời.'),
    ('污染', '工厂废水导致了河流污染。', 'Gōngchǎng fèishuǐ dǎozhìle héliú wūrǎn.', 'Nước thải từ nhà máy gây ra ô nhiễm sông.'),
    ('无论', '无论天气怎么样，我们都要去公园散步。', 'Wú lùn tiān qì zěn me yàng, wǒ men dōu yào qù gōng yuán sàn bù.', 'Bất luận thời tiết thế nào, chúng ta đều phải đi dạo công viên.'),
    ('无聊', '我觉得今天的电影很无聊，打算早点回家。', 'Wǒ jué dé jīn tiān de diàn yǐng hěn wú liáo, dǎ suàn zǎo diǎn huí jiā.', 'Tôi thấy bộ phim hôm nay rất nhàm chán, định về nhà sớm.'),
    ('无', '这里无手机信号，不能打电话。', 'Zhè lǐ wú shǒu jī xìn hào, bù néng dǎ diàn huà.', 'Ở đây không có sóng điện thoại, không thể gọi điện.'),
    ('文章', '他写了一篇关于环保的文章，非常有意思。', 'Tā xiě le yì piān guān yú huán bǎo de wén zhāng, fēi cháng yǒu yì si.', 'Anh ấy viết một bài văn về bảo vệ môi trường, rất thú vị.'),
    ('往往', '他往往晚上十点才开始学习。', 'Tā wǎng wǎng wǎn shàng shí diǎn cái kāi shǐ xué xí.', 'Anh ấy thường bắt đầu học lúc 10 giờ tối.'),
    ('完全', '我完全同意你的看法。', 'Wǒ wán quán tóng yì nǐ de kàn fǎ.', 'Tôi hoàn toàn đồng ý với ý kiến của bạn.'),
    ('味道', '这道菜的味道非常好，你一定要尝尝。', 'Zhè dào cài de wèi dào fēi cháng hǎo, nǐ yí dìng yào cháng cháng.', 'Mùi vị món ăn này rất ngon, bạn nhất định phải thử.'),
    ('危险', '爬山时一定要注意安全，避免危险。', 'Pá shān shí yí dìng yào zhù yì ān quán, bì miǎn wēi xiǎn.', 'Khi leo núi nhất định phải chú ý an toàn, tránh nguy hiểm.'),
    ('卫生间', '请问卫生间在哪里？', 'Qǐng wèn wèi shēng jiān zài nǎ lǐ?', 'Xin hỏi phòng vệ sinh ở đâu?'),
    ('西红柿', '我喜欢吃炒西红柿和鸡蛋。', 'Wǒ xǐ huān chī chǎo xī hóng shì hé jī dàn.', 'Tôi thích ăn cà chua xào trứng.'),
    ('香', '这杯茶闻起来很香。', 'Zhè bēi chá wén qǐlái hěn xiāng.', 'Ly trà này có mùi rất thơm.'),
    ('醒', '我喝了咖啡才完全醒过来。', 'Wǒ hē le kāfēi cái wánquán xǐng guòlái.', 'Tôi chỉ tỉnh hẳn khi uống cà phê.'),
    ('辛苦', '你的工作一定很辛苦吧？', 'Nǐ de gōngzuò yídìng hěn xīnkǔ ba？', 'Công việc của bạn chắc chắn rất vất vả phải không?'),
    ('详细', '请你把计划写得更详细一些。', 'Qǐng nǐ bǎ jìhuà xiě de gèng xiángxì yīxiē.', 'Xin bạn hãy viết kế hoạch chi tiết hơn một chút.'),
    ('许多', '他拥有许多朋友。', 'Tā yǒngyǒu xǔduō péngyǒu.', 'Anh ấy có rất nhiều bạn.'),
    ('行', '这个方案我觉得很行。', 'Zhège fāng''àn wǒ juéde hěn xíng.', 'Tôi thấy phương án này được đấy.'),
    ('羡慕', '我很羡慕你的中文水平。', 'Wǒ hěn xiànmù nǐ de Zhōngwén shuǐpíng.', 'Tôi rất ngưỡng mộ trình độ tiếng Trung của bạn.'),
    ('笑话', '他讲了一个很好笑的笑话。', 'Tā jiǎng le yī gè hěn hǎoxiào de xiàohuà.', 'Anh ấy kể một câu chuyện cười rất hay.'),
    ('相同', '我们有很多相同的兴趣爱好。', 'Wǒmen yǒu hěn duō xiāngtóng de xìngqù àihào.', 'Chúng tôi có rất nhiều sở thích giống nhau.'),
    ('相反', '他的看法和我相反。', 'Tā de kànfǎ hé wǒ xiāngfǎn.', 'Ý kiến của anh ấy ngược lại với tôi.'),
    ('现金', '我带了足够的现金去市场买东西。', 'Wǒ dài le zú gòu de xiàn jīn qù shì chǎng mǎi dōng xī.', 'Tôi mang đủ tiền mặt đi chợ mua đồ.'),
    ('消息', '公司刚刚发布了一个重要的消息。', 'Gōng sī gāng gāng fā bù le yī gè zhòng yào de xiāo xi.', 'Công ty vừa mới công bố một thông tin quan trọng.'),
    ('橡皮', '学生用橡皮擦掉了黑板上的字。', 'Xué shēng yòng xiàng pí cā diào le hēi bǎn shàng de zì.', 'Học sinh dùng cục tẩy để xóa chữ trên bảng đen.'),
    ('效果', '这次广告的效果比预期更好。', 'Zhè cì guǎng gào de xiào guǒ bǐ yù qī gèng hǎo.', 'Hiệu quả của quảng cáo lần này tốt hơn dự đoán.'),
    ('性格', '她的性格开朗，很容易交朋友。', 'Tā de xìng gé kāi lǎng, hěn róng yì jiāo péng yǒu.', 'Tính cách cô ấy cởi mở, rất dễ kết bạn.'),
    ('性别', '报名表上需要填写性别和年龄。', 'Bào míng biǎo shàng xū yào tián xiě xìng bié hé nián líng.', 'Trên phiếu đăng ký cần điền giới tính và tuổi.'),
    ('心情', '听音乐可以帮助我调整心情。', 'Tīng yīn yuè kě yǐ bāng zhù wǒ tiáo zhěng xīn qíng.', 'Nghe nhạc có thể giúp tôi điều chỉnh tâm trạng.'),
    ('幸福', '家人的支持让她感到幸福。', 'Jiā rén de zhī chí ràng tā gǎn dào xìng fú.', 'Sự ủng hộ của gia đình khiến cô ấy cảm thấy hạnh phúc.'),
    ('小说', '我正在读一本非常有趣的小说。', 'Wǒ zhèng zài dú yī běn fēi cháng yǒu qù de xiǎo shuō.', 'Tôi đang đọc một cuốn tiểu thuyết rất thú vị.'),
    ('小吃', '夜市有很多美味的小吃可以尝试。', 'Yè shì yǒu hěn duō měi wèi de xiǎo chī kě yǐ cháng shì.', 'Chợ đêm có nhiều đồ ăn vặt ngon có thể thử.'),
    ('小伙子', '那个小伙子每天早上跑步锻炼身体。', 'Nà gè xiǎo huǒ zi měi tiān zǎo shang pǎo bù duàn liàn shēn tǐ.', 'Anh chàng đó mỗi sáng đều chạy bộ rèn luyện thân thể.'),
    ('学期', '这个学期我选了三门新课。', 'Zhè gè xué qī wǒ xuǎn le sān mén xīn kè.', 'Học kỳ này tôi chọn ba môn học mới.'),
    ('响', '手机铃声响了，他赶紧接电话。', 'Shǒu jī líng shēng xiǎng le, tā gǎn jǐn jiē diàn huà.', 'Điện thoại reo, anh ấy vội vàng nghe điện.'),
    ('咸', '这碗汤太咸了，不能喝。', 'Zhè wǎn tāng tài xián le, bù néng hē.', 'Bát canh này quá mặn, không thể uống được.'),
    ('吸引', '这座城市的美景吸引了很多游客。', 'Zhè zuò chéng shì de měi jǐng xī yǐn le hěn duō yóu kè.', 'Cảnh đẹp của thành phố này thu hút nhiều du khách.'),
    ('兴奋', '考试成绩公布后，她非常兴奋。', 'Kǎo shì chéng jī gōng bù hòu, tā fēi cháng xīng fèn.', 'Sau khi kết quả thi được công bố, cô ấy rất hứng khởi.'),
    ('修理', '我的自行车坏了，需要修理。', 'Wǒ de zì xíng chē huài le, xū yào xiū lǐ.', 'Xe đạp của tôi hỏng, cần phải sửa chữa.'),
    ('信息', '请你把会议的信息发给我。', 'Qǐng nǐ bǎ huì yì de xìn xī fā gěi wǒ.', 'Làm ơn gửi cho tôi thông tin về cuộc họp.'),
    ('信心', '他对完成任务充满了信心。', 'Tā duì wán chéng rèn wù chōng mǎn le xìn xīn.', 'Anh ấy đầy niềm tin vào việc hoàn thành nhiệm vụ.'),
    ('信封', '请把信放进信封里，然后寄出去。', 'Qǐng bǎ xìn fàng jìn xìn fēng lǐ, rán hòu jì chū qù.', 'Làm ơn cho thư vào phong bì rồi gửi đi.'),
    ('压力', '工作中的压力有时候让我感到很累。', 'Gōngzuò zhōng de yā lì yǒu shíhòu ràng wǒ gǎndào hěn lèi.', 'Áp lực trong công việc đôi khi khiến tôi cảm thấy rất mệt.'),
    ('预习', '每天晚上我都会预习第二天的课程内容。', 'Měitiān wǎnshàng wǒ dūhuì yù xí dì èr tiān de kèchéng nèiróng.', 'Mỗi tối tôi đều chuẩn bị trước nội dung bài học ngày mai.'),
    ('页', '请翻到第十页，把课文读一遍。', 'Qǐng fān dào dì shí yè, bǎ kèwén dú yī biàn.', 'Vui lòng lật đến trang thứ mười và đọc bài học một lần.'),
    ('阳光', '早晨的阳光温暖而明亮。', 'Zǎochén de yáng guāng wēnnuǎn ér míngliàng.', 'Ánh nắng buổi sáng ấm áp và sáng sủa.'),
    ('阅读', '他每天花一个小时来阅读新闻。', 'Tā měitiān huā yī gè xiǎoshí lái yuè dú xīnwén.', 'Anh ấy dành một giờ mỗi ngày để đọc tin tức.'),
    ('钥匙', '出门前别忘了带上你的钥匙。', 'Chūmén qián bié wàngle dài shàng nǐ de yào shi.', 'Trước khi ra ngoài đừng quên mang theo chìa khóa của bạn.'),
    ('邮局', '我去邮局寄了一封重要的信。', 'Wǒ qù yóu jú jì le yī fēng zhòngyào de xìn.', 'Tôi đã đến bưu điện gửi một bức thư quan trọng.'),
    ('邀请', '老师邀请我们参加学校的庆典。', 'Lǎoshī yāo qǐng wǒmen cānjiā xuéxiào de qìngdiǎn.', 'Giáo viên mời chúng tôi tham gia lễ kỷ niệm của trường.'),
    ('赢', '我们的球队昨天赢得了比赛。', 'Wǒmen de qiúduì zuótiān yíng dé le bǐsài.', 'Đội của chúng tôi đã thắng trận đấu hôm qua.'),
    ('语言', '学习一种新的语言可以增加交流机会。', 'Xuéxí yī zhǒng xīn de yǔ yán kěyǐ zēngjiā jiāoliú jīhuì.', 'Học một ngôn ngữ mới có thể tăng cơ hội giao tiếp.'),
    ('语法', '学习语法可以帮助我们更准确地说中文。', 'Xuéxí yǔfǎ kěyǐ bāngzhù wǒmen gèng zhǔnquè de shuō zhōngwén.', 'Học ngữ pháp có thể giúp chúng ta nói tiếng Trung chính xác hơn.'),
    ('要是', '要是明天下雨，我们就不去爬山了。', 'Yàoshi míngtiān xiàyǔ, wǒmen jiù bù qù páshān le.', 'Nếu ngày mai mưa, chúng ta sẽ không đi leo núi.'),
    ('艺术', '她对现代艺术非常感兴趣。', 'Tā duì xiàndài yìshù fēicháng gǎn xìngqù.', 'Cô ấy rất quan tâm đến nghệ thuật hiện đại.'),
    ('羽毛球', '周末我和朋友一起打羽毛球。', 'Zhōumò wǒ hé péngyǒu yīqǐ dǎ yǔmáoqiú.', 'Cuối tuần tôi chơi cầu lông cùng bạn bè.'),
    ('约会', '他们今晚有一个重要的约会。', 'Tāmen jīnwǎn yǒu yí gè zhòngyào de yuēhuì.', 'Họ có một cuộc hẹn quan trọng tối nay.'),
    ('研究', '我们学校正在研究新的教学方法。', 'Wǒmen xuéxiào zhèngzài yánjiū xīn de jiàoxué fāngfǎ.', 'Trường chúng tôi đang nghiên cứu phương pháp giảng dạy mới.'),
    ('眼镜', '我忘了带眼镜，看书很困难。', 'Wǒ wàngle dài yǎnjìng, kàn shū hěn kùnnan.', 'Tôi quên mang kính, đọc sách rất khó khăn.'),
    ('盐', '这道菜需要加一点盐。', 'Zhè dào cài xūyào jiā yìdiǎn yán.', 'Món ăn này cần thêm một chút muối.'),
    ('由于', '由于交通堵塞，我上班迟到了。', 'Yóuyú jiāotōng dǔsè, wǒ shàngbān chídào le.', 'Do tắc đường, tôi đi làm bị muộn.'),
    ('由', '这次比赛的结果由裁判决定。', 'Zhè cì bǐsài de jiéguǒ yóu cáipàn juédìng.', 'Kết quả trận đấu này do trọng tài quyết định.'),
    ('牙膏', '早上我忘了带牙膏，不能刷牙。', 'Zǎoshang wǒ wàngle dài yágāo, bù néng shuā yá.', 'Sáng nay tôi quên mang kem đánh răng nên không thể đánh răng.'),
    ('演员', '那个演员在电视剧里很受欢迎。', 'Nàgè yǎnyuán zài diànshìjù lǐ hěn shòu huānyíng.', 'Diễn viên đó rất được yêu thích trong bộ phim truyền hình.'),
    ('演出', '我们今晚去看京剧演出。', 'Wǒmen jīn wǎn qù kàn jīngjù yǎnchū.', 'Tối nay chúng tôi đi xem buổi diễn kịch kinh kịch.'),
    ('永远', '我希望我们永远是好朋友。', 'Wǒ xīwàng wǒmen yǒngyuǎn shì hǎo péngyǒu.', 'Tôi hy vọng chúng ta mãi mãi là bạn tốt.'),
    ('样子', '他累的样子很明显。', 'Tā lèi de yàngzi hěn míngxiǎn.', 'Dáng vẻ của anh ấy rất rõ ràng là mệt.'),
    ('有趣', '这本书的故事非常有趣。', 'Zhè běn shū de gùshì fēicháng yǒuqù.', 'Câu chuyện trong cuốn sách này rất thú vị.'),
    ('意见', '老师听取了学生们的意见。', 'Lǎoshī tīngqǔle xuéshēngmen de yìjiàn.', 'Giáo viên đã nghe ý kiến của các học sinh.'),
    ('愉快', '祝你有一个愉快的假期！', 'Zhù nǐ yǒu yīgè yúkuài de jiàqī!', 'Chúc bạn có một kỳ nghỉ vui vẻ!'),
    ('引起', '这次事故引起了很多关注。', 'Zhè cì shìgù yǐnqǐle hěn duō guānzhù.', 'Vụ tai nạn này đã gây ra nhiều sự chú ý.'),
    ('应聘', '她打算应聘这家公司的职位。', 'Tā dǎsuàn yìngpìn zhè jiā gōngsī de zhíwèi.', 'Cô ấy định ứng tuyển vị trí ở công ty này.'),
    ('幽默', '他的讲话很幽默，大家都笑了。', 'Tā de jiǎnghuà hěn yōumò, dàjiā dōu xiàole.', 'Bài nói chuyện của anh ấy rất hài hước, mọi người đều cười.'),
    ('尤其', '我喜欢水果，尤其喜欢苹果。', 'Wǒ xǐhuān shuǐguǒ, yóuqí xǐhuān píngguǒ.', 'Tôi thích trái cây, đặc biệt là táo.'),
    ('因此', '天气很冷，因此我们穿了厚衣服。', 'Tiānqì hěn lěng, yīncǐ wǒmen chuānle hòu yīfu.', 'Thời tiết rất lạnh, cho nên chúng tôi đã mặc quần áo dày.'),
    ('呀', '你来了呀，我正想找你呢。', 'Nǐ lái le yā, wǒ zhèng xiǎng zhǎo nǐ ne.', 'Bạn đến rồi à, tôi đang định tìm bạn đây.'),
    ('叶子', '秋天的时候，树上的叶子变黄了。', 'Qiūtiān de shíhòu, shù shàng de yèzi biàn huángle.', 'Vào mùa thu, lá trên cây chuyển sang màu vàng.'),
    ('友谊', '我们之间有深厚的友谊。', 'Wǒmen zhī jiān yǒu shēnhòu de yǒuyì.', 'Giữa chúng tôi có một tình bạn sâu sắc.'),
    ('友好', '两个国家保持友好的关系。', 'Liǎng gè guójiā bǎochí yǒuhǎo de guānxi.', 'Hai quốc gia duy trì quan hệ hữu hảo.'),
    ('原谅', '请你原谅我的迟到。', 'Qǐng nǐ yuánliàng wǒ de chídào.', 'Làm ơn tha thứ cho tôi vì đã đến muộn.'),
    ('原来', '原来他不在家，我还找了很久。', 'Yuánlái tā bú zài jiā, wǒ hái zhǎole hěn jiǔ.', 'Hóa ra anh ấy không ở nhà, tôi đã tìm lâu lắm.'),
    ('原因', '他的成功有很多原因。', 'Tā de chénggōng yǒu hěn duō yuányīn.', 'Sự thành công của anh ấy có rất nhiều nguyên nhân.'),
    ('印象', '我对北京的印象非常好，城市很干净。', 'Wǒ duì Běijīng de yìnxiàng fēicháng hǎo, chéngshì hěn gānjìng.', 'Tôi có ấn tượng rất tốt về Bắc Kinh, thành phố rất sạch sẽ.'),
    ('勇敢', '他勇敢地面对困难，没有退缩。', 'Tā yǒnggǎn de miànduì kùnnán, méiyǒu tuìsuō.', 'Anh ấy dũng cảm đối mặt với khó khăn, không lùi bước.'),
    ('养成', '养成每天阅读的习惯对学习很有帮助。', 'Yǎngchéng měitiān yuèdú de xíguàn duì xuéxí hěn yǒu bāngzhù.', 'Hình thành thói quen đọc sách mỗi ngày rất có ích cho việc học.'),
    ('允许', '老师不允许学生在课堂上使用手机。', 'Lǎoshī bù yǔnxǔ xuéshēng zài kètáng shàng shǐyòng shǒujī.', 'Giáo viên không cho phép học sinh sử dụng điện thoại trong lớp.'),
    ('优秀', '她是一名优秀的学生，成绩一直很好。', 'Tā shì yī míng yōuxiù de xuéshēng, chéngjī yīzhí hěn hǎo.', 'Cô ấy là một học sinh xuất sắc, thành tích luôn rất tốt.'),
    ('优点', '这个方案的优点是成本低，效率高。', 'Zhège fāng''àn de yōudiǎn shì chéngběn dī, xiàolǜ gāo.', 'Ưu điểm của kế hoạch này là chi phí thấp và hiệu quả cao.'),
    ('以为', '我以为他今天不来了，没想到他准时到了。', 'Wǒ yǐwéi tā jīntiān bù lái le, méi xiǎngdào tā zhǔnshí dào le.', 'Tôi tưởng rằng anh ấy hôm nay không đến, không ngờ anh ấy đến đúng giờ.'),
    ('以', '我们以成绩作为评奖的标准。', 'Wǒmen yǐ chéngjì zuòwéi píng jiǎng de biāozhǔn.', 'Chúng tôi lấy thành tích làm tiêu chuẩn để trao thưởng.'),
    ('亚洲', '中国是亚洲最大的国家之一。', 'Zhōngguó shì Yàzhōu zuìdà de guójiā zhī yī.', 'Trung Quốc là một trong những quốc gia lớn nhất châu Á.'),
    ('云', '天空中有很多白色的云，天气很舒服。', 'Tiānkōng zhōng yǒu hěn duō báisè de yún, tiānqì hěn shūfu.', 'Trên bầu trời có nhiều đám mây trắng, thời tiết rất dễ chịu.'),
    ('于是', '他忘记带钥匙， 于是只能打电话求助。', 'Tā wàngjì dài yàoshi, yúshì zhǐ néng dǎ diànhuà qiúzhù.', 'Anh ấy quên mang chìa khóa, thế là chỉ có thể gọi điện nhờ giúp đỡ.'),
    ('也许', '也许明天会下雨，记得带伞。', 'Yěxǔ míngtiān huì xiàyǔ, jìde dài sǎn.', 'Có lẽ ngày mai trời sẽ mưa, nhớ mang ô nhé.'),
    ('严重', '他的伤势很严重，需要马上治疗。', 'Tā de shāngshì hěn yánzhòng, xūyào mǎshàng zhìliáo.', 'Vết thương của anh ấy rất nghiêm trọng, cần phải chữa trị ngay.'),
    ('严格', '老师对学生的作业要求很严格。', 'Lǎoshī duì xuéshēng de zuòyè yāoqiú hěn yángé.', 'Giáo viên yêu cầu bài tập của học sinh rất nghiêm khắc.'),
    ('与', '他与同事一起完成了这个项目。', 'Tā yǔ tóngshì yīqǐ wánchéng le zhège xiàngmù.', 'Anh ấy và đồng nghiệp cùng nhau hoàn thành dự án này.'),
    ('一切', '一切准备工作都已经完成了。', 'Yīqiè zhǔnbèi gōngzuò dōu yǐjīng wánchéng le.', 'Tất cả công việc chuẩn bị đã hoàn thành rồi.'),
    ('杂志', '我每个月都会买一本旅游杂志。', 'Wǒ měi gè yuè dōu huì mǎi yī běn lǚyóu zázhì.', 'Tôi mỗi tháng đều mua một cuốn tạp chí du lịch.'),
    ('重视', '公司很重视员工的培训。', 'Gōngsī hěn zhòngshì yuángōng de péixùn.', 'Công ty rất coi trọng đào tạo nhân viên.'),
    ('重点', '这次考试的重点是语法和词汇。', 'Zhè cì kǎoshì de zhòngdiǎn shì yǔfǎ hé cíhuì.', 'Trọng điểm của kỳ thi lần này là ngữ pháp và từ vựng.'),
    ('重', '这个箱子很重，需要两个人搬。', 'Zhège xiāngzi hěn zhòng, xūyào liǎng gè rén bān.', 'Chiếc vali này rất nặng, cần hai người khuân vác.'),
    ('转', '你应该在下一个路口转弯。', 'Nǐ yīnggāi zài xià yī gè lùkǒu zhuǎn wān.', 'Bạn nên rẽ ở ngã tư tiếp theo.'),
    ('赚', '她通过努力工作赚了很多钱。', 'Tā tōngguò nǔlì gōngzuò zhuàn le hěn duō qián.', 'Cô ấy kiếm được nhiều tiền nhờ làm việc chăm chỉ.'),
    ('质量', '这家公司的产品质量非常好。', 'Zhè jiā gōngsī de chǎnpǐn zhìliàng fēicháng hǎo.', 'Chất lượng sản phẩm của công ty này rất tốt.'),
    ('责任', '每个人都应该承担自己的责任。', 'Měi gè rén dōu yīnggāi chéngdān zìjǐ de zérèn.', 'Mọi người đều nên chịu trách nhiệm về bản thân mình.'),
    ('证明', '请出示你的身份证明。', 'Qǐng chūshì nǐ de shēnfèn zhèngmíng.', 'Làm ơn trình giấy chứng minh nhân dân của bạn.'),
    ('著名', '北京有很多著名的旅游景点。', 'Běijīng yǒu hěn duō zhùmíng de lǚyóu jǐngdiǎn.', 'Bắc Kinh có nhiều điểm du lịch nổi tiếng.'),
    ('至少', '你至少要学习一个小时。', 'Nǐ zhìshǎo yào xuéxí yī gè xiǎoshí.', 'Bạn ít nhất phải học một tiếng đồng hồ.'),
    ('自然', '我们应该保护自然环境。', 'Wǒmen yīnggāi bǎohù zìrán huánjìng.', 'Chúng ta nên bảo vệ môi trường tự nhiên.'),
    ('自信', '她在面试中表现得很自信。', 'Tā zài miànshì zhōng biǎoxiàn de hěn zìxìn.', 'Cô ấy thể hiện rất tự tin trong buổi phỏng vấn.'),
    ('脏', '你的衣服上有脏污，需要洗。', 'Nǐ de yīfu shàng yǒu zāng wū, xūyào xǐ.', 'Quần áo của bạn có vết bẩn, cần phải giặt.'),
    ('职业', '你对你的职业感到满意吗？', 'Nǐ duì nǐ de zhí yè gǎn dào mǎn yì ma?', 'Bạn có hài lòng với nghề nghiệp của mình không?'),
    ('租', '我计划下个月租一辆车去旅行。', 'Wǒ jì huà xià gè yuè zū yī liàng chē qù lǚ xíng.', 'Tôi dự định thuê một chiếc xe đi du lịch vào tháng tới.'),
    ('祝贺', '祝贺你通过了考试，真棒！', 'Zhù hè nǐ tōng guò le kǎo shì, zhēn bàng!', 'Chúc mừng bạn đã vượt qua kỳ thi, thật tuyệt!'),
    ('知识', '读书可以增加我们的知识。', 'Dú shū kě yǐ zēng jiā wǒ men de zhī shí.', 'Đọc sách có thể làm tăng kiến thức của chúng ta.'),
    ('真正', '这是真正值得学习的经验。', 'Zhè shì zhēn zhèng zhí dé xué xí de jīng yàn.', 'Đây là kinh nghiệm thật sự đáng để học hỏi.'),
    ('直接', '你可以直接跟经理联系。', 'Nǐ kě yǐ zhí jiē gēn jīng lǐ lián xì.', 'Bạn có thể liên hệ trực tiếp với giám đốc.'),
    ('照', '请照我的指示操作。', 'Qǐng zhào wǒ de zhǐ shì cāo zuò.', 'Vui lòng làm theo chỉ dẫn của tôi.'),
    ('正确', '请确保你的答案正确无误。', 'Qǐng què bǎo nǐ de dá àn zhèng què wú wù.', 'Hãy đảm bảo câu trả lời của bạn là chính xác không sai sót.'),
    ('正式', '他们将在下个月举办正式的会议。', 'Tā men jiāng zài xià gè yuè jǔ bàn zhèng shì de huì yì.', 'Họ sẽ tổ chức cuộc họp chính thức vào tháng tới.'),
    ('正常', '现在一切都恢复正常了。', 'Xiàn zài yī qiè dōu huī fù zhèng cháng le.', 'Bây giờ mọi thứ đã trở lại bình thường rồi.'),
    ('正好', '我到车站时，公交车正好来了。', 'Wǒ dào chēzhàn shí, gōngjiāo chē zhènghǎo lái le.', 'Khi tôi đến bến xe, xe buýt vừa kịp tới.'),
    ('植物', '这座花园里种了很多漂亮的植物。', 'Zhè zuò huāyuán lǐ zhòng le hěn duō piàoliang de zhíwù.', 'Trong khu vườn này trồng rất nhiều thực vật đẹp.'),
    ('最好', '考试前最好复习一下课本内容。', 'Kǎoshì qián zuì hǎo fùxí yīxià kèběn nèiróng.', 'Trước khi thi tốt nhất nên ôn lại nội dung sách giáo khoa.'),
    ('暂时', '电脑坏了，我们暂时用手机工作。', 'Diànnǎo huài le, wǒmen zànshí yòng shǒujī gōngzuò.', 'Máy tính bị hỏng, chúng tôi tạm thời dùng điện thoại làm việc.'),
    ('整理', '我需要整理我的房间，东西太乱了。', 'Wǒ xūyào zhěnglǐ wǒ de fángjiān, dōngxī tài luàn le.', 'Tôi cần dọn dẹp phòng của mình, đồ đạc quá lộn xộn.'),
    ('支持', '家人一直支持我学习汉语。', 'Jiārén yīzhí zhīchí wǒ xuéxí hànyǔ.', 'Gia đình luôn ủng hộ tôi học tiếng Trung.'),
    ('指', '请你指一下地图上的那个地方。', 'Qǐng nǐ zhǐ yīxià dìtú shàng de nàgè dìfang.', 'Xin bạn chỉ giúp tôi chỗ đó trên bản đồ.'),
    ('招聘', '公司正在招聘新的销售人员。', 'Gōngsī zhèngzài zhāopìn xīn de xiāoshòu rényuán.', 'Công ty đang tuyển dụng nhân viên kinh doanh mới.'),
    ('总结', '老师让我们写一篇总结报告。', 'Lǎoshī ràng wǒmen xiě yī piān zǒngjié bàogào.', 'Giáo viên yêu cầu chúng tôi viết một bài tổng kết.'),
    ('座位', '请坐到靠窗的座位上。', 'Qǐng zuò dào kào chuāng de zuòwèi shàng.', 'Xin mời ngồi vào chỗ ngồi gần cửa sổ.'),
    ('座', '北京有很多著名的座建筑。', 'Běijīng yǒu hěn duō zhùmíng de zuò jiànzhù.', 'Bắc Kinh có nhiều tòa nhà nổi tiếng.'),
    ('左右', '会议大约持续两个小时左右。', 'Huìyì dàyuē chíxù liǎng gè xiǎoshí zuǒyòu.', 'Cuộc họp kéo dài khoảng hai tiếng.'),
    ('尊重', '我们应该尊重每个人的观点。', 'Wǒmen yīnggāi zūnzhòng měi gèrén de guāndiǎn.', 'Chúng ta nên tôn trọng ý kiến của mỗi người.'),
    ('增加', '公司今年计划增加员工人数。', 'Gōngsī jīnnián jìhuà zēngjiā yuángōng rénshù.', 'Công ty năm nay dự định tăng số lượng nhân viên.'),
    ('咱们', '咱们明天一起去逛街吧。', 'Zánmen míngtiān yīqǐ qù guàngjiē ba.', 'Chúng ta ngày mai cùng đi mua sắm nhé.'),
    ('周围', '图书馆周围有很多咖啡馆。', 'Túshūguǎn zhōuwéi yǒu hěn duō kāfēiguǎn.', 'Xung quanh thư viện có nhiều quán cà phê.'),
    ('只要', '只要努力，就能取得好成绩。', 'Zhǐyào nǔlì, jiù néng qǔdé hǎo chéngjì.', 'Chỉ cần cố gắng, bạn sẽ đạt được kết quả tốt.'),
    ('只好', '手机没电了，我只好回家充电。', 'Shǒujī méi diàn le, wǒ zhǐhǎo huí jiā chōngdiàn.', 'Đt hết pin rồi, tôi đành về nhà sạc.'),
    ('占线', '他打电话时发现号码占线。', 'Tā dǎ diànhuà shí fāxiàn hàomǎ zhànxiàn.', 'Khi anh ấy gọi điện thì thấy máy bận.'),
    ('准确', '请提供准确的地址信息。', 'Qǐng tígōng zhǔnquè de dìzhǐ xìnxī.', 'Vui lòng cung cấp địa chỉ chính xác.'),
    ('准时', '我们明天必须准时到达机场。', 'Wǒmen míngtiān bìxū zhǔnshí dàodá jīchǎng.', 'Chúng ta phải đến sân bay đúng giờ vào ngày mai.'),
    ('值得', '这部电影非常好看，真的值得一看。', 'Zhè bù diànyǐng fēicháng hǎokàn, zhēn de zhídé yī kàn.', 'Bộ phim này rất hay, thực sự đáng xem.'),
    ('作者', '这本书的作者写了很多畅销书。', 'Zhè běn shū de zuòzhě xiě le hěn duō chàngxiāoshū.', 'Tác giả của cuốn sách này đã viết nhiều sách bán chạy.'),
    ('作用', '运动对身体有很好的作用。', 'Yùndòng duì shēntǐ yǒu hěn hǎo de zuòyòng.', 'Thể thao có tác dụng rất tốt đối với sức khỏe.'),
    ('作家', '他是一个著名的作家，写了很多小说。', 'Tā shì yīgè zhùmíng de zuòjiā, xiě le hěn duō xiǎoshuō.', 'Anh ấy là một tác gia nổi tiếng, đã viết nhiều tiểu thuyết.'),
    ('仔细', '请你仔细看清楚合同的每一条内容。', 'Qǐng nǐ zǐxì kàn qīngchǔ hétóng de měi yītiáo nèiróng.', 'Xin bạn hãy xem kỹ từng điều khoản trong hợp đồng.'),
    ('之', '这是我之所以选择这个学校的原因。', 'Zhè shì wǒ zhī suǒyǐ xuǎnzé zhège xuéxiào de yuányīn.', 'Đây là lý do tôi chọn trường này.'),
    ('主意', '你的主意很好，我们可以试试看。', 'Nǐ de zhǔyì hěn hǎo, wǒmen kěyǐ shì shì kàn.', 'Ý tưởng của bạn rất tốt, chúng ta có thể thử xem.'),
    ('专门', '他专门学习汉语已经三年了。', 'Tā zhuānmén xuéxí hànyǔ yǐjīng sān nián le.', 'Anh ấy đã học tiếng Hán chuyên môn được ba năm rồi.'),
    ('专业', '我大学的专业是计算机科学。', 'Wǒ dàxué de zhuānyè shì jìsuànjī kēxué.', 'Chuyên ngành đại học của tôi là khoa học máy tính.')
),
updated_template_cards as (
  update public.template_cards as card
  set
    example_cn = example.example_cn,
    example_pinyin = example.example_pinyin,
    example_vi = example.example_vi,
    sentence_audio_url = null
  from public.template_decks as deck,
    hsk4_context_examples as example
  where card.template_deck_id = deck.id
    and deck.slug = 'hsk4-co-ban'
    and card.chinese = example.chinese
  returning card.id
)
update public.cards as card
set
  example_cn = example.example_cn,
  example_pinyin = example.example_pinyin,
  example_vi = example.example_vi,
  sentence_audio_url = null
from public.decks as deck,
  hsk4_context_examples as example
where card.deck_id = deck.id
  and card.user_id = deck.user_id
  and (
    deck.source_template_slug = 'hsk4-co-ban'
    or (deck.source_template_slug is null and deck.name = 'HSK4 cơ bản')
  )
  and card.chinese = example.chinese
  and (
    nullif(btrim(card.example_cn), '') is null
    or card.example_cn like '这件事和%有关。'
    or card.example_cn like '今天我们练习%这个词。'
    or card.example_pinyin like 'Zhe jian shi he % youguan.'
    or card.example_pinyin like 'Jintian women lianxi % zhe ge ci.'
  );
