insert into public.template_decks (slug, name, description, level)
values (
  'di-lam-phong-van-300',
  'Từ vựng đi làm và phỏng vấn - 300 từ',
  'Bộ 300 từ vựng tiếng Trung dùng khi đi làm, phỏng vấn, văn phòng, giao tiếp khách hàng, lương thưởng, dự án và kỹ năng nghề nghiệp. Mỗi từ có pinyin, nghĩa tiếng Việt và câu ví dụ.',
  'Đi làm'
)
on conflict (slug) do update
set
  name = excluded.name,
  description = excluded.description,
  level = excluded.level;

with target_deck as (
  select id from public.template_decks where slug = 'di-lam-phong-van-300'
)
insert into public.template_cards (
  template_deck_id,
  chinese,
  pinyin,
  meaning_vi,
  example_cn,
  example_pinyin,
  example_vi,
  position
)
select
  target_deck.id,
  word.chinese,
  word.pinyin,
  word.meaning_vi,
  '在工作中，我经常用到' || word.chinese || '。',
  'Zài gōngzuò zhōng, wǒ jīngcháng yòngdào ' || word.pinyin || '.',
  'Trong công việc, tôi thường dùng đến ' || word.meaning_vi || '.',
  word.position
from target_deck
cross join (
  values
    ('面试', 'miànshì', 'phỏng vấn', 1),
    ('简历', 'jiǎnlì', 'sơ yếu lý lịch, CV', 2),
    ('求职', 'qiúzhí', 'tìm việc', 3),
    ('职位', 'zhíwèi', 'chức vụ, vị trí', 4),
    ('岗位', 'gǎngwèi', 'vị trí công việc', 5),
    ('招聘', 'zhāopìn', 'tuyển dụng', 6),
    ('应聘', 'yìngpìn', 'ứng tuyển', 7),
    ('录用', 'lùyòng', 'tuyển nhận', 8),
    ('入职', 'rùzhí', 'nhận việc', 9),
    ('离职', 'lízhí', 'nghỉ việc', 10),
    ('转正', 'zhuǎnzhèng', 'chuyển chính thức', 11),
    ('试用期', 'shìyòngqī', 'thời gian thử việc', 12),
    ('合同', 'hétong', 'hợp đồng', 13),
    ('劳动合同', 'láodòng hétong', 'hợp đồng lao động', 14),
    ('薪资', 'xīnzī', 'lương, tiền công', 15),
    ('工资', 'gōngzī', 'tiền lương', 16),
    ('底薪', 'dǐxīn', 'lương cơ bản', 17),
    ('提成', 'tíchéng', 'hoa hồng', 18),
    ('奖金', 'jiǎngjīn', 'tiền thưởng', 19),
    ('津贴', 'jīntiē', 'phụ cấp', 20),
    ('福利', 'fúlì', 'phúc lợi', 21),
    ('社保', 'shèbǎo', 'bảo hiểm xã hội', 22),
    ('保险', 'bǎoxiǎn', 'bảo hiểm', 23),
    ('年假', 'niánjià', 'nghỉ phép năm', 24),
    ('请假', 'qǐngjià', 'xin nghỉ phép', 25),
    ('病假', 'bìngjià', 'nghỉ ốm', 26),
    ('事假', 'shìjià', 'nghỉ việc riêng', 27),
    ('加班', 'jiābān', 'tăng ca', 28),
    ('调休', 'tiáoxiū', 'nghỉ bù', 29),
    ('考勤', 'kǎoqín', 'chấm công', 30),
    ('打卡', 'dǎkǎ', 'quẹt thẻ, chấm công', 31),
    ('上班', 'shàngbān', 'đi làm', 32),
    ('下班', 'xiàbān', 'tan làm', 33),
    ('迟到', 'chídào', 'đi muộn', 34),
    ('早退', 'zǎotuì', 'về sớm', 35),
    ('出差', 'chūchāi', 'đi công tác', 36),
    ('培训', 'péixùn', 'đào tạo', 37),
    ('实习', 'shíxí', 'thực tập', 38),
    ('实习生', 'shíxíshēng', 'thực tập sinh', 39),
    ('试岗', 'shìgǎng', 'thử việc tại vị trí', 40),
    ('背景调查', 'bèijǐng diàochá', 'kiểm tra lý lịch', 41),
    ('推荐信', 'tuījiànxìn', 'thư giới thiệu', 42),
    ('学历', 'xuélì', 'trình độ học vấn', 43),
    ('专业', 'zhuānyè', 'chuyên ngành', 44),
    ('毕业', 'bìyè', 'tốt nghiệp', 45),
    ('证书', 'zhèngshū', 'chứng chỉ', 46),
    ('资格证', 'zīgézhèng', 'chứng chỉ nghề', 47),
    ('经验', 'jīngyàn', 'kinh nghiệm', 48),
    ('工作经验', 'gōngzuò jīngyàn', 'kinh nghiệm làm việc', 49),
    ('能力', 'nénglì', 'năng lực', 50),
    ('技能', 'jìnéng', 'kỹ năng', 51),
    ('优点', 'yōudiǎn', 'ưu điểm', 52),
    ('缺点', 'quēdiǎn', 'khuyết điểm', 53),
    ('压力', 'yālì', 'áp lực', 54),
    ('抗压能力', 'kàngyā nénglì', 'khả năng chịu áp lực', 55),
    ('职业规划', 'zhíyè guīhuà', 'kế hoạch nghề nghiệp', 56),
    ('发展空间', 'fāzhǎn kōngjiān', 'không gian phát triển', 57),
    ('晋升', 'jìnshēng', 'thăng chức', 58),
    ('升职', 'shēngzhí', 'thăng chức', 59),
    ('降职', 'jiàngzhí', 'giáng chức', 60),
    ('会议', 'huìyì', 'cuộc họp', 61),
    ('开会', 'kāihuì', 'họp', 62),
    ('议程', 'yìchéng', 'chương trình họp', 63),
    ('记录', 'jìlù', 'ghi chép, biên bản', 64),
    ('通知', 'tōngzhī', 'thông báo', 65),
    ('邮件', 'yóujiàn', 'email', 66),
    ('回复', 'huífù', 'trả lời', 67),
    ('抄送', 'chāosòng', 'gửi kèm CC', 68),
    ('附件', 'fùjiàn', 'tệp đính kèm', 69),
    ('文件', 'wénjiàn', 'tài liệu, hồ sơ', 70),
    ('资料', 'zīliào', 'tài liệu, tư liệu', 71),
    ('表格', 'biǎogé', 'bảng biểu', 72),
    ('报告', 'bàogào', 'báo cáo', 73),
    ('汇报', 'huìbào', 'báo cáo công việc', 74),
    ('总结', 'zǒngjié', 'tổng kết', 75),
    ('计划', 'jìhuà', 'kế hoạch', 76),
    ('安排', 'ānpái', 'sắp xếp', 77),
    ('任务', 'rènwu', 'nhiệm vụ', 78),
    ('目标', 'mùbiāo', 'mục tiêu', 79),
    ('进度', 'jìndù', 'tiến độ', 80),
    ('截止日期', 'jiézhǐ rìqī', 'hạn chót', 81),
    ('流程', 'liúchéng', 'quy trình', 82),
    ('标准', 'biāozhǔn', 'tiêu chuẩn', 83),
    ('制度', 'zhìdù', 'chế độ, quy định', 84),
    ('规定', 'guīdìng', 'quy định', 85),
    ('要求', 'yāoqiú', 'yêu cầu', 86),
    ('原则', 'yuánzé', 'nguyên tắc', 87),
    ('方法', 'fāngfǎ', 'phương pháp', 88),
    ('方案', 'fāngàn', 'phương án', 89),
    ('策略', 'cèlüè', 'chiến lược', 90),
    ('预算', 'yùsuàn', 'ngân sách', 91),
    ('成本', 'chéngběn', 'chi phí', 92),
    ('利润', 'lìrùn', 'lợi nhuận', 93),
    ('收入', 'shōurù', 'doanh thu, thu nhập', 94),
    ('支出', 'zhīchū', 'chi tiêu, khoản chi', 95),
    ('报销', 'bàoxiāo', 'thanh toán hoàn phí', 96),
    ('发票', 'fāpiào', 'hóa đơn', 97),
    ('收据', 'shōujù', 'biên lai', 98),
    ('付款', 'fùkuǎn', 'thanh toán', 99),
    ('收款', 'shōukuǎn', 'thu tiền', 100),
    ('数据', 'shùjù', 'dữ liệu', 101),
    ('分析', 'fēnxī', 'phân tích', 102),
    ('统计', 'tǒngjì', 'thống kê', 103),
    ('结果', 'jiéguǒ', 'kết quả', 104),
    ('原因', 'yuányīn', 'nguyên nhân', 105),
    ('问题', 'wèntí', 'vấn đề', 106),
    ('风险', 'fēngxiǎn', 'rủi ro', 107),
    ('机会', 'jīhuì', 'cơ hội', 108),
    ('挑战', 'tiǎozhàn', 'thử thách', 109),
    ('解决', 'jiějué', 'giải quyết', 110),
    ('处理', 'chǔlǐ', 'xử lý', 111),
    ('改进', 'gǎijìn', 'cải tiến', 112),
    ('优化', 'yōuhuà', 'tối ưu hóa', 113),
    ('执行', 'zhíxíng', 'thực thi', 114),
    ('落实', 'luòshí', 'thực hiện đến nơi', 115),
    ('跟进', 'gēnjìn', 'theo dõi tiếp', 116),
    ('反馈', 'fǎnkuì', 'phản hồi', 117),
    ('确认', 'quèrèn', 'xác nhận', 118),
    ('审核', 'shěnhé', 'xét duyệt, kiểm tra', 119),
    ('批准', 'pīzhǔn', 'phê duyệt', 120),
    ('申请', 'shēnqǐng', 'đăng ký, xin', 121),
    ('提交', 'tíjiāo', 'nộp, gửi lên', 122),
    ('修改', 'xiūgǎi', 'sửa đổi', 123),
    ('更新', 'gēngxīn', 'cập nhật', 124),
    ('删除', 'shānchú', 'xóa', 125),
    ('保存', 'bǎocún', 'lưu lại', 126),
    ('打印', 'dǎyìn', 'in', 127),
    ('扫描', 'sǎomiáo', 'quét scan', 128),
    ('复印', 'fùyìn', 'photocopy', 129),
    ('签字', 'qiānzì', 'ký tên', 130),
    ('盖章', 'gàizhāng', 'đóng dấu', 131),
    ('归档', 'guīdàng', 'lưu hồ sơ', 132),
    ('预约', 'yùyuē', 'đặt lịch hẹn', 133),
    ('取消', 'qǔxiāo', 'hủy bỏ', 134),
    ('推迟', 'tuīchí', 'trì hoãn', 135),
    ('提前', 'tíqián', 'làm trước, sớm hơn', 136),
    ('提醒', 'tíxǐng', 'nhắc nhở', 137),
    ('紧急', 'jǐnjí', 'khẩn cấp', 138),
    ('重要', 'zhòngyào', 'quan trọng', 139),
    ('优先级', 'yōuxiān jí', 'mức ưu tiên', 140),
    ('团队', 'tuánduì', 'đội nhóm', 141),
    ('部门', 'bùmén', 'phòng ban', 142),
    ('同事', 'tóngshì', 'đồng nghiệp', 143),
    ('主管', 'zhǔguǎn', 'người phụ trách, quản lý', 144),
    ('经理', 'jīnglǐ', 'giám đốc, quản lý', 145),
    ('总监', 'zǒngjiān', 'giám đốc bộ phận', 146),
    ('老板', 'lǎobǎn', 'ông chủ, sếp', 147),
    ('员工', 'yuángōng', 'nhân viên', 148),
    ('新人', 'xīnrén', 'người mới', 149),
    ('人事', 'rénshì', 'nhân sự', 150),
    ('行政', 'xíngzhèng', 'hành chính', 151),
    ('财务', 'cáiwù', 'tài vụ, tài chính', 152),
    ('会计', 'kuàijì', 'kế toán', 153),
    ('出纳', 'chūnà', 'thủ quỹ', 154),
    ('销售', 'xiāoshòu', 'bán hàng', 155),
    ('市场', 'shìchǎng', 'thị trường, marketing', 156),
    ('运营', 'yùnyíng', 'vận hành', 157),
    ('客服', 'kèfú', 'chăm sóc khách hàng', 158),
    ('采购', 'cǎigòu', 'mua hàng', 159),
    ('物流', 'wùliú', 'logistics', 160),
    ('仓库', 'cāngkù', 'kho hàng', 161),
    ('生产', 'shēngchǎn', 'sản xuất', 162),
    ('质检', 'zhìjiǎn', 'kiểm tra chất lượng', 163),
    ('技术', 'jìshù', 'kỹ thuật', 164),
    ('研发', 'yánfā', 'nghiên cứu phát triển', 165),
    ('设计', 'shèjì', 'thiết kế', 166),
    ('工程师', 'gōngchéngshī', 'kỹ sư', 167),
    ('程序员', 'chéngxùyuán', 'lập trình viên', 168),
    ('设计师', 'shèjìshī', 'nhà thiết kế', 169),
    ('翻译', 'fānyì', 'phiên dịch, biên dịch', 170),
    ('前台', 'qiántái', 'lễ tân', 171),
    ('秘书', 'mìshū', 'thư ký', 172),
    ('司机', 'sījī', 'tài xế', 173),
    ('工人', 'gōngrén', 'công nhân', 174),
    ('班长', 'bānzhǎng', 'trưởng ca', 175),
    ('组长', 'zǔzhǎng', 'trưởng nhóm', 176),
    ('厂长', 'chǎngzhǎng', 'giám đốc nhà máy', 177),
    ('客户', 'kèhù', 'khách hàng', 178),
    ('供应商', 'gōngyìngshāng', 'nhà cung cấp', 179),
    ('合作伙伴', 'hézuò huǒbàn', 'đối tác', 180),
    ('负责人', 'fùzérén', 'người phụ trách', 181),
    ('联系人', 'liánxìrén', 'người liên hệ', 182),
    ('候选人', 'hòuxuǎnrén', 'ứng viên', 183),
    ('面试官', 'miànshìguān', 'người phỏng vấn', 184),
    ('招聘专员', 'zhāopìn zhuānyuán', 'chuyên viên tuyển dụng', 185),
    ('项目经理', 'xiàngmù jīnglǐ', 'quản lý dự án', 186),
    ('产品经理', 'chǎnpǐn jīnglǐ', 'quản lý sản phẩm', 187),
    ('销售代表', 'xiāoshòu dàibiǎo', 'đại diện bán hàng', 188),
    ('业务员', 'yèwùyuán', 'nhân viên kinh doanh', 189),
    ('助理', 'zhùlǐ', 'trợ lý', 190),
    ('沟通', 'gōutōng', 'giao tiếp', 191),
    ('协调', 'xiétiáo', 'điều phối', 192),
    ('合作', 'hézuò', 'hợp tác', 193),
    ('配合', 'pèihé', 'phối hợp', 194),
    ('支持', 'zhīchí', 'hỗ trợ', 195),
    ('帮助', 'bāngzhù', 'giúp đỡ', 196),
    ('倾听', 'qīngtīng', 'lắng nghe', 197),
    ('表达', 'biǎodá', 'biểu đạt', 198),
    ('说明', 'shuōmíng', 'giải thích, thuyết minh', 199),
    ('介绍', 'jièshào', 'giới thiệu', 200),
    ('谈判', 'tánpàn', 'đàm phán', 201),
    ('说服', 'shuōfú', 'thuyết phục', 202),
    ('协商', 'xiéshāng', 'thương lượng', 203),
    ('投诉', 'tóusù', 'khiếu nại', 204),
    ('道歉', 'dàoqiàn', 'xin lỗi', 205),
    ('解释', 'jiěshì', 'giải thích', 206),
    ('承诺', 'chéngnuò', 'cam kết', 207),
    ('保证', 'bǎozhèng', 'đảm bảo', 208),
    ('负责', 'fùzé', 'phụ trách', 209),
    ('参与', 'cānyù', 'tham gia', 210),
    ('管理', 'guǎnlǐ', 'quản lý', 211),
    ('领导', 'lǐngdǎo', 'lãnh đạo', 212),
    ('指导', 'zhǐdǎo', 'hướng dẫn', 213),
    ('监督', 'jiāndū', 'giám sát', 214),
    ('检查', 'jiǎnchá', 'kiểm tra', 215),
    ('评估', 'pínggū', 'đánh giá', 216),
    ('考核', 'kǎohé', 'đánh giá hiệu suất', 217),
    ('提高', 'tígāo', 'nâng cao', 218),
    ('提升', 'tíshēng', 'nâng cấp, cải thiện', 219),
    ('学习', 'xuéxí', 'học tập', 220),
    ('适应', 'shìyìng', 'thích nghi', 221),
    ('熟悉', 'shúxī', 'quen thuộc, thành thạo', 222),
    ('掌握', 'zhǎngwò', 'nắm vững', 223),
    ('了解', 'liǎojiě', 'hiểu, tìm hiểu', 224),
    ('研究', 'yánjiū', 'nghiên cứu', 225),
    ('创新', 'chuàngxīn', 'đổi mới, sáng tạo', 226),
    ('思考', 'sīkǎo', 'suy nghĩ', 227),
    ('判断', 'pànduàn', 'phán đoán', 228),
    ('决定', 'juédìng', 'quyết định', 229),
    ('承担', 'chéngdān', 'đảm nhận, gánh vác', 230),
    ('责任', 'zérèn', 'trách nhiệm', 231),
    ('主动', 'zhǔdòng', 'chủ động', 232),
    ('认真', 'rènzhēn', 'nghiêm túc', 233),
    ('细心', 'xìxīn', 'cẩn thận, tỉ mỉ', 234),
    ('耐心', 'nàixīn', 'kiên nhẫn', 235),
    ('灵活', 'línghuó', 'linh hoạt', 236),
    ('稳定', 'wěndìng', 'ổn định', 237),
    ('高效', 'gāoxiào', 'hiệu quả cao', 238),
    ('准时', 'zhǔnshí', 'đúng giờ', 239),
    ('可靠', 'kěkào', 'đáng tin cậy', 240),
    ('产品', 'chǎnpǐn', 'sản phẩm', 241),
    ('服务', 'fúwù', 'dịch vụ', 242),
    ('订单', 'dìngdān', 'đơn hàng', 243),
    ('报价', 'bàojià', 'báo giá', 244),
    ('价格', 'jiàgé', 'giá cả', 245),
    ('折扣', 'zhékòu', 'chiết khấu', 246),
    ('样品', 'yàngpǐn', 'hàng mẫu', 247),
    ('质量', 'zhìliàng', 'chất lượng', 248),
    ('数量', 'shùliàng', 'số lượng', 249),
    ('规格', 'guīgé', 'quy cách', 250),
    ('型号', 'xínghào', 'mẫu mã, model', 251),
    ('库存', 'kùcún', 'tồn kho', 252),
    ('交货', 'jiāohuò', 'giao hàng', 253),
    ('发货', 'fāhuò', 'gửi hàng', 254),
    ('收货', 'shōuhuò', 'nhận hàng', 255),
    ('验货', 'yànhuò', 'kiểm hàng', 256),
    ('退货', 'tuìhuò', 'trả hàng', 257),
    ('换货', 'huànhuò', 'đổi hàng', 258),
    ('售后', 'shòuhòu', 'hậu mãi', 259),
    ('保修', 'bǎoxiū', 'bảo hành', 260),
    ('市场调研', 'shìchǎng diàoyán', 'nghiên cứu thị trường', 261),
    ('推广', 'tuīguǎng', 'quảng bá', 262),
    ('广告', 'guǎnggào', 'quảng cáo', 263),
    ('品牌', 'pǐnpái', 'thương hiệu', 264),
    ('竞争对手', 'jìngzhēng duìshǒu', 'đối thủ cạnh tranh', 265),
    ('客户需求', 'kèhù xūqiú', 'nhu cầu khách hàng', 266),
    ('满意度', 'mǎnyìdù', 'mức độ hài lòng', 267),
    ('销售额', 'xiāoshòu é', 'doanh số', 268),
    ('增长', 'zēngzhǎng', 'tăng trưởng', 269),
    ('业绩', 'yèjì', 'thành tích kinh doanh', 270),
    ('办公软件', 'bàngōng ruǎnjiàn', 'phần mềm văn phòng', 271),
    ('系统', 'xìtǒng', 'hệ thống', 272),
    ('账号', 'zhànghào', 'tài khoản', 273),
    ('密码', 'mìmǎ', 'mật khẩu', 274),
    ('权限', 'quánxiàn', 'quyền truy cập', 275),
    ('数据库', 'shùjùkù', 'cơ sở dữ liệu', 276),
    ('网站', 'wǎngzhàn', 'trang web', 277),
    ('应用程序', 'yìngyòng chéngxù', 'ứng dụng', 278),
    ('功能', 'gōngnéng', 'tính năng', 279),
    ('界面', 'jièmiàn', 'giao diện', 280),
    ('测试', 'cèshì', 'kiểm thử', 281),
    ('错误', 'cuòwù', 'lỗi', 282),
    ('故障', 'gùzhàng', 'sự cố', 283),
    ('维护', 'wéihù', 'bảo trì', 284),
    ('升级', 'shēngjí', 'nâng cấp', 285),
    ('安全', 'ānquán', 'an toàn, bảo mật', 286),
    ('保密', 'bǎomì', 'bảo mật, giữ bí mật', 287),
    ('效率', 'xiàolǜ', 'hiệu suất', 288),
    ('自动化', 'zìdònghuà', 'tự động hóa', 289),
    ('人工智能', 'réngōng zhìnéng', 'trí tuệ nhân tạo', 290),
    ('中文水平', 'Zhōngwén shuǐpíng', 'trình độ tiếng Trung', 291),
    ('口语', 'kǒuyǔ', 'khẩu ngữ, nói', 292),
    ('听力', 'tīnglì', 'nghe hiểu', 293),
    ('阅读', 'yuèdú', 'đọc hiểu', 294),
    ('写作', 'xiězuò', 'viết', 295),
    ('翻译能力', 'fānyì nénglì', 'khả năng phiên dịch', 296),
    ('商务中文', 'shāngwù Zhōngwén', 'tiếng Trung thương mại', 297),
    ('跨文化沟通', 'kuà wénhuà gōutōng', 'giao tiếp liên văn hóa', 298),
    ('学习能力', 'xuéxí nénglì', 'khả năng học hỏi', 299),
    ('执行力', 'zhíxínglì', 'năng lực thực thi', 300)
) as word(chinese, pinyin, meaning_vi, position)
on conflict (template_deck_id, chinese) do update
set
  pinyin = excluded.pinyin,
  meaning_vi = excluded.meaning_vi,
  example_cn = excluded.example_cn,
  example_pinyin = excluded.example_pinyin,
  example_vi = excluded.example_vi,
  position = excluded.position;
