-- Add a reusable 100-sentence situational deck with highlighted vocabulary and audio.
insert into public.template_decks (slug, name, description, level)
values (
  'dien-thoai-nhan-tin-cong-viec-100-cau',
  'Điện thoại và nhắn tin công việc - 100 câu',
  '100 câu tiếng Trung thực tế để gọi điện và nhắn tin trong công việc: mở đầu cuộc gọi, chuyển máy, để lại lời nhắn, hẹn gọi lại, xác nhận thông tin, nhắn WeChat và xử lý liên lạc gián đoạn. Mỗi câu có pinyin, nghĩa tiếng Việt, 1-2 từ mới được highlight và audio tạo sẵn.',
  'Luyện câu'
)
on conflict (slug) do update
set name = excluded.name, description = excluded.description, level = excluded.level;

with target_deck as (
  select id from public.template_decks where slug = 'dien-thoai-nhan-tin-cong-viec-100-cau'
)
insert into public.template_sentence_cards (
  template_deck_id, sentence_cn, sentence_pinyin, sentence_vi,
  vocab_json, sentence_audio_url, position
)
select
  target_deck.id, card.sentence_cn, card.sentence_pinyin,
  card.sentence_vi, card.vocab_json::jsonb,
  card.sentence_audio_url, card.position
from target_deck
cross join (
  values
    ('您好，这里是销售部，请问需要找哪位？', 'Nín hǎo, zhèlǐ shì xiāoshòubù, qǐngwèn xūyào zhǎo nǎ wèi?', 'Xin chào, đây là phòng sales, bạn cần gặp ai?', '[{"chinese":"销售部","pinyin":"xiāoshòubù","meaning_vi":"phòng sales"},{"chinese":"需要","pinyin":"xūyào","meaning_vi":"cần, yêu cầu"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-8b292b028d7519c0ef14fb79.mp3', 1),
    ('您好，我是市场部的，请问您找哪位同事？', 'Nín hǎo, wǒ shì shìchǎngbù de, qǐngwèn nín zhǎo nǎ wèi tóngshì?', 'Xin chào, tôi là người của phòng marketing, bạn cần gặp đồng nghiệp nào?', '[{"chinese":"市场部","pinyin":"shìchǎngbù","meaning_vi":"phòng marketing"},{"chinese":"同事","pinyin":"tóngshì","meaning_vi":"đồng nghiệp"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-997204b079a26c98bb40e5f8.mp3', 2),
    ('请问这是公司的正确电话号码吗？', 'Qǐngwèn zhè shì gōngsī de zhèngquè diànhuà hàomǎ ma?', 'Xin hỏi đây có phải số điện thoại công ty chính xác không?', '[{"chinese":"正确","pinyin":"zhèngquè","meaning_vi":"chính xác"},{"chinese":"电话号码","pinyin":"diànhuà hàomǎ","meaning_vi":"số điện thoại"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-2b626b9b6e8d347d27ce6b98.mp3', 3),
    ('请问您打电话是关于什么事宜？', 'Qǐngwèn nín dǎ diànhuà shì guānyú shénme shìyí?', 'Xin hỏi cuộc gọi này liên quan đến việc gì?', '[{"chinese":"事宜","pinyin":"shìyí","meaning_vi":"sự việc, công việc"},{"chinese":"关于","pinyin":"guānyú","meaning_vi":"về, liên quan đến"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-97a09c65243793acc80f824a.mp3', 4),
    ('您现在方便接电话吗？', 'Nín xiànzài fāngbiàn jiē diànhuà ma?', 'Bây giờ bạn có tiện để nghe điện thoại không?', '[{"chinese":"方便","pinyin":"fāngbiàn","meaning_vi":"thuận tiện, tiện lợi"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-1e252ca9ac9e345a0df86320.mp3', 5),
    ('请问您是哪位？', 'Qǐngwèn nín shì nǎ wèi?', 'Xin hỏi bạn là ai?', '[{"chinese":"请问","pinyin":"qǐngwèn","meaning_vi":"xin hỏi"},{"chinese":"哪位","pinyin":"nǎ wèi","meaning_vi":"ngài (kính ngữ khi hỏi người)"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-db26bb9fc1444a04e7f90c73.mp3', 6),
    ('您好，感谢您的来电。', 'Nín hǎo, gǎnxiè nín de láidiàn.', 'Xin chào, cảm ơn bạn đã gọi điện.', '[{"chinese":"感谢","pinyin":"gǎnxiè","meaning_vi":"cảm ơn"},{"chinese":"来电","pinyin":"láidiàn","meaning_vi":"gọi điện"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-78636bd6d6fdc72fe5597731.mp3', 7),
    ('能告诉我您的姓名吗？', 'Néng gàosu wǒ nín de xìngmíng ma?', 'Bạn có thể cho tôi biết tên của bạn không?', '[{"chinese":"姓名","pinyin":"xìngmíng","meaning_vi":"họ tên"},{"chinese":"告诉","pinyin":"gàosu","meaning_vi":"nói cho biết"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-f3136f80ab69cd68cf725534.mp3', 8),
    ('请稍等，我帮您转接相关人员。', 'Qǐng shāo děng, wǒ bāng nín zhuǎnjiē xiāngguān rényuán.', 'Xin vui lòng chờ một chút, tôi sẽ chuyển máy đến người phụ trách.', '[{"chinese":"转接","pinyin":"zhuǎnjiē","meaning_vi":"chuyển máy, chuyển cuộc gọi"},{"chinese":"相关人员","pinyin":"xiāngguān rényuán","meaning_vi":"người phụ trách liên quan"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-7be7375369ee047965f5d763.mp3', 9),
    ('请问您方便说话吗？', 'Qǐngwèn nín fāngbiàn shuōhuà ma?', 'Xin hỏi bạn có thuận tiện để nói chuyện không?', '[{"chinese":"方便","pinyin":"fāngbiàn","meaning_vi":"tiện lợi, thuận tiện"},{"chinese":"说话","pinyin":"shuōhuà","meaning_vi":"nói chuyện"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-70c7087c46ca732362792d0d.mp3', 10),
    ('您需要我帮您传达什么信息吗？', 'Nín xūyào wǒ bāng nín chuándá shénme xìnxī ma?', 'Bạn cần tôi giúp truyền đạt thông tin gì không?', '[{"chinese":"传达","pinyin":"chuándá","meaning_vi":"truyền đạt"},{"chinese":"信息","pinyin":"xìnxī","meaning_vi":"thông tin"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-bc9fc660d0f71cfb92e3e921.mp3', 11),
    ('这边是客服中心，请问有什么可以帮您？', 'Zhè biān shì kèfù zhōngxīn, qǐngwèn yǒu shénme kěyǐ bāng nín?', 'Đây là trung tâm chăm sóc khách hàng, xin hỏi có thể giúp gì bạn?', '[{"chinese":"客服中心","pinyin":"kèfù zhōngxīn","meaning_vi":"trung tâm chăm sóc khách hàng"},{"chinese":"帮","pinyin":"bāng","meaning_vi":"giúp đỡ"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-5f76975505b43000402b3535.mp3', 12),
    ('您能确认一下您的联系方式吗？', 'Nín néng quèrèn yīxià nín de liánxì fāngshì ma?', 'Bạn có thể xác nhận lại cách liên lạc của bạn không?', '[{"chinese":"确认","pinyin":"quèrèn","meaning_vi":"xác nhận"},{"chinese":"联系方式","pinyin":"liánxì fāngshì","meaning_vi":"cách thức liên lạc"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-06a73150da670f230ab18ab9.mp3', 13),
    ('您好，我是负责该项目的工作人员。', 'Nín hǎo, wǒ shì fùzé gāi xiàngmù de gōngzuò rényuán.', 'Xin chào, tôi là nhân viên phụ trách dự án này.', '[{"chinese":"负责","pinyin":"fùzé","meaning_vi":"phụ trách"},{"chinese":"工作人员","pinyin":"gōngzuò rényuán","meaning_vi":"nhân viên"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-c445374a0471578462bb1670.mp3', 14),
    ('请问您是从哪个部门来的？', 'Qǐngwèn nín shì cóng nǎge bùmén lái de?', 'Xin hỏi bạn đến từ phòng ban nào?', '[{"chinese":"部门","pinyin":"bùmén","meaning_vi":"phòng ban"},{"chinese":"请问","pinyin":"qǐngwèn","meaning_vi":"xin hỏi"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-c00edb62a01ff80c4d7755f1.mp3', 15),
    ('您稍等，我马上帮您联系对方。', 'Nín shāo děng, wǒ mǎshàng bāng nín liánxì duìfāng.', 'Bạn chờ một chút, tôi sẽ giúp bạn liên lạc bên đối tác ngay.', '[{"chinese":"联系","pinyin":"liánxì","meaning_vi":"liên lạc"},{"chinese":"对方","pinyin":"duìfāng","meaning_vi":"bên đối phương, đối tác"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-87ef35104855a3d2534266b1.mp3', 16),
    ('我这边收到您的来电，谢谢您。', 'Wǒ zhè biān shōudào nín de láidiàn, xièxiè nín.', 'Bên tôi đã nhận cuộc gọi của bạn, cảm ơn bạn.', '[{"chinese":"收到","pinyin":"shōudào","meaning_vi":"nhận được"},{"chinese":"来电","pinyin":"láidiàn","meaning_vi":"cuộc gọi"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-df6043d05b1a814a09cd2b4e.mp3', 17),
    ('请问您需要找哪位负责人？', 'Qǐngwèn nín xūyào zhǎo nǎ wèi fùzé rén?', 'Xin hỏi bạn cần gặp người phụ trách nào?', '[{"chinese":"负责人","pinyin":"fùzé rén","meaning_vi":"người phụ trách"},{"chinese":"需要","pinyin":"xūyào","meaning_vi":"cần"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-84128371ad945b940ee125d3.mp3', 18),
    ('方便说明一下您负责的业务吗？', 'Fāngbiàn shuōmíng yíxià nín fùzé de yèwù ma?', 'Anh/chị có tiện cho biết mình phụ trách mảng công việc nào không?', '[{"chinese":"负责的业务","pinyin":"fùzé de yèwù","meaning_vi":"mảng công việc phụ trách"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-9e3b80144eb92b1fa39f8f6a.mp3', 19),
    ('请问您有什么具体的需求？', 'Qǐngwèn nín yǒu shénme jùtǐ de xūqiú?', 'Xin hỏi bạn có những nhu cầu cụ thể gì?', '[{"chinese":"具体","pinyin":"jùtǐ","meaning_vi":"cụ thể"},{"chinese":"需求","pinyin":"xūqiú","meaning_vi":"nhu cầu"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-f00277adc799edbcc42c066b.mp3', 20),
    ('请稍等，我帮您转接负责该项目的同事。', 'Qǐng shāo děng, wǒ bāng nín zhuǎn jiē fù zé gāi xiàng mù de tóng shì.', 'Xin vui lòng đợi, tôi sẽ chuyển máy cho đồng nghiệp phụ trách dự án này.', '[{"chinese":"转接","pinyin":"zhuǎn jiē","meaning_vi":"chuyển máy"},{"chinese":"负责","pinyin":"fù zé","meaning_vi":"phụ trách"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-42bbc92c12a51fb2d0448cf8.mp3', 21),
    ('抱歉，您要找的同事现在正忙于会议。', 'Bào qiàn, nín yào zhǎo de tóng shì xiàn zài zhèng máng yú huì yì.', 'Xin lỗi, đồng nghiệp bạn cần liên hệ đang bận họp.', '[{"chinese":"抱歉","pinyin":"bào qiàn","meaning_vi":"xin lỗi"},{"chinese":"会议","pinyin":"huì yì","meaning_vi":"họp"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-9952e046ff672b862d045584.mp3', 22),
    ('抱歉，相关人员暂时不在办公室。', 'Bào qiàn, xiāng guān rén yuán zàn shí bù zài bàn gōng shì.', 'Xin lỗi, người liên quan hiện không có mặt tại văn phòng.', '[{"chinese":"相关人员","pinyin":"xiāng guān rén yuán","meaning_vi":"người liên quan"},{"chinese":"暂时","pinyin":"zàn shí","meaning_vi":"tạm thời"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-04f832a5808e76f5a2dd3619.mp3', 23),
    ('请问可以告诉我您的姓名吗？', 'Qǐng wèn kě yǐ gào sù wǒ nín de xìng míng ma?', 'Xin hỏi có thể cho tôi biết tên của bạn được không?', '[{"chinese":"姓名","pinyin":"xìng míng","meaning_vi":"họ tên"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-0088562b17bdc89e118332b8.mp3', 24),
    ('方便请您提供一个联系电话吗？', 'Fāng biàn qǐng nín tí gōng yí gè lián xì diàn huà ma?', 'Xin quý khách vui lòng cung cấp một số điện thoại liên hệ được không?', '[{"chinese":"联系电话","pinyin":"lián xì diàn huà","meaning_vi":"số điện thoại liên hệ"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-08655f2ef2d47d166d15eb35.mp3', 25),
    ('您可以留下信息，我会转告相关人员。', 'Nín kě yǐ liú xià xìn xī, wǒ huì zhuǎn gào xiāng guān rén yuán.', 'Bạn có thể để lại lời nhắn, tôi sẽ chuyển đến người có liên quan.', '[{"chinese":"信息","pinyin":"xìn xī","meaning_vi":"thông tin, lời nhắn"},{"chinese":"转告","pinyin":"zhuǎn gào","meaning_vi":"truyền đạt"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-3f7210b7facdca1f42645431.mp3', 26),
    ('请告诉我您想留言的内容。', 'Qǐng gào sù wǒ nín xiǎng liú yán de nèi róng.', 'Xin cho biết nội dung lời nhắn mà bạn muốn để lại.', '[{"chinese":"留言","pinyin":"liú yán","meaning_vi":"lời nhắn"},{"chinese":"内容","pinyin":"nèi róng","meaning_vi":"nội dung"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-359819dcf92f76ce30902d02.mp3', 27),
    ('我会提醒相关人员尽快回复您。', 'Wǒ huì tí xǐng xiāng guān rén yuán jǐn kuài huí fù nín.', 'Tôi sẽ nhắc người liên quan phản hồi sớm cho bạn.', '[{"chinese":"提醒","pinyin":"tí xǐng","meaning_vi":"nhắc nhở"},{"chinese":"回复","pinyin":"huí fù","meaning_vi":"phản hồi"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-a0ec2060b3a4a0e851574d30.mp3', 28),
    ('您方便什么时候回电？', 'Nín fāng biàn shén me shí hòu huí diàn?', 'Bạn tiện gọi lại vào lúc nào?', '[{"chinese":"回电","pinyin":"huí diàn","meaning_vi":"gọi lại"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-64e1bfc74a82c892a682c794.mp3', 29),
    ('我会安排他稍后给您回电。', 'Wǒ huì ān pái tā shāo hòu gěi nín huí diàn.', 'Tôi sẽ sắp xếp anh ấy gọi lại cho bạn sau.', '[{"chinese":"安排","pinyin":"ān pái","meaning_vi":"sắp xếp"},{"chinese":"稍后","pinyin":"shāo hòu","meaning_vi":"sau một lúc"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-a69792880ea1bf2e0084ddb8.mp3', 30),
    ('您的信息我已经转达给相关同事了。', 'Nín de xìnxī wǒ yǐjīng zhuǎndá gěi xiāngguān tóngshì le.', 'Tôi đã chuyển thông tin của anh/chị cho đồng nghiệp phụ trách.', '[{"chinese":"转达","pinyin":"zhuǎndá","meaning_vi":"chuyển lời, truyền đạt"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-bfd67e87cfb62c65d359c1ab.mp3', 31),
    ('接电话的分机正在使用中，您稍等。', 'Jiē diàn huà de fēn jī zhèng zài shǐ yòng zhōng, nín shāo děng.', 'Máy lẻ người nhận cuộc gọi đang bận, xin bạn đợi một chút.', '[{"chinese":"分机","pinyin":"fēn jī","meaning_vi":"máy lẻ"},{"chinese":"使用中","pinyin":"shǐ yòng zhōng","meaning_vi":"đang sử dụng"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-e8ee4c47d6a94ade369ea92a.mp3', 32),
    ('您要找的同事现在正在开会。', 'Nín yào zhǎo de tóngshì xiànzài zhèngzài kāihuì.', 'Đồng nghiệp anh/chị cần gặp hiện đang họp.', '[{"chinese":"正在开会","pinyin":"zhèngzài kāihuì","meaning_vi":"đang họp"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-7bf12b687db2b110af8bc4e2.mp3', 33),
    ('很抱歉，他目前不在办公室。', 'Hěn bào qiàn, tā mù qián bù zài bàn gōng shì.', 'Rất tiếc, hiện tại anh ấy không có mặt trong văn phòng.', '[{"chinese":"目前","pinyin":"mù qián","meaning_vi":"hiện tại"},{"chinese":"办公室","pinyin":"bàn gōng shì","meaning_vi":"văn phòng"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-707c67a16410d8523e93f53c.mp3', 34),
    ('请问您贵姓？', 'Qǐng wèn nín guì xìng?', 'Xin hỏi quý danh của quý khách?', '[{"chinese":"贵姓","pinyin":"guì xìng","meaning_vi":"quý danh"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-4c5cd11e7ed14978f2afd9d7.mp3', 35),
    ('请您留下电话，我会让同事尽快联系。', 'Qǐng nín liú xià diàn huà, wǒ huì ràng tóng shì jǐn kuài lián xì.', 'Xin bạn để lại số điện thoại, tôi sẽ bảo đồng nghiệp liên hệ sớm.', '[{"chinese":"留下","pinyin":"liú xià","meaning_vi":"để lại"},{"chinese":"联系","pinyin":"lián xì","meaning_vi":"liên hệ"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-af2538d6a7f13d152237d089.mp3', 36),
    ('方便的话，请您留言，我会转达。', 'Fāng biàn de huà, qǐng nín liú yán, wǒ huì zhuǎn dá.', 'Nếu thuận tiện, bạn vui lòng để lại lời nhắn, tôi sẽ chuyển.', '[{"chinese":"留言","pinyin":"liú yán","meaning_vi":"lời nhắn"},{"chinese":"转达","pinyin":"zhuǎn dá","meaning_vi":"chuyển đạt"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-7b91b71f68af0a440ec2c179.mp3', 37),
    ('已记录您的留言，稍后会回复您。', 'Yǐ jì lù nín de liú yán, shāo hòu huì huí fù nín.', 'Đã ghi lại lời nhắn của bạn, sẽ phản hồi bạn sau.', '[{"chinese":"记录","pinyin":"jì lù","meaning_vi":"ghi lại"},{"chinese":"回复","pinyin":"huí fù","meaning_vi":"phản hồi"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-a8158a343adf8cf0fa14307a.mp3', 38),
    ('请问您方便什么时候回电？', 'Qǐng wèn nín fāng biàn shén me shí hòu huí diàn?', 'Xin hỏi bạn tiện gọi lại vào lúc nào?', '[{"chinese":"方便","pinyin":"fāng biàn","meaning_vi":"thuận tiện"},{"chinese":"回电","pinyin":"huí diàn","meaning_vi":"gọi lại"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-1453cf1c3bfb5367d988c071.mp3', 39),
    ('我已将您的信息通知相关部门。', 'Wǒ yǐ jiāng nín de xìn xī tōng zhī xiāng guān bù mén.', 'Tôi đã thông báo thông tin của bạn cho bộ phận liên quan.', '[{"chinese":"通知","pinyin":"tōng zhī","meaning_vi":"thông báo"},{"chinese":"相关部门","pinyin":"xiāng guān bù mén","meaning_vi":"bộ phận liên quan"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-c7ddf5be4f79287e2bf9bad1.mp3', 40),
    ('请问您确定会议时间是几点开始？', 'Qǐngwèn nín quèdìng huìyì shíjiān shì jǐ diǎn kāishǐ?', 'Xin hỏi quý vị xác nhận thời gian họp bắt đầu lúc mấy giờ?', '[{"chinese":"确定","pinyin":"quèdìng","meaning_vi":"xác nhận, đảm bảo"},{"chinese":"会议","pinyin":"huìyì","meaning_vi":"cuộc họp"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-9d46a11f957684f17f564cec.mp3', 41),
    ('请您确认一下明天的预约时间。', 'Qǐng nín quèrèn yīxià míngtiān de yùyuē shíjiān.', 'Xin quý vị xác nhận lại thời gian hẹn vào ngày mai.', '[{"chinese":"确认","pinyin":"quèrèn","meaning_vi":"xác nhận"},{"chinese":"预约","pinyin":"yùyuē","meaning_vi":"đặt trước, hẹn trước"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-ebdb78a6bb11441d72333585.mp3', 42),
    ('请问会议地点是在公司还是客户那里？', 'Qǐngwèn huìyì dìdiǎn shì zài gōngsī háishì kèhù nàlǐ?', 'Xin hỏi địa điểm họp ở công ty hay tại khách hàng?', '[{"chinese":"会议","pinyin":"huìyì","meaning_vi":"cuộc họp"},{"chinese":"地点","pinyin":"dìdiǎn","meaning_vi":"địa điểm"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-d23b141a59839afc60f70ada.mp3', 43),
    ('请您核对一下邮件地址是否正确。', 'Qǐng nín héduì yīxià yóujiàn dìzhǐ shìfǒu zhèngquè.', 'Xin quý vị kiểm tra lại địa chỉ email chính xác hay không.', '[{"chinese":"核对","pinyin":"héduì","meaning_vi":"đối chiếu, kiểm tra"},{"chinese":"邮件地址","pinyin":"yóujiàn dìzhǐ","meaning_vi":"địa chỉ email"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-0947bb8fdda392cd2082fde2.mp3', 44),
    ('请确认您收到的文件名称是否正确。', 'Qǐng quèrèn nín shōudào de wénjiàn míngchēng shìfǒu zhèngquè.', 'Xin xác nhận tên tài liệu quý vị nhận được có đúng không.', '[{"chinese":"确认","pinyin":"quèrèn","meaning_vi":"xác nhận"},{"chinese":"文件名称","pinyin":"wénjiàn míngchēng","meaning_vi":"tên tài liệu"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-ea051c0f3eef315186c0f6cd.mp3', 45),
    ('请问您需要确认的订单数量是多少？', 'Qǐngwèn nín xūyào quèrèn de dìngdān shùliàng shì duōshao?', 'Xin hỏi số lượng đơn hàng anh/chị cần xác nhận là bao nhiêu?', '[{"chinese":"订单数量","pinyin":"dìngdān shùliàng","meaning_vi":"số lượng đơn hàng"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-dbaae6a62570aea81dd06c53.mp3', 46),
    ('您好，能告诉我当前项目的进度吗？', 'Nín hǎo, néng gàosù wǒ dāngqián xiàngmù de jìndù ma?', 'Xin chào, có thể cho tôi biết tiến độ dự án hiện tại được không?', '[{"chinese":"进度","pinyin":"jìndù","meaning_vi":"tiến độ"},{"chinese":"项目","pinyin":"xiàngmù","meaning_vi":"dự án"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-36b905d19261736b844db031.mp3', 47),
    ('请您具体说明需求以便我们处理。', 'Qǐng nín jùtǐ shuōmíng xūqiú yǐbiàn wǒmen chǔlǐ.', 'Xin quý vị vui lòng giải thích cụ thể yêu cầu để chúng tôi xử lý.', '[{"chinese":"具体","pinyin":"jùtǐ","meaning_vi":"cụ thể"},{"chinese":"需求","pinyin":"xūqiú","meaning_vi":"nhu cầu, yêu cầu"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-e713cd9110f3c5cb672379d0.mp3', 48),
    ('我会重复一遍重要信息以确保准确。', 'Wǒ huì chóngfù yí biàn zhòngyào xìnxī yǐ quèbǎo zhǔnquè.', 'Tôi sẽ đọc lại thông tin quan trọng để đảm bảo chính xác.', '[{"chinese":"重复","pinyin":"chóngfù","meaning_vi":"lặp lại"},{"chinese":"准确","pinyin":"zhǔnquè","meaning_vi":"chính xác"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-91396804503f0043084b5723.mp3', 49),
    ('请您尽快发送书面确认邮件。', 'Qǐng nín jǐnkuài fāsòng shūmiàn quèrèn yóujiàn.', 'Xin quý vị vui lòng gửi email xác nhận bằng văn bản sớm nhất có thể.', '[{"chinese":"发送","pinyin":"fāsòng","meaning_vi":"gửi"},{"chinese":"书面确认","pinyin":"shūmiàn quèrèn","meaning_vi":"xác nhận bằng văn bản"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-d4f438d89a8a0d244b6f3e99.mp3', 50),
    ('会议安排需要确认最终时间。', 'Huìyì ānpái xūyào quèrèn zuìzhōng shíjiān.', 'Sắp xếp cuộc họp cần xác nhận thời gian cuối cùng.', '[{"chinese":"安排","pinyin":"ānpái","meaning_vi":"sắp xếp"},{"chinese":"最终","pinyin":"zuìzhōng","meaning_vi":"cuối cùng"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-419a1857b556ef8bf736f378.mp3', 51),
    ('请确认收件人邮箱地址无误。', 'Qǐng quèrèn shōujiànrén yóuxiāng dìzhǐ wúwù.', 'Xin xác nhận địa chỉ email người nhận không sai.', '[{"chinese":"收件人","pinyin":"shōujiànrén","meaning_vi":"người nhận thư"},{"chinese":"邮箱地址","pinyin":"yóuxiāng dìzhǐ","meaning_vi":"địa chỉ hộp thư điện tử"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-366691f7c6536dac10c5331f.mp3', 52),
    ('请核实合同文件的准确信息。', 'Qǐng héshí hétóng wénjiàn de zhǔnquè xìnxī.', 'Xin kiểm tra chính xác thông tin của hợp đồng.', '[{"chinese":"核实","pinyin":"héshí","meaning_vi":"kiểm tra, xác minh"},{"chinese":"信息","pinyin":"xìnxī","meaning_vi":"thông tin"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-aea17b6cbdd43672c8a9d98f.mp3', 53),
    ('能否确认所需资料的完整性？', 'Néngfǒu quèrèn suǒxū zīliào de wánzhěng xìng?', 'Có thể xác nhận tính đầy đủ của tài liệu cần thiết không?', '[{"chinese":"完整性","pinyin":"wánzhěng xìng","meaning_vi":"tính hoàn chỉnh"},{"chinese":"资料","pinyin":"zīliào","meaning_vi":"tài liệu"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-1a99007702662ff41a7a15a2.mp3', 54),
    ('请确认产品数量和规格是否一致。', 'Qǐng quèrèn chǎnpǐn shùliàng hé guīgé shìfǒu yīzhì.', 'Xin xác nhận số lượng và quy cách sản phẩm có đồng nhất không.', '[{"chinese":"规格","pinyin":"guīgé","meaning_vi":"quy cách, tiêu chuẩn"},{"chinese":"数量","pinyin":"shùliàng","meaning_vi":"số lượng"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-bb2b0a298bd829fd29c6806f.mp3', 55),
    ('麻烦您告知最新项目完成时间。', 'Máfan nín gàozhī zuìxīn xiàngmù wánchéng shíjiān.', 'Xin phiền bạn cho biết thời gian hoàn thành dự án mới nhất.', '[{"chinese":"项目","pinyin":"xiàngmù","meaning_vi":"dự án"},{"chinese":"完成","pinyin":"wánchéng","meaning_vi":"hoàn thành"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-a4a4b6b330c4b9f738b16fbf.mp3', 56),
    ('请详细指出需求细节以便安排。', 'Qǐng xiángxì zhǐchū xūqiú xìjié yǐbiàn ānpái.', 'Vui lòng chỉ rõ chi tiết yêu cầu để bố trí sắp xếp.', '[{"chinese":"详细","pinyin":"xiángxì","meaning_vi":"chi tiết"},{"chinese":"安排","pinyin":"ānpái","meaning_vi":"sắp xếp"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-e8a9bd60ea926eb7b1006499.mp3', 57),
    ('我将复述重要内容以确保无误。', 'Wǒ jiāng fùshù zhòngyào nèiróng yǐ quèbǎo wúwù.', 'Tôi sẽ nhắc lại nội dung quan trọng để đảm bảo không sai sót.', '[{"chinese":"复述","pinyin":"fùshù","meaning_vi":"nhắc lại"},{"chinese":"无误","pinyin":"wúwù","meaning_vi":"không sai sót"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-913de4f921d22d309bba3abd.mp3', 58),
    ('请您尽快通过邮件发送确认信息。', 'Qǐng nín jǐnkuài tōngguò yóujiàn fāsòng quèrèn xìnxī.', 'Xin vui lòng gửi thông tin xác nhận qua email càng sớm càng tốt.', '[{"chinese":"发送","pinyin":"fāsòng","meaning_vi":"gửi"},{"chinese":"确认","pinyin":"quèrèn","meaning_vi":"xác nhận"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-5ebd2f604fab4b2bb57701d6.mp3', 59),
    ('会议日程安排需要您的确认。', 'Huìyì rìchéng ānpái xūyào nín de quèrèn.', 'Lịch trình cuộc họp cần sự xác nhận của quý vị.', '[{"chinese":"日程","pinyin":"rìchéng","meaning_vi":"lịch trình"},{"chinese":"安排","pinyin":"ānpái","meaning_vi":"sắp xếp"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-63e0feeaeba927f8e2935051.mp3', 60),
    ('可以加您的微信吗？', 'Kěyǐ jiā nín de wēixìn ma?', 'Có thể thêm WeChat của anh/chị được không?', '[{"chinese":"加","pinyin":"jiā","meaning_vi":"thêm"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-0059a6da205c521178ed5dea.mp3', 61),
    ('我已经发了好友申请，请查收。', 'Wǒ yǐjīng fāle hǎoyǒu shēnqǐng, qǐng cháshōu.', 'Tôi đã gửi lời mời kết bạn, xin vui lòng kiểm tra.', '[{"chinese":"好友申请","pinyin":"hǎoyǒu shēnqǐng","meaning_vi":"lời mời kết bạn"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-fd8b53ba37ae00db8ada0057.mp3', 62),
    ('您好，我是这个项目的联络人。', 'Nínhǎo, wǒ shì zhège xiàngmù de liánluòrén.', 'Xin chào, tôi là người liên hệ của dự án này.', '[{"chinese":"联络人","pinyin":"liánluòrén","meaning_vi":"người liên hệ"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-339f69a8cb72daf02014ae8c.mp3', 63),
    ('我已经通过微信发给您文件，请查收。', 'Wǒ yǐjīng tōngguò wēixìn fā gěi nín wénjiàn, qǐng cháshōu.', 'Tôi đã gửi tài liệu qua WeChat cho anh/chị, xin kiểm tra.', '[{"chinese":"文件","pinyin":"wénjiàn","meaning_vi":"tài liệu"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-aa6d6b4f7748c69520c7f9f9.mp3', 64),
    ('刚刚发了图片，请您注意查收。', 'Gānggāng fāle túpiàn, qǐng nín zhùyì cháshōu.', 'Tôi vừa gửi hình ảnh, anh/chị vui lòng kiểm tra.', '[{"chinese":"图片","pinyin":"túpiàn","meaning_vi":"hình ảnh"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-20ff435922b0adf459823a5b.mp3', 65),
    ('请查收我发的位置信息。', 'Qǐng cháshōu wǒ fā de wèizhì xìnxī.', 'Xin kiểm tra vị trí tôi đã gửi.', '[{"chinese":"位置信息","pinyin":"wèizhì xìnxī","meaning_vi":"thông tin vị trí"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-9a2f110bf221829a208ab208.mp3', 66),
    ('请您确认收到微信消息。', 'Qǐng nín quèrèn shōudào wēixìn xiāoxi.', 'Xin anh/chị xác nhận đã nhận tin nhắn WeChat.', '[{"chinese":"确认","pinyin":"quèrèn","meaning_vi":"xác nhận"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-635d1393720e50825e4d8f0f.mp3', 67),
    ('请尽快回复微信里的内容。', 'Qǐng jǐnkuài huífù wēixìn lǐ de nèiróng.', 'Xin hồi đáp nội dung trong WeChat càng sớm càng tốt.', '[{"chinese":"回复","pinyin":"huífù","meaning_vi":"hồi đáp"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-210e89e8d0c9410e740de57b.mp3', 68),
    ('项目进度我稍后微信通知您。', 'Xiàngmù jìndù wǒ shāohòu wēixìn tōngzhī nín.', 'Tôi sẽ thông báo tiến độ dự án qua WeChat cho anh/chị sau.', '[{"chinese":"进度","pinyin":"jìndù","meaning_vi":"tiến độ"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-c4f769fc9c9f403c6762c10e.mp3', 69),
    ('我已创建工作微信群，邀请您加入。', 'Wǒ yǐ chuàngjiàn gōngzuò wēixìn qún, yāoqǐng nín jiārù.', 'Tôi đã tạo nhóm WeChat công việc, mời anh/chị tham gia.', '[{"chinese":"创建","pinyin":"chuàngjiàn","meaning_vi":"tạo, thành lập"},{"chinese":"邀请","pinyin":"yāoqǐng","meaning_vi":"mời"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-07563254a296bad928035ff2.mp3', 70),
    ('请您确认群里收到的文件。', 'Qǐng nín quèrèn qún lǐ shōudào de wénjiàn.', 'Xin xác nhận đã nhận tài liệu trong nhóm.', '[{"chinese":"确认","pinyin":"quèrèn","meaning_vi":"xác nhận"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-ba98c024557e5b05a2b52fb9.mp3', 71),
    ('添加微信后请回复确认。', 'Tiānjiā wēixìn hòu qǐng huífù quèrèn.', 'Sau khi thêm WeChat, xin vui lòng hồi đáp xác nhận.', '[{"chinese":"添加","pinyin":"tiānjiā","meaning_vi":"thêm"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-f0fd11f39e39ae1c0dd52f87.mp3', 72),
    ('微信里已发送最新合同，请查收。', 'Wēixìn lǐ yǐ fāsòng zuìxīn hétóng, qǐng cháshōu.', 'Hợp đồng mới nhất đã gửi trong WeChat, xin kiểm tra.', '[{"chinese":"合同","pinyin":"hétóng","meaning_vi":"hợp đồng"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-15f8189b50d67f012a81d09b.mp3', 73),
    ('我会通过微信更新项目进展。', 'Wǒ huì tōngguò wēixìn gēngxīn xiàngmù jìnzhǎn.', 'Tôi sẽ cập nhật tiến triển dự án qua WeChat.', '[{"chinese":"更新","pinyin":"gēngxīn","meaning_vi":"cập nhật"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-baec164dd1234743c4083ffc.mp3', 74),
    ('请勿忘回复微信中的消息。', 'Qǐng wù wàng huífù wēixìn zhōng de xiāoxi.', 'Xin đừng quên trả lời tin nhắn trong WeChat.', '[{"chinese":"回复","pinyin":"huífù","meaning_vi":"trả lời"},{"chinese":"消息","pinyin":"xiāoxi","meaning_vi":"tin nhắn, thông tin"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-4a26bb6f37cfae405a03da66.mp3', 75),
    ('刚刚发送了位置，请随时查看。', 'Gānggāng fāsòngle wèizhì, qǐng suíshí chákàn.', 'Vừa gửi vị trí, xin xem bất cứ lúc nào.', '[{"chinese":"位置","pinyin":"wèizhì","meaning_vi":"vị trí"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-bb552ffeaed0fc6d95194c74.mp3', 76),
    ('微信群已建好，邀请您进入。', 'Wēixìn qún yǐ jiàn hǎo, yāoqǐng nín jìnrù.', 'Nhóm WeChat đã được tạo, mời anh/chị tham gia.', '[{"chinese":"微信群","pinyin":"wēixìn qún","meaning_vi":"nhóm WeChat"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-62bc782870a250052ae6cbbd.mp3', 77),
    ('请确认微信上的信息是否清楚。', 'Qǐng quèrèn wēixìn shàng de xìnxī shìfǒu qīngchǔ.', 'Xin xác nhận thông tin trên WeChat có rõ ràng không.', '[{"chinese":"信息","pinyin":"xìnxī","meaning_vi":"thông tin"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-4c6a93ec9b0dabf630accf01.mp3', 78),
    ('微信文件已经发送，烦请查收。', 'Wēixìn wénjiàn yǐjīng fāsòng, fánqǐng cháshōu.', 'Tài liệu WeChat đã gửi, mong anh/chị kiểm tra.', '[{"chinese":"文件","pinyin":"wénjiàn","meaning_vi":"tài liệu"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-7a6faec2ecb38f063ffa6ad6.mp3', 79),
    ('请您尽快确认收到我发的信息。', 'Qǐng nín jǐnkuài quèrèn shōudào wǒ fā de xìnxī.', 'Xin vui lòng xác nhận đã nhận thông tin tôi gửi sớm nhất có thể.', '[{"chinese":"确认","pinyin":"quèrèn","meaning_vi":"xác nhận"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-e5b4972d25ef1901e94a6755.mp3', 80),
    ('信号有点弱，您能换到信号好一点的位置吗？', 'Xìnhào yǒudiǎn ruò, nín néng huàn dào xìnhào hǎo yìdiǎn de wèizhì ma?', 'Tín hiệu hơi yếu, anh/chị có thể chuyển sang chỗ có tín hiệu tốt hơn không?', '[{"chinese":"信号","pinyin":"xìnhào","meaning_vi":"tín hiệu"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-8d3d0039c77a1880275fd35c.mp3', 81),
    ('抱歉，您的声音有点断断续续，我没听清楚。', 'Bàoqiàn, nín de shēngyīn yǒudiǎn duànduàn xùxù, wǒ méi tīng qīngchu.', 'Xin lỗi, giọng của anh/chị hơi bị đứt quãng, tôi không nghe rõ.', '[{"chinese":"抱歉","pinyin":"bàoqiàn","meaning_vi":"xin lỗi"},{"chinese":"断断续续","pinyin":"duànduàn xùxù","meaning_vi":"đứt quãng, không liên tục"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-e669a341179900e12eb8af12.mp3', 82),
    ('请您说得慢一点，方便我记录信息。', 'Qǐng nín shuō dé màn yīdiǎn, fāngbiàn wǒ jìlù xìnxī.', 'Xin anh/chị nói chậm hơn một chút để tôi tiện ghi lại thông tin.', '[{"chinese":"记录","pinyin":"jìlù","meaning_vi":"ghi lại"},{"chinese":"方便","pinyin":"fāngbiàn","meaning_vi":"thuận tiện"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-52b3d82d224465fe31c73827.mp3', 83),
    ('抱歉，您能重复一遍刚才的内容吗？', 'Bàoqiàn, nín néng chóngfù yībiàn gāngcái de nèiróng ma?', 'Xin lỗi, anh/chị có thể nhắc lại nội dung vừa rồi được không?', '[{"chinese":"重复","pinyin":"chóngfù","meaning_vi":"lặp lại, nhắc lại"},{"chinese":"内容","pinyin":"nèiróng","meaning_vi":"nội dung"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-66e91c0d3fcf489cf6362297.mp3', 84),
    ('对不起，刚才电话断了，我们重新联系一下。', 'Duìbuqǐ, gāngcái diànhuà duàn le, wǒmen chóngxīn liánxì yíxià.', 'Xin lỗi, cuộc gọi vừa bị ngắt, chúng ta kết nối lại nhé.', '[{"chinese":"重新联系","pinyin":"chóngxīn liánxì","meaning_vi":"liên hệ lại"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-2fd7d531efc369de57a127c1.mp3', 85),
    ('您好，请问您打错号码了吗？这里不是相关部门。', 'Nín hǎo, qǐngwèn nín dǎ cuò hàomǎ le ma? Zhèlǐ bùshì xiāngguān bùmén.', 'Xin chào, anh/chị có gọi nhầm số không? Đây không phải là phòng ban liên quan.', '[{"chinese":"号码","pinyin":"hàomǎ","meaning_vi":"số điện thoại"},{"chinese":"部门","pinyin":"bùmén","meaning_vi":"phòng ban"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-dff1778173ab61634e0ada95.mp3', 86),
    ('这里比较吵，能否改为发微信沟通？', 'Zhèlǐ bǐjiào chǎo, néngfǒu gǎi wèi fā Wēixìn gōutōng?', 'Ở đây khá ồn, có thể chuyển sang nhắn WeChat để trao đổi được không?', '[{"chinese":"比较","pinyin":"bǐjiào","meaning_vi":"so sánh, khá"},{"chinese":"沟通","pinyin":"gōutōng","meaning_vi":"giao tiếp, trao đổi"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-c257eff90c0ad3514f682582.mp3', 87),
    ('电话信号不稳定，稍后我给您回电。', 'Diànhuà xìnhào bù wěndìng, shāohòu wǒ gěi nín huí diàn.', 'Tín hiệu điện thoại không ổn định, tôi sẽ gọi lại cho anh/chị sau.', '[{"chinese":"不稳定","pinyin":"bù wěndìng","meaning_vi":"không ổn định"},{"chinese":"回电","pinyin":"huí diàn","meaning_vi":"gọi lại (điện thoại)"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-065b9d59e884c0ca77c80d05.mp3', 88),
    ('抱歉打扰了，我先挂断了，下次再联系。', 'Bàoqiàn dǎrǎo le, wǒ xiān guàduàn le, xià cì zài liánxì.', 'Xin lỗi đã làm phiền, tôi sẽ ngắt máy trước, lần sau sẽ liên lạc lại.', '[{"chinese":"打扰","pinyin":"dǎrǎo","meaning_vi":"làm phiền"},{"chinese":"挂断","pinyin":"guàduàn","meaning_vi":"ngắt máy"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-60287b95d254c9556c5f55b1.mp3', 89),
    ('对不起，您说话的声音太小，能稍微大声一点吗？', 'Duìbùqǐ, nín shuōhuà de shēngyīn tài xiǎo, néng shāowéi dàshēng yīdiǎn ma?', 'Xin lỗi, giọng anh/chị nhỏ quá, có thể nói to hơn một chút được không?', '[{"chinese":"声音","pinyin":"shēngyīn","meaning_vi":"âm thanh, giọng nói"},{"chinese":"大声","pinyin":"dàshēng","meaning_vi":"lớn tiếng"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-5f8743f3ac28668b0ccb330f.mp3', 90),
    ('请问您方便用短信沟通吗？电话连接不太好。', 'Qǐngwèn nín fāngbiàn yòng duǎnxìn gōutōng ma? Diànhuà liánjiē bù tài hǎo.', 'Anh/chị có tiện trao đổi qua tin nhắn không? Kết nối điện thoại không được tốt lắm.', '[{"chinese":"短信","pinyin":"duǎnxìn","meaning_vi":"tin nhắn"},{"chinese":"连接","pinyin":"liánjiē","meaning_vi":"kết nối"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-a369dbc54d5e884749318d7b.mp3', 91),
    ('请您稍等，我确认一下信号情况。', 'Qǐng nín shāo děng, wǒ quèrèn yīxià xìnhào qíngkuàng.', 'Anh/chị vui lòng đợi một chút, tôi kiểm tra tình trạng tín hiệu.', '[{"chinese":"确认","pinyin":"quèrèn","meaning_vi":"xác nhận"},{"chinese":"情况","pinyin":"qíngkuàng","meaning_vi":"tình hình, tình trạng"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-4c89fb5cd4096b7d143985b6.mp3', 92),
    ('抱歉，您的电话时断时续，我无法记录完整内容。', 'Bàoqiàn, nín de diànhuà shí duàn shí xù, wǒ wúfǎ jìlù wánzhěng nèiróng.', 'Xin lỗi, điện thoại của anh/chị lúc có lúc không, tôi không thể ghi hết nội dung.', '[{"chinese":"时断时续","pinyin":"shí duàn shí xù","meaning_vi":"lúc được lúc không"},{"chinese":"完整","pinyin":"wánzhěng","meaning_vi":"đầy đủ, hoàn chỉnh"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-11825bb31ec630b0af9f2a7b.mp3', 93),
    ('这里环境嘈杂，是否方便稍后通过微信联系？', 'Zhèlǐ huánjìng cáozá, shìfǒu fāngbiàn shāohòu tōngguò Wēixìn liánxì?', 'Môi trường ở đây rất ồn ào, anh/chị có thể liên hệ qua WeChat sau được không?', '[{"chinese":"环境","pinyin":"huánjìng","meaning_vi":"môi trường"},{"chinese":"嘈杂","pinyin":"cáozá","meaning_vi":"ồn ào"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-0de5e07e286211f37f2421bf.mp3', 94),
    ('对不起，听不清楚您的话，请再说一遍。', 'Duìbùqǐ, tīng bù qīngchǔ nín de huà, qǐng zài shuō yībiàn.', 'Xin lỗi, tôi không nghe rõ lời anh/chị, xin hãy nói lại một lần nữa.', '[{"chinese":"听不清楚","pinyin":"tīng bù qīngchǔ","meaning_vi":"nghe không rõ"},{"chinese":"再说","pinyin":"zài shuō","meaning_vi":"nói lại"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-6698e4e4df7d5476c5451b68.mp3', 95),
    ('刚才电话突然断了，我稍后会再打给您。', 'Gāngcái diànhuà túrán duàn le, wǒ shāohòu huì zài dǎ gěi nín.', 'Cuộc gọi vừa rồi bị ngắt, tôi sẽ gọi lại cho anh/chị sau.', '[{"chinese":"突然","pinyin":"túrán","meaning_vi":"đột nhiên"},{"chinese":"断了","pinyin":"duàn le","meaning_vi":"bị ngắt"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-fda83d28b196d01ea8ef5e7a.mp3', 96),
    ('抱歉打扰，能否请您稍后再联系？', 'Bàoqiàn dǎrǎo, néngfǒu qǐng nín shāohòu zài liánxì?', 'Xin lỗi làm phiền, anh/chị có thể liên lạc lại sau được không?', '[{"chinese":"抱歉","pinyin":"bàoqiàn","meaning_vi":"xin lỗi"},{"chinese":"打扰","pinyin":"dǎrǎo","meaning_vi":"làm phiền"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-956d1f49a97de81322aa3227.mp3', 97),
    ('谢谢您的理解，祝您工作顺利，再见。', 'Xièxiè nín de lǐjiě, zhù nín gōngzuò shùnlì, zàijiàn.', 'Cảm ơn anh/chị đã thông cảm, chúc công việc thuận lợi, hẹn gặp lại.', '[{"chinese":"理解","pinyin":"lǐjiě","meaning_vi":"hiểu, thông cảm"},{"chinese":"顺利","pinyin":"shùnlì","meaning_vi":"thuận lợi"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-e36497ac8db5e6ccadf5a54d.mp3', 98),
    ('您打的号码不正确，请核对后再拨。', 'Nín dǎ de hàomǎ bù zhèngquè, qǐng héduì hòu zài bō.', 'Số anh/chị gọi không đúng, xin vui lòng kiểm tra rồi gọi lại.', '[{"chinese":"不正确","pinyin":"bù zhèngquè","meaning_vi":"không chính xác"},{"chinese":"核对","pinyin":"héduì","meaning_vi":"kiểm tra, đối chiếu"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-052282fe3d2547ffd344a0e2.mp3', 99),
    ('请您尽量使用耳机，以免外界噪音影响通话质量。', 'Qǐng nín jǐnliàng shǐyòng ěrjī, yǐmiǎn wàijiè zàoyīn yǐngxiǎng tōnghuà zhìliàng.', 'Anh/chị cố gắng sử dụng tai nghe để tránh tiếng ồn bên ngoài ảnh hưởng chất lượng cuộc gọi.', '[{"chinese":"噪音","pinyin":"zàoyīn","meaning_vi":"tiếng ồn"},{"chinese":"影响","pinyin":"yǐngxiǎng","meaning_vi":"ảnh hưởng"}]', 'https://ssmqppvkgffknfqdvpwg.supabase.co/storage/v1/object/public/card-audio/templates/dien-thoai-nhan-tin-cong-viec-100-cau/sentence-baf3fc309a56ec8e118ec42b.mp3', 100)
) as card(
  sentence_cn, sentence_pinyin, sentence_vi,
  vocab_json, sentence_audio_url, position
)
on conflict (template_deck_id, sentence_cn) do update
set
  sentence_pinyin = excluded.sentence_pinyin,
  sentence_vi = excluded.sentence_vi,
  vocab_json = excluded.vocab_json,
  sentence_audio_url = excluded.sentence_audio_url,
  position = excluded.position;

delete from public.template_sentence_cards
where template_deck_id = (
  select id from public.template_decks where slug = 'dien-thoai-nhan-tin-cong-viec-100-cau'
)
and sentence_cn not in ('您好，这里是销售部，请问需要找哪位？', '您好，我是市场部的，请问您找哪位同事？', '请问这是公司的正确电话号码吗？', '请问您打电话是关于什么事宜？', '您现在方便接电话吗？', '请问您是哪位？', '您好，感谢您的来电。', '能告诉我您的姓名吗？', '请稍等，我帮您转接相关人员。', '请问您方便说话吗？', '您需要我帮您传达什么信息吗？', '这边是客服中心，请问有什么可以帮您？', '您能确认一下您的联系方式吗？', '您好，我是负责该项目的工作人员。', '请问您是从哪个部门来的？', '您稍等，我马上帮您联系对方。', '我这边收到您的来电，谢谢您。', '请问您需要找哪位负责人？', '方便说明一下您负责的业务吗？', '请问您有什么具体的需求？', '请稍等，我帮您转接负责该项目的同事。', '抱歉，您要找的同事现在正忙于会议。', '抱歉，相关人员暂时不在办公室。', '请问可以告诉我您的姓名吗？', '方便请您提供一个联系电话吗？', '您可以留下信息，我会转告相关人员。', '请告诉我您想留言的内容。', '我会提醒相关人员尽快回复您。', '您方便什么时候回电？', '我会安排他稍后给您回电。', '您的信息我已经转达给相关同事了。', '接电话的分机正在使用中，您稍等。', '您要找的同事现在正在开会。', '很抱歉，他目前不在办公室。', '请问您贵姓？', '请您留下电话，我会让同事尽快联系。', '方便的话，请您留言，我会转达。', '已记录您的留言，稍后会回复您。', '请问您方便什么时候回电？', '我已将您的信息通知相关部门。', '请问您确定会议时间是几点开始？', '请您确认一下明天的预约时间。', '请问会议地点是在公司还是客户那里？', '请您核对一下邮件地址是否正确。', '请确认您收到的文件名称是否正确。', '请问您需要确认的订单数量是多少？', '您好，能告诉我当前项目的进度吗？', '请您具体说明需求以便我们处理。', '我会重复一遍重要信息以确保准确。', '请您尽快发送书面确认邮件。', '会议安排需要确认最终时间。', '请确认收件人邮箱地址无误。', '请核实合同文件的准确信息。', '能否确认所需资料的完整性？', '请确认产品数量和规格是否一致。', '麻烦您告知最新项目完成时间。', '请详细指出需求细节以便安排。', '我将复述重要内容以确保无误。', '请您尽快通过邮件发送确认信息。', '会议日程安排需要您的确认。', '可以加您的微信吗？', '我已经发了好友申请，请查收。', '您好，我是这个项目的联络人。', '我已经通过微信发给您文件，请查收。', '刚刚发了图片，请您注意查收。', '请查收我发的位置信息。', '请您确认收到微信消息。', '请尽快回复微信里的内容。', '项目进度我稍后微信通知您。', '我已创建工作微信群，邀请您加入。', '请您确认群里收到的文件。', '添加微信后请回复确认。', '微信里已发送最新合同，请查收。', '我会通过微信更新项目进展。', '请勿忘回复微信中的消息。', '刚刚发送了位置，请随时查看。', '微信群已建好，邀请您进入。', '请确认微信上的信息是否清楚。', '微信文件已经发送，烦请查收。', '请您尽快确认收到我发的信息。', '信号有点弱，您能换到信号好一点的位置吗？', '抱歉，您的声音有点断断续续，我没听清楚。', '请您说得慢一点，方便我记录信息。', '抱歉，您能重复一遍刚才的内容吗？', '对不起，刚才电话断了，我们重新联系一下。', '您好，请问您打错号码了吗？这里不是相关部门。', '这里比较吵，能否改为发微信沟通？', '电话信号不稳定，稍后我给您回电。', '抱歉打扰了，我先挂断了，下次再联系。', '对不起，您说话的声音太小，能稍微大声一点吗？', '请问您方便用短信沟通吗？电话连接不太好。', '请您稍等，我确认一下信号情况。', '抱歉，您的电话时断时续，我无法记录完整内容。', '这里环境嘈杂，是否方便稍后通过微信联系？', '对不起，听不清楚您的话，请再说一遍。', '刚才电话突然断了，我稍后会再打给您。', '抱歉打扰，能否请您稍后再联系？', '谢谢您的理解，祝您工作顺利，再见。', '您打的号码不正确，请核对后再拨。', '请您尽量使用耳机，以免外界噪音影响通话质量。');
